### ISSUE TITLE
Introduce roles_path to support nested roles in OIDC config (eg. keyclock nested roles)

### ISSUE THREAD

**Issue by hardik-k-shah** [opensearch-project/security#1003]
We should introduced roles_path 

`
```java
if (jsonRolesPath != null) {
                Object roles = JsonPath.using(jsonPathConfig).parse(claims.asMap()).read(jsonRolesPath);
                return splitRoles(roles);
        
````

This way customer using the "." in their key in payload will not be affected

_Originally posted by @palashhedau in https://github.com/opendistro-for-elasticsearch/security/pull/698#discussion_r566357711_

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
