### ISSUE TITLE
DLS for writes aka Applying data constraints for writes?

### ISSUE THREAD

**Issue by arungitan** [opensearch-project/security#1025]
we are currently exploring opendistro security features for our (java/spring) application. Based on some experiments, it seems that Document-level security (DLS) only applies to queries? Currently, then, it is possible for the user to write data that would then become invisible to them because of DLS! This is obviously not desired in most applications.
Is there a current (or planned) feature which would allow DLS (or similar concept) to be applied transparently when data is written? (to clarify- what I mean by transparent is that the indexing request should fail if the data does not meet the specified dynamic constraints) 

Currently, the only options seem to be to duplicate the constraints that we express as DLS into application logic for writes and/or an ingest pipeline doing a similar thing. The lack of this data protection on writes also prevents us from using user impersonation.

(cross-posted to opendistrocommunity as well).

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
