### ISSUE TITLE
[Feature Request] AWS IAM as authentication backend (re-opened)

### ISSUE THREAD

**Issue by root360-AndreasUlm** [opensearch-project/security#1034]
As https://github.com/opendistro-for-elasticsearch/security/issues/995 was closed without even waiting for my response and not reconsidering my request at all, I'm re-opening it by creating a new issue.

If there are any further questions just ask and allow me to respond before closing the issue, please.

----
Original text:

Hi,

I haven't found any hint in the authentication configuration [1] whcih is why I'm creating an issue.
It would be a nice feature to be able to use AWS IAM as authentication backend.
There seems to be a possibility as there is already a plugin for kubernetes [2] but I could not yet find a way to port it to opendistro-for-elasticsearch.

Regards,
Andreas

[1] https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/concepts/
[2] https://github.com/kubernetes-sigs/aws-iam-authenticator

----
Response by @cliu123 :

AWS Elasticsearch supports policy-based identity and access control, which is based on AWS IAM. Please see the documentation.

---
My response to @cliu123 :

@cliu123 This issue is not about AWS Elasticsearch but AWS IAM support in opendistro-for-elasticsearch.
We are running our own Elasticsearch cluster with opendistro-for-elasticsearch as part of our [Wazuh](https://wazuh.com) setup.
Due to the limited nature of AWS Elasticsearch concerning installation of plugins we cannot use AWS Elasticsearch.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
