### ISSUE TITLE
Session timeouts with LDAP users

### ISSUE THREAD

**Issue by Joelp** [opensearch-project/security#1041]
I am happy with internal users, session works well with kibana settings:
```
opendistro_security.session.keepalive: true
opendistro_security.cookie.ttl: 0
opendistro_security.session.ttl: 259200000
```

But I have session timeout, in few minutes, with LDAP users logged in. Even if I am logged in as an LDAP user, I sometimes see no index exists message in visualization. (Could not locate that index-pattern (id: AWKUrBJZGsWMYrgk6_P1), click here to re-create it). 

Is there any way to configure timeout/keepalive for LDAP users too?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
