### ISSUE TITLE
Add indices:monitor/settings/get permission to kibana_server

### ISSUE THREAD

**Issue by mxmorin** [opensearch-project/security#1049]
We used kibanaserver as elasticsearch.username in th kibana.yml

We have this error in the logs : 
`{"type":"log","@timestamp":"2021-02-23T11:19:38Z","tags":["error","elasticsearch","data"],"pid":49784,"message":"[security_exception]: no permissions for [indices:monitor/settings/get] and User [name=kibanaserver, backend_roles=[], requestedTenant=null]"}
`
Can you add this permission to the static role ?

**Comment by vrozov** [comment]
kibanaserver has all necessary permissions for indices that it needs to access. Please check what indices it tries to access and why

**Comment by mxmorin** [comment]
@vrozov thanks for your response
I can't know which indice is concerned because this is not mentionned in the logs. See also #186

Kibanaserver is mapped to kibana_server rôle which doesn't have monitor/settings/get permission
![image](https://user-images.githubusercontent.com/58942529/110322536-8dff8800-8013-11eb-9873-b1f5a53da779.png)

I don't know too which process needs this permission

**Comment by pitch-d** [comment]
When enabling logging of kibanaserver and REST and TRASNSPORT categories AUTHENTICATED and GRANTED_PRIVILEGES in Security/Audit logs settings it is possible to find out what @vrozov is asking for in the .security-auditlog-indices.
As I can see this error is only appearing when any user is logging in via kibana.
These two security-audit-logs are produced at the same timestamp:

[kibana-login-MISSING_PRIVILEGES.txt](https://github.com/opensearch-project/security/files/6389343/kibana-login-MISSING_PRIVILEGES.txt)

**Comment by vrozov** [comment]
@mxmorin Please see my comments on  #186. Log entry provides details on what index or alias the request is resolved to.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
