### ISSUE TITLE
Accept authentication via remote_user header

### ISSUE THREAD

**Issue by LaramieSmile** [opensearch-project/security#1050]
Hey All,
I was wondering if there was a way, or if it could be a feature request, to allow using the built in HTTP authorization for HTTP access based on a passed REMOTE_USER header.

Use case is I already have authentication setup in front of kibana(proxied by Apache) using our orgs kerberos and 2FA authentication.  I'd rather be able to keep the 2FA and just pass the user to Kibana/elastic and have it use the built in HTTP roles backend.

**Comment by pawelw1** [comment]
@LaramieSmile have you found a solution to your issue? See if this link can help you. 

https://opensearch.org/docs/latest/security-plugin/configuration/proxy/

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
