### ISSUE TITLE
Saved Objects

### ISSUE THREAD

**Issue by mporracindie** [opensearch-project/security#1052]
Hi,

Since the implementation of tenants, each one has objects associated with it. It would be great to have a way to list tenants and export objects from each one. 
I have tried using the [Saved Objects API](https://www.elastic.co/guide/en/kibana/7.x/saved-objects-api-find.html) for kibana but it doesn't seem to be working.

**Comment by hardik-k-shah** [comment]
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/53

**Comment by davidlago** [comment]
Closing in favor of https://github.com/opensearch-project/security-dashboards-plugin/issues/53
