### ISSUE TITLE
You need to update your documentation to describe the new nodes_dn.yml file.

### ISSUE THREAD

**Issue by Atreus-Technologies** [opensearch-project/security#1053]
The documentation describing the yaml files required to get the security plugin running are out of date.  [This](https://github.com/opendistro-for-elasticsearch/security/pull/362) PR made it necessary to add a nodes_dn.yml file into the security config directory, and you get an error complaining about its absence if you leave nodes_dn as a key in elasticsearch.yml as described in the documents.

There is a whole [page](https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/yaml/) dedicated to describing the .yml files required to make the plugin work, but nodes_dn.yml isn't mentioned

**Comment by Anthony7774** [comment]
This is now updated in opensearch [docs](https://opensearch.org/docs/latest/security-plugin/configuration/yaml/#nodes_dnyml)

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
