### ISSUE TITLE
Change URI for configuration API

### ISSUE THREAD

**Issue by aetter** [opensearch-project/security#108]
Currently, a call to `GET _opendistro/_security/api/config` returns a `config` object:

```json
{
  "config": {
    "dynamic": {
      ...
    }
  }
}
```

But then if you try use that response as the request body, you receive an error:

```json
PUT _opendistro/_security/api/config
{
  "config": {
    "dynamic": {
      ...
    }
  }
}

{
    "error": "Incorrect HTTP method for uri [/_opendistro/_security/api/config] and method [PUT], allowed: [GET, PATCH]",
    "status": 405
}
```

Instead, you have to remove the `config` object in the request body and send the request to `config/config`:

```json
PUT _opendistro/_security/api/config/config
{
  "dynamic": {
    ...
  }
}

{
    "status": "OK",
    "message": "'config' updated."
}
```

**Expected behavior**: the following request should work:

```json
```json
PUT _opendistro/_security/api/config
{
  "config": {
    "dynamic": {
      ...
    }
  }
}
```

**Current behavior**: The request errors out.

**Comment by hardik-k-shah** [comment]
Additionally, this endpoint should be "_opendistro/_security/api/securityconfig" 
this endpoint is not consistent across different ODFE version.

**Comment by pawelw1** [comment]
@aetter As per OpenDistro documentation the valid endpoint is `_opendistro/_security/api/securityconfig`

https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/api/#configuration

Check also OpenSearch docs. 
https://opensearch.org/docs/latest/security-plugin/access-control/api/#configuration

**Comment by cliu123** [comment]
Right API paths are documented.
