### ISSUE TITLE
Return HTTP 409 on version confict when creating & updating users/roles

### ISSUE THREAD

**Issue by phillbaker** [opensearch-project/security#1095]
Hello, I opened https://github.com/opendistro-for-elasticsearch/security/issues/1077 earlier, related to https://github.com/phillbaker/terraform-provider-elasticsearch/issues/154.

When OpenDistro receives parallel requests to create or update users or roles, it returns an HTTP 500 response similar to:
```
{"status":"INTERNAL_SERVER_ERROR","message":"Error [internalusers]: version conflict, required seqNo [31], primary term [1]. current document has seqNo [32] and primary term [1]"}
``` 

I've been able to [reproduce this consistently in a CI test](https://github.com/phillbaker/terraform-provider-elasticsearch/commit/b397f19678cc24cd6625b7872b181106ceb1cb6f).

Similar to Elasticsearch itself, these conflict exceptions should return a http 409 instead of a 500 to signal that this is an expect error case and a retry is expected.

**Comment by andy840314** [comment]
The fix is merged. Feel free to reopen it or open a new issue if there are any concerns.
