### ISSUE TITLE
kibana_read_only role is not available for role-mapping

### ISSUE THREAD

**Issue by cujeff09** [opensearch-project/security#1096]
We're new to Open Distro for Elasticsearch after using the Elastic product for many years.  We're trying to create a read-only user in our Open Distro for Elasticsearch 7.9.1 implementation with Open Distro Security Version: 1.11.0.0.  We defined the user as follows:
`{
  "password": "__PASSWORD__",
  "opendistro_security_roles": [
    "kibana_read_only",
    "kibana_user"
  ],
  "attributes": {
    "full_name": "Read only user",
    "email": "fake@email.com"
  }
}`

We define other Kibana users this way with opendistro_security_role kibana_user.  This is the first one where we are adding kibana_read_only per https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/users-roles/#predefined-roles, and in kibana.yml, I see:
`opendistro_security.readonly_mode.roles: - kibana_read_only`

When we try to apply this user, however, we get the following error:
`curl -sS -XPUT -H 'Authorization: Basic XXXX' -H 'Content-Type: application/json' -d @<file> http://odfe-elasticsearch-client-service:9200/_opendistro/_security/api/internalusers/read_only_user
output='{"status":"NOT_FOUND","message":"Role '\''kibana_read_only'\'' is not available for role-mapping."}'`

Where is kibana_read_only defined and why can't we map a user to it?

**Comment by Anthony7774** [comment]
Hi @cujeff09 I'\m not able to reproduce your issue and I'm able to run the curl PUT command with the new user. As this is not related to any particular bug or feature request, I would recommend to post a question on the [OpenSearch forum](https://discuss.opendistrocommunity.dev/c/security/3), as there we are usually quick to respond to these and similar issues in more detail

**Comment by cujeff09** [comment]
Will do, thank you!

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
