### ISSUE TITLE
ERROR: checksum file

### ISSUE THREAD

**Issue by kinseii** [opensearch-project/security#1097]
Hello,

I have a problem with SHA512 checksum:
When i'm try install security plugin in Elasticsearch:
_bin/elasticsearch-plugin install -b com.amazon.opendistroforelasticsearch:opendistro_security:1.13.1.0 -v_
I have error:
_Checking if url exists: https://repo1.maven.org/maven2/com/amazon/opendistroforelasticsearch/opendistro_security/1.13.1.0/opendistro_security-linux-x86_64-1.13.1.0.zip
-> Downloading com.amazon.opendistroforelasticsearch:opendistro_security:1.13.1.0 from maven central
Retrieving zip from https://repo1.maven.org/maven2/com/amazon/opendistroforelasticsearch/opendistro_security/1.13.1.0/opendistro_security-1.13.1.0.zip
-> Failed installing com.amazon.opendistroforelasticsearch:opendistro_security:1.13.1.0
-> Rolling back com.amazon.opendistroforelasticsearch:opendistro_security:1.13.1.0
-> Rolled back com.amazon.opendistroforelasticsearch:opendistro_security:1.13.1.0
ERROR: checksum file at [https://repo1.maven.org/maven2/com/amazon/opendistroforelasticsearch/opendistro_security/1.13.1.0/opendistro_security-1.13.1.0.zip.sha512] is not for this plugin, expected [opendistro_security-1.13.1.0.zip] but was [opendistro-security-1.13.1.0.zip]_

I'm download opendistro_security-1.13.1.0.zip.sha512 and see error in name:
_99b0527ec7f780758ae1787a109f8db5bc9f58711dcfcc976aa94de0308748718c03738525809cc24c57ce58febac00ff5dc343a21c8e3d3762c79c7a92a4602  opendistro-security-1.13.1.0.zip_

Name must be: opendistro**_**security-1.13.1.0.zip

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
