### ISSUE TITLE
"Add" and "replace" operation do the same thing in PATCH requests

### ISSUE THREAD

**Issue by aetter** [opensearch-project/security#1099]
Hi all, I'm not sure how widespread this is across our API(s), but it seems like the add and replace operations of the PATCH method are both replacing whatever they find. I could be misreading [the specification](https://tools.ietf.org/html/rfc6902#section-4.1), but it seems like add should be "create if it doesn't exist, append if it does." Replace seems to work as expected, which is "fail if it doesn't exist, replace if it does."

Steps:

1. Create a role.

```
PUT _opendistro/_security/api/roles/new-role
{
	"cluster_permissions": [
		"manage_snapshots"
	],
	"index_permissions": [{
		"index_patterns": [
			"*"
		],
		"fls": [],
		"masked_fields": [],
		"allowed_actions": [
			"indices:data/write/index",
			"indices:admin/create"
		]
	}],
	"tenant_permissions": [{
		"tenant_patterns": [
			"new-tenant"
		],
		"allowed_actions": [
			"kibana_all_write"
		]
	}]
}
```

2. Patch it with the `add` operation.

```
PATCH _opendistro/_security/api/roles/new-role
[
  {
    "op": "add", "path": "/index_permissions/0/allowed_actions", "value": ["indices:admin/create"]
  }
]
```

3. Retrieve it.

```
GET _opendistro/_security/api/roles/new-role
```

**Current behavior**: `new-role` had its index permissions replaced with just `indices:admin/create`.
**Expected behavior**: `indices:admin/create` gets appended to the list of permissions.

4. Recreate the role.

```
PUT _opendistro/_security/api/roles/new-role
{
	"cluster_permissions": [
		"manage_snapshots"
	],
	"index_permissions": [{
		"index_patterns": [
			"*"
		],
		"fls": [],
		"masked_fields": [],
		"allowed_actions": [
			"indices:data/write/index",
			"indices:admin/create"
		]
	}],
	"tenant_permissions": [{
		"tenant_patterns": [
			"new-tenant"
		],
		"allowed_actions": [
			"kibana_all_write"
		]
	}]
}
```

5. This time, patch it with the "replace" operation.

```
PATCH _opendistro/_security/api/roles/new-role
[
  {
    "op": "replace", "path": "/index_permissions/0/allowed_actions", "value": ["indices:admin/create"]
  }
]
```

Note that the outcome is identical. More details [here](https://github.com/opendistro/for-elasticsearch-docs/issues/450) from @JohnMops.

**Comment by willemveerman** [comment]
This is causing issues for us as well - any chance it could get triaged and investigated?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
