### ISSUE TITLE
Create user have read only permission not really read only

### ISSUE THREAD

**Issue by BlackMetalz** [opensearch-project/security#1107]
Currently. I’m stuck on creating a user for a developer used for the query which has read-only permission.

read-only role:

Cluster permission:
```
cluster_composite_ops_ro
cluster_monitor
indices:admin/template/get
```
Index Permission:
Pattern: * ( i want give user for all user can read everything from es )
index permission: 
``` read / get /search ```
Those setting is good and prevent no info log related to lack of permission on ODFE Log.
But somehow user still can delete index by query:

DELETE index_name
Version: 7.8.0 and 7.10.2

Update: I tried to create index custom-like
```
security-auditlog-2021.03.01_test
```
and can not delete it
but other index patterns, it can delete it as well. So what is different here :smiley:

**Comment by Anthony7774** [comment]
For anyone looking for details, this was resolved in [forum](https://discuss.opendistrocommunity.dev/t/create-user-have-read-only-permission-query-via-dev-tools/5467/20)

**Comment by BlackMetalz** [comment]
Yes, this issue can close now <3
