### ISSUE TITLE
Ignore case sensitive in backend roles

### ISSUE THREAD

**Issue by hollden** [opensearch-project/security#1125]
Can it possible to configure security plugin to ignore case sensivity in backend roles?
For expamle backend role TesT_Role should match test_tole in role_mapping. 
Because there isn't any pattern about upper letters in backend roles which I reсeive from AD and it will be more simpler just ignore capital letters than rename all roles in AD.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
