### ISSUE TITLE
Rotating admin credentials

### ISSUE THREAD

**Issue by franco-martin** [opensearch-project/security#1159]
Context:
Enterprise deployment, AD for authentication and authorization and internal db for service accounts.
Use case:
We need to rotate the admin credential without deleting all the internal accounts by uploading the internal_users.yml is this possible?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
