### ISSUE TITLE
ldap authz requires truststore to be configured

### ISSUE THREAD

**Issue by joeryan** [opensearch-project/security#116]
Authentication succeeds, but authorization fails to contact ldap servers unless a truststore is configured and available.

 The opendistro_security.ssl.transport.truststore_filepath and/or opendistro_security.http.transport.truststore_filepath appear to be required for authz to function correctly. I kept getting an Empty file path for opendistro_security.ssl.transport.truststore_filepath error when trying to use ldap for authz even though authc worked correctly. I'm not sure if this is a documentation issue or implementation issue. 

- related issue reported in [for-elasticsearch-docs](https://github.com/opendistro/for-elasticsearch-docs/issues/112)
- [truststore listed as alternative method in documentation](https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/tls/#keystore-and-truststore-files)
- [forum post on issue with ldap authz and error](https://discuss.opendistrocommunity.dev/t/error-empty-file-path-for-opendistro-security-ssl-transport-truststore-filepath/733)

**Comment by pouyana** [comment]
Hi, 
you can use the java default trust store it is located in `/etc/ssl/certs/java/cacerts`. Just copy it to the elasticsearch folder and give the relative path in the `elasticsearch.yml` file

**Comment by joeryan** [comment]
In my environment, the default java truststore does not contain the appropriate CAs and is insufficient.  But as long as a valid truststore is defined and available, it works as expected.  The problem is that the documentation indicates this is an optional substitute for certificates and private keys.  I did open an issue for documentation, but haven't seen any activity on that.  I don't know if this should just be documented that a truststore is required for authz or if this is a bug.

**Comment by bgagnon** [comment]
I was also surprised to find this. I would not have expected LDAPS to be related to `opendistro_security.ssl.transport` which is about node-to-node communications, not outgoing connections to LDAP.

**Comment by nebulon42** [comment]
I did also run into this with OIDC. There also the setting `truststore_filepath` is required otherwise you run into an error despite the documentation saying that this is optional. The documentation is clearly off here. Also not sure why the system does not just use the default trust store?

**Comment by pawelw1** [comment]
@joeryan As per documentation the security plugin validates the TLS certificate of the LDAP servers against the root CA configured in elasticsearch.yml (or opensearch.yml in OpenSearch).
If root CA is not present in that truststore then either should be added to the truststore or defined in LDAP configuration in config.yml. 

ODFE:
https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/ldap/#certificate-validation

OpenSearch:
https://opensearch.org/docs/latest/security-plugin/configuration/ldap/#certificate-validation

**Comment by joeryan** [comment]
Issue for this repository was closed by updates to documentation.
