### ISSUE TITLE
Audit Logs: audit_request_remote_address always shows kibana address

### ISSUE THREAD

**Issue by skkosuri-amzn** [opensearch-project/security#1162]
`audit_request_remote_address` in the audit log always shows OpenSearch Dashboards IP address instead of user browser IP address. If OpenSearch and OpenSearch Dashboards are running on the same node, it would show `127.0.0.1`.

**Comment by vrozov** [comment]
This is expected. The request originates from Kibana and security plugin is supposed to log the actual ip of the address that initiated the request. Security plugin can't distinguish requests that initiates from Kibana from requests that initiated on the same hosts from other curl or any other http(s) client. If kibana injects a header with ip address of the client to the request that it sends to ES, that header is available as part of audit log message.
