### ISSUE TITLE
[Bug] Multi-tenancy not working with default config

### ISSUE THREAD

**Issue by hsiang9431-amzn** [opensearch-project/security#1163]
**Describe the bug**
Default configuration in security plugin does not capture index name changed by `OpenSearch Dashboards`

Additional manual steps are required to update such config after cluster startup 

**To Reproduce**
1. Start a new cluster with security plugin
2. install demo configuration for security plugin (run `plugins/opensearch-security/tools/install_demo_configuration.sh`)
3. Multi-tenancy does not work, all visualizations are added as if in `Global` tenant

**Expected behavior**
Multi-tenancy should work

**Plugins**
Security

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
latest ubuntu docker image as of issue open date

**Additional context**
This fix requires altering default values and may break integration tests.
Given current timeline proper fix may not make it in time.

However, a work around can be applied to newly installed clusters as following:
1. install opensearch with security plugin
2. in opensearch installation path, find `plugins/opensearch-security/securityconfig/config.yml`
3. add following configuration item:
```yaml
config:
  dynamic:
    kibana:
      multitenancy_enabled: true
      server_username: kibanaserver
      index: '.opensearch_dashboards'
  ```
4. run `plugins/opensearch-security/tools/install_demo_configuration.sh`
5. startup the cluster as normal, changes for fixing this issue should be applied to the cluster

**Comment by hsiang9431-amzn** [comment]
Proposed fix regarding default configuration

Updating this line which assigns default values for dashboards index
https://github.com/opensearch-project/security/blob/aafa36d335258cfe6269c8c9bbf3ffa4a409c5f9/src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java#L140

For providing backward compatibility, add documentation for using this script:
https://github.com/opensearch-project/security/blob/main/tools/securityadmin.sh
It will require system administrator to config the cluster manually to comply with existing `.kibana` indices

**Comment by vrozov** [comment]
@hsiang9431-amzn Please follow repo convention for filing issues. Use labels instead of `[]` to classify issues.

**Comment by davidlago** [comment]
Apologies for the radio silence... This no longer seems to be an issue with the current docker images for the project. If in fact there is still an issue, please add repro steps and we'll take a look. Thanks!
