### ISSUE TITLE
Ensure backwards compatibility with ODFE

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1169]
Coming from [opensearch-plugins#12](https://github.com/opensearch-project/opensearch-plugins/issues/12), enable upgrade to OpenSearch, while supporting backward compatibility.

- [x] Rename Namespaces (e.g. `com.amazon.opendistroforelasticsearch` to `org.opensearch`)
- [x] Rename Classes, Methods, Variables 
- [x] Rename Remaining Identifiers (e.g. `Opendistro` to `OpenSearch`).
- [x] Rename, and Backwards Compatibility for Rest APIs
- [x] Rename, and Backwards Compatibility for Settings 
- [x] Rename, and Backwards Compatibility for Indices
- [x] Run in a backwards compatible way on top of OpenSearch 1.0 that has joined an ES 7.10.x cluster 
- [x] Run in a backwards compatible way on top of OpenSearch 1.0 that has joined an ODFE 1.13.x cluster 
- [x] Drop in replacement for the Opendistro version 1.13 of the plugin

**Comment by vrozov** [comment]
@dblock The list is incomplete. It is necessary to ensure backward compatibility for transport actions, serialized documents and serialized headers (wire compatibility with ES 7.10.x and ODFE 1.13).

**Comment by dblock** [comment]
> @dblock The list is incomplete. It is necessary to ensure backward compatibility for transport actions, serialized documents and serialized headers (wire compatibility with ES 7.10.x and ODFE 1.13).

Did I just poorly word "Run in a backwards compatible way on top of OpenSearch 1.0 that has joined an ODFE 1.13.x cluster"? We already have bugs such as https://github.com/opensearch-project/OpenSearch/issues/667 open. 

We can expand that to transport actions, serialized documents and serialized headers. Do you know these things as something plugins have to deal with? For security, just go ahead and edit the issue description as you see fit.

**Comment by vrozov** [comment]
"Run in a backwards compatible way on top of OpenSearch 1.0 that has joined an ODFE 1.13.x cluster" sounds more like a test plan compared to "Rename, and Backwards Compatibility for Rest APIs", so it would be better to have "Rename and Backward  compatibility for transport actions".
