### ISSUE TITLE
Add integration testing with OpenSearch

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1177]
**Is your feature request related to a problem? Please describe.**

In a conversation [here](https://github.com/opensearch-project/security/pull/1174#issuecomment-845487348) we said that _security plugin relies on unit tests_. Given how tightly coupled security is with many other plugins we may want to bring in some integration testing into the project and cover any dependencies.

**Describe the solution you'd like**

Integration testing run as part of CI.

**Comment by peternied** [comment]
Thanks @dblock closing this issue in favor of https://github.com/opensearch-project/security/issues/1761
