### ISSUE TITLE
settings usage does not trigger reading fall back keys

### ISSUE THREAD

**Issue by hsiang9431-amzn** [opensearch-project/security#1183]
Security plugin consumes `org.opensearch.common.settings.Settings` classes with hard coded keys and default values by calling methods such as `Settings.get` and all variants of it.

ref: `Settings.get` and its variants declaration:
https://github.com/opensearch-project/OpenSearch/blob/9c95cf424b405693196deb98f526b5a05916b905/server/src/main/java/org/opensearch/common/settings/Settings.java#L255

https://github.com/opensearch-project/OpenSearch/blob/9c95cf424b405693196deb98f526b5a05916b905/server/src/main/java/org/opensearch/common/settings/Settings.java#L296

These functions support coding inline default values and these values are declared across the entire security plugin code. Following are some examples for it.

https://github.com/opensearch-project/security/blob/d3f2f98ff4fd3bac5f1ef1c9c9f8e58ebb978275/src/main/java/org/opensearch/security/auditlog/sink/ExternalOpenSearchSink.java#L60

https://github.com/opensearch-project/security/blob/d3f2f98ff4fd3bac5f1ef1c9c9f8e58ebb978275/src/main/java/org/opensearch/security/privileges/SecurityIndexAccessEvaluator.java#L70

However, these functions do not trigger using fallback keys declared in code, that is, these functions supports only a single key that is passed into it. That means each line of such code supports only one possible key to read from `org.opensearch.common.settings.Settings` class. In this case, there is no easy way to support fallback values in `opensearch.yml` file when it comes to security plugin as there exist almost 150 such configurations all over the code.

To make things more challenging, there exist some constructors that take settings key as parameter in its constructor
https://github.com/opensearch-project/security/blob/d3f2f98ff4fd3bac5f1ef1c9c9f8e58ebb978275/src/main/java/org/opensearch/security/auditlog/sink/WebhookSink.java#L61

In this example, `settingsPrefix` is passed in from the constructors then immediately passed to `super` class constructor. It is later accessed in this line, which stores the value and access settings later in execution

https://github.com/opensearch-project/security/blob/d3f2f98ff4fd3bac5f1ef1c9c9f8e58ebb978275/src/main/java/org/opensearch/security/auditlog/sink/AuditLogSink.java#L46

**Comment by dblock** [comment]
@hsiang9431-amzn could you please add the details of what we discussed and decided to capture the information here?

**Comment by andy840314** [comment]
We added fallback setting only on `opendistro_security_config.ssl_dual_mode_enabled` eventually since only this setting in security plugin is a cluster setting.
PR: https://github.com/opensearch-project/security/pull/1190
