### ISSUE TITLE
[BUG] Document-level security not working with nested documents 

### ISSUE THREAD

**Issue by kostteg** [opensearch-project/security#1187]
**Describe the bug**
I have an index with some nested documents and am trying to use Document-level security feature.
When I'm trying to perform a simple search request
```
_search?pretty=true&q=*
```
I get this error:
```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "Parent query must not match any docs besides parent filter. Combine them as must (+) and must-not (-) clauses to find a problem doc. docID=1"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "my-index",
        "node" : "pWhrtIQPRdCWuw6hyeGCwQ",
        "reason" : {
          "type" : "illegal_state_exception",
          "reason" : "Parent query must not match any docs besides parent filter. Combine them as must (+) and must-not (-) clauses to find a problem doc. docID=1"
        }
      }
    ],
    "caused_by" : {
      "type" : "illegal_state_exception",
      "reason" : "Parent query must not match any docs besides parent filter. Combine them as must (+) and must-not (-) clauses to find a problem doc. docID=1",
      "caused_by" : {
        "type" : "illegal_state_exception",
        "reason" : "Parent query must not match any docs besides parent filter. Combine them as must (+) and must-not (-) clauses to find a problem doc. docID=1"
      }
    }
  },
  "status" : 500
}
```

**To Reproduce**
1. Start Opensearch and Opensearch-dashboards using `docker-compose` with docker-compose.yml using _1.0.0-beta1_ images version
2. Create index with one _text_ and one _nested_ field
```
PUT my-index
{
  "mappings": {
    "properties": {
      "field1": {
        "type": "text"
      },
      "field2": {
        "type": "nested",
        "properties": {
          "field3": {
            "type": "text"
          }
        }
      }
    }
  }
}

```
3. Put several documents to the index:
```
POST my-index/_bulk
{ "create" : { "_index" : "my-index", "_id" : "1" } }
{ "field1": "a"}
{ "create" : { "_index" : "my-index", "_id" : "2" } }
{ "field1": "b", "field2": [    {      "field3": "1"    },    {      "field3": "2"    }  ]}
{ "create" : { "_index" : "my-index", "_id" : "3" } }
{ "field1": "b"}
{ "create" : { "_index" : "my-index", "_id" : "4" } }
{ "field1": "a","field2": [    {      "field3": "1"    },    {      "field3": "2"    }  ]}

```
4. Create role in Opensearch-dashboards with _read_ index-permission + this Document-level security query
```
{
  "bool": {
    "must_not": {
      "match": {
        "field1": "a"
      }
    }
  }
}
```
5. Create user and map it to the role
6. Perform simple search request by this user
```
_search?pretty=true&q=*
```
7. See the error described above

**Expected behavior**
This search request should return all documents, except those which were filtered out by the DLS-request.
So 2 documents are expected:
```
"hits": [
      {
        "_index": "my-index",
        "_type": "_doc",
        "_id": "2",
        "_score": 0,
        "_source": {
          "field1": "b",
          "field2": [
            {
              "field3": "1"
            },
            {
              "field3": "2"
            }
          ]
        }
      },
      {
        "_index": "my-index",
        "_type": "_doc",
        "_id": "3",
        "_score": 0,
        "_source": {
          "field1": "b"
        }
      }
    ]
```

**Plugins**
Nothing special except the default plugins

**Host/Environment (please complete the following information):**
docker images _opensearchproject/opensearch:1.0.0-beta1_ and _opensearchproject/opensearch-dashboards:1.0.0-beta1_

**Additional context**
I also tried this on _OpenDistro for ElasticSearch_ docker images. Specifically, amazon/opendistro-for-elasticsearch:1.2.1 and amazon/opendistro-for-elasticsearch:1.9.0 (and corresponding Kibana) images.

**Comment by kostteg** [comment]
Started discussion on this issue here:
https://discuss.opendistrocommunity.dev/t/document-level-security-fails-with-nested-documents/6248

**Comment by andy840314** [comment]
Lucene is used to parse the document-level security query. For this to work for nested documents, you must include a field that identifies the parent document as a parent or it will throw `illegal_state_exception`.
Like this example discussed here. https://discuss.opendistrocommunity.dev/t/document-level-security-fails-with-nested-documents/6248
```
{
  "bool": {
    "must": [
      {"exists": {
        "field": "field1"
         }
      }
    ],
    "must_not": [
      {"match": {
        "field1": "a"
      }}
    ]
  }
}
```
This is actually not a bug but an implementation by Lucene.
Will close this issue for now, feel free to reopen it if there are any questions or correct me if I am wrong.

**Comment by kostteg** [comment]
Sorry, but the problem is that [simple DLS-query + some existing nested documents in my index] => just breaks the "q=*" query. This query (at least from the client-side) doesn't deal with nested documents at all (and neither does DLS-query).
So this looks like a bug.

Thank you for the link to the related discussion on discuss.opendistrocommunity.dev but actually it was me who started that discussion ^_^.
The workaround mentioned there does work indeed. But, as I said in that discussion, I don't understand why that workaround is needed at all. I glanced over the relevant Lucene source and there is already some code which deals with nested docs if they exist in the index https://github.com/opensearch-project/security/blob/2b69d9c84d807fc68b3ad9770d8bb75f6b99e725/src/main/java/org/opensearch/security/configuration/DlsQueryParser.java#L144

P.S.
Github doesn't allow me to reopen this issue, could you please reopen it @andy840314

**Comment by andy840314** [comment]
> Thank you for the link to the related discussion on discuss.opendistrocommunity.dev but actually it was me who started that discussion ^_^.

Yes, i know you started the discussion. Sorry forgot to mention that. Just want to mention the example in the discussion.

I am wrong about my comments above. There is definitely an issue since this happens when using only `must_not` clause.
The exception comes from here.
https://github.com/opensearch-project/security/blob/2b69d9c84d807fc68b3ad9770d8bb75f6b99e725/src/main/java/org/opensearch/security/configuration/DlsQueryParser.java#L161
It could be that `parentDocumentsFilter` contains all non-nested docs so when you use `must_not` clause only, it also matches nested docs and this results in the exception.
If you provide `must: exist: field: "field1"`, it matches only the non-nested docs so the query works.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
