### ISSUE TITLE
Support for custom OAuth services

### ISSUE THREAD

**Issue by braunsonm** [opensearch-project/security#119]
Hello,

I'd like to add my organizations OAuth provider as a security endpoint for kibana. Is this functionality on the roadmap?

Thanks

**Comment by minhdanh** [comment]
Any updates on this?

**Comment by nateynateynate** [comment]
Pardon the radio silence on this one. If I might be so bold as to ask you to to give the latest release of OpenSearch a try. If your OAuth provider supports the OpenID standard, you should be able to configure it with the help of 

https://opensearch.org/docs/latest/security-plugin/configuration/openid-connect/

Feel free to reopen if necessary!
