### ISSUE TITLE
Add code lint and checkstyles to the repository

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/security#1201]
**Is your feature request related to a problem? Please describe.**
Set some code linter and checkstyles for the repository.
Every PR sees a bunch of whitespace, indentation etc comments instead an automatic linter and rules should make life easier.
This should be added to gradle and verified in CI.

**Describe the solution you'd like**
We should be able to use: https://github.com/diffplug/spotless/tree/master/plugin-maven
Ref to other plugin: https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L473

**Comment by saratvemulapalli** [comment]
Not sure why I was assigned. This was a recommendation and security team should decide and implement whats best for you.

**Comment by vrozov** [comment]
@saratvemulapalli There is no common code style that can be applied to the security plugin. Please feel free to implement one.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
