### ISSUE TITLE
How to report security vulnerabilities which are not novel?

### ISSUE THREAD

**Issue by cjcjameson** [opensearch-project/security#1208]
**Describe the bug**

The policy at https://github.com/opensearch-project/.github/edit/main/SECURITY.md assumes that the person is reporting a novel security defect. I agree that novel security defect reporting should follow a process like that.

What if we want to call out that there's been a CVE in a dependency that this repository takes, and ask that the library be upgraded?

**To Reproduce**

My company's security team thinks this is insecure software because it brings Dependency Foo v1.2.3 <redacted url>

I'm unsure whether I can mention that in this issue tracker

**Expected behavior**

If it's already on the nvd.nist.gov , I should just create an issue. Or a PR if I'm so inclined.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!

**Comment by peternied** [comment]
@cjcjameson This is a great question, we've got the codebase configured with dependabot to file issues, for example see _CVE-2022-38751 (Medium) detected in snakeyaml-1.31.jar_ - https://github.com/opensearch-project/security/issues/2071

If you know about an issue in a dependency that can be updated we are happy to receive pull requests to resolve these issues, thanks for the contribution you made in https://github.com/opensearch-project/security/pull/1210

If there isn't a clear path forward please use caution and use AWS/Amazon Security [vulnerability reporting page](http://aws.amazon.com/security/vulnerability-reporting/) or directly via email to aws-security@amazon.com - it will get to us with urgency so we can figure out how to best respond.
