### ISSUE TITLE
securityadmin.sh overwrites config

### ISSUE THREAD

**Issue by celesteking** [opensearch-project/security#1250]
There MUST be something done with your documentation guys. Really, why would you tell users to re-run `securityadmin.sh` if you effectively destroy all existing configuration and upload the one that's defined by configs. Why not just try to merge it instead? 

Why not put a red warning in docs that running this script will erase all their config?

I had to modify admin user config to include a snapshot restore role (why not include that by default?!) and reran the script which erased hours of work.

**Comment by dblock** [comment]
ouch, cc: @aetter

**Comment by vrozov** [comment]
@celesteking security plugin provides REST API to add (merge) role to the existing roles, there is no need to re-run securityadmin.sh for that use case. The securityadmin is mostly designed for backup and restore use case.

@aetter Please close this issue after updating documentation.

**Comment by aetter** [comment]
I'm in complete agreement that we should offer some sort of merge option on the script. Blowing away the existing configuration without a word of warning in the script itself flies in the face of user expectations, and it's the only way to add new reserved or hidden users. Until we improve the script, I've added an extensive warning section here: https://github.com/opensearch-project/documentation-website/pull/135

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
