### ISSUE TITLE
[BUG] _cat/nodes is missing details during rolling upgrade

### ISSUE THREAD

**Issue by skkosuri-amzn** [opensearch-project/security#1276]
**Describe the bug**

> curl https://localhost:9200/_cat/nodes?v -u admin:admin --insecure
> ip        heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
> 127.0.0.1           61          99   0    0.05    0.08     0.08 dimr      *      <xxx>-skkosuri-1111111>.amazon.com
> 127.0.0.1           12          99   0    0.05    0.08     0.08 dimr      -      <xxx>-skkosuri-1111111>.amazon.com
> 127.0.0.1                                                                        dimr      -      <xxx>-skkosuri-1111111>.amazon.com
> 

Missing heap.percen, ram, cpu for the new OpenSearch node.

**To Reproduce**
1. Setup 3 node ODFE cluster (yml changes 9300, 9301, 9302)
2. Ingest data to an index.
3. Setup few cluster settings.
4. Shutdown one node and replace with OpenSearch node.
Copy the *data* folder and yml config to OpenSearch
5. Do a GET /_cluster/settings on the OpenSearch node.
curl https://localhost:9200/_cat/nodes?v -u admin:admin --insecure

**Expected behavior**
All _cat/nodes details must be present for all nodes including new OpenSearch node

**Host/Environment (please complete the following information):**
Linux -AL2
**Additional context**

**Comment by skkosuri-amzn** [comment]
> I'll leave this issue open and transfer to security but my hunch it feels like the original problem after solving it should solve this one too.

Very much possible. I dont remember seeing this without security plugin on your system.

**Comment by andy840314** [comment]
This issue is no longer seen when the namespaces are reverted back. Definitely is related to this issue #1259

**Comment by vrozov** [comment]
duplicate of #1259.
