### ISSUE TITLE
Standardize branching to match OpenSearch

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1296]
Coming from [.github#13](https://github.com/opensearch-project/.github/issues/13), standardize release branching to match what [OpenSearch](https://github.com/opensearch-project/OpenSearch) is [doing](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#branching).

1. Create a `1.0` branch for the OpenSearch 1.0 release, `1.x` branch for next 1.1 release, and use `main` for 2.0 development. Make sure CI is enabled on those.
2. Update your release/branching documentation. If you don't have one, add a RELEASING.md that links to, or has content from [.github/RELEASING.md](https://github.com/opensearch-project/.github/blob/main/RELEASING.md).
3. If you are using a `develop` branch, stop. You should be using the default `main` brach for furthermost, future development. 
4. Delete any merged/stale/develop/feature branches that are no longer in use.
5. Communicate any changes in process to your team.

Refer to [release branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#branching) for more information.

**Comment by vrozov** [comment]
I'd like to discuss the branching strategy and see if it is the best option for the security plugin. Please keep the issue open till I am back in 2 weeks.

**Comment by dblock** [comment]
> I'd like to discuss the branching strategy and see if it is the best option for the security plugin. Please keep the issue open till I am back in 2 weeks.

OpenSearch GA is July 12, so that's too late. Please assign this issue to someone who's not OOO.

**Comment by CEHENKLE** [comment]
@vrozov this is not an area we can have different repos in opensearch using different approaches.  If you have concerns, raise them here, but keep in mind it's something that needs to apply to all repos.  Additionally, we're need to standardize for builds  before GA, so as @dblock said, please delegate while you are out.

**Comment by cliu123** [comment]
There was a discussion on the branching strategy in rc1 release. We can revisit that discussion before making this decision.

**Comment by cliu123** [comment]
Discussed with @dblock, It will be fine only to create branches as needed. OpenSearch is doing parallel development for `1.x` and `2.0`(might have some backward incompatible features), which is why OpenSearch cut `1.x` branch for future `1.1`, `1.2`, and `1.3` etc releases. Security plugin is going to cut `1.0` branch as soon as OpenSearch release 1.0 gets launched, cut `1.x` branch when it is needed and document the branching/releasing strategy in `RELEASING.md` file.

**Comment by dblock** [comment]
Re: needed, it sounds like https://github.com/opensearch-project/security/pull/1256#discussion_r659029106 should go into 1.1, and right now you don't have a place to merge it on

**Comment by cliu123** [comment]
> it sounds like #1256 (comment) should go into 1.1, and right now you don't have a place to merge it on

It will stay in `main` and will be a part of next OpenSearch release.

**Comment by dblock** [comment]
I think we are revisiting this plan to be more flexible given what's happening in 1.1, see https://github.com/opensearch-project/.github/pull/33/files for a proposal.
