### ISSUE TITLE
[Feature] Be able to aggregate users via their roles

### ISSUE THREAD

**Issue by asfoorial** [opensearch-project/security#1301]
Need to enable adding roles to other roles so that the role mapping of the containing role will be updated automatically to have all (direct and in-direct) users in the sub-roles. 

Example: Below is an example with two roles
Role Name: all_employees
Role mapping: user1, user2 

Role Name: engineers
Role mapping: user3, user4 

After adding engineers to all_employees then the role mapping of all_employees become (user1, user2, user3, user4. 

Removing engineers from all_employees will also result in removing (user3, user4) from the role mapping of all_employees.

**Comment by scrawfor99** [comment]
[Triage] This feature remains a relevant request. Adding the "help wanted" tag. Similar somewhat to #98.

**Comment by davidlago** [comment]
Closing in favor of #98 to track in a single place.
