### ISSUE TITLE
Maven or Gradle?

### ISSUE THREAD

**Issue by frotsch** [opensearch-project/security#1306]
Is this project supposed to be build with gradle or maven? I see a pom.xml file as well as a build.gradle file. One of them should be removed IMHO.

When trying to build with gradle I get a `Missing -ParchivePath command line switch pointing to built plugin ZIP` error message.

**Comment by vrozov** [comment]
The project uses maven to build everything except for Linux distributions packages. Please see README for the details on how to build.

**Comment by dblock** [comment]
@frotsch if you want to contribute some more content into https://github.com/opensearch-project/security/blob/main/DEVELOPER_GUIDE.md that would be appreciated
