### ISSUE TITLE
Support for custom header for Authorization for Basic HTTP auth  

### ISSUE THREAD

**Issue by abbashus** [opensearch-project/security#1332]
**Is your feature request related to a problem? Please describe.**
Currently HTTP Basic authentication uses `Authorization` header for extracting username and password from request.
We have a use case where the header is either remapped to a different header for example `Authorization` -> `X-Amzn-Remapped-Authorization` or completely consumed if `Authorization` contains [Signature Version 4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) signature by AWS API Gateway.

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html

**Describe the solution you'd like**
A way in the `securityconfig/config.yml` file to define the custom header used for authentication.

If security plugin already has this feature please guide us to the right documentation.

**Comment by andy840314** [comment]
Security plugin currently does not have this feature. We will have to do some investigation about the security concerns about this.

**Comment by scrawfor99** [comment]
[Triage] Closing this issue because of significant security concerns. A workaround solution would be to add a proxy in-front of OpenSearch and routing through there. Thank you.
