### ISSUE TITLE
Review Usages of actionGet API Call

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/security#1336]
**Describe the bug**
Review usages of actionGet API calls so that this API if being called in a single threaded pool should use timeouts or should be called asynchronously. 

PRs in alerting (https://github.com/opensearch-project/alerting/pull/130) and index management (https://github.com/opensearch-project/index-management/pull/100) where we have replaced the usages of the actionGet API calls which are blocking in nature and block the execution of the program with the callback listeners for the API call response. Using this API with time outs is okay but the execution should be made asynchronous. 

Sample Usage in Security: 

https://github.com/opensearch-project/security/blob/13f888f735a9bef7cb3b80aac07f5bebaaaa08cc/src/main/java/org/opensearch/security/tools/SecurityAdmin.java#L565

https://github.com/opensearch-project/security/blob/13f888f735a9bef7cb3b80aac07f5bebaaaa08cc/src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java#L216

https://github.com/opensearch-project/security/blob/13f888f735a9bef7cb3b80aac07f5bebaaaa08cc/src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java#L232

https://github.com/opensearch-project/security/blob/13f888f735a9bef7cb3b80aac07f5bebaaaa08cc/src/main/java/org/opensearch/security/auditlog/sink/InternalOpenSearchSink.java#L78

We should review all such usages.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
