### ISSUE TITLE
Security for cross cluster replication. 

### ISSUE THREAD

**Issue by saikaranam-amazon** [opensearch-project/security#1337]
*Background on Replication*
- Replication runs as a background task and fetches the latest operations on the leader and replays them onto the follower.
- These requests are triggered as transport actions at both leader/follower cluster. 
- With security enabled on both the clusters, these actions should be authorized at each cluster

*Replication API Sample API*
Below is sample request for the start API - `use_roles` tracks the roles used by the replication to authorize requests at leader cluster and follower cluster. 
- Replication needs validation on these roles against the user at both leader and follower cluster.
```
PUT localhost:9200/_plugins/_replication/customer/_start
Content-Type: application/json
Authorization: admin:admin

{  
   "leader_cluster" : "source",  
   "follower_index": "customer",
   "use_roles": {
        "leader_cluster_role": "role1",
        "follower_cluster_role": "role2"
   }
}
```

*Role Injection support for Cross cluster replication*
 - Cross cluster replication needs a way to authorize requests at the remote cluster end.

*Role Validation*
- User can be associated with multiple roles. Privileges check against the transport actions happens based on all these roles combined. 
- For other plugins, there is no direct way to force the evaluation to certain role(s) to see if the permissions to transport actions are associated with these respective role(s).
- In order to force the evaluation and validation check for certain transport actions, Plugins can pass `validate_roles` transients and security plugin will choose these roles to evaluate the permissions for the triggered transport actions.
- If the evaluation succeeds, the request goes through and plugins will be able to associate/remember these certain roles for the rest of the actions (that can be triggered as part of role injection).

*Flow for start API(with validation checks)*

![Cross_Cluster_Replication_Security_PR_Flow](https://user-images.githubusercontent.com/71428218/133106906-57beff2b-6e75-46a6-aa2f-2316ee7b37cf.jpg)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by saikaranam-amazon** [comment]
> As discussed lets add architecture diagram, sample APIs, end to end call flow here with proper example.

Updated the issue description with the relevant details.

**Comment by scrawfor99** [comment]
[Triage] Closing because we have already integrated CCR.
