### ISSUE TITLE
CI for backport PRs to opendistro branches fail

### ISSUE THREAD

**Issue by vrozov** [opensearch-project/security#1338]

**Comment by andy840314** [comment]
Adding some details.
It happens specifically on 1.2, 1.3, 1.5, 1.6, 1.7. The CI gets stuck and keeps spitting the following error message.

`2021-07-23T18:22:46.8129418Z [2021-07-23T18:22:46,809][ERROR][com.amazon.opendistroforelasticsearch.security.configuration.ConfigurationLoaderSecurity7] Failure No shard available for [org.elasticsearch.action.get.MultiGetShardRequest@7b85d0ef] retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN] (index=.opendistro_security)`

**Comment by vrozov** [comment]
I see couple of issues here:
- CI should not get stuck (should timeout). 
- Please see why `.opendistro_security` index shards are not getting allocated to nodes

**Comment by peternied** [comment]
We are not supporting backporting to opendistro branches, support for them has been discontinued
