### ISSUE TITLE
[BUG] open distro index name in 1.0.0 opensearch cluster

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/security#1362]
**Describe the bug**
Freshly built cluster generates this security index:
![image](https://user-images.githubusercontent.com/2643715/127624571-d249247b-bf9e-403b-9436-ab0fa9048d08.png)

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by andy840314** [comment]
Considering backward incompatibility, we decided not to change the index names. This index name is expected.
