### ISSUE TITLE
Give the hash.sh input for password

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/security#1391]
**Is your feature request related to a problem? Please describe.**
When I'm generating passwords, I can't see what I'm pasting into the hash.sh utility (it doesn't show stars or anything). It can't be used programmatically to generate a bunch of passwords. 

**Describe the solution you'd like**
Let me provide the password as an command line input argument (i.e. ./hash.sh -p thepassword) and output only the generated hash.

**Describe alternatives you've considered**

**Additional context**

**Comment by scrawfor99** [comment]
[Triage] Closing because resolved.
