### ISSUE TITLE
Correct copyright notices to reflect Copyright OpenSearch Contributors

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1395]
Coming from https://github.com/opensearch-project/.github/issues/21.

The correct copyright for open-source projects in opensearch-project is "Copyright OpenSearch Contributors". Please correct any places that say otherwise, especially where it says copyright Amazon. Make sure NOTICE.txt and README match. See https://github.com/opensearch-project/.github/pull/24 for an example.

**Comment by vrozov** [comment]
@dblock Removing copyright from existing files that are already copyrighted does not sound right to me.

**Comment by dblock** [comment]
@vrozov IANAL, but this has been reviewed by an attorney, I believe because we hold copyright we are allowed to update it for future code/releases
