### ISSUE TITLE
Trying to push configs with securityadmin.sh to no success 

### ISSUE THREAD

**Issue by mkapoor17** [opensearch-project/security#140]
I want to push the configuration files with securityadmin.sh, but i get the following error from OpensDistro:

```
Elasticsearch Version: 7.1.1
Open Distro Security Version: 1.1.0.0
Fail-fast is activated
Diagnostic trace written to: /usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin_diag_trace_2019-Sep-12_18-01-30.txt
Contacting elasticsearch cluster 'elasticsearch' ...
Clustername: es-opendistro-dev
Clusterstate: YELLOW
Number of nodes: 5
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from /usr/share/elasticsearch/plugins/opendistro_security/securityconfig
Will update '_doc/config' with ../securityconfig/config.yml
   FAIL: Configuration for 'config' failed because of ElasticsearchSecurityException[Open Distro Security not initialized for indices:data/write/bulk[s]]
Will update '_doc/roles' with ../securityconfig/roles.yml
   FAIL: Configuration for 'roles' failed because of ElasticsearchSecurityException[Open Distro Security not initialized for indices:data/write/bulk[s]]
Will update '_doc/rolesmapping' with ../securityconfig/roles_mapping.yml
   FAIL: Configuration for 'rolesmapping' failed because of ElasticsearchSecurityException[Open Distro Security not initialized for indices:data/write/bulk[s]]
Will update '_doc/internalusers' with ../securityconfig/internal_users.yml
   FAIL: Configuration for 'internalusers' failed because of ElasticsearchSecurityException[Open Distro Security not initialized for indices:data/write/bulk[s]]
Will update '_doc/actiongroups' with ../securityconfig/action_groups.yml
   FAIL: Configuration for 'actiongroups' failed because of ElasticsearchSecurityException[Open Distro Security not initialized for indices:data/write/bulk[s]]
Will update '_doc/tenants' with ../securityconfig/tenants.yml
   FAIL: Configuration for 'tenants' failed because of ElasticsearchSecurityException[Open Distro Security not initialized for indices:data/write/bulk[s]]
```
I've confirmed that we aren't overwriting the `all_access` role in roles.yml. Addtionally, we have `opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]` set in our elasticsearch.yml.
I have in `indices:data/write/bulk[s]]` initialized in action_groups, not really sure why this exception is occurring. Would really appreciate some guidance as this has been troublesome for me.

**Comment by KelvinHeHeHe** [comment]
Clusterstate is green for me, but I have the same issue after running the script, any solution?
Thanks.

**Comment by braunsonm** [comment]
Same issue here, haven't been able to find a solution.

**Comment by KelvinHeHeHe** [comment]
> Clusterstate is green for me, but I have the same issue after running the script, any solution?
> Thanks.

![2](https://user-images.githubusercontent.com/57084483/76827891-c0d8cb00-685a-11ea-9aa8-b50f5670bbe0.PNG)
![1](https://user-images.githubusercontent.com/57084483/76827895-c2a28e80-685a-11ea-9bb3-6c7aeab594b3.PNG)

Upload more screenshot for reference.

**Comment by KelvinHeHeHe** [comment]
Finally, I remove all the data under the location "/var/lib/elasticsearch/nodes", then restart elasticsearch service, it works.

**Comment by nateynateynate** [comment]
Thanks for bringing your question here, @mkapoor17 . 

I can't quite tell if @KelvinHeHeHe 's suggestion ever solved your issue or not, but since the time of your request for help the Open Distro made it all the way to 1.13, at which time the OpenSearch project absorbed and replaced it. I can't help but notice your output was from OpenDistro 1.1. 

I suggest you try again using the latest OpenSearch (https://opensearch.org/downloads.html) if this is still an issue for you.  If you end up needing further community help after that, there's always good help to be found in the OpenSearch forums (https://discuss.opendistrocommunity.dev/)
