### ISSUE TITLE
[BUG] Return HTTP 409 on version confict when creating & updating tenants

### ISSUE THREAD

**Issue by phillbaker** [opensearch-project/security#1402]
**Describe the bug**

Hello, I opened https://github.com/opensearch-project/security/issues/1095 earlier, which has recently been fixed (thanks!), but it looks like a HTTP 500 (instead of 409) is being returned for the tenant endpoint as well. This is related to https://github.com/phillbaker/terraform-provider-elasticsearch/issues/206.

When OpenDistro receives parallel requests to create or update tenants (`/_opendistro/_security/api/tenants/{name}`), it returns an HTTP 500 response.

Similar to Elasticsearch itself, these conflict exceptions should return a http 409 instead of a 500 to signal that this is an expect error case and a retry is expected.

**To Reproduce**
1. Issue concurrent PUT requests to the tenant endpoint, e.g. `/_opendistro/_security/api/tenants/tenant_1`, `/_opendistro/_security/api/tenants/tenant_2`
2. See 500

**Expected behavior**
A HTTP 409 instead of HTTP 500.

**Plugins**
Opendistro

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 
 - Version 20.04.2

**Additional context**
N/A

**Comment by scrawfor99** [comment]
[Triage] Issue is still relevant and being labelled as a "good first issue". Thank you.

**Comment by prabhask5** [comment]
This issue might be deprecated because when I try to test it I get a 409 error, let me know if I'm doing anything wrong here:
![Screenshot 2023-10-18 at 9 58 04 PM](https://github.com/opensearch-project/security/assets/66924475/ec33ba54-ee31-4cf7-b2cc-8042e8296985)

**Comment by cwperks** [comment]
From the code, it does look like this may have been resolved at one point. Thank you for confirming.

The relevant API is [TenantsApiAction](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/dlic/rest/api/TenantsApiAction.java) which is now a subclass of AbstractApiAction which has support for handling [conflicts](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/dlic/rest/api/AbstractApiAction.java#L465). FYI HTTP status code 409 is the status code for [conflict](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409).

**Comment by prabhask5** [comment]
> @prabhask5 if a test doesn't exist around this behavior, would it make sense to create one?
> 
> I see a similar test for the Users API endpoints [here](https://github.com/opensearch-project/security/blob/main/src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java#L123-L152), but I don't see any around tenants.

Sure! I can make a PR to add this test
