### ISSUE TITLE
[BUG] Snapshot build doesn't produce a snapshot build or an artifact named with -SNAPSHOT

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1403]
**Describe the bug**

Coming from https://github.com/opensearch-project/opensearch-build/pull/189, attempting to build a snapshot version of this plugin:

```
mvn -B clean package -Padvanced -DskipTests -Dopensearch.version=1.0.0-SNAPSHOT -Dbuild.snapshot=true
```

produces `target/releases/opensearch-security-1.0.0.0.zip`, I expected it to produce `opensearch-security-1.0.0.0-SNAPSHOT.zip` like other plugins.

or for it to get renamed in output from assembly step?

```
./gradlew build buildDeb buildRpm --no-daemon -ParchivePath=target/releases/opensearch-security-1.0.0.0.zip -Dbuild.snapshot=true
```

**Expected behavior**

Produce `opensearch-security-1.0.0.0-SNAPSHOT.zip` and any other artifact to include `-SNAPSHOT` as well as internal version to include SNAPSHOT so that we don't accidentally promote snapshot builds to release.

**Comment by vrozov** [comment]
@dblock `-Dbuild.snapshot=true` is a gradle option, not a maven option. Passing it to maven does not make maven to build snapshot.

**Comment by dblock** [comment]
> @dblock `-Dbuild.snapshot=true` is a gradle option, not a maven option. Passing it to maven does not make maven to build snapshot.

How do I build a snapshot version of the security plugin?

**Comment by dblock** [comment]
With changes in https://github.com/opensearch-project/security/pull/1409, building a `-SNAPSHOT` version against OpenSearch 1.1. works like so:

```
mvn -B clean package -Padvanced -DskipTests -Dopensearch.version=1.1.0-SNAPSHOT
artifact_zip=$(ls $(pwd)/target/releases/opensearch-security-*.zip | grep -v admin-standalone)
./gradlew assemble --no-daemon -ParchivePath=$artifact_zip -Dopensearch.version=1.1.0-SNAPSHOT
```

**Comment by dblock** [comment]
#1409 was closed in favor of https://github.com/opensearch-project/opensearch-build/pull/356
