### ISSUE TITLE
Remove ISM and Alerting index from proteted,system indices

### ISSUE THREAD

**Issue by Jakob3xD** [opensearch-project/security#1411]
**Is your feature request related to a problem? Please describe.**
The Alerting and the ISM Plugin wont work correctly when using the options `plugins.security.protected_indices.indices` or `plugins.security.system_indices.indices` defined in the `securityconfig/opensearch.yml.example` file.

**Describe the solution you'd like**
Allow the Opensearch System to use `'.opendistro-alerting-config', '.opendistro-ism-config'` even when they are marked as protected or system index.

**Describe alternatives you've considered**
Remove `'.opendistro-alerting-config', '.opendistro-ism-config'` from the example files.
Maybe it would also make sense to give a hint to NOT add those indices to the config.

**Additional context**
I opened an issue for that in the ISM repository but as it is also affecting alerting I opened the issue here and closed the other one.
https://github.com/opensearch-project/index-management/issues/120

**Comment by skkosuri-amzn** [comment]
@Jakob3xD We removed protected-indices config from the `securityconfig/opensearch.yml.example` .
Could you pls provide more details on the error you are getting with system-indices config. More details on system indices: [link](https://opensearch.org/docs/security-plugin/configuration/system-indices/)

**Comment by Jakob3xD** [comment]
@skkosuri-amzn Sorry for the late response.
## System Indices
### `.opendistro-alerting-config` 
It is not possible to perform any API action. The API will respond with `{"statusCode":401,"error":"Unauthorized","message":"Authentication required"}`.

###  `.opendistro-ism-*`
It is not possible to create policies and indices will not initiate with a policy.
Creating a policy: `[security_exception] no permissions for [] and User [name=jakob, backend_roles=[some.backend.role], requestedTenant=]`
```
[2021-09-06T08:38:38,150][WARN ][o.o.s.c.SecurityFlsDlsIndexSearcherWrapper] [host1.example.com] search action for .opendistro-ism-config is not allowed for a non adminDN user
[2021-09-06T08:38:38,158][WARN ][o.o.s.p.SecurityIndexAccessEvaluator] [host1.example.com] indices:data/write/index for '.opendistro_security' index is not allowed for a regular user
```
## Protected Indices
### `.opendistro-alerting-config`
It is possible to create resources via the API and the Dashboard but the dashboard will not display any resource.

###  `.opendistro-ism-*`
It is possible to create policies but the will not initiate when applied to an index.
It will only display the following message without further details:
`"message": "Fail to load policy: policy_xy"`

**Comment by dr-travis** [comment]
Has this issue been solved? I encountered similar problem on aws opensearch.

**Comment by scrawfor99** [comment]
[Triage] Hi @Jakob3xD, following up on this issue it looks like you may be able to resolve your problem by modifying the default demo configuration file found [here](https://github.com/opensearch-project/security/blob/main/tools/install_demo_configuration.sh). Please file a new issue if this does not resolve you issue. Thank you.
