### ISSUE TITLE
Add maven wrapper plugin to the project

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/security#1413]
**Is your feature request related to a problem? Please describe.**

Similar to Gradle wrapper, provide a Maven wrapper for this project.  This enables users to have a fully encapsulated build setup provided by the project.

**Describe the solution you'd like**
There is wrapper plugin for maven (https://github.com/takari/maven-wrapper) which is going to be a default wrapper in Maven 4.0.

Adding this wrapper plugin to this project, makes life easier for users as they don't have to manage different versions of Maven locally.  This also helps the CI system not to worry about managing Maven versions as well.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by vrozov** [comment]
I'd prefer to wait till Apache Maven accepts maven wrapper as a contribution.

**Comment by adnapibar** [comment]
> I'd prefer to wait till Apache Maven accepts maven wrapper as a contribution.

It is already accepted and released as part of maven 4 which is to be released yet. 
https://github.com/apache/maven-wrapper-plugin
https://issues.apache.org/jira/projects/MWRAPPER/issues/MWRAPPER-13?filter=allopenissues

So, for this version of maven this is the plugin to be used.

**Comment by vrozov** [comment]
It needs to be part of the official Apache maven release and looks like will require upgrade to maven 4.0. Relying on a project that is not backed by Apache Maven may limit our ability to upgrade maven version to the next minor release.

**Comment by davidlago** [comment]
Closing as we will be moving to Gradle soon.
