### ISSUE TITLE
Pull request template is asking for things it should't be

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1423]
**Describe the bug**

Contributors to OpenSearch no longer are asked to confirm the following:

<img width="872" alt="Screen Shot 2021-08-24 at 5 43 10 PM" src="https://user-images.githubusercontent.com/542335/130694052-b07291e3-91ba-4110-abad-7e986476d4a9.png">

Please update the PR template from https://github.com/opensearch-project/.github/blob/main/PULL_REQUEST_TEMPLATE.md.

**Comment by elfisher** [comment]
I'd recommend updating the PR template to follow [the template](https://github.com/opensearch-project/.github/blob/main/PULL_REQUEST_TEMPLATE.md) in .github to be consistent with other repos in the organization

**Comment by davidlago** [comment]
Closed with #1543
