### ISSUE TITLE
[BUG] Confusing index template permissions level

### ISSUE THREAD

**Issue by davidshtian** [opensearch-project/security#1432]
**Describe the bug**
Try to add index template to role and map to a user, due to official [Access Control Permissions docs](https://opensearch.org/docs/security-plugin/access-control/permissions/), I tried to add **index permission** to the role.

For the new [index template] (https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html#index-templates), the setting _"indices:admin/index_template/get"_ (also this permission is not included in [Access Control Permissions docs](https://opensearch.org/docs/security-plugin/access-control/permissions/)) is okay.

However, for the [legacy template](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates-v1.html), the setting _"indices:admin/template/get"_ is not working, and I need to add this permission to cluster level permissions, and it works.

**To Reproduce**
1. Go to 'Security/Roles'
2. Click on 'Create role'
3. Add permission _"indices:admin/template/get"_ to **Index permissions**
4. See error below:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "no permissions for [indices:admin/template/delete] and User [name=template, backend_roles=[], requestedTenant=__user__]"
      }
    ],
    "type" : "security_exception",
    "reason" : "no permissions for [indices:admin/template/delete] and User [name=template, backend_roles=[], requestedTenant=__user__]"
  },
  "status" : 403
}
```
5. Add permission _"indices:admin/template/get"_ to **Cluster permissions**, and the query executed successfully.

**Expected behavior**
Modify the _"indices:admin/index_template/get"_ permission to index level as its name showed.

**Plugins**
Security plugin.

**Screenshots**
Not working setting:
![image](https://user-images.githubusercontent.com/14228056/130817151-2e3fd869-4ff3-42a0-9ff4-9cb28b36d74f.png)
Working setting:
![image](https://user-images.githubusercontent.com/14228056/130817321-fab4b2d9-476e-4d5c-b87e-93f4e53eddd1.png)

**Host/Environment (please complete the following information):**
 - OS: Amazon Linux release 2
 - Version 1.0.0

**Additional context**
N/A

**Comment by CEHENKLE** [comment]
Transferring issue to security plugin in.  Please let me know (@) if this is the wrong location.   Thanks!

**Comment by scrawfor99** [comment]
[Triage] @cwperks could you take a minute to review this when you get a chance. Thank you.

**Comment by cwperks** [comment]
Closing this issue as there is a related issues in dashboards to solve this problem with UX:

- https://github.com/opensearch-project/security-dashboards-plugin/issues/1347
- https://github.com/opensearch-project/security-dashboards-plugin/issues/1346

There is a related PR in the security-dashboards-plugin to add all actions to the dropdowns:

- https://github.com/opensearch-project/security-dashboards-plugin/pull/1333
- There needs to be an associated PR with the documentation website to add the actions to the permissions page: https://opensearch.org/docs/latest/security/access-control/permissions/
- As pointed out, the legacy `indices:admin/template/*` permissions are cluster permissions even though they are prefixed with `indices:`. This should be reflected on the permissions page on the documentation website
