### ISSUE TITLE
Unable to map AD user created in AD server with special characters in roles->mappings.

### ISSUE THREAD

**Issue by dishabodade** [opensearch-project/security#1433]
# LDAP user with some special characters if tried to map in roles->mappings, respective role does not get assigned to that user.

We configure AD server with ODFE setup and tried to access ODFE using AD users.
for that, we tried to map a particular AD user to full_access role form mappings.
The users created in AD server are "testuser()!#$%" and "testuser"

**case1 :** tried to map testuser to role full_access - its working fine, roles gets assigned to that user.

**case2:** tried to map testuser()!#$% to role full_access - its not working,  role has not assigned to that user.

**case3:** created a group in AD server, added user with special characters in that group and mapped that group as a backend role to role full_access - its working fine, role gets assigned to user.

**Expected behavior**
Either it should allow users with special characters or it should show a proper error message that map user should not contain specific special characters. And if user with specific special characters are there, create a group and add that group as a backend role.

**Plugins**
All plugins are installed.

## OpenDistro Version
1.13.2.0  
docker image : amazon/opendistro-for-elasticsearch:1.13.2

**OpenDistro-for-elasticsearch Version**
1.13.2.0
docker image: amazon/opendistro-for-elasticsearch:1.13.2

**Plugins**
All plugins provided by opendistro

**Host/Environment (please complete the following information):**
 - OS: ubuntu server 18.04.04
 - Browser and version : chrome Version 92.0.4515.159 (Official Build) (64-bit)

**Additional context**
It's not a show stopper, but for tracking purposes logging it.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
