### ISSUE TITLE
Add script to easilly generate certificates

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/security#1446]
**Is your feature request related to a problem? Please describe.**
I'm having a lot trouble generating new certificates for open search. I have encountered this with Open Distro as well. I tried getting the DN's from the original certificates, but it still gives errors:

```
#!/bin/sh
#DN's are from the default configs
openssl genrsa -out root-ca-key.pem 2048
openssl req -new -x509 -sha256 -key root-ca-key.pem -subj "/DC=com/DC=example/O=Example Com Inc./OU=Example Com Inc. Root CA/CN=Example Com Inc. Root CA" -out root-ca.pem
openssl genrsa -out admin-key-temp.pem 2048
openssl pkcs8 -inform PEM -outform PEM -in admin-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out admin-key.pem
openssl req -new -key admin-key.pem -subj "/C=de/L=test/O=client/OU=client/CN=kirk" -out admin.csr
openssl x509 -req -in admin.csr -CA root-ca.pem -CAkey root-ca-key.pem -CAcreateserial -sha256 -out admin.pem
openssl genrsa -out esnode-key-temp.pem 2048
openssl pkcs8 -inform PEM -outform PEM -in esnode-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out esnode-key.pem
openssl req -new -key esnode-key.pem -subj "/DC=de/L=test/O=node/OU=node/CN=node-0.example.com" -out esnode.csr
openssl x509 -req -in esnode.csr -CA root-ca.pem -CAkey root-ca-key.pem -CAcreateserial -sha256 -out esnode.pem
rm admin-key-temp.pem
rm admin.csr
rm esnode-key-temp.pem
rm esnode.csr
rm root-ca.srl
```

![image](https://user-images.githubusercontent.com/2643715/125843329-8ad17689-cb5f-4382-8aa6-79bc0968c3e7.png)

Nodes won't accept the certs. Can you post a convenient script like this where you just have to enter some var's and it'll generate the certs? 

The inital setup command has the certs embedded as well, but that leaves the cluster wide open for penetration if you don't update the admin cert.

**Describe the solution you'd like**
Simple script to generate a set of certs which nodes will accept (with the k8s cluster I don't mind the certs being the same for the nodes)

**Describe alternatives you've considered**

**Additional context**

**Comment by peternied** [comment]
@vrozov Could you look into this request?

**Comment by ict-one-nl** [comment]
This has improved with the improved documentation with regard to the certificates. But it would be beneficial to not have the same admin cert every time a new cluster is deployed. This poses a security risk when a user does not know this.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
