### ISSUE TITLE
[BUG] Move json-smart into dev dependencies?

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1455]
**Describe the bug**

Looking at [the pom](https://github.com/opensearch-project/security/blob/6436c155347355292ed91c108eade5f6f119c40b/pom.xml#L133) I am seeing json-smart pulled in. This ends up shipping as `./plugins/opensearch-security/json-smart-2.4.7.jar`. If I am not mistaken this is only [used in tests](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/opensearch-project/.*%24+net.minidev&patternType=literal) and should be removed.

**Comment by vrozov** [comment]
`json-smart` is the transitive dependency of `json-path` and `json-path` is used in production code
