### ISSUE TITLE
Release version 1.2

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1459]
Coming from [opensearch-build#567](https://github.com/opensearch-project/opensearch-build/issues/567), release version 1.2. Please follow the following checklist.

### Preparation

- [x] Assign this issue to a release owner.
- [x] Finalize scope and feature set and update [the Public Roadmap](https://github.com/orgs/opensearch-project/projects/1).
- [x] Create, update, triage and label all features and issues targeted for this release with `v1.2.0`.

### CI/CD

- [x] Increment version on main to `1.2.0.0`.
- [x] Ensure working and passing CI.
- [x] Re(add) this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0).

### Pre-Release

- [x] Branch and build from a `1.2` branch.
- [x] Update your branch in the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0).
- [x] Feature complete, pencils down.
- [x] Fix bugs that target this release.

### Release

- [x] Complete [documentation](https://github.com/opensearch-project/documentation-website).
- [x] Gather, review and publish release notes.
- [x] Verify all issued labeled for this release are closed or labelled for the next release.

### Post Release

- [x] Create [a release tag](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#tagging).
- [ ] Suggest improvements to [this template](https://github.com/opensearch-project/opensearch-plugins/templates/release.md).
- [x] Conduct a postmortem, and publish its results.

**Comment by peternied** [comment]
@cliu123 Until Friday the 12th at noon PST, any tests that use distribution downloader were running against old bits and need to be rerun.  Can you please see if your team was impacted, rerun the tests, and then mark the tests run as completed in https://github.com/opensearch-project/opensearch-build/issues/954?

**Comment by peternied** [comment]
Tests were triggered, note there are failures https://github.com/opensearch-project/security/runs/4229250371?check_suite_focus=true  @cliu123 please follow up to resolve any issues.

**Comment by cliu123** [comment]
@peternied Passed: https://github.com/opensearch-project/security/runs/4230860050?check_suite_focus=true
