### ISSUE TITLE
Use SNAPSHOT artifacts from maven for dependencies

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1466]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/45, use SNAPSHOT Maven dependencies from [aws.oss.sonatype.org](https://aws.oss.sonatype.org/content/repositories/snapshots). See https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#building-within-the-opensearch-build-system for details.

**Comment by davidlago** [comment]
Thanks for the suggestion @dblock ... I had no idea, this is going to cut a considerable time from our CI!
