### ISSUE TITLE
Role template - LDAP results

### ISSUE THREAD

**Issue by sathomps** [opensearch-project/security#147]
currently have authc=SAML and authz=LDAP. The LDAP filter example is the following.

LDAP
Search Base: ou=groups,dc=com
Search Filter: (member=cn=sthomps,ou=users,dc=com)

LDAP Results
cn=1,dc=com
cn=2,dc=com

When a user logs in, they should only be able to view indexes: 1 & 2 - not 3.

I can accomplish this using the following setup explained [here](https://discuss.elastic.co/t/automatically-create-role-based-on-index/199693/2). Does opendistro support this use case?

If not - I'm assuming that I need to create a custom HTTPAuthenticator?

**Comment by pawelw1** [comment]
@sathomps Have you found a solution to your issue?

**Comment by sathomps** [comment]
Yes I did but not but auto-creating the role.  For my use case, it flows like the following.
* create index=1
* create role=1 mapped to index 1 with read/search & backend role mapping = 1

LDAP Results
cn=1,dc=com

User only sees index 1

**Comment by cliu123** [comment]
@sathomps Thanks for bringing up the use case! But security plugin doesn't support automatically creating role upon index creation as of now. We'd love to accept a PR if you're interested in adding this contribution.

**Comment by sathomps** [comment]
@cliu123

Thanks for reaching out.  After having some time to chew on this I think it's better to just close this one out.
