### ISSUE TITLE
problem of assignment of rights

### ISSUE THREAD

**Issue by SherrikFake** [opensearch-project/security#1471]
**Is your feature request related to a problem? Please describe.**
Good afternoon, faced with the problem of assignment of rights. The essence of the problem:
1) Created scheduled reports that are generated every day
2) I want to create a user with minimal rights: to view reports and upload.
3) My actions - I create a user (local) 

- - Security
- - Internal users 
- - Create an internal user
- - I set a username and password
Assign (via mapping) the role "reports_read_access" 
- - Security
- - Roles
- - "reports_read_access" 
- - Mappings

I log in as a user and get an error : 
_Error loading report definitions table.
Insufficient permissions. Reach out to your OpenSearch Dashboards administrator._

After I tried to create my own role- copied it from "reports_read_access" added Tenant permissions Read and also specified the template of my index, permissions: 
get
read
index

The result is the same I get an error. tell me what I'm doing wrong?

**Comment by davidlago** [comment]
Hi @SherrikFake. This looks like a bug. Which version of OpenSearch are you using? Any logs you could attach to this issue that could help troubleshoot? Thanks!

**Comment by davidlago** [comment]
Closing due to missing repro steps... please feel free to re-open if this is still an issue and provide additional reproduction steps. Thanks!
