### ISSUE TITLE
Add MacOS Support

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1475]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/96, add MacOS (Darwin) support.

- [ ] Passing CI on MacOS
- [ ] Documentation

**Comment by davidlago** [comment]
Conversation happening over at https://github.com/opensearch-project/security/issues/2423

**Comment by davidlago** [comment]
re-opening, as this issue is the one being tracked in the meta
