### ISSUE TITLE
Add a script that generates a demo configuration on Windows

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1476]
**Is your feature request related to a problem? Please describe.**
We have https://github.com/opensearch-project/security/blob/main/tools/install_demo_configuration.sh that works on *nix.

**Describe the solution you'd like**
A similar install_demo_configuration.bat that works on Windows.

**Additional context**
Coming from #1474 and https://github.com/opensearch-project/opensearch-build/issues/828. The distribution includes a shell script to configure a plain .zip distribution of the product. It doesn't work on Windows, unclear how to get started to get a working distribution.

**Comment by peternied** [comment]
The *nix script does work if you've got [WSL](https://learn.microsoft.com/en-us/windows/wsl/) installed, what do you think about having that as a prereq?

**Comment by cwperks** [comment]
Closing this issue. This was added in https://github.com/opensearch-project/security/pull/2161
