### ISSUE TITLE
[BUG] By default user can access all data streams messages

### ISSUE THREAD

**Issue by thethir13en** [opensearch-project/security#1498]
**Describe the bug**
User, only has own_index role, can perform search/delete actions on data streams in cluster.

**To Reproduce**
1. Create user has no roles mapped (I've created it from Opensearch Dashboards)
2. Create index template with data_stream attribute, e.g:
    PUT _index_template/logs-template
        {
          "index_patterns": [
            "logs-*"
          ],
          "data_stream": {},
          "priority": 100
        }
3. Send logs to **logs-** data stream
4. Log in to Opensearch dashboards with this user
5. Send request GET logs-* or DELETE logs-*

**Expected behavior**
Plugin have to restrict access to data streams for user without permissions for this data streams.

**Plugins enabled**
opensearch-node1 opensearch-alerting             1.0.0.0
opensearch-node1 opensearch-anomaly-detection    1.0.0.0
opensearch-node1 opensearch-asynchronous-search  1.0.0.0
opensearch-node1 opensearch-index-management     1.0.1.0
opensearch-node1 opensearch-job-scheduler        1.0.0.0
opensearch-node1 opensearch-knn                  1.0.0.0
opensearch-node1 opensearch-notebooks            1.0.0.0
opensearch-node1 opensearch-performance-analyzer 1.0.1.0
opensearch-node1 opensearch-reports-scheduler    1.0.0.0
opensearch-node1 opensearch-security             1.0.1.0
opensearch-node1 opensearch-sql                  1.0.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/14818442/141280569-43f87e85-e6a4-4bb9-98b0-adbf2e0dea30.png)
![image](https://user-images.githubusercontent.com/14818442/141280689-e2479f75-0baa-4432-a976-479bfabd0d46.png)
![image](https://user-images.githubusercontent.com/14818442/141280740-ecf891f4-a612-4235-b46a-a28791e7f98a.png)

**Host/Environment (please complete the following information):**
 - OS: Windows + WSL2 + Docker
 - Version [1.0.1.0,1.1.0.0]

**Comment by rursprung** [comment]
@peternied: is the problem reported by @sastorsl the one you fixed in #1999 or is this yet another problem (and maybe still unresolved)?

**Comment by peternied** [comment]
@sastorsl Could check if this scenario is resolved in the recent [2.2.0 release](https://opensearch.org/downloads.html)?  If you still see a vulnerability please contact aws-security@amazon.com and CC me petern@amazon.com so we can investigate further.

**Comment by peternied** [comment]
@rursprung Thanks for noticing this, I'm not sure based on the report if it is the same issue or a different issue without knowing more about the system configuration.
