### ISSUE TITLE
Update integTest gradle scripts to run via remote cluster independently

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/security#1499]
**Is your feature request related to a problem?**
With the existing implementation of integration tests, opensearch plugins use the same test framework as local integration tests which spin up test clusters by itself. This is a hacky way to override the endpoint from local spun up test clusters (via `opensearch.testclusters` gradle plugin) with the remote cluster endpoint. 

The solution doesn't work when we would like to test the opensearch bundle as part of the release. The test frameworks expect the artifact to be available before we could test them. To clean this up, plugins have to create gradle scripts for remote endpoints to run https://github.com/opensearch-project/opensearch-build#integration-tests for the release cycle. 

**What solution would you like?**
Refer to: https://github.com/opensearch-project/anomaly-detection/pull/298 and make similar changes to the plugin.
Also if you have a custom name to invoke these tests, update the `integtest.sh` script in https://github.com/opensearch-project/opensearch-build/blob/main/scripts/default/integtest.sh

**Comment by dblock** [comment]
Was this done?

**Comment by davidlago** [comment]
No. We had a discussion around it, as a result amending the recommendations on the TESTING document at the project level [here](https://github.com/opensearch-project/OpenSearch/pull/1930). TL;DR in some cases it is not practical to run tests pointing to an external cluster if the cluster settings themselves are under test and we need to recreate a variety of scenarios.

**Comment by davidlago** [comment]
Closing as the security plugin will not be moving to the infra cluster for the reasons in the discussion linked above. If there are any concerns, let's resuscitate that discussion.
