### ISSUE TITLE
Make bouncycastle dependency abstracted

### ISSUE THREAD

**Issue by cjcjameson** [opensearch-project/security#1500]
**Is your feature request related to a problem? Please describe.**

The problem is that security scans complain about bouncycastle from time-to-time. Perhaps we can upgrade / fix the CVEs, but perhaps we can workaround the security issue by removing bouncycastle

**Describe the solution you'd like**

@wjcarpenter can give more details, but some abstraction?

**Describe alternatives you've considered**

We will also follow-up for the specific bouncycastle CVE reports ; cc @nicolasbockg

**Comment by duhang** [comment]
Has this issue been put on OpenSearch Roadmap right?
We would really like to see this item being implemented.
Many thanks!

**Comment by peternied** [comment]
@duhang Thanks for your interest, this is not being tracked in any of the security plugin teams backlogs.  If you are interested in seeing this happen in a future OpenSearch release I would love review a draft pull request.  I've also added the `help wanted` tag to signal this.

**Comment by cwperks** [comment]
Done in https://github.com/opensearch-project/security/issues/4583
