### ISSUE TITLE
Default CI Java Version to Java 11, run tests on 8, 14 and 17

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1502]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/64, default CI Java version to 11 (LTS), and run tests on 8, 14 and 17.

- [x] Change the default Java version for CI in GitHub actions from 14/15 to 11 (LTS).
- [x] Add Java 8, 14 (used before), and 17 (next LTS) to the CI matrix.
- [x] Document Java versions in DEVELOPER_GUIDE.md.

Note: Java-17 is no longer a part of 1.3 release

**Comment by dblock** [comment]
Add 17 to the matrix and you can close this.

**Comment by DarshitChanpura** [comment]
Java 17 has a known bug which breaks couple of tests. It is tracked separately in #1620. @dblock can we close this issue?

**Comment by DarshitChanpura** [comment]
@dblock Should we remove Java-17 from CI build matrix as we are pushing this to 2.0? or should we downgrade Gradle to 6.9 to have all tests run on Java-17 (PR: https://github.com/opensearch-project/security/pull/1661)?
