### ISSUE TITLE
DLS: Add support for Terms Lookup Queries

### ISSUE THREAD

**Issue by jochenkressin** [opensearch-project/security#1508]
**Is your feature request related to a problem? Please describe.**
Some users/customers report the need to use Term Lookup Queries (TLQ) with Document-level security.  This comes in handy if, for example, the access permissions for documents in an index are stored in a separate, second index. At the moment the Document-level security feature does not support TLQ and throws an error if TLQ is used as DLS query.

**Describe the solution you'd like**
DLS should support Term Lookup Queries. If the DLS query does not contain any Term Lookup Query, the current DLS code should be executed as before. If we detect a TLQ in the DLS query, we should treat it differently.

**Describe alternatives you've considered**
None.

**Additional context**
We are working on a solution for this and would like to contribute it. This issue is for tracking.

**Comment by stockholmux** [comment]
@davidlago This looks like a proposal not a feature request.
