### ISSUE TITLE
Pattern Based Field Masking For Inner Json Field:

### ISSUE THREAD

**Issue by ozanonurtek** [opensearch-project/security#152]
Hello ODFE Team,

I successfully installed the latest version(1.2) of odfe via docker. First I decided to go with sample Log data information. During role based index authorization, I try to apply regex as written in [documentation](https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/field-masking/#advanced-pattern-based-field-masking). However, I couldn't enable it for following json source
```
"_source": {
    "referer": "http://twitter.com/success/ni-h-ish-ng",
    "request": "/styles/ads.css",
    "agent": "Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.50 Safari/534.24",
    "extension": "css",
    "memory": null,
    "ip": "111.58.155.54",
    "index": "kibana_sample_data_logs",
    "message": "111.58.155.54 - - [2018-08-03T07:12:52.205Z] \"GET /styles/ads.css HTTP/1.1\" 200 8070 \"-\" \"Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.50 Safari/534.24\"",
    "url": "https://cdn.elastic-elastic-elastic.org/styles/ads.css",
    "tags": [
      "success",
      "info"
    ],
    "geo": {
      "srcdest": "IN:NG",
      "src": "IN",
      "coordinates": {
        "lon": -81.81947222,
        "lat": 38.92977778
      },
      "dest": "NG"
    },
    "utc_time": "2019-10-11T07:12:52.205Z",
    "bytes": 8070,
    "machine": {
      "os": "win 7",
      "ram": 15032385536
    },
    "response": 200,
    "clientip": "111.58.155.XXX",
    "host": "cdn.elastic-elastic-elastic.org",
    "phpmemory": null,
    "timestamp": "2019-10-11T07:12:52.205Z"
  },
```

Is it possible to apply pattern based field masking for geo.coordinates.lat? Here is what I try so far:

![Screen Shot 2019-10-11 at 15 21 13](https://user-images.githubusercontent.com/14114739/66651092-db1ed500-ec3a-11e9-803a-430d6a25fe35.png)

As you can see, same filter works for clientip but does not works for which is geo.coordinates.lat:

![Screen Shot 2019-10-11 at 15 23 15](https://user-images.githubusercontent.com/14114739/66651178-13261800-ec3b-11e9-9115-a9e958711fbf.png)

Any help is appreciated, thank you

**Comment by aetter** [comment]
Hi @ozanonurtek, thanks a bunch for reporting. I'm pretty sure this is a bug. The easiest test:

<img width="666" alt="bug" src="https://user-images.githubusercontent.com/9122297/67219029-96d2c800-f3e4-11e9-8acc-d91a310dea4e.png">

Search results include:

```json
"geo": {
  "srcdest": "IN:NG",
  "src": "IN",
  "coordinates": {
    "lat": 38.92977778
  },
  "dest": "NG"
}
```

Expectation is that `lat` would be anonymized in the same way that `lon` has been properly excluded.

**Comment by ozanonurtek** [comment]
@aesgithub thanks for your support. Is this issue open for pull requests? I wanna give it a try to fix it 🎉

**Comment by aetter** [comment]
@ozanonurtek absolutely, we really appreciate pull requests.

**Comment by nateynateynate** [comment]
@ozanonurtek - thanks for your enthusiasm in helping to contribute to our project! I'm curious if you're still hoping to submit a PR for this issue. If you could see if the issue still exists on the latest OpenSearch before doing so, that would be awesome.  

If you're hoping to contribute code, are there any resources I can help provide you to help get you started?

**Comment by ozanonurtek** [comment]
@nateynateynate could not find a way to fix this and forgot to write it here. I'll check the latest version of the OpenSearch for the same issue and post it here.
