### ISSUE TITLE
Update to log4j 1.2.16

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1523]
**Is your feature request related to a problem? Please describe.**

Log4j 2.16 has been released, https://lists.apache.org/thread/d6v4r6nosxysyq9rvnr779336yf0woz4

**Describe the solution you'd like**

Upgrade to log4j 2.16, following OpenSearch.

https://github.com/opensearch-project/OpenSearch/pull/1721

**Comment by dblock** [comment]
Alternatively, https://github.com/opensearch-project/security/issues/1519

**Comment by davidlago** [comment]
Fixed 1.2.2
