### ISSUE TITLE
Suppress reoccurring false positive SSRF reported by CodeQL

### ISSUE THREAD

**Issue by davidlago** [opensearch-project/security#1527]
Look into [this report from CodeQL](https://github.com/opensearch-project/security/pull/1526/checks?check_run_id=4529181983) about a SSRF finding in `src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/KeySetRetriever.java:74`. It was first reported on 7/14 and since been dispositioned as a fale positive and reopened several times. Use this issue to track the investigation and final disposition (or remediation) for this finding.

**Comment by davidlago** [comment]
@andy840314 @hardik-k-shah @vrozov please provide your inputs since you have context on this finding and have previously dispositioned/re-opened. Thanks!

**Comment by peternied** [comment]
I've looked into this issue, this is OK, we are pulling the URI for the JwksUri from the OpenIdConnect endpoint, the endpoint needs to be trusted it required to be can be specified by the user.

I'll dig in and see if we can suppress this issue more strongly.

**Comment by peternied** [comment]
Look at https://github.com/opensearch-project/security/security/code-scanning/9 as well

**Comment by peternied** [comment]
Dug in, the security alert was last triggered 8 months ago and hasn't cropped back up even with minor changes in [KeySetsRetriever](https://github.com/opensearch-project/security/blob/main/src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/KeySetRetriever.java).  I think we can safely close this issue and not worry about it.
