### ISSUE TITLE
Replace maven by gradle

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1533]
**Is your feature request related to a problem? Please describe.**

When working with multiple plugins, such as when making a patch release, security plugin is a 1-off and creates unnecessary friction. 

See https://github.com/opensearch-project/opensearch-plugins/pull/119 and https://github.com/opensearch-project/opensearch-build/blob/main/scripts/components/security/build.sh#L70 as examples.

**Describe the solution you'd like**
Replace maven with standardized gradle implementation just like all the other plugins in OpenSearch.

**Comment by davidlago** [comment]
#1121 was a first attempt at this.

This PR is outdated and it does too many things: move CI to gradle, upgrade gradle version, update tests (apparently this last one was more involved as it introduced a new runner)...

We are prioritizing work on our test suite, to start using the OpenSearch Test Framework, and moving to gradle is part of that initiative. That said, @cliu123, do you think there is a subset of that PR that we could merge, moving to gradle while leaving the tests mostly unchanged until we tackle that larger body of work?

**Comment by rs-eliatra** [comment]
PR: https://github.com/opensearch-project/security/pull/1592
