### ISSUE TITLE
Add optional description field for Roles

### ISSUE THREAD

**Issue by spapadop** [opensearch-project/security#1561]
**Is your feature request related to a problem? Please describe.**
Roles definition can be complex enough that makes it a bit difficult to understand their purpose by only studying their permissions. Especially when multiple tenants are involved and multiple use-cases are served by the same cluster, roles definitions can get complicated.

**Describe the solution you'd like**
It would be nice to have an optional `description` field that can be filled in when creating Roles, so that we can keep track of what is the purpose of each created role, as a reminder of why we created it in the first place and what is it supposed to do. Then, of course, that should be included in the Dashboards UI accordingly.

**Describe alternatives you've considered**
Role name gives some info, but often that's not sufficient to explain complex use-cases.

**Comment by cwperks** [comment]
`description` is a field that can be assigned to a role. Here's an [example](https://github.com/opensearch-project/security/blob/main/src/main/resources/static_config/static_roles.yml#L10) of a description on the `all_access` role. Closing this issue.
