### ISSUE TITLE
[BUG] Unexpected role set used for document level security. 

### ISSUE THREAD

**Issue by matmore** [opensearch-project/security#1568]
**Describe the bug:**
Opensearch Document Level Security (DLS) leverages the backend roles of a user to facilitate authorisation decisions. I was expecting the Opensearch roles to be utilised for this purpose; similar to managing the index level permissions. I'm looking at the parameter substitution as outlined here: [https://opensearch.org/docs/latest/security-plugin/access-control/document-level-security/#parameter-substitution](https://opensearch.org/docs/latest/security-plugin/access-control/document-level-security/#parameter-substitution).

I've got an issue currently where the backend roles are inflexibly named and require the role mapping functionality to align to something more useful within the DLS. I've done a bit of a hunt around and it looks like it comes down to the following bits of code: [https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java#L924-L931](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java#L924-L931) and [https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/user/User.java#L66-L70](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/user/User.java#L66-L70).

I understand that there will be a fair amount of existing dependencies leveraging this functionality in this state. I'm proposing the exposure of the Opensearch specific roles as an additional substitution value to remedy; let me know if there's something I'm missing on this one.

**Expected behaviour:**
The `${user.roles}` having resolved to the set of roles which is the output of the role mapping configuration within Opensearch. 

**Plugins:**
Default docker image 

**Host/Environment (please complete the following information):**
OpenSearch v.1.2.3 - Docker image

**Additional context:**
For additional context, I've got a dependency on a backend authentication system which it is impractical to manipulate to align to what is required to facilitate the DLS. The role mapping functional allows for the translation of the backend roles over to something more practical but doesn't seem to be utilised for the DLS authorisation decisions.

**Comment by ae-govau** [comment]
(I work with @matmore) - we'd be happy to contribute a PR along these lines (e.g. switch `user.roles` to the output or role-mapping config, or alternately add a `user.openDistroSecurityRoles` substitution), but wanted to check first if either of these approaches would be welcomed?
