### ISSUE TITLE
Multiple roles and DLS/FLS: role with no DLS/FLS should "win"

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/security#1572]
**Is your feature request related to a problem? Please describe.**
situation:
* there are two roles: role A with DLS, role B without DLS, both giving access to an index X
* role A is granted to all users (intent: grant it to all "real" users so that they see only the data they need)
* role B is granted to a technical user to give him additional rights (e.g. data import user which needs to be able to see all documents)
* because role A is granted to all users it is also given to the technical user

due to the user having role B he should be able to see _all_ documents in index X, even though he also has role A.

**Describe the solution you'd like**
there should be an option to change the behaviour so that the role with no DLS wins.

Search Guard has this feature using a config-option (system-wide setting: `dfm_empty_overrides_all`):
* [release notes](https://docs.search-guard.com/latest/changelog-searchguard-7x-42_0_0#document--and-field-level-security)
* [documentation for DLS](https://docs.search-guard.com/latest/document-level-security#multiple-roles-and-document-level-security)

**Describe alternatives you've considered**
* granting the role(s) with DLS only to users with specific roles: e.g. in our setup there's only one user in the whole system which shouldn't have this role. there's no way (e.g. backend role in the JWT) which could be used to identify the other users
* granting the role(s) with DLS to all users except users of a specific group: it's not possible to define a role mapping as "everything except"
also, both options would be cumbersome to manage the more roles exist and there's a risk that then a user might not be granted a restricting role and can see everything by accident.

**Additional context**
n/a

**Comment by jochenkressin** [comment]
I have created a patch for this feature including a Unit test, please find attached.
[dfm_empty_overwrites_all.patch.zip](https://github.com/opensearch-project/security/files/8392370/dfm_empty_overwrites_all.patch.zip)

**Comment by cliu123** [comment]
@jochenkressin Thanks for the patch! I've converted it to a [PR](https://github.com/opensearch-project/security/issues/1572)

**Comment by cliu123** [comment]
PR#1735 has been merged.
