### ISSUE TITLE
[BUG] Documented audit log settings do not work

### ISSUE THREAD

**Issue by trondhindenes** [opensearch-project/security#1581]
**Describe the bug**
I'm trying to tweak the audit log settings, but I'm gettings this:

relevant snippet of opensearch.yml:
```
plugins:
  security:
    audit:
      type: internal_opensearch
      config:
        enable_transport: false
```

```
java.lang.IllegalArgumentException: unknown setting [plugins.security.audit.config.enable_transport] did you mean any of [plugins.security.audit.config.enable_ssl, plugins.security.audit.config.pemkey_password, plugins.security.audit.config.enable_ssl_client_auth, plugins.security.audit.config.password, plugins.security.audit.config.username, plugins.security.audit.config.cert_alias, plugins.security.audit.config.pemcert_content, plugins.security.audit.config.pemkey_content]?
```

**To Reproduce**
Add audit settings as shown above

**Expected behavior**
I would expect the server to start and the documented audit settings to work

**Plugins**
All defaults 

**Screenshots**

**Host/Environment (please complete the following information):**
Default docker image, version 1.2.4

**Additional context**

**Comment by pawelw1** [comment]
@trondhindenes This setting is still under `opendistro_security.audit.enable_transport: true` in opensearch.yml. However, it will be deprecated in v2.0.0 according to the logs.

**Comment by dblock** [comment]
Do we still have a bug? The new name was supposed to work and log a deprecation, wasn't it?

**Comment by davidlago** [comment]
Good question. Reopening until we can provide an answer or a fix :)

**Comment by peternied** [comment]
@trondhindenes I know you filed this a way back, but it should be fixed in the next release of OpenSearch

**Comment by trondhindenes** [comment]
thanks!
