### ISSUE TITLE
Migrate build system from Maven to Gradle

### ISSUE THREAD

**Issue by rs-eliatra** [opensearch-project/security#1591]
**Is your feature request related to a problem? Please describe.**
In [OpenSearch DEVELOPER_GUIDE ](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#gradle-build):

>We use Gradle to build OpenSearch because it is flexible enough to not only build and package OpenSearch, but also orchestrate all of the ways that we have to test OpenSearch.

Currently there is a mix inside OpenSearch Security Plugin:
- build / tests by maven
- Gradle is used to build RPMs
- CD script uses both: maven & gradle

**Describe the solution you'd like**
Migrate build system from Maven to Gradle

**Additional context**
It will be the 1st step in migration to OpenSearch Build Framework which is fully based on Gradle.

**Comment by davidlago** [comment]
@rs-eliatra there was already a ticket for this here #1533, closing this as a duplicate so we track things in just one place. Thanks!
