### ISSUE TITLE
[BUG] Correspondence between new and legacy ssl_dual_mode_enable

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/security#1599]
**Describe the bug**

The new `plugins.security_config.ssl_dual_mode_enabled` and legacy `opendistro_security_config.ssl_dual_mode_enabled` properties do not always stay in-sync. I expect that the values for these two fields should remain consistently the same in all situations.

**To Reproduce - Approach 1: Disabling**

1. Start Docker & Wait

```
docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" -d opensearchproject/opensearch:1.2.4
```

2. Get Settings

```
curl 'https://localhost:9200/_cluster/settings?include_defaults&flat_settings&pretty' -k -u admin:admin -s | grep ssl_dual_mode_enabled
```

Actual output:

```
    "opendistro_security_config.ssl_dual_mode_enabled" : "false",
    "plugins.security_config.ssl_dual_mode_enabled" : "false",
```

3. Enable the legacy value:

```
curl 'https://localhost:9200/_cluster/settings' -k -u admin:admin -X PUT -H 'Content-Type: application/json' -d '{
  "persistent" : {
    "opendistro_security_config.ssl_dual_mode_enabled" : true
  }
}'
```

Result:

```
{"acknowledged":true,"persistent":{"opendistro_security_config":{"ssl_dual_mode_enabled":"true"}},"transient":{}}
```

4. Check Both Fields for Correspondence

```
curl 'https://localhost:9200/_cluster/settings?include_defaults&flat_settings&pretty' -k -u admin:admin -s | grep ssl_dual_mode_enabled
```

As expected, both new and legacy values are updated to `true`.

```
    "opendistro_security_config.ssl_dual_mode_enabled" : "true"
    "plugins.security_config.ssl_dual_mode_enabled" : "true",
```

5. Disable the New Field

```
curl 'https://localhost:9200/_cluster/settings' -k -u admin:admin -X PUT -H 'Content-Type: application/json' -d '
  "persistent" : {
    "plugins.security_config.ssl_dual_mode_enabled" : false
  }
}'
```
```
{"acknowledged":true,"persistent":{"plugins":{"security_config":{"ssl_dual_mode_enabled":"false"}}},"transient":{}}
```

6. Check for correspondence

```
curl 'https://localhost:9200/_cluster/settings?include_defaults&flat_settings&pretty' -k -u admin:admin -s | grep ssl_dual_mode_enabled
```

Here I expect that both values will be `false`, but they are different:

```
    "opendistro_security_config.ssl_dual_mode_enabled" : "true",
    "plugins.security_config.ssl_dual_mode_enabled" : "false"
```

**To Reproduce - Approach 2: Enabling**

1. Start Docker & Wait

```
docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" -d opensearchproject/opensearch:1.2.4
```

2. Get Settings

```
curl 'https://localhost:9200/_cluster/settings?include_defaults&flat_settings&pretty' -k -u admin:admin -s | grep ssl_dual_mode_enabled
```

Actual output:

```
    "opendistro_security_config.ssl_dual_mode_enabled" : "false",
    "plugins.security_config.ssl_dual_mode_enabled" : "false",
```

3. Enable the New Field

```
 curl 'https://localhost:9200/_cluster/settings' -k -u admin:admin -X PUT -H 'Content-Type: application/json' -d '{
  "persistent" : {
    "plugins.security_config.ssl_dual_mode_enabled" : true
  }
}'
```
```
{"acknowledged":true,"persistent":{"plugins":{"security_config":{"ssl_dual_mode_enabled":"true"}}},"transient":{}}
```

4. Check for correspondence

```
curl 'https://localhost:9200/_cluster/settings?include_defaults&flat_settings&pretty' -k -u admin:admin -s | grep ssl_dual_mode_enabled
```

Here I expect that both values will be `true`, but they are different:

```
    "plugins.security_config.ssl_dual_mode_enabled" : "true"
    "opendistro_security_config.ssl_dual_mode_enabled" : "false",
```

**Expected behavior**

I expect that these two values remain in-sync during all changes. What would it mean for one SSL dual mode to be enabled and another disabled?

**Additional Context**

It appears that changing the legacy field will consistently update the new field, for both enable and disable. I did not include those steps but, it should be easy to attempt by modifying the above.

**Comment by cliu123** [comment]
This is actually the expected bahavior. Security plugin introduced the new setting `plugins.security_config.ssl_dual_mode_enabled` during migration from ODFE to OpenSearch in order to retain backward compatibility with ODFE. In OpenSearch, the old setting is being used as a fallback only when an ODFE cluster gets upgrade to OpenSearch where the old setting is set, but the new setting hasn't been set yet(`=null`). In this case, the new setting will automatically take the value of the old setting. But there's no need to change the old setting with the value of new setting in any scenarios.

**Comment by dlvenable** [comment]
@cliu123 , I find this rather unexpected. I understand that the old setting is there for OpenDistro and the new setting is the one going forward. But, I don't understand what it means for them to have different values.

```
    "plugins.security_config.ssl_dual_mode_enabled" : "true"
    "opendistro_security_config.ssl_dual_mode_enabled" : "false",
```

What does this mean? Which takes precedence? What is the actual state of SSL dual mode here?

In general, when migrating a property from an old namespace to a new namespace, the property has only one underlying value. The new setting and old old setting are more like two different views to access that singular source of truth.

**Comment by cliu123** [comment]
Great questions! This is the strategy that was taken to retain the backward compatibility of OpenSearch security plugin with OpenDistro security plugin.
When `plugins.security_config.ssl_dual_mode_enabled` is not `null`, it always should take precedence regardless of the value of `opendistro_security_config.ssl_dual_mode_enabled`.

**Comment by dlvenable** [comment]
Thank you for clarifying that behavior.

I do still believe that this is a bug however. For clients which are using the old property name, they may be getting incorrect information. As noted in my example above, the dual mode can be enabled (`true`), but the old property reports _incorrectly_ that it is disabled (`false`).

**Comment by cliu123** [comment]
This might be a bit misleading with the old and the new settings, but security plugin does not have any bugs in here. As I mentioned above, as long as the new setting `plugins.security_config.ssl_dual_mode_enabled` is set(not `null`), OpenSearch security plugin does not take the value of the old setting. So in your case, `plugins.security_config.ssl_dual_mode_enabled` is `true`, then ssl dual mode is enabled regardless of the value or even existence of the old setting. Client should also be updated with using the new setting after migrating to OpenSearch security plugin.

**Comment by DarshitChanpura** [comment]
Closing for now. Please see the comments above and let us know if you any questions.
