### ISSUE TITLE
[BUG] Flaky tests resulting in unpredictable CI pipeline build behavior

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#1602]
**Describe the bug**
The project contains some flaky tests which result in unpredictable CI build failures.

**To Reproduce**
Not so easy to reproduce but one example here is an example of flaky test.
You can run using `mvn test Dtest=TenantInfoActionTest`

Also, take a look at example [logs](https://github.com/opensearch-project/security/runs/5127235599) from one of the CI runs which shows the failed build due to this flaky test.

**Plugins**
Security plugin

**Screenshots**
Above example on local build:
![flaky-test](https://user-images.githubusercontent.com/35282393/153284163-751942fd-6f95-45f0-a0d5-9bd1cc268f09.png)

**Comment by dblock** [comment]
I recommend opening individual issues for every flaky test and creating a label for those, [similar to OpenSearch](https://github.com/opensearch-project/OpenSearch/issues?q=is%3Aissue+is%3Aopen+label%3A%22Flakey+Random+Test+Failure%22).
