### ISSUE TITLE
Are test failures actually failing the build?

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#1613]
Take a look the these two builds:

> [Gradle build](https://github.com/opensearch-project/security/runs/5202605259?check_suite_focus=true) for java 14:
```
1115 tests completed, 6 failed, 47 skipped
```

> [Maven build](https://github.com/opensearch-project/security/runs/5202477311?check_suite_focus=true) from a merge prior to Gradle merge:
```
2022-02-15T16:08:20.6424291Z [WARNING] Tests run: 1084, Failures: 0, Errors: 0, Skipped: 27, Flakes: 2
```

There are two issues here:
1. Test numbers are different
2. 6 tests failed on gradle build, but the build still passed. Is this expected behaviour?

**Comment by DarshitChanpura** [comment]
Steps to investigate:

1. Look into the latest build on main.
2. Check if any tasks have failed tests.
3. Verify whether these failures were reported for a flaky test that eventually passed or is it actually failing but is not enough for BUILD to be marked as "FAILED"

There are two possible outcomes of this:
- If the behavior is expected, then no further action is required. Can comment as such and close this issue.
- If it is not expected, then further investigation in a follow-up issue, with steps to address it, will be needed.

**Comment by cwperks** [comment]
Tests do fail the CI checks. There is retry logic that retries a test up to 5x until the test passes and will fail the suite if all 5 retries fail. Closing this issue.
