### ISSUE TITLE
Make version dynamic based on OpenSearch version and -SNAPSHOT

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1627]
**Is your feature request related to a problem? Please describe.**

Security plugin tracks the version and -SNAPSHOT option of OpenSearch. Make version and snapshot configurable from calling build script.

**Describe the solution you'd like**

Replace version and snapshot definition in https://github.com/opensearch-project/security/blob/main/build.gradle#L131 and friends by something dynamic, see https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#define-a-version-based-on-the-opensearch-dependency for details.

**Additional context**

Examples: 

https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L21
https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L70
https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L76

**Comment by peternied** [comment]
Nice, thanks for the heads up.

**Comment by peternied** [comment]
This work is done!
