### ISSUE TITLE
[CheckStyle] While checkstyle is run, but it is not enforced 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#1659]
I've created a PR that enables enforcement but disables all rules, https://github.com/opensearch-project/security/compare/main...peternied:enforce-checkstyle?expand=1, if we turned these rules on we would run into 35,974 issues to resolve 😮 

### `./gradlew checkstyleMain`
```
  ...
  Checkstyle files with violations: 266
  Checkstyle violations by severity: [error:18588]
```

### `./gradlew checkstyleTest`
```
  ...
  Checkstyle files with violations: 181
  Checkstyle violations by severity: [error:17386]
```

We can enable rules on a piecemeal basis for specific rules or files.  Lets track how this can be done in this issue.

**Comment by cwperks** [comment]
Checkstyle is running as a CI check now. Closing this issue.
