### ISSUE TITLE
Deprecate the "Master" nomenclature

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/security#1664]
**Is your feature request related to a problem? Please describe.**
[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "master"with "cluster manager".
issue: https://github.com/opensearch-project/OpenSearch/issues/472, with the plan for its terminology replacement.

Although the existing usages with "master" will be supported in OpenSearch version 2.x to keep the backwards compatibility, please prepare for the nomenclature change in advance, and replace all the usages with "master" terminology in the code base.
All the OpenSearch REST APIs and settings that contain "master" terminology will be deprecated in 2.0, and alternative usages will be added.

**Describe the solution you'd like**
Replace the terminology "master" with "cluster manager".

When being compatible with OpenSearch 2.0:
- Replace "master" in code comment and internal variable/method name
- Replace OpenSearch setting that contains "master" with the provided inclusive setting
replace `cluster.initial_master_nodes` with `cluster.initial_cluster_manager_nodes` in https://github.com/opensearch-project/security/blob/1.3.1.0/tools/install_demo_configuration.sh#L385

When being compatible with OpenSearch 3.0:
- Replace "master" in the reference to OpenSearch Java API

**Describe alternatives you've considered**
None.

**Additional context**
An existing PR: https://github.com/opensearch-project/security/pull/1746

**Comment by dblock** [comment]
For 2.0, at a minimum please ensure that the plugin is not calling any deprecated APIs in core or another plugin, and confirm below, then remove the 2.0.0 label. If you have time, do the complete deprecation as described in this issue.

**Comment by peternied** [comment]
> > > There is an issue in security plugin [opensearch-project/security#1746](https://github.com/opensearch-project/security/pull/1746) that we are considering to merge post code freeze.  There has been a setting that was renamed as part of  inclusive naming in opensearch core which is used in security plugin scripts.
> > > **Pros**: New inclusive terms usage is in alignment within our release, its a focused change that is validated by CI checks before entering the distribution build.  There is a minimal risk of destabilizing perf/stress tests in progress
> > > **Cons**: Additional inclusive terminology changes are not in for security plugin, and has no outward facing impact making it a good candidate for the next patch release.
> 
> [Recapping offline conversation] While this change would be valuable, it **does not meet** the requirements for the 2.0.0-rc1 release. There are concerns about modifying the setup scripts late in the process. We will add this to the next release.

From https://github.com/opensearch-project/opensearch-build/issues/1624#issuecomment-1105448472

**Comment by peternied** [comment]
Before we close this lets add a checkstyle rule to look for this terminology and error if it is detected

**Comment by cliu123** [comment]
No more action items for this issue.

**Comment by peternied** [comment]
Searching for 'master' in our codebase has [26 results](https://github.com/opensearch-project/security/search?q=master produces).  Lets see if we can get that to zero, that checkstyle rule hasn't been enabled, we should turn it on and also drive that count to zero.

**Comment by cliu123** [comment]
There are multiple APIs in OpenSearch core still have `master` terminology, so security plugin cannot remove all of them: `node.master`, `ClusterChangedEvent.localNodeMaster()`, `org.opensearch.action.support.master`, `MasterNodeOperationRequestBuilder`.

**Comment by tlfeng** [comment]
Hey @cliu123, thanks for pointing out. I'm trying deprecating all the Java APIs (public class, method, variable) with "master" terminology, and providing the alternative usage with "cluster manager" in OpenSearch 2.1 by the issue https://github.com/opensearch-project/OpenSearch/issues/1684.
I will update the description in the issue to ask for using the alternative Java APIs in a further 2.x version.
