### ISSUE TITLE
Deprecate the "Blacklist / Whitelist" nomenclature

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/security#1665]
**Is your feature request related to a problem? Please describe.**
[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "blacklist / whitelist" with "denylist / allowlist".
issue: https://github.com/opensearch-project/OpenSearch/issues/1483, with the plan for its terminology replacement.

Although the existing usages with "blacklist / whitelist" will be supported in OpenSearch version 2.x until further notice to keep the backwards compatibility, it's suggested to prepare for the nomenclature change in advance, and replace all the usages with "blacklist / whitelist" terminology in the code base.

**Describe the solution you'd like**
Replace the terminology "blacklist / whitelist" with "denylist / allowlist".

When being compatible with OpenSearch 2.0:
- Replace "whitelist" in code comment and internal method / class name.
- Replace "whitelist" in REST API and Setting
- Replace "whitelist" in documentation

Specifically,
- Impacted REST API: `GET (or PUT or PATCH) _plugins/_security/api/whitelist`
Code: https://github.com/opensearch-project/security/blob/1.2.4.0/src/main/java/org/opensearch/security/dlic/rest/api/WhitelistApiAction.java
Detail: “whitelist” contains in the API endpoint.
- Impacted configuration file: `whitelist.yml`
Document: https://www.opensearch.org/docs/1.2/security-plugin/configuration/yaml/#whitelistyml
Detail: It is a YAML file in `plugins/opensearch-security/securityconfig` directory, configurations defined in the file can be imported to Security plugin.

**Describe alternatives you've considered**
None.

**Additional context**
An existing PR: https://github.com/opensearch-project/security/pull/1560

**Comment by peternied** [comment]
Deprecate did not make it in time for the v2.0.0 release, it will be targeted for v2.1.0

**Comment by davidlago** [comment]
Talked to @cliu123 offline, he is working on this and we are still targeting 2.0 GA.

**Comment by cliu123** [comment]
Closing with merging #1808.
