### ISSUE TITLE
Standardize file locations for supporting files

### ISSUE THREAD

**Issue by sean-zheng-amazon** [opensearch-project/security#1673]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/127. 

We should standardize the file location across plugins by implementing following conventions:

- All supporting files for plugins should stay within the plugin's own folder: /plugins/my-plugin
- Within plugin's folder, we recommend following directory structure:
  - ./config: config files
  - ./bin: executables
  - ./lib: for plugins that use native libraries (e.g. libKNNIndexV2_0_11.so)
  - ./install: scripts called to bootstrap the plugin before first use.
  - ./docs: document files
  - ./certs: certificates for the security plugin
  - ./data: test/demo data
- All scripts should come in *nix and .bat flavors, should use OpenSearch's defaults for environment variables like $JAVA_HOME, so users can override these but don't need to specify them by default. Scripts should have 0755 permissions by default.

**Comment by peternied** [comment]
We've had some concerns about making this change, voiced them in the main issue.  I'll deep dive into this tomorrow to see what's feasible for the libs/config/bin alignment

> @.sean-zheng-amazon we have been looking into this from the security plugin, it is going to break a large amount of our documentation / related to change the tooling paths that we have used for the audit/hash/securityadmin scripts.
> 
> This does not seem high value for the breaking change. Rather than centralize these scripts, what about creating an `OpenSearch Admin` tool that abstracts these paths entirely? FYI @.setiah that has been looking into this concept.

**Comment by peternied** [comment]
For 2.0.0 we will complete this task for all folder except for `bin`, PR is in process now.
