### ISSUE TITLE
skip_users for local account not working as expected.

### ISSUE THREAD

**Issue by avanand-git** [opensearch-project/security#168]
Hello There,

when i configure skip_users for local accouts:

skip_users:
  - admin
  - es_admin_local
  - logstash_monitor

[2019-11-21T02:38:03,549][WARN ][c.a.o.s.a.BackendRegistry] [clsjclw001] Authentication finally failed for logstash_monitor from 10.20.174.35:39794

I have added this section to both authc and authz.
I can login to the system properly with the account and works, Due to the above message, LDAP connections are getting piled up and not getting closed.

**Comment by pawelw1** [comment]
@avanand-git have you found a solution to this issue? Would you mind sending config.yml if the issue persists?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
