### ISSUE TITLE
Documentation for kibana object permissions

### ISSUE THREAD

**Issue by sdwerwed** [opensearch-project/security#1688]
I wanted to save a query in the Discover web page in opensearch dashboards by using a restricted role and it was giving me a misleading permission error about `indices:data/write/index`: 

`[security_exception]: no permissions for [indices:data/write/index] and User [name=xxxx, backend_roles=[yyyy], requestedTenant=]`

Actually, it was missing the `kibana:saved_objects/*/write`: 
```
"tenant_permissions": [
    {
        "tenant_patterns": [
            "*"
        ],
        "allowed_actions": [
            "kibana:saved_objects/*/write"
        ]
    }
]
```

Request:
1. We would like to see the correct permission issue
3. We would like to have in the documentation the permission list for kibana:saved_objects like in [here](https://opensearch.org/docs/latest/security-plugin/access-control/permissions/#index-permissions)

**Comment by peternied** [comment]
[Triage] thanks for filing this issue.

**Comment by DarshitChanpura** [comment]
There are multiple types of permissions that allow `write` and the server doesn't know which permission to supply as it lacks the context in the request, and so there is an ambiguity between the permissions.

Closing this issue as this is the limitation that prevents us from fixing it.
