### ISSUE TITLE
Remove TransportClient auth/auth related code

### ISSUE THREAD

**Issue by jochenkressin** [opensearch-project/security#1700]
**Is your feature request related to a problem? Please describe.**
Since in 2.0 the TransportClient will be deprecated/removed, we should also remove code related to Transport auth/auth. Apart from the actual auth/auth code, this would also include the AuditLog feature and categories like Transport FAILED_LOGIN and Transport AUTHENTICATED.

**Describe the solution you'd like**
Remove all code related to TransportClient auth/auth.

**Describe alternatives you've considered**
Leave the code in there and end up with dead code and technical debt

**Additional context**
I will submit a PR for this.

**Comment by davidlago** [comment]
Duplicate of #1578
