### ISSUE TITLE
Can opensearch-security support Elasticsearch?

### ISSUE THREAD

**Issue by 5yanfei** [opensearch-project/security#1704]
In Elasticsearch, security features such as LDAP are only supported in the paid version.

Would like to ask, is it possible to configure opensearch-security in Elasticsearch's plugin to implement LDAP?

If so, is there any documentation for us to refer to, we don't know how to enable opensearch-security in elasticsearch.yml.

**Comment by davidlago** [comment]
Hi @5yanfei. Previous versions of the security plugin were used in OpenDistro for Elasticsearch (ODFE) https://opendistro.github.io/for-elasticsearch/ to add security features to the open source distribution of Elasticsearch. That said, those versions will soon be end of life and are no longer receiving security patches etc, so the recommendation would be to upgrade/migrate to OpenSearch and get the new distributions from there, fully open source. From the ODFE website:

>Open source Elasticsearch and Kibana 7.10.2 will soon be end of life, and are no longer receiving active development, security patches, or bugfixes. All users should be running software that receives timely security patches. The OpenSearch project was launched to provide a path forward for open source Elasticsearch and Open Distro users that ensures they always have access to security and new innovation.

>Now is the time to migrate to OpenSearch to take advantage of the newest features, performance improvements, bugfixes, and security patches. See [what’s so great about OpenSearch](https://opensearch.org/docs/latest#why-use-opensearch) and [get help migrating](https://opensearch.org/blog/technical-posts/2021/07/how-to-upgrade-from-opendistro-to-opensearch/).

**Comment by 5yanfei** [comment]
> Hi @5yanfei. Previous versions of the security plugin were used in OpenDistro for Elasticsearch (ODFE) https://opendistro.github.io/for-elasticsearch/ to add security features to the open source distribution of Elasticsearch. That said, those versions will soon be end of life and are no longer receiving security patches etc, so the recommendation would be to upgrade/migrate to OpenSearch and get the new distributions from there, fully open source. From the ODFE website:
> 
> > Open source Elasticsearch and Kibana 7.10.2 will soon be end of life, and are no longer receiving active development, security patches, or bugfixes. All users should be running software that receives timely security patches. The OpenSearch project was launched to provide a path forward for open source Elasticsearch and Open Distro users that ensures they always have access to security and new innovation.
> 
> > Now is the time to migrate to OpenSearch to take advantage of the newest features, performance improvements, bugfixes, and security patches. See [what’s so great about OpenSearch](https://opensearch.org/docs/latest#why-use-opensearch) and [get help migrating](https://opensearch.org/blog/technical-posts/2021/07/how-to-upgrade-from-opendistro-to-opensearch/).

Hello @davidlago ,

I see that the supported version of Security Plugin v1.13.1.0 is Elasticsearch (Apache 2.0 licensed code only) v7.10.2;
Does Security Plugin v1.13.1.0 support Elasticsearch v8.1.0?

Or Is there any Security Plugin that supports Elasticsearch v8.1.0? We want to use LDAP functionality in Elasticsearch.

**Comment by davidlago** [comment]
@5yanfei no it does not. Questions for support for versions beyond v7.10.2 are better directed elsewhere.
