### ISSUE TITLE
[BUG]SAML SingleLogoutService requests to ADFS are not signed and causing errors when we trigger dashboard logout

### ISSUE THREAD

**Issue by arurus-aws** [opensearch-project/security#1717]
**Describe the bug**
SingleLogoutService requests are not signed  and ADFS is rejecting these requests,  as requests are not signed. 

**To Reproduce**
1. Configure SAML with ADFS as IDP to login to DashBoard.
2. As part of configuration, in adfs metadata.xml, keep SingleLogoutService urls
3. Trigger Logout on Kibana dashboard.

**Expected behavior**
OpenSearch should post Signed SingleLogoutService requests to ADFS. 

**Additional context**
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/saml.html

**Comment by peternied** [comment]
[Triage] Thanks for filing this issue.

**Comment by devardee** [comment]
@peternied this issue can be closed. The plugin does support signing SAML requests

https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/saml/#request-signing

**Comment by peternied** [comment]
@devardee Thanks for looking at this issue, I did not see documentation saying why this feature should not be supported, did I miss something?

However being that its support its called out, it seems like this issue could be transitioned from a bug to a feature request instead.

**Comment by devardee** [comment]
@peternied the feature requested in the issue is already supported by the plugin. However, the AWS Managed Opensearch Service does not provide this feature.
