### ISSUE TITLE
ldap password in config file

### ISSUE THREAD

**Issue by df-cgdm** [opensearch-project/security#173]
The bind password used for authentication and/or authorization is both readable in the config file and in Kibana.
It will be better to use a hash like for internal user password or to store the password with another mechanism like the elastic keystore.

**Comment by Luckyyyshot** [comment]
I'm having the same problem. I'm currently working on something with a requirement that no passwords must be in plain text. It might not give much more meaningful security in reality, but it will allow this system to conform to many countries regulations for no sensitive data to be found in plain text.

**Comment by df-cgdm** [comment]
Any update?

**Comment by Luckyyyshot** [comment]
Not to my knowledge.

**Comment by df-cgdm** [comment]
Hello any update on this ?
Another solution is also to store the ldap password in the keystore

**Comment by df-cgdm** [comment]
Hello, any progress on this requirement?

**Comment by peternied** [comment]
No progress, but we'd gladly review a pull request for this functionality

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!

**Comment by df-cgdm** [comment]
This issue should still be considered (I have not enought skill to help you on this :) )
