### ISSUE TITLE
[FEATURE] Make openid_auth_domain able to use internal role mappings for backend_roles

### ISSUE THREAD

**Issue by 53rg3** [opensearch-project/security#1748]
**Is your feature request related to a problem?**

In the `securityconfig/config.yml`, when using `openid_auth_domain` as `authc` then it is possible to define a `roles_key` which sources the `backend_roles` roles of the user from the ID token. It seems that the internal `roles_mapping.yml` is ignored. Both fields `backend_roles` & `and_backend_roles` seem to be ignored when using `openid_auth_domain`.

![image](https://user-images.githubusercontent.com/37144074/162161773-51e2f47f-533f-4806-870c-608d5894f799.png)

This requires the OpenID provider to handle backend roles, which is hard to do if one tries to uphold the infrastructure as code principal.

**What solution would you like?**

If the `roles_key` is empty or undefined then it would make sense to look up the roles mapping in `roles_mapping.yml` and assign the backend roles based on the values in `backend_roles`.

- Maybe `java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java` could look up `roles_mapping.yml` additionally
- Maybe there could be a `authz` backend for OpenID which is like `internal`

**What alternatives have you considered?**

I tried everything and nothing seems to make this work, except setting up the `roles_key` in the ID token.

**Do you have any additional context?**

As far as I can judge it from the code the logic is simply not there to handle this case.

**Comment by Anthony7774** [comment]
@53rg3 I'm not fully understanding what is the issue you are reporting.

The oidc login **can** provide groups/roles via roles_key in JWT token (These are considered "backend_roles"). If they are provided and match the entry in config.yaml (under roles_key), they are extracted and then used in _internal_ roles_mapping.yaml to map to relevant "opensearch role" defined in roles.yaml.

If, for some reason, you are not using the backend role feature with oidc and would like to use roles_mapping.yml to map to opensearch roles by using usernames (of course not very feasible if you have 100s of users), you can always leave the roles_key blank (roles_key: "") and just extract the username (subject_key: "name") and in roles_mapping.yaml file, map to opensearch roles using usernames:

`testRole1:
  users:
  - "username1"`

Is this what you are looking for?

**Comment by 53rg3** [comment]
@Anthony7774 Thanks for your reply.

> The oidc login can provide groups/roles via roles_key in JWT token (These are considered "backend_roles").

Yes. We solved this problem by providing the roles from our OIDC service (KeyCloak) in the `roles_key` in the ID token. But this what we'd like to avoid. We rather would like to statically configure users and roles in the config files.

> If, for some reason, you are not using the backend role feature with oidc and would like to use roles_mapping.yml to map to opensearch roles by using usernames

This is the point of my feature request. I would like to use OIDC in combination with the `roles_mapping.yml` file. The problem is that even though users which are configured in `roles_mapping.yml` at a specific role, the set `backend_roles` of this role are ignored. See the screenshot in first post:

![image](https://user-images.githubusercontent.com/37144074/163392543-dbbb64e3-e313-4632-aa07-feac6e8a5434.png)

The users `p0310ss` & `dot-admin` can authenticate via OIDC and they **do get** the role `all_access` but they **do not get** the backend role `admin`, because `java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java` doesn't implement the logic for that. It just looks for the `roles_key` and if doesn't find it, then it doesn't assign any backend roles. 

This feature would be beneficial for users practicing infrastructure & configuration as code. It's easier to render a config file from a template than having to deal with REST APIs

**Comment by 53rg3** [comment]
Misunderstood "backend roles", docs say:

> (Optional) Arbitrary strings that you specify or that come from an external authentication system (e.g. LDAP/Active Directory). Backend roles can help simplify the role mapping process. Rather than mapping a role to 100 individual users, you can map the role to a single backend role that all 100 users share.

So they are specifically from EXTERNAL backends and have nothing to do with the OpenSearch backend. There's the magic internal role "api_access" which gives users access to the security settings. Mapping users to the internal role "admin" doesn't give them access. Confusing.
