### ISSUE TITLE
LDAP Queries all groups of user, with a timeout and slow log-in

### ISSUE THREAD

**Issue by aretakisv** [opensearch-project/security#175]
I have setup LDAP and trying to use the ActiveDirectory memberOf value, which exposes the groups of the user.
Also disabled the rolesearch_enabled but still takes long time. Is there a good example how to configure this?

**Comment by hkarpf** [comment]
Same issue here....makes it unusable...

**Comment by orest-gulman** [comment]
Hi guys, I've had the same issue with LDAP, the login take so long ~30 seconds or longer, but after I switch port from 389 to 3268, it's start authenticate like a rocket.

**Comment by pawelw1** [comment]
@anirudha Do you still have the same issue with the latest versions of ODFE or OpenSearch?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
