### ISSUE TITLE
[BUG] Missing default observability roles

### ISSUE THREAD

**Issue by lizsnyder** [opensearch-project/security#1759]
**What is the bug?**
According to https://github.com/opensearch-project/security/pull/1484, we added two new default roles for observability (observability_read_access and observability_full_access). However, I'm not seeing these roles in the **Roles** dropdown menu within OpenSearch Dashboards (in 1.2 or 1.3). 

**How can one reproduce the bug?**
1. Go to OpenSearch Dashboards 1.2 and click **Security** in the left nav.
2. Click **Roles**.
3. Search for "observability" in the search box.
4. Notice that no roles appear.

**What is the expected behavior?**
When filtering for "observability", user should see the following roles: 
- observability_read_access
- observability_full_access

<img width="1223" alt="Screen Shot 2022-04-11 at 17 04 56" src="https://user-images.githubusercontent.com/31932630/162852598-09cddc70-4031-4b18-9109-204f16b5ea0f.png">

**What is your host/environment?**
 - OS: Mac
 - Version 12.2.1

**Comment by lizsnyder** [comment]
CC @joshuali925

**Comment by joshuali925** [comment]
@lizsnyder I wasn't able to reproduce this with fresh installs of OpenSearch `1.2.0` and `1.3.1` tarball on linux, the observability roles showed up for me in both versions.
![image](https://user-images.githubusercontent.com/28062824/163243369-15c43738-0d49-444b-983c-c4b56ba44395.png)

One reason could be that your cluster was upgraded from an older version of OpenSearch, where the security index won't be newly created so new default roles won't be added. If this happens, admin can create the observability roles manually as a workaround.
```
PUT _plugins/_security/api/roles/observability_read_access
{
  "cluster_permissions": [
    "cluster:admin/opensearch/observability/get"
  ]
}

PUT _plugins/_security/api/roles/observability_full_access
{
  "cluster_permissions": [
    "cluster:admin/opensearch/observability/create",
    "cluster:admin/opensearch/observability/update",
    "cluster:admin/opensearch/observability/delete",
    "cluster:admin/opensearch/observability/get"
  ]
}
```

I believe this issue can be closed as i remember this is a known limitation of security plugin (I don't have permission to close, need someone from security team), but feel free to comment/reopen if you have concerns, thanks!

**Comment by lizsnyder** [comment]
@joshuali925 okay, thanks. I'm also not seeing them on the default installation of OpenSearch Dashboards for the managed Amazon OpenSearch Service. Is this a concern?

**Comment by joshuali925** [comment]
> @joshuali925 okay, thanks. I'm also not seeing them on the default installation of OpenSearch Dashboards for the managed Amazon OpenSearch Service. Is this a concern?

Probably need someone from security to check what's missing there
