### ISSUE TITLE
[Testing] Security needs integration tests that run with the distribution suite.

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#1761]
Related to https://github.com/opensearch-project/opensearch-build/issues/58

The security has integration tests that execute within its CI systems, but many of those tests configure/start/stop a local cluster to exercise different security configurations.  This methodology is incompatible with the model used in the distribution tests.  No matter how this is reconciled we need to onboard into the standard testing framework.

* [x] Determine what if any tests can be run on the standard cluster
* [x] #1991
* [ ] Onboard these tests into the distribution workflow
* [ ] Determine the coverage gaps or tests that need to be created/adopted - create additional tasks.

**Comment by cliu123** [comment]
There's [another issue](https://github.com/opensearch-project/security/issues/1177) for this. Close one of them?

**Comment by cliu123** [comment]
@peternied @davidlago This issue looks to be closed with #1499.

**Comment by davidlago** [comment]
Not quite, I don't think so. For the purposes of 2.0, #1499 is closed as a no-op for security. But I believe that this issue that @peternied created was to follow up in future releases to see what if anything we can do to perhaps run a subset of the ITs against the standard cluster.

**Comment by peternied** [comment]
I think we should capture the minimal set of functionality we should test from the sanity tests that we run on a release from https://github.com/opensearch-project/security/issues/1800

**Comment by DarshitChanpura** [comment]
[Update] This won't be completed in time for 2.1.0 and is to be moved to 2.2.0
