### ISSUE TITLE
Replace checked-in ZIPs with downloads of official releases

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1767]
Coming from https://github.com/opensearch-project/opensearch-build/issues/1750, replace checked in ZIP(s) with dynamic dependencies.

```
./security/bwc-test/src/test/resources/1.0.1.0/opensearch-security-1.0.1.0.zip
./security/bwc-test/src/test/resources/1.3.0.0/opensearch-security-1.3.0.0.zip
```

**Comment by davidlago** [comment]
@DarshitChanpura is taking a look at it today (I see a draft PR just created)

**Comment by cliu123** [comment]
Blocked by [this issue](https://github.com/opensearch-project/OpenSearch/issues/2987).

**Comment by cliu123** [comment]
Thanks for resolving [the issue](https://github.com/opensearch-project/OpenSearch/issues/2987)

**Comment by cliu123** [comment]
Closing with #1774.
