### ISSUE TITLE
NOTICE.txt and THIRD-PARTY.txt appear to be out of date

### ISSUE THREAD

**Issue by wdwalker-oracle** [opensearch-project/security#1768]
We need to know how to properly attribute the binary material when redistributing within another product.

When I look at NOTICE.txt, I only see references to OpenSearch contributors, Apache, and Bouncy Castle. When I do a quick grep through the sources in the repo, however, I find other notices such as these:

  ~ Copyright 2015-2018 _floragunn_ GmbH
 \* Copyright 2002-2017 the original author or authors.
 \* Copyright 2015-2017 floragunn GmbH
 \* Copyright 2015-2018 _floragunn_ GmbH
 \* Copyright 2015-2018 floragunn GmbH
 \* Copyright 2015-2019 floragunn GmbH
 \* Copyright 2017 floragunn GmbH
\# Copyright (c) 2006, 2008 Junio C Hamano
\# Copyright 2015 the original author or authors.
//  Copyright (c) 1995-2017 Mort Bay Consulting Pty. Ltd.
\@rem Copyright 2015 the original author or authors.

And, THIRD-PARTY.txt doesn't appear to have been updated in 3 years. I see several references to elasticsearch in that file, for example.

Are you all planning to take a pass at updating these files in the near future?

**Comment by peternied** [comment]
We recommend that you ask your legal counsel how to properly attribute the binary. See Apache-2.0 license section 4c and 4d. We do not have any plan to update the notice text file.
