### ISSUE TITLE
[FEATURE] JWT: validate audience claim

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/security#1780]
**Is your feature request related to a problem?**
JWTs contain the `aud` claim with the audience for which the token is valid.
consumers of a token should validate this claim to see if it is intended for them (it's possible for an IdP - which the consumer trusts - to issue a JWT which isn't intended for this specific consumer).

see also the RFC:  https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3

**What solution would you like?**
it should thus be possible to specify the value(s) for `aud` in the configuration which should be accepted by OpenSearch Security when it received a JWT.

IMHO there should be only one acceptable `aud` value for one OpenSearch cluster as the cluster itself is the audience, i.e. this is a global setting and not a setting per auth domain.

**What alternatives have you considered?**
n/a

**Do you have any additional context?**
* this has been implemented by @floragunn in Search Guard here: https://git.floragunn.com/search-guard/search-guard-suite-enterprise/-/merge_requests/132 (note: this is *not* under the Apache 2.0 license!)
* the same should be done for the `iss` claim (see #1781)

**Comment by peternied** [comment]
@rursprung Thanks for the feature request.
