### ISSUE TITLE
[FEATURE] JWT: validate issuer claim

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/security#1781]
**Is your feature request related to a problem?**
JWTs contain the `iss` claim with the issuer which created the token.
consumers of a token should validate this claim to see if it is the expected issuer and to decide against which public key to validate the claim.

see also the RFC: https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.1

**What solution would you like?**
it should be possible to specify the expected value for `iss` per JWT auth domain and the JWT auth domain then (only) gets picked based on the `iss`.
if no value is set on the auth domain it'll just have the current behaviour (i.e. test all auth domains in order).

**What alternatives have you considered?**
n/a

**Do you have any additional context?**
* this has been implemented by @floragunn in Search Guard here: https://git.floragunn.com/search-guard/search-guard-suite-enterprise/-/merge_requests/132 (note: this is *not* under the Apache 2.0 license!)
* the same should be done for the `aud` claim (see #1780)

**Comment by peternied** [comment]
@rursprung Thanks for the feature request.
