### ISSUE TITLE
Integrate auto-password generation into security plugin bootstrap logic

### ISSUE THREAD

**Issue by setiah** [opensearch-project/security#1787]
The proposal is to integrate the PasswordSetup logic that generates strong secure passwords into the security plugin bootstrap logic, so that the secure passwords are auto-generated when the OpenSearch process w/ security plugin bootstraps. This feature to provide secure out of the box password should be behind a setting so that it can be disabled/enabled at will. Initially in 2.x versions, we might want to default it to false so that we don't break users currently using admin:admin but going forward, we may want to switch defaults to auto-generate strong passwords during first bootstrap. This will enable deprecation of admin:admin default password.

**Comment by setiah** [comment]
The plan here is to add the bootstrap time auto-password generation logic behind a feature flag, with default disabled. In 2.x line, users can explicitly enable the flag to get out of the box strong passwords for in-built security users ("admin", "kibanaserver", "kibanaro", etc.). With the next major version, the flag can be changed to be enabled by default, which will bootstrap the cluster with default strong auto-generated passwords.

**Comment by setiah** [comment]
@ryanbogan I tested the current [implementation](https://github.com/ryanbogan/security/commit/114ba36716cbd6fd7f3802295ef2de60b7849910) for auto-generating passwords on bootstrap. There are a couple of issues that need to be fixed - 

1. The passwords get auto-generated each time the node bootstraps even when the earlier bootstrap generated the password. Thus the previous password ends up getting overwritten. This needs to be fixed. The password generation should happen only once during bootstrapping.
2. The passwords are not shared in a user-friendly way in the logs. They seem to be scattered all over the place in the logs. The bootstrapping process on completion should display passwords in a legible way to the users.
3. The password generation and sharing logic should work for docker and rpm distribution as well. Users setting up OpenSearch with docker and rpm should be able to read auto-generated passwords in a user-friendly way.
4. Add mechanism for this to work with docker-compose, as in case of docker-compose there is no way to share auto-generated passwords during bootstrapping.

**Comment by derek-ho** [comment]
Closing this due to implementation of OPENSEARCH_INITIAL_ADMIN_PASSWORD in 2.12
