### ISSUE TITLE
Publish plugin zips to maven repo

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/security#1801]
### Description

With existing setup the plugin jars are only published to maven repo, but not the generated plugin zips.

### Related META issue

https://github.com/opensearch-project/opensearch-build/issues/1916

### Current Behavior

Existing all maven publications target the jar files to publish to maven, but not the generated distribution zips.

### Expected Behavior

Along with plugin jars, plugin zips should also be published to maven repo with right maven coordinates, so user can download these plugins using dependancy model.

### Steps To Reproduce

1. Run the gradle assemble task that outputs jar and zips.
2. Using build setup the jars are published to local staging maven repo.
3. Zip's are just added to distribution's folder during build runtime.
4. Finally once build is done, just the jar files are added to local maven repo and updates to the manifest file, but not the zips.

### Proposed solution
A custom gradle plugin solution that can create the publication task for the zips to get published to local staging maven repo with right maven coordinates.
Add/Configure the custom gradle plugin openseearch.pluginzip to the gradle project and test the generated plugin zip's to upload to local maven repo.
More details on how to use the Plugin:
https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip

**Comment by cliu123** [comment]
I see that @prudhvigodithi has already been working on this. [PR](https://github.com/opensearch-project/security/pull/1757)

**Comment by prudhvigodithi** [comment]
Hey @cliu123 , that was very early phase of testing of adding a subproject in each repo, now we have developed a custom plugin that can be just applied in each repo, here is the [documentation](https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip) link of the custom plugin, please try and let me know if you are able add this custom plugin opensearch.pluginzip to security.

**Comment by bbarani** [comment]
@cliu123 @davidlago   Can you please make the necessary changes as listed on the document to support publishing your zips to Maven?

**Comment by cliu123** [comment]
https://github.com/opensearch-project/opensearch-build/issues/1916#issuecomment-1124194740

**Comment by peternied** [comment]
@bbarani Unfortunately the security plugin was not onboarded in the same gradle pattern as the other plugins, we will need to spend time to re-write our build.gradle to take advantage of this work.  Is there someone that has experience in setting up one of these build files that we could work with to speed up the effort?

FYI @davidlago

**Comment by davidlago** [comment]
This was not initially planned for 2.0 GA and it requires a rewrite of our build files, we might have to slate these changes in for 2.1 instead (cc @dblock @CEHENKLE )

**Comment by prudhvigodithi** [comment]
Hey @cliu123 @davidlago dave, just following up to see if `opensearch.pluginzip` is integrated, if not please make the necessary changes to add `opensearch.pluginzip` to support publishing your zips to Maven.

**Comment by cliu123** [comment]
@prudhvigodithi `opensearch.pluginzip` has not been integrated yet, but [it](https://github.com/opensearch-project/security/issues/1839) is in our backlog.
