### ISSUE TITLE
Kibana SSO session problem with ADFS IDP

### ISSUE THREAD

**Issue by tocw** [opensearch-project/security#181]
Hello, 
we have two OD clusters (1.2.1 and 1.1.0 deployed with docker) that use SAML authentication configured with ADFS. Authentication works fine except the session expires after one hour which results in strange browser behavior. Instead of refreshing the token it shows the browser basic authentication popup like in the screenshot below (Chrome latest):

![kibana1](https://user-images.githubusercontent.com/17469832/70793531-cb874e00-1d9b-11ea-887e-ac4c294fe6ca.PNG)

I have also noticed that if I delete the **_security_authentication_** cookie and refresh I get authenticated automatically.

![kibana2](https://user-images.githubusercontent.com/17469832/70793540-d04c0200-1d9b-11ea-8e4f-d5f89883b245.PNG)

Also, for some corporate devices connected to AD it is even impossible to authenticate as the users get the _SAML authentication error_ page in Kibana. It can be avoided by using incognito mode.

Do you have any idea what may be causing this problem? Do we need to reconfigure the session timeouts or some specific browser/ADFS settings?

Thanks

**Comment by hollden** [comment]
I have almost the same problem, but in my case kibana just shows me error:
`{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred."}`
In logs I see that token has been expired and it hasn't been renewed.

**Comment by pawelw1** [comment]
@tocw Have you found a solution to your issue?

**Comment by tocw** [comment]
Hi @pawelw1 
I have not found the solution. I have also finished working with OD clusters almost a year ago.

**Comment by pawelw1** [comment]
@tocw  thanks for the reply.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
