### ISSUE TITLE
[Bug] jackson dependencies should be synchronized with OpenSearch

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#1816]
This is the second time we've had a distribution build break because both OpenSearch and security plugin have imported different versions of the jackson libraries.  We need a way to make sure the correct dependencies are in the security plugin and those dependencies will not create conflicts with OpenSearch.

**Comment by reta** [comment]
@peternied the problem at large is that `security` plugin does not rely on `opensearch.opensearchplugin` (like in template [1] fe) so it is not possible to benefit from the shared versions using:

```
"implementation 'com.fasterxml.jackson.core:jackson-databind:${versions.jackson_databind}"
```

Do you by any chance now why the `opensearch.opensearchplugin` is skipped over?

[1] https://github.com/opensearch-project/opensearch-plugin-template-java/blob/main/build.gradle

**Comment by cliu123** [comment]
@reta Security plugin [migrated the build system from Maven to Gradle](https://github.com/opensearch-project/security/pull/1592), but still does not use `pensearch.opensearchplugin` as of now.

**Comment by reta** [comment]
Thanks @peternied , should we repurpose this issue to use `opensearch.opensearchplugin` in `security` instead of patching versions?

**Comment by peternied** [comment]
@reta Lets close this issue, and I'll use the follow up in security to prevent a 3rd incident
