### ISSUE TITLE
[Refactor] Rename `.opendistro_security` index to `.opensearch_security`

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#1822]
This change is part of the renaming effort last year for the project from OpenDistro to OpenSearch. As a part of this effort:

- [ ] Look up `opendistro_security` and rename it to `opensearch_security`
- [ ] All the test cases should pass after this change
- [ ] Sanity test by installing this plugin in OpenSearch

**Comment by cliu123** [comment]
The plan is not to rename indices. 
Related discussion: https://github.com/opensearch-project/opensearch-plugins/issues/17#issuecomment-847204447

**Comment by peternied** [comment]
We have a couple of conversations in flight about how/where security data is stored.  As we move forward in these efforts we can shift the index name.
