### ISSUE TITLE
[BUG] opendistro in API path to retrieve the cluster’s security certificates

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/security#1827]
**What is the bug?**

API to retrieve  the cluster’s security certificates contains `_opendistro` instead of `_plugins` . This is inconsistent behavior as compared to all other security APIs. 
 

**What is the expected behavior?**

API to retrieve  the cluster’s security certificates becomes  `_plugins/_security/api/ssl/certs` 

**Do you have any additional context?**

[Documentation link](https://opensearch.org/docs/latest/security-plugin/access-control/api/#get-certificates)

**Comment by cliu123** [comment]
Both `_plugins/_security/api` and `_opendistro/_security/api` are supported to retain backward compatibility.

**Comment by gbbafna** [comment]
`_plugins/_security/api ` is not working . Only `_opendistro/_security/api` path is working for retrieving the security certificates . [Related forum post ](https://forum.opensearch.org/t/cant-get-the-node-s-dn-from-each-follower-cluster/9484)
