### ISSUE TITLE
Opensearch SAML authentication with Azure AD

### ISSUE THREAD

**Issue by KannappanSomu** [opensearch-project/security#1834]
Opensearch SAML authentication with Azure AD:

Is there any pointers on how to deploy SAML authentication with Azure AD in opensearch chart ? 
In values file , i dint find anything related to this, any help is appreciated .

**Comment by peterzhuamazon** [comment]
Transfer to security plugin repo to take a look.

**Comment by cliu123** [comment]
Would you please re-route this support request to [OpenSearch security forum](https://forum.opensearch.org/c/security/3?), so everyone will have a reference to this?
