### ISSUE TITLE
[Bug}[OpenSearch AD Role with Azure AD] How to map Azure AD roles in OpenSearch roles.

### ISSUE THREAD

**Issue by kunal-parsewar** [opensearch-project/security#1843]
I have setup the SSO using saml between zure AD and OpenSearch.

Now I have many team using the opensearch via opensearch dashboard and they login using azure ad credentials. Now I have to create the different roles for each and every different team in the opensearch dashboard and need to add them individually into that roles.

How can i map the roles / groups created in Azure AD directly in the opensearch dashboard so that I don't need to do different configuration by creating different roles .

My OpenSearch and dashboard is running on aks cluster and opensearch version is 1.2.4.

Please do let me know if you have any information regarding the same.

**Comment by peternied** [comment]
Thanks for asking this question @kunal-parsewar, as this is about support with our features please use the [OpenSearch forums](https://forum.opensearch.org/c/security/3).  Consider adding a link to the discussion on this issue after you've created it.  Thanks.
