### ISSUE TITLE
[BUG] "Tenant global_tenant is not allowed for user ..."  and ldap authc/z

### ISSUE THREAD

**Issue by tsgit** [opensearch-project/security#1859]
**What is the bug?**
the global tenant cannot be selected in dashboard and the opensearch log shows 

[WARN ][o.o.s.c.PrivilegesInterceptorImpl] [osearch-logging-node-1] Tenant global_tenant is not allowed for user ....

this started after upgrading from opensearch (-dashboards) 1.3.1 to 1.3.2

with version 1.3.1 there is no such problem.

**How can one reproduce the bug?**
1. Go to "switch tenants" after connecting/authenticating to dashboard via proxy and ldap
2. The "Global" tenant is greyed out and there is text "Contact the administrator to get access to global tenant"

3. opensearch log shows

  [o.o.s.c.PrivilegesInterceptorImpl] [osearch-logging-node-1] Tenant global_tenant is not allowed for user

**What is the expected behavior?**
The global tenant should be accessible to all users. multitenancy is enabled in opensearch-dashboards.yml  via 

opensearch_security.multitenancy.enabled: true
opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]

**What is your host/environment?**
 - OS: Redhat Enterprise Linux
 - Version RHEL7.9
 - Plugins
./bin/opensearch-plugin list
opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-ml
opensearch-observability
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-sql

**Do you have any screenshots?**

**Do you have any additional context?**

This problem emerged after the upgrade from opensearch/opensearch-dashboards from 1.3.1 to 1.3.2

authentication enabled:
anonymous_auth_enabled: true
xff.enabled: true
basic_internal_auth_domain (4)
proxy_auth_domain (3)
ldap  (5)

authz:
roles_from_myldap

ldap groups are used to map additional roles to the user authenticated via proxy. This works as intended (no change from 1.3.1 to 1.3.2) and the roles are properly shown in "View roles and identities" from dashboard.

In addition, since the upgrade I see error messages  

[ERROR][o.o.s.a.BackendRegistry  ] [osearch-node-1] Cannot retrieve roles for User [name=admin, backend_roles=[admin], requestedTenant=null] from ldap due to OpenSearchSecurityException[OpenSearchSecurityException[No user admin found]]; nested: OpenSearchSecurityException[No user admin found];

from attempts to retrieve additional roles for internal users from ldap. Previously there were no such warnings.

Thanks for any suggestions you might have.

**Comment by cliu123** [comment]
@tsgit I couldn't reproduce the issue on 1.3.2. Would you please share your steps to upgrade from 1.3.1 to 1.3.2?

**Comment by tsgit** [comment]
download and unpack 
https://artifacts.opensearch.org/releases/bundle/opensearch/1.3.2/opensearch-1.3.2-linux-x64.tar.gzhttps://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/1.3.2/opensearch-dashboards-1.3.2-linux-x64.tar.gz

copy opensearch-1.3.1/config/opensearch.yml to opensearch-1.3.2/config/opensearch.yml
copy opensearch-dashboards-1.3.1/config/opensearch_dashboards.yml opensearch-dashboards-1.3.2/config/opensearch_dashboards.yml

the path.data config points to a persistent directory

adjust ./opensearch/config/jvm.options to point to actual location of 
-Djava.security.policy=./opensearch-1.3.2/plugins/opensearch-performance-analyzer/pa_config/opensearch_security.policy  (that's a separately reported issue)


stop opensearch-dashboards and opensearch
start opensearch and opensearch-dashboards

visit the dashboard via proxy and watch the opensearch log

**Comment by tsgit** [comment]
I do not run the opensearch-tar-install.sh script, since the security plugin is already configured and the options certificates are set. I have used this approach for all releases since version 1.2.0.

**Comment by DarshitChanpura** [comment]
[Triage] Can you please open this as a support request on [the forum](https://forum.opensearch.org/)

**Comment by mirisu2** [comment]
did you manage to resolve this problem?
I have the same error too.
`[2022-06-20T13:06:32,515][WARN ][o.o.s.c.PrivilegesInterceptorImpl] [opensearch-2] Tenant global_tenant is not allowed for user ...`
opensearch version is 1.3.2
