### ISSUE TITLE
[Feature] Automate license header generation for all new files

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#1867]
Created as a follow-up for [this issue](https://github.com/opensearch-project/security/issues/1744) to add automation to license header generation whenever a new file is created.

**Comment by peternied** [comment]
[Triage] Could you add more details on how you'd want this resolved?

**Comment by davidlago** [comment]
@DarshitChanpura still need more details here (also, would this be better as an wider-than-this-repo issue?)

**Comment by DarshitChanpura** [comment]
Closing this issue as the configuration to add a license header has to be developer and their IDE specific can be easily configured. License header check is enabled in build.gradle
