### ISSUE TITLE
[BUG] Security configuration is bootstrapped in yml format and then converted into json

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#1872]
**What is the bug?**
When configurating permissions for a cluster there is a yaml format, see https://opensearch.org/docs/latest/security-plugin/configuration/yaml/, after the cluster has started the security configuration on disk is not updated causing drift.  Updating the security configuration is done with JSON based structure, which while similar to yaml in structure is not human parsable for differences.

**What is the expected behavior?**
Security configuration for OpenSearch should be easy to check for differences and confirm the intended settings are in place for peace of mind.

**Comment by cliu123** [comment]
We have no plan to change the current YAML strategy. If there's a specific use case that needs to be addressed, please post on this issue and the issue will be re-opened.
