### ISSUE TITLE
[BUG] Action groups are used as a crutch to fix bad permissions naming

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#1875]
**What is the bug?**
[Action groups](https://opensearch.org/docs/latest/security-plugin/access-control/api/#action-groups) create a way to group together several permissions under another name.  These groups do not follow naming conventions or standards allowing confusing actions group names like "cluster_composite_ops".  Without any heirarchy or pattern its hard to interpret what this value means.

Furthermore when supplied in a role, such as the following, its hard to know where one permissions overlaps with another such as the following read-only implied actions groups:

```json
{
   "my-role": {
      "cluster_permissions": [ "cluster_composite_ops_ro" ],
      "index_permissions": [
         { "allowed_actions":  [ "read" ] }
      ],
      "tenant_permissions": [
         { "allowed_actions":  [ "kibana_all_read" ] }
      ]
   }
}
```

**What is the expected behavior?**
Action groups should not exist, or they should be formed in a way that they bring clarity to the permissions being granted.

**Comment by cwperks** [comment]
[Triage] Closing this issue as it has sat in the issue list for over 6 months. @peternied please re-open with a proposal for action group re-design if you would like to see this work achieved in a future version of OpenSearch.
