### ISSUE TITLE
[BUG] Several actions cannot be delegated to users and must be run as an admin user

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#1878]
**What is the bug?**
There are APIs, such as [reloadcerts](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/ssl/rest/SecuritySSLReloadCertsAction.java#L42), which are only authorized for full admin users.

**What is the expected behavior?**
There should be granular permissions that for all actions in OpenSearch to be individually assigned.  The large blast radius in production clusters when performing operational tasks goes against common security practices like the [least privileged](https://www.beyondtrust.com/blog/entry/what-is-least-privilege).

**Do you have any additional context?**
> Also, Just noticed [this](https://github.com/opensearch-project/security/blob/1.3.2.0/src/main/java/org/opensearch/security/ssl/rest/SecuritySSLCertsInfoAction.java#L122-L126) which gets in the way of me having an internal user run the refresh command. This could be it's own permissions group, potentially.

_Originally reported by @patcable in https://github.com/opensearch-project/security/issues/1877_

### Other APIs that are admin only
* `nodesdn`
* `allowlist`
* `actiongroup`
* `user` / `internalusers`
* `roles`
* `rolesmapping`
* `tenants`

**Comment by willyborankin** [comment]
Hi @davidlago and @peternied  Out company is interested in fixing this problem, so I can prepare PR for it. Wdyt?

**Comment by peternied** [comment]
@willyborankin That would be awesome, I'd love to see a PR!

**Comment by willyborankin** [comment]
@peternied ok will try to do it asap

**Comment by davidlago** [comment]
Closing as #2411 was merged and released in 2.8
