### ISSUE TITLE
[BUG] on opensearch 2.0.0, securityadmin.sh is still looking for whitelist.yml instead of allowlist.yml 

### ISSUE THREAD

**Issue by phijojo** [opensearch-project/security#1879]
**What is the bug?**
While running the script `securityadmin.sh`  on OpenSearch 2.0.0, I can see it is checking for whitelist.yml. According to the [documentation](https://opensearch.org/docs/latest/breaking-changes/#deprecate-outdated-nomenclature), the whitelist.yml is deprecated and is replaced with allowlist.yml in 2.0.0. It reproducible on docker images

**How can one reproduce the bug?**
1. add `allowlist.yml` on `/usr/share/opensearch/plugins/opensearch-security/securityconfig/`
2. Go to `/usr/share/opensearch/plugins/opensearch-security/tools`
3.  Run securtiyadmin.sh 
`  ./securityadmin.sh -cd ../securityconfig/ -icl   -nhnv   -cacert ../../../config/certs/ca.crt  -cert ../../../config/certs/admin.pem  -key ../../../config/certs/admin.key`

**What is the expected behavior?**
While running the script . It should accept allowlist.yml instead of whitelist.yml. The script should not be expected to look for whitelist.yml on 2.0.0 images

**What is your host/environment?**
 - OS: Linux, Docker,Kubernetes
 - Version:  
 - Plugins: Security

**Do you have any screenshots?**
running securityadmin.sh without whitelist.yml
![image](https://user-images.githubusercontent.com/7951881/172558191-eb816809-9268-4741-8932-a934bb728fb2.png)

When adding whitelist.yml, its works fine
![](https://files.slack.com/files-pri/T6N963685-F03JNHSJAHJ/image.png)

**Do you have any additional context?**
This is a blocker for [PR]( https://github.com/opensearch-project/helm-charts/pull/272)

**Comment by peternied** [comment]
[Triage] Thanks for filing this issue.  @cliu123 do you have more context on this issue you could added?

**Comment by cliu123** [comment]
@phijojo  [The allowlist config and API](https://github.com/opensearch-project/security/pull/1808) will be introduced in OpenSearch 2.1.0 release as [planned](https://github.com/opensearch-project/OpenSearch/issues/2589#issuecomment-1101707941). We do apologize that the documentation does not reflect the accurate information.
