### ISSUE TITLE
BWC test to support multiple upgrade paths

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/security#1889]
This issue is to track the pending item mentioned in [the PR review comment](https://github.com/opensearch-project/security/pull/1883#pullrequestreview-1004722820).
BWC tests need to support multiple upgrade paths. This needs a generic solution in BWC test framework that can applied to all OpenSearch components.

**Comment by peternied** [comment]
Waiting on https://github.com/opensearch-project/OpenSearch/issues/3607
