### ISSUE TITLE
[BUG] The exceptions causing security not initilzed are not logged

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/security#1896]
**What is the bug?**
When OpenSearch cluster is red, security plugin cannot be initilized. But the exceptions causing security plugin not initilized are not logged. It is necessary to log all the exceptions to facilitate debugging security plugin initiation issues.

**How can one reproduce the bug?**
```
{"message":"OpenSearch Security not initialized ... security_exception","statusCode":503,"error":"Service Unavailable"}
```

**Comment by DarshitChanpura** [comment]
[Triage] Need more information about reproducing the error. We are happy to accept a PR for this issue.

**Comment by peternied** [comment]
[Triage] @cliu123 I don't see any updates, could you please provide more details?

**Comment by cliu123** [comment]
All exceptions causing [security plugin not initilizing successfully](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java#L180) need to be caught.

**Comment by peternied** [comment]
@cliu123 could update the description to include reproduction steps?

**Comment by cliu123** [comment]
The issue was reported offline. I'm also waiting for the reproduce steps from the source of the issue. I couldn't find the alias on Github to tag the right person. But I already requested reproduce steps offline. Let's give them some time to rely.

**Comment by cliu123** [comment]
@devardee Thanks for sharing your GitHub alias! Would you please provide the reproduce steps for the error message and add more details on what errors need to be logged?
```
{"message":"OpenSearch Security not initialized ... security_exception","statusCode":503,"error":"Service Unavailable"}
