### ISSUE TITLE
Test reliability is impacting CI workflows

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#1917]
There has been an increased number of test failures that have started to prevent continuous integration for pull requests.  It looks like this has been accelerated by the recent cut over to the Randomizer test runner.  While there has been progress with pull requests like https://github.com/opensearch-project/security/pull/1914, we should continue to invest in this space to keep our build and test runs passing consistently.

List of tests that have seen issues blocking a pull request:
* [x] TenantInfoActionTest.testTenantInfoAPIAccess
* [x] ComplianceAuditlogTest.testComplianceEnable
* [x] ComplianceAuditlogTest. testSourceFilterMsearch

List of tests that have seen issues failures, but passed on retry:
* [ ] TransportUserInjectorIntegTest.testSecurityUserInjection
* [ ] AllowlistApiTest.testAllowlistAuditComplianceLogging
* [ ] LegacyTenantInfoActionTests.testTenantInfoAPIUpdate

As we see more tests with issues or resolve test issue I'll update this list

**Comment by DarshitChanpura** [comment]
[Triage] Thank you for filing this. @peternied Please update this issue with when you will be done with it.

**Comment by peternied** [comment]
Another instance of `ComplianceAuditlogTest.testComplianceEnable` impacting a pull request https://github.com/opensearch-project/security/pull/1923, failures in https://github.com/opensearch-project/security/actions/runs/2579777726/attempts/1

**Comment by peternied** [comment]
Another instance in https://github.com/opensearch-project/security/pull/1924, `TenantInfoActionTest.testTenantInfoAPIAccess` was the blocking test

**Comment by peternied** [comment]
[Triage] @cwperks after you've fix the blocking test lets close out this issue.
