### ISSUE TITLE
[BUG] java.io.OptionalDataException - Cache Timeout

### ISSUE THREAD

**Issue by msoler8785** [opensearch-project/security#1927]
**What is the bug?**
When the auth cache expires it isn't properly updated causing a `java.io.OptionalDataException` exception to be returned from OpenSearch.

**How can one reproduce the bug?**
1. Use the Bulk API after the `plugins.security.cache.ttl_minutes` period has elapsed.

**What is the expected behavior?**
The cache is refreshed and there are no errors.

**What is your host/environment?**
 - OS: Ubuntu 20.04.4 LTS
 - Version: 2.0.1
 - Plugins: Standard

**Do you have any additional context?**
* Please see: https://github.com/opensearch-project/security/issues/1961
* Issue can cause data loss if using Logstash.

**Comment by peternied** [comment]
[Triage] Thanks for filing this issue @msoler8785 we will look into this issue.

**Comment by TheMeier** [comment]
I suspect this might be the reason for a problem we are seeing. We have installed a fresh cluster version 2.1.0. We deliver logs with fluent-bit. Every hour the delivery fails with:
```
"status":500,"error":{"type":"exception","reason":"java.io.OptionalDataException","caused_by":{"type":"i_o_exception","reason":null}}}}
```
It fails for roughly one hour and starts working again. Then one hour later the cycle repeats.
Clearing the cache (via dashboards or curl) does not resolve the problem.

What does resolve the problem ist to run securityadmin.sh with the exact same permissions again.

**Comment by TheMeier** [comment]
> What does resolve the problem ist to run securityadmin.sh with the exact same permissions again.

Even that does not reliably fix the problem.

**Comment by cwperks** [comment]
Closing as https://github.com/opensearch-project/security/pull/1970 has been merged
