### ISSUE TITLE
Staging for version increment automation

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/security#1930]
### Description

Gradle project: Staging to add gradle tasks (`setVersion` and `versionIncrement`) that support version increment automation for supported versions and add/update `gradle.properties` file to the project.

### Related META issue

Part of: https://github.com/opensearch-project/opensearch-build/issues/1375
From solution: https://github.com/opensearch-project/opensearch-build/issues/1375#issuecomment-1159476686

### Current Behavior

Version Increment is a process that needs to be done for all plugin repos during and after a specific release.
This is time consuming and includes lot of manual human effort (that can lead to multiple errors) to go through each repo, check for previous merged PR and then create a version increment PR, allow plugin team to review, follow-up, update the PR with suggestions and then finally get merged for CI to run.

### Expected Behavior

After every release expect to raise an [AUTO] PR that increments the version.
Sample automation version increment PR's: [job-scheduler](https://github.com/prudhvigodithi/job-scheduler/pull/1), [common-utils](https://github.com/prudhvigodithi/common-utils/pull/1), [anomaly-detection](https://github.com/prudhvigodithi/anomaly-detection/pull/1), [k-NN](https://github.com/prudhvigodithi/k-NN/pull/1)

### Proposed solution

Automate this version increment process across all plugin components, that increment’s the version, modifies the required files and raise a PR that awaits for plugin team approval, this way an engineer need not spend hours of time to increment the version for all plugin components.

### Implementation Changes:

Add gradle `versionIncrement` and `setVersion` tasks to the project. 

`setVersion` : This task will update the gradle property `opensearch.version` and updates the value in `gradle.properties` file.

`gradle.properties` : Contains gradle project properties that can be used by project during runtime, for version increment uses `opensearch.version`.

`versionIncrement` : This task is configurable and depends on the plugin requirement to modify any files where version is present and that needs to incremented, this task uses [ant.replaceregexp](https://ant.apache.org/manual/Tasks/replaceregexp.html) to parse the required files that are added in include() section of the task. 

Sample Implementation PR's: [job-scheduler](https://github.com/opensearch-project/job-scheduler/pull/196), [common-utils](https://github.com/opensearch-project/common-utils/pull/192), [anomaly-detection](https://github.com/opensearch-project/anomaly-detection/pull/603), [k-NN](https://github.com/opensearch-project/k-NN/pull/432)
More examples: https://github.com/opensearch-project/opensearch-build/issues/1375#issuecomment-1165692455

**Comment by peternied** [comment]
@prudhvigodithi This work is done, can we close this issue?

**Comment by cwperks** [comment]
@prudhvigodithi This PR was included in the 2.2.0 release. Closing this issue.
