### ISSUE TITLE
securityadmin.sh should set to executable

### ISSUE THREAD

**Issue by jeff-cook** [opensearch-project/security#194]
All shell scripts in the plugins/opendistro_security/tools directory should be set to executable.

**Comment by rtsisyk** [comment]
I have the same problem on OpenShift 4.x:

```
OpenDistro for Elasticsearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/elasticsearch
Elasticsearch install type: rpm/deb on CentOS Linux release 7.8.2003 (Core)
Elasticsearch config dir: /usr/share/elasticsearch/config
Elasticsearch config file: /usr/share/elasticsearch/config/elasticsearch.yml
Elasticsearch bin dir: /usr/share/elasticsearch/bin
Elasticsearch plugins dir: /usr/share/elasticsearch/plugins
Elasticsearch lib dir: /usr/share/elasticsearch/lib
Detected Elasticsearch Version: x-content-7.6.1
Detected Open Distro Security Version: 1.7.0.0

chmod: changing permissions of '/usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh': Operation not permitted
```

**Comment by fbartnitzek** [comment]
Any progress on this issue for openshift-users? 
Mounting `docker-entrypoint.sh`, `install_demo_configuration.sh` and `securityadmin.sh` explicitly via helm-configmaps with an executable fileMode and commented out `chmod` isn't perfect either...

**Comment by swapwalivkar** [comment]
Any update on this issue.
I am getting same error while trying to deploy elk on openshift container platform

**Comment by ckvtvm-arch** [comment]
I am also facing the same issue in OCP 4.6

**Comment by jheidecker** [comment]
Chiming in on this issue. OKD 4.7

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
