### ISSUE TITLE
[BUG] auth/http/saml/Saml2SettingsProvider.java still using _opendistro/ instead of _plugins/

### ISSUE THREAD

**Issue by kzinas-adv** [opensearch-project/security#1941]
**What is the bug?**
A clear and concise description of the bug.
opensearch-project/security-dashboards-plugin in version 2.1.0 changed SAML2 authentication endpoint to   `_plugins/_security/saml/acs`
while  opensearch-project/security use old one `/_opendistro/_security/saml/acs`
This creates clash as users need modify this place by hand to get SAML working.  

**How can one reproduce the bug?**
Use opensearch 2.1.0 with SAML 

**What is the expected behavior?**
Get opensearch 2.2.0 working out of the box.

security-dashboards-plugin BUG issue:
https://github.com/opensearch-project/security-dashboards-plugin/issues/1031

**Comment by kzinas-adv** [comment]
https://github.com/opensearch-project/security/pull/1936/commits

**Comment by peternied** [comment]
Lets put some more attention back onto this issue during the triage meeting.  All the history boils down to we need to make this change backwards compatible with both paths and when it was originally rolled out it wasn't compatible

**Comment by scrawfor99** [comment]
[Triage] This issue should be reviewed again since it is not currently backwards compatible. Let's have someone pick up the issue to become BWC.

**Comment by peternied** [comment]
@RyanL1997 You might want to look into multiple endpoints, seems like it is supported in SAML 2.0 [1] [2].

- [1] https://stackoverflow.com/q/28659811/533057
- [2] https://stackoverflow.com/q/39567112/533057

**Comment by RyanL1997** [comment]
### Update on Aug/30/2023
Transferring the internal discussion result here: security team decided to deprecate all the legacy prefix thats related to SAML usages all at once at the next major version. Plz use the issue (https://github.com/opensearch-project/security/issues/3271) for better tracking.
