### ISSUE TITLE
Open search roles and users is not working for any index pattern expect for '*'

### ISSUE THREAD

**Issue by kdbmadhavi** [opensearch-project/security#1944]
I was trying to create new user ans role for certain indices
i used https://opensearch.org/docs/latest/security-plugin/access-control/users-roles/ document
I created the role where i specified required index-pattern, user and mapped role, it always ended up showing up 
{"statusCode":403,"error":"Forbidden","message":"no permissions for [indices:data/read/search] and User [name=aicasino, backend_roles=[], requestedTenant=]: security_exception"}

below image shows my role inputs ,even though i gave all permissions at cluster level or index level the issue persisted
It was unable to refer the index pattern which  i specified.
I also tried with API which was of no use.
Please help me.
Thank You
<img width="226" alt="role" src="https://user-images.githubusercontent.com/107416892/178717138-a55f0fec-e8d2-49df-9c18-435c15c8dcfb.png">

**Comment by kdbmadhavi** [comment]
any progress on the issue

**Comment by cliu123** [comment]
@kdbmadhavi Would you please provide more information about the issue by following this template?
```
**What is the bug?**
A clear and concise description of the bug.

**How can one reproduce the bug?**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**What is the expected behavior?**
A clear and concise description of what you expected to happen.

**What is your host/environment?**
 - OS: [e.g. iOS]
 - Version [e.g. 22]
 - Plugins

**Do you have any screenshots?**
If applicable, add screenshots to help explain your problem.

**Do you have any additional context?**
Add any other context about the problem.

**Comment by kdbmadhavi** [comment]
sure @cliu123 ,thanks for responding back ,i need the solution ASAP
so the issue occured when i am trying to assign user with few index pattern
AIM: is to create a seperate user for some of the indices in opensearch
Procedure followed:

I followed mainly steps from the following link https://opensearch.org/docs/latest/security-plugin/access-control/users-roles/#set-up-a-bulk-access-role-in-opensearch-dashboards


created role:
Open OpenSearch logged with admin credentials.
Choose Security, Roles.
Create a new role named readrole.
For Cluster permissions, add the cluster_composite_ops(tried giving cluster_all and all).
For Index pattern, add an existing index pattern as it is like my-index-*.
For index permissions, add the write action group.
Choose Create.

created user:
Choose Security, Internal Users, and Create internal user
Provided a username and password


later Mapped the role to your user:
Choose the Mapped users tab in roles > Manage mapping > specified user.
Choose Map.

when i logged opensearch with the new user no index was listed in discover tab,a blank opensearch screen appeared,
when i inspected the page it was showing 403 issue:
{"statusCode":403,"error":"Forbidden","message":"no permissions for [indices:data/read/search] and User [name=aicasino, backend_roles=[], requestedTenant=]: security_exception"}

**Comment by cliu123** [comment]
@kdbmadhavi Thanks for filing the issue! The index permission mentioned in the issue is `*` that is different from the index pattern permission being granted in the screenshot. Would you please provide your configurations and transfer your questions to [the forum](https://forum.opensearch.org/c/security/3)?
