### ISSUE TITLE
Bump the main branch to 3.0

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/security#1953]
**Is your feature request related to a problem?**
We're working on few changes in cross cluster replication for 3.0. For us to be able to use CCR on 3.0, we need to have security plugin also bumped up to 3.0. 
I see that was already done as part of [this PR](https://github.com/opensearch-project/security/pull/1890) but was reverted [here](https://github.com/opensearch-project/security/pull/1901).  Not sure why it was reverted though.

**What solution would you like?**
Bump the main branch to 3.0 and add to OS build manifest.
cc: @DarshitChanpura @peternied @cliu123

**Comment by cliu123** [comment]
The change was reverted in [this PR](https://github.com/opensearch-project/security/pull/1901) because it failed the BWC, so it was blocking 2.1.0 release.

**Comment by peternied** [comment]
Following up in OpenSearch, see https://github.com/opensearch-project/OpenSearch/issues/3615

**Comment by dblock** [comment]
Nothing should be blocking this anymore.

**Comment by ankitkala** [comment]
@peternied @DarshitChanpura Can you guys also add security to 3.0 manifest: https://github.com/opensearch-project/opensearch-build/blob/main/manifests/3.0.0/opensearch-3.0.0.yml
