### ISSUE TITLE
[FEATURE] Update to Gradle 7.5

### ISSUE THREAD

**Issue by reta** [opensearch-project/security#1962]
**Is your feature request related to a problem? Please describe.**
Gradle 7.5 is out [1]

[1] https://github.com/gradle/gradle/releases/tag/v7.5.0

**Describe the solution you'd like**
Update to Gradle 7.5

**Describe alternatives you've considered**
Keep using Gradle 7.4.2

**Additional context**
Related to https://github.com/opensearch-project/OpenSearch/issues/3901

**Comment by peternied** [comment]
This should target v3.0.0, as this was where OpenSearch applied the updated

**Comment by reta** [comment]
@peternied it was backported to 2.2.0
