### ISSUE TITLE
Need to provide both whitelist.yaml and allowlist.yml in the security configuration even when whitelist.ym should have been replaced with allowlist.yml

### ISSUE THREAD

**Issue by pratikshavyas** [opensearch-project/security#1975]
**What is the bug?**
As part of Opensearch 2.x to include more inclusive naming conventions, whitelist.yml is replaced with allowlist.yml in security configuration files.
However, I observed that we still need to provide both whitelist.yml and allowlist.yml files in the configuration, otherwise it throws an error while running security admin.

**How can one reproduce the bug?**
Install opensearch v2.1.0 with security

**What is the expected behavior?**
whitelist.yml config file should have been replaced with allowlist.yml and securityAdmin should have run fine. Both files should not have been necessary.

**What is your host/environment?**
 - Opensearch version 2.1.0
 - OPensearch security version 2.1.0.0

**Do you have any additional context?**
When running securityadmin.sh on v2.1.0, I still see that we need to provide both whitelist.yaml and allowlist.yml in the security configuration.

`OpenSearch Version: 2.1.0
Contacting opensearch cluster 'wyz' and wait for YELLOW clusterstate ...
Clusterstate: GREEN
Number of nodes: 6
Number of data nodes: 1
.opendistro_security index does not exists, attempt to create it ... done (0-all replicas)
Populate config from /etc/opensearch/opensearch-security/
Will update '/config' with /etc/opensearch/opensearch-security/config.yml
   SUCC: Configuration for 'config' created or updated
Will update '/roles' with /etc/opensearch/opensearch-security/roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update '/rolesmapping' with /etc/opensearch/opensearch-security/roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update '/internalusers' with /etc/opensearch/opensearch-security/internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Will update '/actiongroups' with /etc/opensearch/opensearch-security/action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated
Will update '/tenants' with /etc/opensearch/opensearch-security/tenants.yml
   SUCC: Configuration for 'tenants' created or updated
Will update '/nodesdn' with /etc/opensearch/opensearch-security/nodes_dn.yml
   SUCC: Configuration for 'nodesdn' created or updated
Will update '/whitelist' with /etc/opensearch/opensearch-security/whitelist.yml
   SUCC: Configuration for 'whitelist' created or updated
Will update '/audit' with /etc/opensearch/opensearch-security/audit.yml
   SUCC: Configuration for 'audit' created or updated
SUCC: Expected 10 config types for node {"updated_config_types":["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"],"updated_config_size":10,"message":null} is 10 (["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"]) due to: null
SUCC: Expected 10 config types for node {"updated_config_types":["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"],"updated_config_size":10,"message":null} is 10 (["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"]) due to: null
SUCC: Expected 10 config types for node {"updated_config_types":["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"],"updated_config_size":10,"message":null} is 10 (["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"]) due to: null
SUCC: Expected 10 config types for node {"updated_config_types":["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"],"updated_config_size":10,"message":null} is 10 (["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"]) due to: null
SUCC: Expected 10 config types for node {"updated_config_types":["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"],"updated_config_size":10,"message":null} is 10 (["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"]) due to: null
SUCC: Expected 10 config types for node {"updated_config_types":["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"],"updated_config_size":10,"message":null} is 10 (["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"]) due to: null
SUCC: Expected 10 config types for node {"updated_config_types":["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"],"updated_config_size":10,"message":null} is 10 (["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"]) due to: null
Done with success
securityadmin ended`

If I do not provide whitelist.yml and give only allowlist.yml in security-config, I get an error as below:
`ERR: Seems /etc/opensearch/opensearch-security/whitelist.yml is not in OpenSearch Security 7 format: java.io.FileNotFoundException: /etc/opensearch/opensearch-security/whitelist.yml (No such file or directory)`

**Comment by cliu123** [comment]
@pratikshavyas Thanks for filing this issue! 
`whitelist.yml` is deprecated, but won't be removed until OpenSearch 3.0. It was designed to be honored only when `allowlist.yml` is not present in the cluster. The behavior that you run into in the securityAdmin tool is not expected and we'll investigate it.

**Comment by peternied** [comment]
Thanks for filing, when we remove whitelist.yml for 3.0.0 this scenario will be a little cleaner without the extraneous references.

**Comment by Mawiguk0** [comment]
Disabling the white- or allowlists via the feature flag inside the files gives a weird behavior.
The error that securityadmin gives indicates a file being not found, whereas the file is there, valid and parsed.

Looking forward to see a new approach in 3.0.0
