### ISSUE TITLE
[BUG] No handler found for URI /_plugins/_security/api/nodesdn

### ISSUE THREAD

**Issue by dredwilliams** [opensearch-project/security#1998]
The API for the security plugin does not seem to be able to handle the API for the nodes_dn data. 

From the Dev Console inside dashboards or externally using curl and the admin keys, this request:

```
 GET _plugins/_security/api/nodesdn
```

results in

```
 {
   "error" : "no handler found for uri [/_plugins/_security/api/nodesdn] and method [GET]"
 }
```

This is a new install of RPM-based OpenSearch 2.1.0 running on RHEL8

I use the `plugins.security.nodes_dn` parameter in the `opensearch.yml` file to implement host validation, but would like to move to the nodes_dn.yml file -- but the documentation on that is lacking at the moment.

**Comment by peternied** [comment]
@dredwilliams I see that this was closed shortly after it was opened, Is there an issue around this feature or its documentation?
