### ISSUE TITLE
[Infrastructure] Intermittent 1.3 branch CI failures

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#2023]
The recent [update](https://github.com/opensearch-project/security/pull/2004) of dependencies in 1.3 took 6 times of the CI running to pass CI. 

This was a minor fix to increment dependencies flagged by whitesource as having vulnerabilities and `jackson-databind` was upgraded to align with 1.x and with core's `version.properties`.

Some of the tests that failed intermittently include:

```
-org.opensearch.security.HttpIntegrationTests > testTenantInfo FAILED
    java.lang.AssertionError at HttpIntegrationTests.java:685

- org.opensearch.security.auditlog.integration.BasicAuditlogTest > testRestMethod FAILED
    java.lang.AssertionError at BasicAuditlogTest.java:854

- org.opensearch.security.auditlog.AuditLogTestSuite > org.opensearch.security.auditlog.sink.WebhookAuditLogTest.postGetHttpTest FAILED
    java.net.BindException: Address already in use (Bind failed)

- org.opensearch.security.ssl.SSLTest > testCRL FAILED
    java.lang.RuntimeException at SSLTest.java:798
        Caused by: org.opensearch.http.BindHttpException at AbstractHttpServerTransport.java:203
            Caused by: java.net.BindException at Net.java:-2

- org.opensearch.security.ssl.SSLTest > testTLSv12 FAILED
    java.lang.RuntimeException at SSLTest.java:874
        Caused by: org.opensearch.http.BindHttpException at AbstractHttpServerTransport.java:203
            Caused by: java.net.BindException at Net.java:-2
```

**Comment by scrawfor99** [comment]
For reference here is a link to a specific instance of the types of improvements that may improve stability look at issue #2278

**Comment by scrawfor99** [comment]
I have been working on this and I think that the issue is caused because the webhookAuditLogTest tests are called multiple times directly and also from AuditLogTestSuite. The tests actually pass 3 times (all called from the suite) before failing the first time they are directly called by webhook. Will look into this further on Monday.

**Comment by peternied** [comment]
I think I've tackled many of these failures in https://github.com/opensearch-project/security/pull/2291 - take a look

**Comment by scrawfor99** [comment]
I will definitely take a look at it and see where we are at with your fixes!

**Comment by scrawfor99** [comment]
Closed since changes fixed test failures.
