### ISSUE TITLE
[Support] How should we signal a release is no longer supported?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2025]
As of the writing of this issue there are many branches in this codebase that are not supported such as `opendistro-*` as well as `1.0`.  How should we communicate the currently supported versions?  What actions should we take or not on these branches?  Should we delete branch pointers since tags have been created for these releases?

**Comment by rursprung** [comment]
> If that is the case, wdyt about bubbling this issue up to the project to have that discussion with all repos represented?

i'd also strongly suggest to not have a plugin-specific mechanism for this but instead solve this at an organisation-level: the support duration and corresponding handling of the branches should be the same for all repos under the opensearch-project umbrella. probably even [opensearch-plugins](https://github.com/opensearch-project/opensearch-plugins) is the wrong place to discuss this as this isn't plugin-specific but relevant also for the server & dashboards.

**Comment by peternied** [comment]
Closing this out in favor of https://github.com/opensearch-project/.github/issues/83 thanks for the feedback @davidlago @rursprung
