### ISSUE TITLE
duplicate check for role in ConfigModelV7#TenantHolder#mapTenants

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/security#2035]
the check looks for `kibana_user` twice:
https://github.com/opensearch-project/security/blob/6b7a5869c84d453bb22be861a88b744512fa0d64/src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java#L1130-L1131

this is obviously not needed. the question is what it should be in reality, if there should be something else or if the duplicate line can just be removed.

furthermore the case-sensitivity seems spotty as it explicitly checks the lower- & upper-case version of `all_access` but not of the others - is this as intended or should the check be done properly case-insensitive for all?

**Comment by rursprung** [comment]
@Hailong-am / @davidlago: since #2183 has been merged i guess this is fixed? can you please double-check and close the issue (and mention the versions where it has been fixed)? thanks!

**Comment by Hailong-am** [comment]
The fix is included in release 2.4
