### ISSUE TITLE
Remaining areas to replace legacy references of opendistro and move to inclusive language

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#2050]
There have been a few recent updates to the Documentation Website to update documentation in areas that were missed from the transition away from legacy `opendistro` references or to the use of inclusive language. 

Here are three examples:

- [ ] [Fix setting name for LDAP custom attribute filter](https://github.com/opensearch-project/documentation-website/pull/912)
- [ ] [Update documentation from opensearch_security_roles to opendistro_security_roles](https://github.com/opensearch-project/documentation-website/pull/892)
- [ ] [Change /_plugins/_security/.. routes to /_opendistro/_security/... for SAML until plugins route is supported](https://github.com/opensearch-project/documentation-website/pull/877)

I'm opening an issue to keep track of any instances that come up to keep track of the remaining areas that need to be updated.

**Comment by peternied** [comment]
@cwperks Thanks for filing this, could we separate out the individual actions that we need to take, maybe create issues for the legacy API paths, update legacy settings, or change documentation around the roles.  This way we can close them as they are completed.

**Comment by cwperks** [comment]
@peternied 3 new issues have been created to track each issue independently.

- https://github.com/opensearch-project/security/issues/2059
- https://github.com/opensearch-project/security/issues/2058
- https://github.com/opensearch-project/security/issues/2060

**Comment by peternied** [comment]
@cwperks Thanks for filing these issues, we will close them as we work these issues.
