### ISSUE TITLE
[FEATURE] Integration tests should generate X.509 certificates in the course of tests execution

### ISSUE THREAD

**Issue by lukasz-soszynski-eliatra** [opensearch-project/security#2057]
**Is your feature request related to a problem?**
The issue is related to the new test framework, please see https://github.com/opensearch-project/security/pull/1967#discussion_r952757079

**What solution would you like?**
Use certificates which are generated dynamically instead of certificates which are hard coded in source code.

**What alternatives have you considered?**
It is possible to still use certificates hardcoded in source code

**Do you have any additional context?**
The feature is related to the extension of new test framework for integration tests: https://github.com/opensearch-project/security/pull/1967

**Comment by cwperks** [comment]
[Triage] This was addressed in the new test framework, but should be extended to all integration tests

**Comment by scrawfor99** [comment]
I am not sure how realistic this is without using bouncy castle: https://stackoverflow.com/questions/1615871/creating-an-x509-certificate-in-java-without-bouncycastle?rq=4. 

@cwperks you said there was hesitancy to use Bouncy Castle for this task? It seems like this will require writing our own serializer for the certificates.

**Comment by cwperks** [comment]
Cert generation is done in the integrationTest framework. Closing this issue.
