### ISSUE TITLE
Legacy reference to `opendistro` in `internal_users.yml`

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#2058]
There is a reference to `opendistro` in `internal_users.yml` as an attribute name `opendistro_security_roles`. This was discovered in (https://github.com/opensearch-project/security/issues/1339) where a user had copied the example configuration on the documentation website which referenced `opensearch_security_roles` and received an `Unrecognized field` error when running security admin. 

The documentation website has since been reverted to display `opendistro_security_roles` in this PR: https://github.com/opensearch-project/documentation-website/pull/892.

We should revisit this area to replace the reference to the legacy `opendistro`.

**Comment by peternied** [comment]
Thanks for filing this, I think that this would be a good fix, but this might not be a good time to make this change.
