### ISSUE TITLE
Replace non-inclusive term "whitelist" in LDAP configuration

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#2059]
A recently filed issue (https://github.com/opensearch-project/security/issues/2032) revealed a discrepancy between the documentation website and the actual config parameter when configuring LDAP for an authentication backend. The documentation website was displaying a parameter `custom_attr_allowlist`, while the security plugin looks for `custom_attr_whitelist`. The documentation website has been reverted temporarily to show the actual parameter (https://github.com/opensearch-project/documentation-website/pull/912).

This change is part of the broader initiative in opensearch to remove non-inclusive language: https://github.com/opensearch-project/OpenSearch/issues/1483

**Comment by peternied** [comment]
Lets make sure we deprecate this config value in the 2.X line, and make sure that this has been replaced for the 3.0 release.
