### ISSUE TITLE
[BUG]There is no complete mTLS handshake when REST client connects to mTLS enabled opensearch ES

### ISSUE THREAD

**Issue by lsa5521** [opensearch-project/security#2067]
**What is the bug?**
When connected with curl having client certificate to mTLS enabled ES saw expected mTLS handshake sequence but
when did the same with opensearch REST client saw only TLS handshake in a tcpdump. 
The functionally it worked and there was a proper response from the ES

**How can one reproduce the bug?**
Description of the test is in the README file of the attached project and project itself has the code showing this behavior

**What is the expected behavior?**
Expected complete mTLS handshake and saw only TLS related messages in a tcpdump

**What is your host/environment?**
 - Linux

[ESRestClientOpenSearchBug.zip](https://github.com/opensearch-project/security/files/9481024/ESRestClientOpenSearchBug.zip)

**Comment by peternied** [comment]
@lsa5521 Could you please create a support request in https://forum.opensearch.org/c/security/3.

**Comment by lsa5521** [comment]
Posted in the forum https://forum.opensearch.org/t/there-is-no-complete-mtls-handshake-when-rest-client-connects-to-mtls-enabled-opensearch-es/10859
