### ISSUE TITLE
[FEATURE] Support LDAP pool pruning

### ISSUE THREAD

**Issue by Martin-Kemp** [opensearch-project/security#2090]
**Is your feature request related to a problem?**

LDAP pool pruning is a common requirement for connecting to productive ldap servers. Currently the pruning period and idle time is hard coded to 5 and 10 minutes respectively. It would be nice to be able to configure this through `config.yml`.

**What solution would you like?**

Configure ldap connection pool pruning period and idle time through `config.yml`. For example, currently you can enable pooling and set the min and max size. ideally `pool.idle_time` and `pool.pruning_period` should also be configurable. Like this:
```
pool.enabled: true
pool.min_size: 0
pool.max_size: 5
pool.idle_time: 2
pool.pruning_period: 1
```

**What alternatives have you considered?**

I'm currently running a custom image with above change.

**Do you have any additional context?**

Pruning period and idle time is currently set [here](https://github.com/opensearch-project/security/blob/main/src/main/java/com/amazon/dlic/auth/ldap2/LDAPConnectionFactoryFactory.java#L130)

Maybe I'm not understanding the code correctly and this config can actually be set somewhere because there is a setting referenced:

```
        result.setPruneStrategy(new IdlePruneStrategy(Duration.ofMinutes(this.settings.getAsLong("pruning.period", 5l)),
                Duration.ofMinutes(this.settings.getAsLong("pruning.idleTime", 10l))));
```
But I have no idea where to set `pruning.period` and `pruning.idleTime`.

**Comment by peternied** [comment]
The fix for this issue has been merged, and will be released in the next 2.X distribution
