### ISSUE TITLE
LDAP timeouts

### ISSUE THREAD

**Issue by BlOcKoUt** [opensearch-project/security#211]
Like the elasticsearch xpack plugin (https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html) it would be good to be able to setup:

> timeout.tcp_connect
> The TCP connect timeout period for establishing an LDAP connection. An s at the end indicates seconds, or ms indicates milliseconds. Defaults to 5s (5 seconds ).
> timeout.tcp_read
> The TCP read timeout period after establishing an LDAP connection. An s at the end indicates seconds, or ms indicates milliseconds. Defaults to 5s (5 seconds ).
> timeout.ldap_search
> The LDAP Server enforced timeout period for an LDAP search. An s at the end indicates seconds, or ms indicates milliseconds. Defaults to 5s (5 seconds ).

My issue is that LDAP is working just fine if i disable 2FA logins, but if it's enabled I need a bit higher timeout so user have a chance to enter it. By default it just fail user auth after 5 seconds and realistically we need like 20s.

I'm not sure, it's probably possible to set it up on elasticsearch level but can't figure out how. Will try to look into it...

Thanks in advance!

**Comment by BlOcKoUt** [comment]
Looks like timeouts are hardcoded here https://github.com/opendistro-for-elasticsearch/security/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/security/httpclient/HttpClient.java#L258-L264

**Comment by kumode** [comment]
Would be great if this issue would get some attention!

**Comment by nateynateynate** [comment]
Closed by #307 in for-elasticsearch-docs
