### ISSUE TITLE
[BUG] - permissions on specific indeces do not work unless get and indices:data/read/search are granted to *

### ISSUE THREAD

**Issue by anubisg1** [opensearch-project/security#2120]
**What is the bug?**
When granting permissions to a specific index, no request will work unless also `get` and `indices:data/read/search` are granted to all indeces `*` .

This grants too much and allows users that should be restricted to access a single index to see much more than they should 

**How can one reproduce the bug?**
1. make sure at least 2 indeces exist
2. go to security , roles and create a new role so that the `read` permission is granted to only one of the two indeces, also grant `read only` to the global tenant
3. assign the role to a user
4. access the data , it will fail
5. go back to the role and grant also `get` and `indices:data/read/search` to all indeces
6. access again the data, now it will work but all indeces are visible

**What is the expected behavior?**
i should not be required to grant access to other indeces

**What is your host/environment?**
 - OS: ubuntu, azure AKS
 - Version 2.3.0
 - Plugins installed using the kubernetes operator, no plugins added expect default

**Do you have any screenshots?**

**Do you have any additional context?**
in the specific my role has the following permissions

```
indexes: network-* , filebeat-* 
permission: read
```

`do_not_fail_on_forbidden: true` is also configured 

when loggin in, the api call 

```
api/saved_objects/_find?fields=title&per_page=1&search=*&search_fields=title&type=index-pattern
```

returns with:

```
{"statusCode":403,"error":"Forbidden","message":"no permissions for [indices:data/read/search] and User ...
```

adding the following permissions does nothing.

```
index: *
permissions: 
    - "indices:data/read/search/template"
    - "indices:data/read/msearch/template"
```  

the only way i can get some progress is by granting:

```
index: *
permission: indices:data/read/search 
```

in that case, the previous call succeed 

and returns

```
{
	"page": 1,
	"per_page": 1,
	"total": 4,
	"saved_objects": [{
		"type": "index-pattern",
		"id": "network-*",
		"attributes": {
			"title": "network-*"
		},
		"references": [],
		"migrationVersion": {
			"index-pattern": "7.6.0"
		},
		"updated_at": "2022-09-29T10:44:29.857Z",
		"version": "Wzk3LDdd",
		"namespaces": ["default"],
		"score": 1
	}]
}
```

unfortunately there are still problems as trying to access discover or dashboards

for the api call `api/opensearch-dashboards/settings`

the response is

` {"statusCode":403,"error":"Forbidden","message":"no permissions for [indices:data/write/update] and User `

for the api call `/api/saved_objects/_bulk_get`

the response is 

` {"statusCode":403,"error":"Forbidden","message":"no permissions for [] and User `

the only way i can properly browse is to grant `indices:data/read/search` + ` get ` .
when the read permission is granted to * i obtain the following answer to the api call

`
api/saved_objects/_find?fields=title&per_page=1&search=*&search_fields=title&type=index-pattern
`

```
{
	"page": 1,
	"per_page": 10000,
	"total": 4,
	"saved_objects": [{
		"type": "index-pattern",
		"id": "network-*",
		"attributes": {
			"title": "network-*"
		},
		"references": [],
		"migrationVersion": {
			"index-pattern": "7.6.0"
		},
		"updated_at": "2022-09-29T10:44:29.857Z",
		"version": "Wzk3LDdd",
		"namespaces": ["default"],
		"score": 0
	}, {
		"type": "index-pattern",
		"id": "filebeat-*",
		"attributes": {
			"title": "filebeat-*"
		},
		"references": [],
		"migrationVersion": {
			"index-pattern": "7.6.0"
		},
		"updated_at": "2022-09-29T10:44:29.857Z",
		"version": "WzEwNCw3XQ==",
		"namespaces": ["default"],
		"score": 0
	}, {
		"type": "index-pattern",
		"id": "snmp-*",
		"attributes": {
			"title": "snmp-*"
		},
		"references": [],
		"migrationVersion": {
			"index-pattern": "7.6.0"
		},
		"updated_at": "2022-09-29T12:30:48.194Z",
		"version": "WzEwNyw3XQ==",
		"namespaces": ["default"],
		"score": 0
	}, {
		"type": "index-pattern",
		"id": "security-auditlog-*",
		"attributes": {
			"title": "security-auditlog-*"
		},
		"references": [],
		"migrationVersion": {
			"index-pattern": "7.6.0"
		},
		"updated_at": "2022-09-29T12:31:07.357Z",
		"version": "WzEwOCw3XQ==",
		"namespaces": ["default"],
		"score": 0
	}]
}
```

notice  how a lot more indexes are returned compared to before

**Comment by scrawfor99** [comment]
@cwperks could tag this as #help_wanted and #triaged?

**Comment by cwperks** [comment]
[Triage] Re-surfacing this issue. @cwperks could you take a look?

**Comment by k11h-de** [comment]
Has anyone being able to solve or workaround it?

**Comment by sarajeev** [comment]
@anubisg1 @k11h-de 
This will work if you add one more indeces pattern with read access i.e. indeces "?kibana" and permission "read". So by this way you will be able to access your given indeces.
Here still there is one problem, that is you will be able to see other indeces as well, but when you try to aaccess them, then it will give you access denied error.

**Comment by anubisg1** [comment]
thanks i'll give it a try

**Comment by k11h-de** [comment]
That did work for me. Thanks a million.
