### ISSUE TITLE
[HTTP/2] Functional Test cases

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2125]
With https://github.com/opensearch-project/security/pull/2051 the security plugin supports HTTP/2 but there are no new tests cases that verify this functionality.  We should make sure before the release of 3.0.0 we have checks in place to ensure there are no regressions.

**Comment by peternied** [comment]
@reta Did you have anything you'd like to expand on this issue?

**Comment by reta** [comment]
@peternied yes, we basically do not have client support at the moment for HTTP/2 side, I am working on it [1] but it takes a bit longer than I planned. So basically may question would be: is it acceptable to add tests which a) either use Netty HTTP/2 client b) or use Apache HttpClient 5.x? Rest Client and HLRC are out of options right now.

[1] https://github.com/opensearch-project/OpenSearch/pull/4459/files

**Comment by peternied** [comment]
Assuming the final OpenSearch Rest Client implementations leverage Netty, Apache, or another standard library for the communication interface, using HTTP/2 implementation from Netty/Apache for the tests in this library would be fine to me.

If we were developing anything outside the standard that needed additional verification, then it might make to hold off until the RC/HLRC were avaliable, or at least augment testing with that at a further date/time.

**Comment by peternied** [comment]
As we have lead time on v3.0.0 - I am not concerned about delivering these test quickly, but instead making sure that we do not forget them and build them with appropriate coverage.

**Comment by reta** [comment]
@peternied if you don't mind, please assign this issue to me, I will make sure the test suites are present
