### ISSUE TITLE
[BUG] Security Plugin does not have batch script for install demo configurations for windows

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/security#2148]
As a follow up to this issue:
https://github.com/opensearch-project/security/issues/2122

The install demo configuration script is only available in Shell form.
This means it is not possible to run it in Windows env.

In ODFE we run the script pre-configured for user in LINUX machine before assembling the windows zip.
We have to do the same now for OpenSearch: https://github.com/opensearch-project/opensearch-build/pull/2704.

The above is a temporary solution and we achieve this change by utilizing the mingw env within the windows jenkins agent, simulating a linux shell env to generate the demo certs, or the start up of the cluster will fail with security installed.

We think it is a better solution if security team can provide a batch file version of the install demo configuration script so we can resolve this issue natively on Windows without the need to pre-populate the certs for users, or simulating a LINUX shell env on Windows, as it is not done in Tarball as of yet.

Thanks.

**Comment by vinayak15** [comment]
[Triaged] @cwperks Can you please follow up with peterzhuamazon regarding this issue.

**Comment by cwperks** [comment]
@peterzhuamazon @bbarani The script for the batch file of `install_demo_configuration.bat` is written and verified using multiple workspaces and automated with a `windows-latest` github runner against 2.x. There is currently a problem with the automated validation on 3.0.0 which is being resolved. See comment here (https://github.com/opensearch-project/security/pull/2161#issuecomment-1290602057) for context. 

According to the discussion on here (https://github.com/opensearch-project/OpenSearch/issues/4942) - one solution is for core to revert a recent change that prevents opensearch nodes to be brought up on the github runners and re-work the change.

**Comment by minalsha** [comment]
@cwperks https://github.com/opensearch-project/OpenSearch/pull/4949 has been merged.

**Comment by cwperks** [comment]
Thank you @minalsha and @peterzhuamazon ! Would it be possible to create another snapshot distribution with this change included: https://github.com/opensearch-project/security/pull/2161/files#diff-3e971aab38c741b1cb89584068ce23192213a18b1ecc885ac7b450bf5a5bb86eR89

**Comment by peterzhuamazon** [comment]
> Thank you @minalsha and @peterzhuamazon ! Would it be possible to create another snapshot distribution with the change included. We pull the snapshot distribution from here: https://github.com/opensearch-project/security/pull/2161/files#diff-3e971aab38c741b1cb89584068ce23192213a18b1ecc885ac7b450bf5a5bb86eR89

Hi @cwperks Im working on that right now might take some time.
Thanks.

**Comment by peterzhuamazon** [comment]
Ignore my last comment it is quicker than I think:
https://build.ci.opensearch.org/job/distribution-build-opensearch/6322/console

**Comment by cwperks** [comment]
The most recent windows plugin-install new CI step has completed successfully with the new snapshot build! https://github.com/opensearch-project/security/actions/runs/3340448709/jobs/5530552763

**Comment by cwperks** [comment]
Closing this ticket since the Batch script is merged. I will file a new issue with the `plugin-install.yml` github action to run the opensearch node as a user other than administrator.
