### ISSUE TITLE
[BUG] hasValidDNs is not handling the rdn order change of subject and issuerDN.

### ISSUE THREAD

**Issue by shubhmkr-amazon** [opensearch-project/security#2159]
**What is the bug?**
After changing the order of subjectDN field of the new certificate giving a cert validation error response(500).  As it is comparing the whole DN field as a whole String.
Current cert Subject: C=DE, L=Test, O=Test, OU=SSL, CN=node-1.example.com
New cert  Subject: CN=node-1.example.com, OU=SSL, C=DE, L=Test, O=Test

**How can one reproduce the bug?**
Steps to reproduce the behaviour:
1. Run unit testcase 'testSSLReloadCerts_Pass_NonSSLOnly' with attached certificates.
2. Check the result it is giving error response(500) instead of 200.

**What is the expected behaviour?**
From my point of view new certificate should be successfully validated. (Response code 200).

According to rfc document:-  https://www.rfc-editor.org/rfc/rfc5280#section-7.1

```
Two relative distinguished names RDN1 and RDN2 match if
they have the same number of naming attributes
and for each naming attribute in RDN1 there is a matching naming
attribute in RDN2. Two distinguished names DN1 and DN2 match if they
have the same number of RDNs, for each RDN in DN1 there is a matching
RDN in DN2, and the matching RDNs appear in the same order in both DNs.

```
This section of text from rfc document is confusing and asked on multiple platform.  From going through them I found two interpretation:-

1. Order of RDN in the DN matters As the RDNSequence(DN)  is sequence of RDN and I think sequence itself mean ordered and for RDN its mentioned as set which means order does not matter.  ([rfc section:- 4.1.2.4](https://www.rfc-editor.org/rfc/rfc5280#section-4.1.2.4)).

2. Two DNs have to be considered equal even if they differ in the order of naming attributes in some matching relative distinguished name.

Some of the discussion related to this topic:-
https://stackoverflow.com/questions/33080136/ordering-of-rdn-attributes-in-a-cas-certification-sign-process
https://security.stackexchange.com/questions/93985/openssl-x509-is-there-an-order-in-subjectname-fields
https://web.archive.org/web/20180328032619/http://openssl.6102.n7.nabble.com/Is-ordering-of-distinguished-names-for-subject-and-issuer-in-OpenSSl-0-9-8-certificates-important-td43602.html
https://frasertweedale.github.io/blog-redhat/posts/2019-05-28-a-dn-is-not-a-string.html

Let me explain my understanding with example
Example 1.
subject:- C=DE, L=Test, O=Test, OU=SSL,OU=COM, CN=node-1.example.com
subject:- C=DE, L=Test, O=Test, OU=COM, OU=SSL,CN=node-1.example.com
These are matching as per 1st interpretation as well as 2nd.

Example 2.
subject:- C=DE, L=Test, O=Test, OU=SSL,OU=COM, CN=node-1.example.com
subject:-  CN=node-1.example.com,C=DE, L=Test, O=Test, OU=SSL,OU=COM
These are not matching as per 1st interpretation but matching with 2nd. (As per current logic they are not equal).

**My point is if we consider 1st as correct then we have to modify for MVA, as current logic is not working on it. **

*I am attaching certificate for testing*
[Archive.zip](https://github.com/opensearch-project/security/files/9767603/Archive.zip)

Local testing
[test-report.txt](https://github.com/opensearch-project/security/files/9797129/test-report.txt)

**Comment by scrawfor99** [comment]
[TRIAGE] @cwperks can you review the associated pull request? Thank you.

**Comment by peternied** [comment]
It looks like this is related to https://github.com/opensearch-project/security/issues/2054 @shubhmkr-amazon Can you confirm if you are addressing the behavior of this other issue as well?

**Comment by cwperks** [comment]
@shubhmkr-amazon Some of the RDN attributes like DC (or Domain component) are not reversible. 

i.e. `CN=cwperx,DC=example,DC=org` is not the same as `CN=cwperx,DC=org,DC=example`.

For elements of an RDN with the same attribute name, order needs to be preserved if the line is re-arranged.

See my comment here (https://github.com/opensearch-project/security/issues/1640#issuecomment-1217028594) on a similar github issue.

**Comment by shubhmkr-amazon** [comment]
@cwperks Thank you for looking into this issue. In some part of rfc document its mentioned that order did not matter in [practical.]  (https://www.rfc-editor.org/rfc/rfc6125#section-2.3.1). Let me look some more into it closing for now.
