### ISSUE TITLE
[Failing CI] Main branch build is failing

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#2165]
# Description

`main` CI started failing due to an effort to migrate http client/core to 5.x via https://github.com/opensearch-project/OpenSearch/pull/4459

Since we transitively pull these dependencies which were removed, the CI failed.
```
  api "org.apache.httpcomponents:httpclient:${versions.httpclient}"
  api "org.apache.httpcomponents:httpcore:${versions.httpcore}"
  api "org.apache.httpcomponents:httpasyncclient:${versions.httpasyncclient}"
  api "org.apache.httpcomponents:httpcore-nio:${versions.httpcore}"
```

There is an ongoing effort to fix this.

# Expectations
CI should be green

**Comment by reta** [comment]
https://github.com/opensearch-project/security/issues/2171

**Comment by DarshitChanpura** [comment]
Closing this as it was solve via: https://github.com/opensearch-project/security/issues/2171
