### ISSUE TITLE
[SecurityAdmin] Failure when "OpenSearch Security not initialized" 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2173]
Hello All,
I have tried to explain my scenario in points. 

1. Installed opensearch and opensearch dashboards - version 2.2.1 using yum
2. Was able to start both opensearch and opensearch dashboards without any issues
3. Accessed OS dashboards using Chrome and even data ingestion from metric beat was successful
4. As it was single node cluster, tried building a cluster formation with one cluster-master node and two data nodes.
5. After making required changes as listed in the [documentation](https://opensearch.org/docs/latest/opensearch/cluster/), I was able to start the cluster-master.
6. But while doing a CURL command to the cluster, was getting "OpenSearch Security not initialized"
7. So as per my research following the link to sort out the [security admin](https://opensearch.org/docs/latest/security-plugin/configuration/security-admin/) issue

Request the group's help to see if this a known issue and confirm any workaround in place?

**Execution of security admin is leading up to the following errors:**
`./securityadmin.sh -cd /etc/opensearch/opensearch-security -rev -icl -nhnv    -cacert ../../../config/root-ca.pem    -cert ../../../config/kirk.pem    -key ../../../config/kirk-key.pem -h <private-IP> -p 9200 --accept-red-cluster`

**Logs from security admin execution:**

```
Security Admin v7
Will connect to 10.1.4.117:9200 ... done
Connected as "CN=kirk,OU=client,O=client,L=test,C=de"
OpenSearch Version: 2.2.1
Contacting opensearch cluster 'opensearch' ...
Clustername: opensearch-cluster
Clusterstate: RED
Number of nodes: 1
Number of data nodes: 0
.opendistro_security index already exists, so we do not need to create one.
ERR: .opendistro_security index state is RED.
Legacy index '.opendistro_security' (ES 6) detected (or forced). You should migrate the configuration!
Populate config from /etc/opensearch/opensearch-security/
Will update '/config' with /etc/opensearch/opensearch-security/config.yml (legacy mode)
   FAIL: Configuration for 'config' failed because of java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-6 [ACTIVE]
Will update '/roles' with /etc/opensearch/opensearch-security/roles.yml (legacy mode)
   FAIL: Configuration for 'roles' failed because of java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-7 [ACTIVE]
Will update '/rolesmapping' with /etc/opensearch/opensearch-security/roles_mapping.yml (legacy mode)
   FAIL: Configuration for 'rolesmapping' failed because of java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-8 [ACTIVE]
Will update '/internalusers' with /etc/opensearch/opensearch-security/internal_users.yml (legacy mode)
   FAIL: Configuration for 'internalusers' failed because of java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-9 [ACTIVE]
Will update '/actiongroups' with /etc/opensearch/opensearch-security/action_groups.yml (legacy mode)
   FAIL: Configuration for 'actiongroups' failed because of java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-10 [ACTIVE]
Will update '/nodesdn' with /etc/opensearch/opensearch-security/nodes_dn.yml (legacy mode)
   FAIL: Configuration for 'nodesdn' failed because of java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-11 [ACTIVE]
Will update '/whitelist' with /etc/opensearch/opensearch-security/whitelist.yml (legacy mode)
   FAIL: Configuration for 'whitelist' failed because of java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-12 [ACTIVE]
Will update '/audit' with /etc/opensearch/opensearch-security/audit.yml (legacy mode)
   FAIL: Configuration for 'audit' failed because of java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-13 [ACTIVE]
ERR: cannot upload configuration, see errors above
```

_-- Filed on the behalf of @kcharikrish_

**Comment by peternied** [comment]
> "OpenSearch Security not initialized"

This is likely what is causing all the trouble, when the cluster is coming online the security plugin replicates all of its settings to each node via a special index called `.opendistro_security`.  This index has to be present on each node, you would need to troubleshoot if that error was resolved because the index was initialized and synced between nodes.  If you can run `GET /_cat/shards?v` and you see it replicated on all nodes then the next step would be to diagnose cluster health.

Until the cluster is healthy and all nodes are in communication you'll have trouble engaging with the security tooling.  Do you have more logs you can share from the cluster that would help clarify the source of the issue?

**Comment by peternied** [comment]
Note, unless we hear back in 2 weeks, Nov 1st, we will automatically close out this issue assuming it was workaround-able

**Comment by scrawfor99** [comment]
[TRIAGE] Hi @kcharikrish, just following up to make sure you saw this issue was created. Please take a moment to update the issue how you best see fit and respond with any information about the logs that you can share from the cluster. Thank you.

**Comment by peternied** [comment]
[Triage] Its past Nov 1st so we are closing out this issue.

**Comment by pcdot14** [comment]
Do we have any solution for this?
