### ISSUE TITLE
[BUG] - Documentation guide not building the project

### ISSUE THREAD

**Issue by nishp77** [opensearch-project/security#2174]
**What is the bug?**
During ./gradlew clean assemble when setting up the project throws error of detecting some dependencies tried both JAVA 11 and 17 results the same issue

**How can one reproduce the bug?**
1. Go to https://github.com/opensearch-project/security/blob/main/DEVELOPER_GUIDE.md#prerequisites
2. Follow all the setups till the 'building' 
3. run the command ./gradlew clean assemble

**What is the expected behavior?**
Should build the project

**What is your host/environment?**
 - OS: Linux (Fedora)
 - Version [e.g. 36]
 - Security

**Do you have any screenshots?**
![image](https://user-images.githubusercontent.com/35785259/196355151-dfbd9db9-abe5-4faa-b4aa-0b2a8c09ee62.png)

**Do you have any additional context?**
Add any other context about the problem.

**Comment by peternied** [comment]
We had build breaks in main that were recently resolved, can you post your commit SHA, failures are expected if you are not built off of [41d68cc](https://github.com/opensearch-project/security/commit/41d68ccb30b52f285ea350038437871d72d59c83).

I can't tell the source of the error as it looks like its off the screen, if you are running the latest commit and are still seeing the error, could you copy the whole console output and paste into a GIST [1] that you link here?  


[1] https://gist.github.com/

**Comment by nishp77** [comment]
Yes its the same SHA --> 41d68ccb30b52f285ea350038437871d72d59c83

**Comment by nishp77** [comment]
Just pulled the latest commit, it's working now thanks however do you know the reason why it was breaking at compile time?

**Comment by peternied** [comment]
@nishp77 Our main branch is associated with OpenSearch's main branch, which occasionally gets breaking changes that are targeting the 3.0.0 release.  This synchronization can lead to breaks like this one, most of the types we fix them quickly, but in this case, it was a hard issue to resolve checkout the pull request if you are curious about the details [1].  We created an issue in OpenSearch-build [2] to see if we can better detect/mitigate issues like this in the future.

[1] https://github.com/opensearch-project/security/pull/2166
[2] https://github.com/opensearch-project/opensearch-build/issues/2749
