### ISSUE TITLE
[BUG] No cluster-level perm match for User

### ISSUE THREAD

**Issue by vinylen** [opensearch-project/security#2182]
**What is the bug?**
After upgrading to OpenSearch 2.3.0, we are experiencing issues with sending alerts to Slack channels. If we take a look in the notifications tab for the alert itself, we can see the following error message:

`Error:  Failed running action: org.opensearch.OpenSearchSecurityException: no permissions for  [cluster:admin/opensearch/notifications/configs/get] and associated  roles [reports_full_access, own_index, itdev, alerting_full_access,  anomaly_full_access]`

If i go into the logs of one of the OpenSearch data nodes i can see this log appears multiple times:
`
[2022-10-18T15:02:03,042][INFO ][o.o.s.p.PrivilegesEvaluator] [opensearch-node01] No cluster-level perm match for User [name=plugin, backend_roles=[], requestedTenant=null] Resolved [aliases=[*], allIndices=[*], types=[*], originalRequested=[*], remoteIndices=[]] [Action [cluster:admin/opensearch/notifications/configs/get]] [RolesChecked [reports_full_access, own_index, itdev, alerting_full_access, anomaly_full_access]]. No permissions for [cluster:admin/opensearch/notifications/configs/get]`

This has started to appear after the changes to notifications happened. Which user is missing the permissions? It only says name=plugin.

**How can one reproduce the bug?**
1. Create an alert to send to a slack channel with a version before notifications was implemented
2. Upgrade to latest OpenSearch
3. Have the alert trigger, which should produce the error message above about missing permissions for user=plugin

**What is the expected behavior?**
Report which user is missing the required permissions.

**What is your host/environment?**
 - OS: Ubuntu 22.04 with OpenSearch running in docker
 - Version 22.04
 - Plugins S3-repository/prometheus-exporter

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by scrawfor99** [comment]
[TRIAGE] Hi @vinylen, thank you for filing this issue. Would you be able to provide information on which version you were migrating from as well as any snippets of your config files you are willing to share? @cliu123 can you follow up on this.

**Comment by cliu123** [comment]
@vinylen I have a couple of quick things. Would you please confirm?

- Which version is this upgrade from?

- Does this issue happen during rolling upgrade? If yes, there's already been [another issue](https://github.com/opensearch-project/security/issues/2168) for this. If it's possible, please try full upgrade(bring down all nodes, upgrade all nodes and then start all nodes.)

**Comment by vinylen** [comment]
@cliu123 

This is an upgrade from OpenSearch 1.2.4 and OpenSearch-Dashboard 1.2.0.

Yes this was a rolling upgrade. So the nodes have already been upgraded to 2.3.0. Would rebooting each node have a similar effect? We would rather not bring the whole cluster down if it can be avoidable.

**Comment by scrawfor99** [comment]
Hi @vinylen, thank you for following up. I believe that rebooting each node will only work as a rolling upgrade/restart. So will likely have the same behavior as your have been experiencing. I am going to tag @cwperks to see if he can confirm this as he is someone who knows a lot about these types of intricacies.

Because your issue has not been fully addressed, I am also going to mark it as untriaged to make sure that it is revisited in our next meeting for further discussion. If you have interest in attending the next meeting to discuss this issue please join via the information at https://opensearch.org/events/2022-1128-dev-triage-security/.

**Comment by cwperks** [comment]
@vinylen The notifications plug-in was added in 2.0 - https://opensearch.org/docs/2.0/breaking-changes. With the addition of the plug-in there are 2 roles associated with the plugin `notifications_full_access` and `notifications_read_access` that can be used to grant privileges.

Are you using `internal_auth` as one of the authentication backends in the `authc` section of `config/opensearch-security/config.yml`? If `plugin` is an internal user you can modify the role assigned to this user using OSD -> Main Menu -> Security -> Roles and modify the role that user `plugin` is assigned to.

**Comment by vinylen** [comment]
Thank you @cwperks & @scrawfor99.

> With the addition of the plug-in there are 2 roles associated with the plugin notifications_full_access and notifications_read_access that can be used to grant privileges.

We seem to be missing these roles:

```
GET _plugins/_security/api/roles/notifications_full_access

{
  "status" : "NOT_FOUND",
  "message" : "Resource 'notifications_full_access' not found."
}
```
```
GET _plugins/_security/api/roles/notifications_read_access

{
  "status" : "NOT_FOUND",
  "message" : "Resource 'notifications_read_access' not found."
}
```

We are using `basic_internal_auth_domain` as referenced by the security tab in opensearch-dashboards. The thing is that we don't have a user called `plugin` either:

```
GET _plugins/_security/api/internalusers/plugin

{
  "status" : "NOT_FOUND",
  "message" : "Resource 'plugin' not found."
}
```

I wonder if we are missing more security roles then. What would be the recommended way to import the latest security roles and keep the existing ones that we have custom-made?

Thanks

**Comment by cwperks** [comment]
Hey @vinylen , one option is to use security admin (https://opensearch.org/docs/latest/security-plugin/configuration/security-admin/), but make sure to read the section titled `A word of caution` where it instructs you on how to take a backup of the security index. 

I would recommend taking a snapshot of your data as well. Please kind in mind, that if you take a snapshot of all indices (include the system index for security) you will need to connect with the admin certificate to restore.

I am not sure where the username `plugin` is coming from, but I see it in a few posts on the forum including yours. Thank you for posting the question on the forum first.
