### ISSUE TITLE
[FEATURE] AuditMessage validation in tests should be more useful / removed

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2188]
**Is your feature request related to a problem?**
Test code was written to verify the format of audit log messages.  This code is clunky as in tests it's written as `Assert.assertTrue(validateMsgs(messages));`.  It would be far more useful if it emitted errors about why the message(s) are invalid rather than asserting false.

Furthermore; It is not clear that the message format level validation in the integration tests is useful, so we should investigate under what conditions we are testing for/against.

Code in question
https://github.com/opensearch-project/security/blob/b836040c577894a08db9377d46a3d4eaca426fb8/src/test/java/org/opensearch/security/auditlog/AbstractAuditlogiUnitTest.java#L88

**What solution would you like?**
We should have assertions that clearly indicate what is wrong so the failure message can be instructive to developers diagnosing the tests, or we should remove this functionality if it isn't providing valid to our test cases.

**Comment by scrawfor99** [comment]
[TRIAGE] Moved to backlog and good first issue applied.
