### ISSUE TITLE
RCA: Varied CI Build performance for MacOS, Windows and Ubuntu

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#2209]
Build times:

Ubuntu (Fastest)             |  Windows              |  MacOS (slowest)
:-------------------------:|:-------------------------:|:-------------------------:
<img width="1116" alt="Screen Shot 2022-10-31 at 1 42 26 PM" src="https://user-images.githubusercontent.com/35282393/199073943-70ce28ee-a0c3-4340-9062-01ca0a3082e8.png"> | <img width="1116" alt="Screen Shot 2022-10-31 at 1 42 31 PM" src="https://user-images.githubusercontent.com/35282393/199073946-f22d4e63-a7aa-48a4-8e1d-1239627f99fb.png"> | <img width="1116" alt="Screen Shot 2022-10-31 at 1 42 36 PM" src="https://user-images.githubusercontent.com/35282393/199073948-ec9369a9-a46e-4bac-936d-e98a78fcdc78.png">

Total CI run time is 5 hrs 47 mins which is unfeasible:
<img width="731" alt="Screen Shot 2022-10-31 at 1 36 28 PM" src="https://user-images.githubusercontent.com/35282393/199073330-2deec428-9381-4630-a21d-1430f11a0e1c.png">

Looking at the images above, `Build and Test` step takes the most time. (MacOS takes almost 2.5x the time than Ubuntu, and Windows takes ~ 2x the time than Ubuntu)

Going one step further and looking at the logs for each OS build for `Build and Test`:
1. MacOS: logs show a slurry of `Connection refused` and `Node closed while execution action` leading to multiple retries causing the build time to go up. At some point we also see `Failed to start the node` and `Address already in use` messages too.
2. Windows: Sees similar log messages above but relatively less frequent.

**Comment by peternied** [comment]
Maybe we could try using larger runners for the windows instance, `windows-latest-8-cores`? [1]


[1] https://github.blog/changelog/2022-10-20-github-actions-larger-hosted-runners-are-now-automatically-created-for-customers/

**Comment by DarshitChanpura** [comment]
Closing this as CI seems to be stable, macos runners have been disabled and the build times between ubuntu and windows are within 2 mins of each other.
