### ISSUE TITLE
Enable opensearch auth type proxy on aws opensearch 

### ISSUE THREAD

**Issue by amitgilad3** [opensearch-project/security#2214]
HI, i was wondering if its possible to enable proxy based auth on aws opensearch and if so can somebody point me in the right direction.

Thanks

**Comment by peternied** [comment]
Thanks for reaching out, try looking on https://opensearch.org/docs/latest/security-plugin/configuration/proxy/, if that does not work please use https://forum.opensearch.org/c/security/3 for support.
