### ISSUE TITLE
Opensearch node runs as Administrator for window-install in plugin install Github Action

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#2215]
**What is the bug?**

Commands inside a windows runner for a Github Action run as Administrator. The new `windows-install` job  in `plugin_install.yml` (https://github.com/opensearch-project/security/blob/main/.github/workflows/plugin_install.yml) needs to be able to start a node as a user without elevated permissions since Opensearch has restrictions on being able to startup a node as the root account. 

Specifically, this step of the action needs to run as non-admin.

```
- name: Run OpenSearch with plugin
      run: |
        cd ..
        start .\Opensearch\bin\opensearch.bat
```

Discussion on this PR: https://github.com/opensearch-project/security/pull/2161

**How can one reproduce the bug?**

Change the SNAPSHOT build in `plugin-install` to a version of the SNAPSHOT with the change forbidding a windows account with elevated privileges to run the node. I believe https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/6322/windows/x64/zip/dist/opensearch/opensearch-3.0.0-windows-x64.zip will work, but need to verify this. The number after 3.0.0 in the URL is the distribution build number

**What is the expected behavior?**

An opensearch node is successfully brought up on the github windows runner using a non-admin account

**What is your host/environment?**
 - Github `windows-latest` runner

**Do you have any screenshots?**

**Do you have any additional context?**

- Lots of discussion here: https://github.com/opensearch-project/security/pull/2161
- and here: https://github.com/opensearch-project/OpenSearch/issues/4942#issuecomment-1298022105

**Comment by dbwiddis** [comment]
Solution: https://github.com/opensearch-project/OpenSearch/issues/4942#issuecomment-1301733503

**Comment by cwperks** [comment]
[Triage] @scrawfor99 Can you please provide an update?

**Comment by davidlago** [comment]
@scrawfor99 any updates on this one?
