### ISSUE TITLE
[BUG] Intermittent test failure `RestApiComplianceAuditlogTest.testAutoInit`

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2229]
**What is the bug?**
Seeing intermittent test failures from `org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testAutoInit` [1]  The test passed on 5 of 6 platform/jdk combinations.

**How can one reproduce the bug?**
Unclear how to reproduce the bug, consult https://github.com/opensearch-project/security/actions/runs/3381396002/jobs/5615256769 for detailed failure information.

**What is the expected behavior?**
Tests should only fail when an error was introduced in the codebase, or network infrastructure was unavailable.

**Do you have any additional context?**
Impacted https://github.com/opensearch-project/security/pull/2224

**Comment by cwperks** [comment]
This test was stabilized in https://github.com/opensearch-project/security/pull/3733
