### ISSUE TITLE
[BUG] Intermittent test failure `SlowIntegrationTests.testDelayInSecurityIndexInitialization`

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2230]
**What is the bug?**
Seeing intermittent test failures from `org.opensearch.security.SlowIntegrationTests.testDelayInSecurityIndexInitialization` [1]  The test passed on 5 of 6 platform/jdk combinations.

**How can one reproduce the bug?**
Unclear how to reproduce the bug, consult the build output for detailed failure information.

**What is the expected behavior?**
Tests should only fail when an error was introduced in the codebase, or network infrastructure was unavailable.

**Do you have any additional context?**
Impacted https://github.com/opensearch-project/security/pull/2225

[1] https://github.com/opensearch-project/security/actions/runs/3381396002/jobs/5615256769

**Comment by DarshitChanpura** [comment]
This issue still persists. Here is latest CI on main, at the time of writing this, https://github.com/opensearch-project/security/actions/runs/3526748585/jobs/5915032714

**Comment by peternied** [comment]
Impacted test run https://github.com/opensearch-project/security/actions/runs/6898810477/attempts/2?pr=3719

**Comment by peternied** [comment]
- Impacted test run https://github.com/opensearch-project/security/actions/runs/6919927176/job/18823842619?pr=3741, impacted PR https://github.com/opensearch-project/security/pull/3741

**Comment by peternied** [comment]
- Impacted test run https://github.com/opensearch-project/security/actions/runs/6949168658/job/18910461790?pr=3759, impacted PR #3759

**Comment by peternied** [comment]
- Impacted test run https://github.com/opensearch-project/security/actions/runs/6947393851/job/18901098103?pr=3758, impacted PR #3758
