### ISSUE TITLE
[Branch Protection] Re-enable Require 'backward-compatibility`

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2235]
For the `main` branch backward compatibility tests have been disabled while the following issues are unresolved

- https://github.com/opensearch-project/security/issues/2221

Once this issues have been resolved the branch protection requirements should be restored to normal

**Comment by cwperks** [comment]
[Triage] @peternied Please close this issue once BWC Test failure has been resolved and branch protection re-applied.

Can we also remove the second item on the list as it is unrelated?

**Comment by DarshitChanpura** [comment]
@peternied @cwperks I've added these 4 branch protection rules to main

backward-compatibility (11, ubuntu-latest)
backward-compatibility (11, windows-latest)
backward-compatibility (17, ubuntu-latest)
backward-compatibility (17, windows-latest)

Feel free to re-open this issue if there is anything else that needs to be changed
