### ISSUE TITLE
[FEATURE] During OpenSearch service starting for GHA workflow be able to supply script/config modification 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#2252]
**Is your feature request related to a problem?**
It was brought to my attention by @cwperks that it would be nice if the settings contained in our startup scripts i.e. `install_demo_configuration`  could be added directly to the `opensearch.yml`  file. This would then allow for the various workflows and GitHub Actions to not require that users specify a path to the demo configurations for their plugins (https://github.com/opensearch-project/security/pull/2239). 

**What solution would you like?**
Be able to specify in some way the configurations needed for a plugin or a redirect to a file containing these configurations within the opensearch.yml file. 

**What alternatives have you considered?**
Currently the same functionality is implemented by passing a path to a script containing all the configuration steps.

**Comment by peternied** [comment]
[Triage] Thanks for writing up this issue, re-wrote the title to more clearly match the use case.

**Comment by scrawfor99** [comment]
This issue is resolved with PR #2271
