### ISSUE TITLE
[Backport Request] Backport Auditlog Do/Wait Logic to 1.3 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#2278]
In PR #1758, logic was added for a do/wait model of the auditlog tests. This change improved test success rates by enforcing an order of operations for the various tests. This change would be particularly useful for the flaky 1.3 branch. 

Unfortunately, the backport is not straightforward and requires changes to security beyond basic merge conflicts. 

**What solution would you like?**
A backport of the linked PR into 1.3 with the hope of improving reliability. 

**What alternatives have you considered?**
In the past, the backport has been abandoned because of its complexity. This is probably fine as I do not think this backport will fix the main failures in 1.3 testing--the improper closure of sockets--but it would be nice to backport these changes to increase reliability as much as possible. 

**Do you have any additional context?**
After backporting the changes and addressing and further conflicts, you will run into an issue where the tests attempt to access the `auditlog` subdirectory. I think this is a directory in OpenSearch core and not the security plugin so it will require backporting the changes in core that introduced that directory before these changes to allow for the tests to work.

**Comment by RyanL1997** [comment]
[Triaged] @scrawfor99 thanks for filing this and I will help to take a look into this one as well.

**Comment by RyanL1997** [comment]
Closing this one and link this one to (#2023 )
