### ISSUE TITLE
[Retrospective] Release 2.4.0 Retrospective 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#2280]
We just released OpenSearch 2.4.0. To make sure that we do not lose issues that arose during the process please add them here. 

Please add comments to this issue, they can be small or large in scope. Honest feedback is important to improve our processes, suggestions are also welcomed but not required. What went great? What could be improved?  

What will happen to this issue post release?

There will be a discussion(s) about how the release went and how the next release can be improved. Then this ticket will be updated with the notes of that discussion along side action items. This information will then be shared with the Build repository for them to take action on anything beyond the scope of the security repository.

**Comment by peternied** [comment]
Quickly capturing a couple of things broken down for us:
- BWC tests broken in main causing delays in 2.4.0
- Windows platform onboarding was rocky - didn't have standard ways to get build artifacts, we missed adding BWC tests and for Dashboards we integration tests flavors were not tested on windows before release.
- Stale main builds and distribution build breaks.
- LARGE backlog of pull requests, lots of rebasing an general pain getting changes in 

Good stuff!
- Lots of great issues created to improve the codebase
- Collaboration across teams and repos was really high
- Triage meeting promoted into the publicly accessible forum
