### ISSUE TITLE
Backport Windows support to 1.x branch

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/security#2281]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/181, backport Windows support to 1.x branch.

### Critical Path
- [x] Increment to 1.3.7
- [x] Windows demo script.bat
- [x] Build on windows machine
- [x] Run CI on Windows
  - [x] JDK 11
  - [x] JDK 14
  - [x] JDK 8
- [x] JDK8 compatibility for Utf-8
- [x] Plugin install for Windows

### Non Blockers
- [x] Test reliability
- [x] Github workflow updates
- [x] Branch protection rules
- [x] Spotbugs

### Not in scope
- Backwards compatibility testing

If you are already have an issue tracking backport Windows CI to 1.x branch, please link here.

**Comment by cwperks** [comment]
While trying to backport these 2 PRs I encountered some issues around Java 8:

- https://github.com/opensearch-project/security/pull/2206 - Fix windows encoding issues
- https://github.com/opensearch-project/security/pull/2190 - Add CI for Windows and MacOS platforms

1. `SecurityUtilsTest` - `Pattern.onMatchPredicate` is not available, `List.of` is not available
2. FIleWriter and FileReader both do not have constructors that take Charset. 

The work I have done so far can be found on this branch: https://github.com/opensearch-project/security/pull/2206 - Fix windows encoding issues
https://github.com/opensearch-project/security/pull/2190 - Add CI for Windows and MacOS platformshttps://github.com/cwperks/security/tree/backport/backport-2206-to-1.3

**Comment by peternied** [comment]
The PR #2291 in draft handles all of the outstanding critical path except for JDK14.  I'll hunt that down tomorrow while getting the remaining changes reviewed.

@davidlago @CEHENKLE @rishabh6788 Security is building in 1.3.7 and is part of the distribution.  Downstream teams should not be blocked for any build/testing.  Based of the current speed of development Security will have delivered all critical path issues by EOD Monday Dec 5 for the security plugin.
