### ISSUE TITLE
Unable to create different dashboards (for specific tenant) | unable to filter logs by index (for specific tenant)   [BUG]

### ISSUE THREAD

**Issue by rashed-k** [opensearch-project/security#2282]
**What is the bug?**
User permission not being applied in specific tenant. 

**How can one reproduce the bug?**
- I logged in with admin into opensearch dashboard and switched to custom tenant called "rmk" and created simple dashboard using gauge count which has container* index pattern  (index pattern "container*" was created first).
- I then created a user to map it to the role I had created for rmk tenant. 

![Screen Shot 2022-11-29 at 2 19 56 pm](https://user-images.githubusercontent.com/74450886/204430979-d1f751c3-be75-4dc7-9954-e00c57831409.png)

![Screen Shot 2022-11-29 at 2 22 19 pm](https://user-images.githubusercontent.com/74450886/204430995-5715d1af-c071-4730-bf04-2f04d09498f8.png)

**What is the expected behavior?**
My expectation is that the user can only view logs and dashboard related to container* but after the security permissions applied the user is unable to view any dashboard or logs in discovery in "rmk" tenant. However, when I logged in with admin back again, I noticed that the dashboard and saved objects were visible in global and rmk tenant. 

**What is your host/environment?**
 - OS: [e.g. iOS] -- Linux/UNIX ( AWS - EKS) 
 - opensearch - dashboard (helm chart- 1.2.0 / app version - 1.2.0 )
 - opensearch - (helm chart 1.7.4 / app version 1.2.4 ) 
 - Plugins -- ( Did not add additionally, default from helm chart app version 1.2.0)

**Do you have any screenshots?**
When the user logs in (tenant "rmk") the permission applied by the admin does not apply. The page seems blank when discover, dashboard or visualise is clicked at left bar.

![Screen Shot 2022-11-29 at 4 19 41 pm](https://user-images.githubusercontent.com/74450886/204445367-b9d91808-01c3-4b01-9632-d381b1039bbc.png)

Could someone help me understand the steps required to give only permissions related to read and search container* pattern for specific tenant?

**Comment by rashed-k** [comment]
.kibana* needs to be added in index.

**Comment by peternied** [comment]
@rashed-k This sounds like a support issue, we have many questions and answers on the OpenSearch forums - check it them out here https://forum.opensearch.org/c/security/3
