### ISSUE TITLE
Internal authentication DB username spec inconsistency

### ISSUE THREAD

**Issue by DJSundog** [opensearch-project/security#229]
While developing a custom kibana plugin for a client looking to deploy an ODfE cluster, my team has been asked to configure user access using the internal authentication database. 

We've developed functionality to add users to the internal auth db via the REST API without an issue, initially.

While updating some of our test users via the Kibana security plugin rather than the REST API, we've been presented with the following error trying to save the modified user:

`Username must not contain '*', '.' or curly brackets`

However, the REST API enforces no such requirements on usernames for newly created or modified users. Users created via the REST API using an email address as a username are able to log in as we had expected without issue.

Could someone address this inconsistency and (preferably) remove the restriction on `.` characters in usernames via the kibana security plugin, or alternatively (and definitely not preferred) add the restriction to the REST API for consistency?

**Comment by DJSundog** [comment]
Can we get some feedback on this so we know whether or not we need to switch to a different solution?

**Comment by DJSundog** [comment]
Still nothing?

**Comment by hardik-k-shah** [comment]
Thanks for raising this. We will look into this.

**Comment by WennySoft** [comment]
I currently hit this issue also. We have several FQDN of servers used as username which worked very well (I am not sure if this restiricton was already in ODFE 1.3.0 and we just did not reognize it) but now with ODFE 1.9.0 I get this error.

Please remove the dots-restriction as it would be difficult to get non-conflicting usernames otherwise

**Comment by Anthony7774** [comment]
@DJSundog @WennySoft This appears to be fixed in latest Opensearch version 1.2.0, perhaps you might want to think about upgrading if you are still using old odfe versions.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
