### ISSUE TITLE
[BUG] [CI Failure] CI job `build-artifact-names` fails

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#2314]
CI check fails due to failure during `build-artifact-names`.

See: https://github.com/opensearch-project/security/actions/runs/3651213248/jobs/6168160238 for details

**Comment by reta** [comment]
To give a background on this: there were API changes on Gradle 7.6 related to JVM metadata. The OpenSearch core 3.0.0 has been updated in such a way that those API changes (which leak through Gradle plugins) are non breaking. Sadly, the it seems like OpenSearch 3.0.0 snapshots have not been published for a looong time, the older plugins are being getting picked.

**Comment by peternied** [comment]
We've already had a couple of updates to this test code when the 'version' increment code is hardly touch.  This is a low value test that is requiring a lot of upkeep, I'm going to remove it.

- #2323
