### ISSUE TITLE
[BUG] Basic auth with no creds does not give a warning.

### ISSUE THREAD

**Issue by abhivka7** [opensearch-project/security#2346]
**What is the bug?**
Using basic auth with no creds should give a warning in logs. But right now the logging level is trace and not warn.

**How can one reproduce the bug?**
1. Create an opensearch domain with basic auth, and try to do a get request on it without passing credentials. It will just send the message: "Unauthorized" and only log if trace logging is enabled.

**What is the expected behavior?**
As an admin, I don't have any visibility into why my users are not able to login without enabling [trace logs](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/auth/BackendRegistry.java#L270) 

**What is your host/environment?**
 - Security plugin enabled with OpenSearch 1.3 domain

**Comment by DarshitChanpura** [comment]
[Triage] @abhivka7 Thank you for filing this bug. Could you please elaborate more on the use case that you have in mind for this scenario?

**Comment by cwperks** [comment]
Closing this issue.

This has been merged into main and 2.x:

- https://github.com/opensearch-project/security/pull/2347
- https://github.com/opensearch-project/security/pull/2364
