### ISSUE TITLE
[BUG] securityadmin and hash scripts do not work in Windows

### ISSUE THREAD

**Issue by Docubytes** [opensearch-project/security#2368]
I am trying to reset password using hash.bat file on windows system but it is not working i am getting the following error, could you please help me? or suggest me how to reset admin password

![image](https://user-images.githubusercontent.com/91736985/209361222-80b7b2eb-25bb-4849-b9f0-5e490dd73a85.png)

i think it looking for Open Distro folder which i can't see on openserach folder

**Comment by peternied** [comment]
@Docubytes Thanks for filing, these scripts were missed when we added support for windows - thanks for catching this.

**Comment by Docubytes** [comment]
Could you please provide me scripts through some url or share folder so I can add it to my application?

**Comment by peternied** [comment]
@Docubytes Checkout the pull request I just created, it has the modifications you can apply on top of the batch file(s) locally to get unblocked.

I suspect that you might need to set JAVA home based on the error message
