### ISSUE TITLE
[FEATURE] pom.xml missing

### ISSUE THREAD

**Issue by satyamsah** [opensearch-project/security#2380]
can we have a default pom.xml generated in the project.

**Comment by peternied** [comment]
In our public maven [1] and snapshot repositories [2] I see pom.xml files for version 2.4.1.0  If this doesn't work for you, please provide more details and we will reopen, thanks!

- [1] https://mvnrepository.com/artifact/org.opensearch.plugin/opensearch-security/2.4.1.0
- [2] https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/opensearch-security/2.4.0.0-SNAPSHOT/
