### ISSUE TITLE
Allow environment variables in yml files

### ISSUE THREAD

**Issue by untoldone** [opensearch-project/security#24]
My expectation would be opendistro yml files would be treated the same as elasticsearch yml files.

Currently you cannot include an environment variable in `opendistro_security/securityconfig/internal_users.yml`. Other ES config files allow this https://www.elastic.co/guide/en/logstash/current/environment-variables.html

The benefit of doing this is that Docker based opendistro deployments could be secured on launch via using env variables injected from a secrets store. The alternative to this is that I've written a descendant docker image that also includes a template generator to dynamically render the internal_users.yml file based on the contents of the secrets store.

**Comment by desaintmartin** [comment]
Could you share such an image (or Dockerfile)? this is not difficult to do but very useful.

**Comment by micheljung** [comment]
Here's a workaround in case you're working with docker-compose and .env:

```bash
(set -a; source .env; envsubst < opendistro_security/securityconfig/internal_users.yml > /tmp/internal_users.yml; mv /tmp/internal_users.yml opendistro_security/securityconfig/internal_users.yml)
```

```bash
# Workaround for https://github.com/opendistro-for-elasticsearch/security/issues/24
awk 'FNR==NR {n=index($1,"=");if(n){vars[substr($i, 1, n - 1)]=substr($i, n + 1)}; next } { for (i in vars) gsub("\\$\\{"i"\\}", vars[i]) }1' \
  .env opendistro_security/securityconfig/internal_users.yml > ~/internal_users.yml
mv -f ~/internal_users.yml opendistro_security/securityconfig/internal_users.yml
```

**Comment by GezimSejdiu** [comment]
Hey @untoldone , 

for some of the yml files that is possible out of the box as described here: https://docs.search-guard.com/latest/configuration-password-handling but not possible i.e. to [set `opendistro_security.nodes_dn` via environment variable](https://discuss.opendistrocommunity.dev/t/set-opendistro-security-nodes-dn-via-environment-variable).

Any idea how that can be done without running a script that overrides these values (as @micheljung [workaround](https://github.com/opendistro-for-elasticsearch/security/issues/24#issuecomment-777306037) suggested, b.t.w that a lot for your workaround).

**Comment by scrawfor99** [comment]
[Triage 2/6/2023] There are numerous initiatives to improve the user experience of our admin tools. Currently, we are looking at other ways of improving this experience. Closing this issue as part of project maintenance.
