### ISSUE TITLE
[BUG] [CI] [1.x] WhiteSource checks failed

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#2400]
In the latest merge to 1.x as of creating this issue, the build for PR #2337 encountered WhiteSource CI check failure. This failure is impacting other branches as well. This issue is to track the fix.

__Expected Behavior__: WhiteSource check CI to pass

**Comment by scrawfor99** [comment]
[Triage] To be used as a tracking issue for recording the fix of the WhiteSource issue on the 1.x branch.
