### ISSUE TITLE
[BUG] Default action group cluster_manage_index_templates should include permissions for composable index templates

### ISSUE THREAD

**Issue by srt** [opensearch-project/security#2407]
**What is the bug?**
The default action group `cluster_manage_index_templates` currently only contains the permission `indices:admin/template/*` for legacy templates. It should also include `indices:admin/index_template/*` to support composable templates.

**How can one reproduce the bug?**
1. Create a role with `cluster_permissions` set to `cluster_manage_index_templates`
2. Create a user with that role
3. Send a PutIndexTemplateRequest to OpenSearch
4. See error `[security_exception] no permissions for [indices:admin/index_template/put]`

**What is the expected behavior?**
Composable templates can be managed by users with `cluster_manage_index_templates` permission.

**What is your host/environment?**
 - 2.4.1

**Comment by scrawfor99** [comment]
[Triage] @scrawfor99 please follow up and add additional notes on the issue stating what additional actions it permits. 

@srt, if you would like to contribute to the codebase I would encourage you to take a moment to address the change in a PR to this [file](https://github.com/opensearch-project/security/blob/9cdaeca7e97ca4a4351a2d7bbc729db0f4a1704e/src/main/resources/static_config/static_action_groups.yml#L1). Thank you!

**Comment by cwperks** [comment]
Closing this issue as https://github.com/opensearch-project/security/pull/2409 was merged.
