### ISSUE TITLE
[BUG] NoSuchMethodError when using an ECC certificate

### ISSUE THREAD

**Issue by DaPipe** [opensearch-project/security#2419]
**What is the bug?**
A fresh install configured to use an ECC certificate for transport and http gives the errors below:
```
java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
...
Caused by: java.lang.NoSuchMethodError: 'org.bouncycastle.asn1.ASN1Object org.bouncycastle.asn1.sec.ECPrivateKey.getParametersObject()'
```
**How can one reproduce the bug?**
1. Install from Opensearch YUM repo
2. Configure to use TLS certificate with ECC key
3. Start Opensearch
4. Get the NoSuchMethodError above in the log. 

**What is the expected behavior?**
Support for ECC certificates.

**What is your host/environment?**
 - OS: Oracle Linux
 - Version: 8
 - Hardened to: CIS Oracle Linux 8 Benchmark v2.0.0, Level 2 server
 - Fresh install, no extra plugins

**Do you have any additional context?**
This appears to be caused by a version mismatch with the Bouncy Castle libraries included with the install. 
The included libraries are bcprov-jdk15on-1.67.jar and bcpkix-jdk15on-1.70.jar. 
The performance analyzer plugin is using the bcprov-jdk15on-1.70.jar library, so I copied that jar to replace the 1.67 and it appears to have fixed the issue. 
This a fresh install so I won't know if this causes other issues for a few days at least.

**Comment by scrawfor99** [comment]
[Triage] @cwperks could you take a chance to look at this. Thank you.

**Comment by cwperks** [comment]
Closing this issue as solved. The issue was due to mismatching version of bouncy castle jars and solved with https://github.com/opensearch-project/security/pull/2422.
