### ISSUE TITLE
Add MacOS build support

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/security#2423]
**Is your feature request related to a problem?**
I tried to run the gradle tests per the readme.md file, but part of the tests failed because it tried to talk to either a LDAP-server or an opensearch cluster. It would be nice that these requirements could be met easilly (and documented how this is done). One option is to include a docker-compose file.

**What solution would you like?**
docker-compose file?

**What alternatives have you considered?**
Setting up stuff myself, but wasn't exactly clear how.

**Do you have any additional context?**
Ran the master branch tests last week

**Comment by peternied** [comment]
Hmm, maybe we need to clean up that readme documentation, `./gradlew test` does everything you need nice and easy on your local machine, no external systems setup required.  However, we have a ton more platform specific checks and workflows that are covered by our GitHub Actions.

Creating a pull request / draft PR is the best way to run the tests if you want to make sure things are in working order.  Speaking only for myself, I don't mind PRs while you are still building out tests/components.

**Comment by ict-one-nl** [comment]
Hm I tried to run the testsuite on macos arm arch, but out of the box the tests failed and I saw it try to connect to ldap/OS.

**Comment by peternied** [comment]
Could you post the error, maybe a summary here and the full output to a gist?

**Comment by ict-one-nl** [comment]
Commands executed

git pull
./gradlew clean test

don't know if I can find the logs so I took screenshots during the process

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/215885506-588c5423-e0c1-45f6-8f15-3c60f5d401f8.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/215885624-fcb64055-9d26-46ac-a164-66bce511a448.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/215886070-3c4a02ae-2835-4407-bcd9-f28fd7a26a02.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/215886246-942ca3e5-48f1-4d98-a351-073d6b883b04.png">

<img width="1626" alt="image" src="https://user-images.githubusercontent.com/2643715/215886312-937c0bc9-a2d7-4fa2-8adb-e3b2cc1cfebc.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/215886401-b39e875e-0c0a-4a0b-9190-b259a0e8eaec.png">

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/2643715/215887386-842d1866-373a-40d2-ae50-19e6efd01e95.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/215887653-6c0bc1bc-159c-45d0-ae0d-4a34790c68c2.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/215887691-aa76415e-4db8-4922-8661-61496bda359f.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/215889264-0f6fc94e-7def-47ef-b43e-8cba8df430af.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/215890090-7006e1ea-3384-4663-a26d-700c61cfc971.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/215890680-85635702-c46c-4f04-8efd-50abeed6cb55.png">

<img width="1799" alt="image" src="https://user-images.githubusercontent.com/2643715/215890708-23c6872b-6316-4f60-bade-559799e73cd2.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/215891767-535e10e3-a408-46f9-be8b-8b26b776522e.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/215892207-d30071ad-5d45-4034-bb81-7543491a4763.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/215892779-61503685-8af2-4208-a18b-043cd6fc9501.png">

<img width="1783" alt="image" src="https://user-images.githubusercontent.com/2643715/215893271-b774411b-096f-41fa-885b-aa2966dc3d30.png">

95% success rate. Is 41 minutes normal? Ran it on a macbook pro m1 max 10c/32GB

**Comment by cwperks** [comment]
@ict-one-nl What version of Java are you using? I would recommend using Java 11 or 17 to match the version of java run at build time in the Github Actions (GHA). See https://github.com/opensearch-project/security/blob/main/.github/workflows/ci.yml#L9-L37 for details on the command run via GHA.

**Comment by ict-one-nl** [comment]
Used the latest openjdk through homebrew, forced openjdk17 now, but - from eyeballing it - got the same errors. Will try the Oracle JDK tomorrow, thanks for the hints :)

**Comment by scrawfor99** [comment]
[Triage] Hi @ict-one-nl, thank you for filing this issue. Did trying the different JDK version fix anything? I know that we do not currently support MacOS though this is something in the works. I would be interested in hearing if you found any results or have any notes as we continue to develop platform support.

**Comment by ict-one-nl** [comment]
JDK-19 didn't fix it, JDK 17.0.6 gives the same result. Running Ventura 13.2 (22D49)

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2643715/217082313-1d1420ef-80db-4000-9d07-cf4df5344d64.png">

**Comment by davidlago** [comment]
This issue is being tracked here https://github.com/opensearch-project/security/issues/1475

**Comment by ict-one-nl** [comment]
👍👍
