### ISSUE TITLE
Add auto github release workflow

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/security#2435]
### Is your feature request related to a problem?
As part of OpenSearch releases, `opensearch-build` pushes a tag for the release commit.
But publishing a github release based on the tag is manual.

### What solution would you like?
We've added this workflow[1] in OpenSearch which publishes github releases automatically when a tag is pushed.

Add this workflow to all repos releasing software in the project.
See example: https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/auto-release.yml
Example Release: https://github.com/opensearch-project/OpenSearch/releases/tag/2.5.0

[1] https://github.com/opensearch-project/opensearch-plugins/blob/main/WORKFLOWS.md#auto-github-releases

**Comment by cwperks** [comment]
[Triage] @reta Tagging you for this issue.
