### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#2437]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by scrawfor99** [comment]
@dblock, do you want us to remove groups entirely and just add individuals? For instance, Security has 

opensearch-project/admin
opendistroforelasticsearch-security
opensearch-ci-bot 
opensearch-project/plugins 
opensearch-project/security
opensearch-project/security-non-maintainers 
opensearch-project/transfer-request
opensearch-project/triage 

Each with their own different permissions. Do you want me to go through and manually add the people in each group to their appropriate role? Or do you just want us to address the maintainers and security-non-maintainers and see that they are each assigned individually and then update the markdown and codeowners files?

**Comment by scrawfor99** [comment]
All set!

**Comment by dblock** [comment]
You had the `security` group with 7 members and all your maintainers had Admin level access. I've removed the group and downgraded everyone to maintain.

**Comment by peternied** [comment]
I've reviewed the list, there was a security triage group, but not the OpenSearch triage group.  I've added the correct project groups.

There is a bot user `opendistroforelasticsearch-security` that I'm double checking it access.  Once it is clear what this account is for and its been given the appropriate access I'll close out this issue.

**Comment by peternied** [comment]
All access setting have been baselined

**Comment by dblock** [comment]
Verified, thanks.
