### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#2449]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the Security repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| Security | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | Code Hygiene, Certificate of Origin, Plugin install  | https://github.com/opensearch-project/security/issues/2449 | 

I don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by peternied** [comment]
This looks right, but I would recommend adding 'code coverage' on the list of things we are tracking at the org level
