### ISSUE TITLE
[BUG] hash.sh script should not return deprecation message in output

### ISSUE THREAD

**Issue by defesteban** [opensearch-project/security#2485]
**What is the bug?**
`hash.sh` script should return only password, but now it returns
```
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
$2y$12$qqrlE8ZCdZOg4AwU5vjKO.MYFR4iGovWXsrY5LHlmxTgU3UJq7COG
```
as a result of password hash. Could you please separate streams for output and deprecation message?

**How can one reproduce the bug?**
1. Run in OpenSearch pod:
    ```
    password=$("${OPENSEARCH_HOME}/plugins/opensearch-security/tools/hash.sh" -p "basic") 
    ```
2. Check what is inside `password` variable:
    ```
    echo "$password"
    ```
3. Now result is as follows:
    ```
    **************************************************************************
    ** This tool will be deprecated in the next major release of OpenSearch **
    ** https://github.com/opensearch-project/security/issues/1755           **
    **************************************************************************
    $2y$12$qqrlE8ZCdZOg4AwU5vjKO.MYFR4iGovWXsrY5LHlmxTgU3UJq7COG
    ```

**What is the expected behavior?**
`hash.sh` script should return only password.

**What is your host/environment?**
 - Version: 2.4.1

**Comment by defesteban** [comment]
Hi, @davidlago 
Could you highlight the PR where this bug was fixed?

**Comment by davidlago** [comment]
My bad! I misread @scrawfor99 comment and thought that these were output via error output vs regular output thus could be parsed out in how people use this script. Re-opening, and back to "happily accepting PRs" :)

**Comment by davidosorno** [comment]
@defesteban I will look into it.

**Comment by davidosorno** [comment]
Hello @defesteban, I am  Looking into it.
Is it ok if the password is generated to a file? 
The deprecation message is still useful information.

**Comment by defesteban** [comment]
Hello, @davidosorno 
Is there an ability to redirect the deprecation message to error output instead of standard output?

**Comment by davidosorno** [comment]
Yes, there is a way to do it.
I'll do it and create a PR to get some feedback.
