### ISSUE TITLE
[Bug] Triage meeting what do do with 'Least recent discussed issue' section?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2519]
## Discussion around what to do with 'Least recent discussed issue'
_Notes taken via [GIST](https://gist.github.com/) during the triage meeting on March 06, 2023_

@peternied Seems like we should leave these issues alone, maybe retask the end of the meeting?
@davidlago OCD aspect, it would be nice to have everything cleared out.  On the otherhand does this send the wrong message about addressing issues.
@sandeshkr419 Sander As a product owner for 2 teams, seperate container for 'longer term' items, allow revisiting in the future.
  Make its clear that an issue isn't actively maintained / planned for implementation.
@cwperks Is there a way to collect RFCs for the project. (Seems like there is a way to do this with GitHub's functionality)

If we aren't changing how we handle older issues, what do we do with this part of the meeting?

  Reviewing the oldest item might not be useful over time - that issue will stay consistent.

@sandeshkr419  Could add ranking usefulness during planning poker exercise.  Mechanism to see what the community wants.
@peternied We have https://forum.opensearch.org/ which could be used to source community 'engaged' issues.  Might be the wrong kinds of issues / help requests vs tasks to focus on.

- No conclusion, Make a pull request to https://github.com/opensearch-project/security/blob/main/TRIAGING.md with any recommendations.

- Scrum of scrums? Maybe there is a way to pull out other requirements from larger project perspective.  Teams operate organically, not all are in alignment on intake process.

- Want to provide structure for the way the OpenSearch-Project runs, create an issue/PR in https://github.com/opensearch-project/.github

**Comment by davidlago** [comment]
I'm taking a pass at all of our open issues, will be done by EOD. Let's close this issue for now... a combination of "leave them alone" with a sweep/review every now and then is a good balance.
