### ISSUE TITLE
[BUG] Migrate modern build.gradle into 1.x branches

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2535]
## Background
There are many features of OpenSearch and its related ecosystem of tools that are java code as well as gradle plugins.  When security was initially [[migrated to gradle](https://github.com/opensearch-project/security/pull/1592)] the connection to gradle plugins provided by OpenSearch were not included.

After mounting issues such as aligning transitive dependency versions [1], publishing plugin zip files [2], and running OpenSearch's integration tests[3], a [[second gradle migration](https://github.com/opensearch-project/security/pull/1888)] was performed.  This build change was involved.

The security plugin codebase is running this second iteration on its `main` branches, in addition to the `2.X`, and `2.1+` branches.

## Problem
1.x and 1.3 branches are using the first iteration of the gradle build, leaving many features are locked away from being backported. 

### Blocked features backports
- https://github.com/opensearch-project/security/pull/1958
- https://github.com/opensearch-project/security/pull/2438
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1351

## Related Issues
- [1] https://github.com/opensearch-project/security/issues/1816
- [2] https://github.com/opensearch-project/security/issues/1801
- [3] https://github.com/opensearch-project/security/issues/1761
- [migrated to gradle] https://github.com/opensearch-project/security/pull/1592
- [second gradle migration] https://github.com/opensearch-project/security/pull/1888

**Comment by peternied** [comment]
Opened this issue in the wrong repo - but it impacts security dashboard plugin too

**Comment by cwperks** [comment]
Closing this issue. The changes to `build.gradle` will not be backported to the 1.x branches.
