### ISSUE TITLE
[Question] How does extension registration and de-registration tie into the security system?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2546]
On service startup, all extenesions are loaded, and scopes are validated.
- For every extensions they make a call to enable or disable service accounts.
  - If Enabled, create or return existing service account
  - If Disabled, deactive or do not create service account

**Comment by peternied** [comment]
@scrawfor99 I think this is covered in your docs, do you want to update this issue or close and incorporate these ideas elsewhere

**Comment by scrawfor99** [comment]
Hi @peternied, I will go ahead and add this to the Service Accounts issue.
