### ISSUE TITLE
[BUG] Permissions Lost During Rolling Upgrade

### ISSUE THREAD

**Issue by terryquigleysas** [opensearch-project/security#2580]
**What is the bug?**
Raised initially at https://forum.opensearch.org/t/permissions-lost-during-rolling-upgrade/13328

Observed when upgrading a 3 node cluster from OpenSearch 1.3.8 to 2.5.0

I have an admintest user with full permissions that works as expected on a clean install for both 1.3.8 and 2.5.0.

When I perform a rolling upgrade, on the first node to be OpenSearch 2.5.0, the user no longer has full permissions on that node - see curl sample below. I can still search but not perform any cluster queries.

I can still connect to the other 1.3.8 nodes with full access.

If I force all nodes to be 2.5.0 the issue resolves itself but this means we currently have an unwanted workaround in our code.

**How can one reproduce the bug?**
1. Deploy a cluster of 3 master/data nodes using OpenSearch 1.3.8
2. Create admintest user with all_access persmissions:
`{
“password”: “admintest”,
“opendistro_security_roles”: [
“all_access”
],
“backend_roles”: [
“all_access”
],
“attributes”: {
“attribute1”: “value1”,
“attribute2”: “value2”
}
}`
4. Upgrade a node in cluster to 2.5.0
5. Query the _cat/nodes endpoint on the 2.5.0 node using admintest
`curl -k -s “https://:9200/_cat/nodes?v” -u admintest:admintest}`

`{“error”:{“root_cause”:[{“type”:“security_exception”,“reason”:“no permissions for [cluster:monitor/state] and User [name=admintest, backend_roles=[cluster_all, cluster:monitor/state], all_access], requestedTenant=null]”}],“type”:“security_exception”,“reason”:“no permissions for [cluster:monitor/state] and User [name=admintest, backend_roles=[cluster_all, cluster:monitor/state], all_access], requestedTenant=null]”},“status”:403`

**What is the expected behavior?**
The admintest user should always have full access on all nodes

**What is your host/environment?**
 - Linux
 - OpenSearch 1.3.8 to 2.5.0
 - Plugins
    - analysis-icu
    - analysis-kuromoji
    - analysis-nori
    - analysis-phonetic
    - analysis-smartcn
    - analysis-stempel
    - mapper-murmur3

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by cwperks** [comment]
Hi @terryquigleysas, I have replicated your issue and doing an investigation now. I have also found a workaround that may work for you as well. I noticed in the description that you are setting the backend role of `admintest` to `all_access` when `all_access` is one of the internal opensearch roles. Backend roles are mapped to internal opensearch roles through roles mappings and you can see that default mapping for `all_access` here: https://github.com/opensearch-project/security/blob/main/config/roles_mapping.yml#L13-L17

```
all_access:
  reserved: false
  backend_roles:
  - "admin"
  description: "Maps admin to all_access"
```

I have confirmed locally by creating a 3-node cluster of 1.3.8 nodes and creating `admintest` using:

```
curl -XPUT https://admin:admin@localhost:9200/_opendistro/_security/api/internalusers/admintest --insecure --header "Content-Type: application/json" --data '{ "password": "admintest", "opendistro_security_roles": [ "all_access" ], "backend_roles": [ "admin" ], "attributes": { "attribute1": "value1", "attribute2": "value2" } }'
```

After creating the user I verified it could call `/_cat/nodes` then killed one of the 1.3.8 nodes and replaced it with a 2.5.0 node. I called the same endpoint on the 2.5.0 node in the mixed cluster and the request worked.

**Comment by terryquigleysas** [comment]
@cwperks Changing the backend roles does not work for us unfortunately.
We will stick with our current workaround to force a cluster restart until the solution is found.

**Comment by terryquigleysas** [comment]
@cwperks That does have different behaviour and removes the block when I run manually. We will need to build this into our code to verify but it looks to be a more promising workaround.

Thanks.

**Comment by scrawfor99** [comment]
[Triage] Hi @terryquigleysas, thank you for taking the time to file this issue. As mentioned above, it seems like there is an issue with the cluster permissions occurring during a rolling upgrade. Craig mentioned a workaround which may be an option for the meantime, but obviously having a rolling upgrade is a priority. Assigning this as Sprint Backlog due to importance.

**Comment by willyborankin** [comment]
I faced with such problem. In your configuration you have `opendistro_security_roles` an maybe `backend_roles` they are not serialized between nodes or somehow lost during serialization (did not investigate it deeper). To fix the problem just map your users via roles mapping:
```
some_role:
   - users: [some_user]
```
in such combination it works.

**Comment by peternied** [comment]
Resolved by 
- https://github.com/opensearch-project/security/pull/2498
