### ISSUE TITLE
[Feature Request] API does not allow export of saved objects in non-default tenant

### ISSUE THREAD

**Issue by torbenaa** [opensearch-project/security#2592]
I want to create a simple backup tool to save objects in all tenants. 

I can fetch the list of tenants at /_plugins/_security/api/tenants

Exporting the ndjson file from /api/saved_objects/_export only applies to the default tenant for the current user.

How can I export saved objects from other non-private tenants ? The API does not support this.

Opensearch version 2.4.1

**Comment by scrawfor99** [comment]
[Triage] Hi @torbenaa, thank you for taking the time to file this issue. Currently, we do not support these features. We do not have any documented API for using a backup tool to backup a saved object. You could consider using the features offered by the [snapshot management system](https://opensearch.org/docs/latest/api-reference/snapshots/get-snapshot/).
