### ISSUE TITLE
[Extensions] Modify Job Schedule's ScheduleParser to read in the refresh token field

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#2627]
The [ScheduleParser](https://github.com/opensearch-project/job-scheduler/blob/main/spi/src/main/java/org/opensearch/jobscheduler/spi/schedule/ScheduleParser.java) class in Job Scheduler is responsible for reading from schedules from within job definition's registered to the Job Scheduler. Plugin's make Job Scheduler aware of indices they will use to store job definitions and part of those job definitions contains information about the schedule.

The schedule information will also now include a `refresh_token` which identifies the creator (owner) of the job definition. The ScheduleParser needs to be updated to read this additional field.

**Comment by scrawfor99** [comment]
[Triage] This is part of the Extensions project.
