### ISSUE TITLE
[Security Review] Rest admin permissions 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2632]
The Rest Admin Permission feature was merged into the main branch.  It opens up access to the security configuration through REST APIs which were previously only accessible through an admin client certificate.  This is a considerable accessibility improvement that changes the security posture of OpenSearch clusters.

This feature requires completing a security review [1].  More details will be forthcoming as we assess timelines and scope.

Related links:
- [1] https://github.com/opensearch-project/.github/blob/main/RELEASING.md#security-reviews
- https://github.com/opensearch-project/security/pull/2411
- https://github.com/opensearch-project/security/issues/1878
- https://github.com/opensearch-project/security/issues/2571

**Comment by scrawfor99** [comment]
[Triage] Thank you @peternied for bringing this to everyone's attention. You raise an excellent point and we will all be mindful of this moving forward. I will leave this open as it is tracking the current reversion.
