### ISSUE TITLE
Test failing: Expected "Red cluster during testDelay testDelayInSecurityIndexInitialization " 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#2648]
**What is the bug?**
When testing changes coming from #2594, I encountered an issue where all CI pass except the Windows & JDK 11 build. This build fails with the following message: 

```
org.opensearch.security.SlowIntegrationTests > testDelayInSecurityIndexInitialization FAILED
    java.lang.AssertionError: Expected IOException here due to red cluster state
        at __randomizedtesting.SeedInfo.seed([1E6879A7E247E31B:3A7FD9AB095284F4]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.security.SlowIntegrationTests.testDelayInSecurityIndexInitialization(SlowIntegrationTests.java:163)
```

This seems like it could be a flaky test considering it only fails on the one configuration. When I look at the individual failures, all tests pass locally and with the other configurations. 

This is a potential blocker for #2594.

**Comment by peternied** [comment]
@scrawfor99 Did you mean to close this?

**Comment by scrawfor99** [comment]
@peternied, yeah, it is still an issue but I miss read the error. It is expected to fail with an IOException, right now it is a ConnectionErrorException. I am going to have to diagnose this along with the other two failing tests.
