### ISSUE TITLE
[BUG] Code Coverage is broken

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2649]
**What is the bug?**
Code coverage is being uploaded on pull requests due to errors:
```
{'detail': ErrorDetail(string='Missing "owner" argument. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```
_JDK11 build [[Source]](https://github.com/opensearch-project/security/actions/runs/4619770087/jobs/8168961129)_

```
{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```
_JDK17 build [[Source]](https://github.com/opensearch-project/security/actions/runs/4619770087/jobs/8168961333)_

**What is the expected behavior?**
Looks like our github action is [uses: codecov/codecov-action@v1](https://github.com/opensearch-project/security/blob/4988a74cdeac09be2e2657c6ab0793a63af76065/.github/workflows/ci.yml#L40)  this is deprecated and should be replaced with v3 - see details from https://github.com/codecov/codecov-action#%EF%B8%8F--deprecation-of-v1

**Comment by scrawfor99** [comment]
[Triage] Hi @peternied, thank you for taking the time to file this issue. I see you labelled this as a good first issue, and we definitely agree. Thank you.

**Comment by peternied** [comment]
Looks like this wasn't fixed, taking another attempt to fix this

**Comment by peternied** [comment]
Going to keep this opened until the backport [1] is created and merged into 2.x
- [1] https://github.com/opensearch-project/security/pull/3668

**Comment by scrawfor99** [comment]
Just FYI, I did not actually close this on you, I think it auto closed when I merged that PR @peternied

**Comment by peternied** [comment]
I haven't seen failures on CC in the past several days, and the PR I had out wasn't making any difference
