### ISSUE TITLE
[BUG] [CI] Windows build failing due to issue executing batch scripts

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#2657]
**What is the bug?**
This error was observed in CI failure for Windows tasks:
```
Exec output and error:
| Output for cmd:The following usage of the path operator in batch-parameter
| substitution is invalid: %~nxI
| 
| 
| For valid formats type CALL /? or FOR /?
| The syntax of the command is incorrect.
```
**Affected PRs:**
- #2557 - Run https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/4638567185/jobs/8211713749?pr=1396
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1396 - Run https://github.com/opensearch-project/security/actions/runs/4633403696/jobs/8198592237?pr=2557

**What is the expected behavior?**
CI should pass

**Comment by cwperks** [comment]
@DarshitChanpura, I am seeing this same error on job-scheduler too: https://github.com/opensearch-project/job-scheduler/pull/360

**Comment by scrawfor99** [comment]
[Triage] Hi @DarshitChanpura, thank you for taking the time to file this issue. I have been looking into this but have not yet found a solution. Based off my checks and Craig's findings, I am starting to think this may be an issue with the GitHub runner's parsing.

**Comment by vamsi-amazon** [comment]
@DarshitChanpura  I am seeing this error in windows integ tests for sql plugin: https://github.com/opensearch-project/sql/actions/runs/4660531784/jobs/8248701010?pr=1507

Is this change anywhere related to this...https://github.com/opensearch-project/OpenSearch/commit/0202de5849dcdcef61e1a2ad3b6a270574fbf2ed
