### ISSUE TITLE
[FEATURE] Refactor BackendRegistry to notifyIpAuthFailureListeners before auditing Failed Login and HTTPChallenge authenticator check

### ISSUE THREAD

**Issue by rutuja-amazon** [opensearch-project/security#2686]
Requesting refactor of `BackendRegistry` to invoke `notifyIpAuthFailureListeners` before auditlogging and Challenge authenticator check so that IP based rate limiting `AddressBasedRateLimiter` can be invoked when multiple wrong requests are sent from an attacker IP.

Ref:
https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/auth/BackendRegistry.java
https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/auth/limiting/AddressBasedRateLimiter.java

**Comment by scrawfor99** [comment]
[Triaging] Hi @rutuja-amazon, thank you for opening up this issue. Given the detail of exploration you have placed in this issue, we would encourage you to open a PR for the maintainers to review.
