### ISSUE TITLE
[Extensions] Audit Logging: Log when permissions have been granted/revoked and on privilege evaluation

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#2700]
Authorization in the REST layer needs to keep a log of requests that have been permitted and blocked, similar to how its logged for authorization in the Transport layer inside `SecurityFilter`.

In order for this issue to be addressed, changes will need to be made to the Security plugin so that when authorization on the REST layer occurs, the specific permissions granted to the subject are reported in the audit log. 

Resolves:

- As a cluster admin, I have record of when permissions granted/revoked

Details can be found in this PR: https://github.com/opensearch-project/security/pull/2753

**Comment by peternied** [comment]
Looks like https://github.com/opensearch-project/security/issues/3099 was a duplicate filing for the same kind of issue
