### ISSUE TITLE
[BUG] Audit log missing Username for failed basic auth request when SAML is enabled for given domain

### ISSUE THREAD

**Issue by niravpi** [opensearch-project/security#2721]
**What is the bug?**
For SAML enabled domain, Audit log is showing ```audit_request_effective_user``` as ```<NONE>```  for failed basic auth requests (incorrect username/password)

**How can one reproduce the bug?**
* Create any SAML enabled domain
* Enable Audit log for that domain 
* Now try to run any curl request ( via basic auth ) for the domain with incorrect username/password
* You will see that in the audit log ```audit_request_effective_user``` will be represented as a ```<NONE>```

**What is the expected behavior?**
For SAML enabled domain, in the audit log ```audit_request_effective_user``` should be having username details for failed basic auth requests as well

**What is your host/environment?**
 - OS: Linux
 - Plugins: Security

**Do you have any screenshots?**
NA

**Comment by scrawfor99** [comment]
[Triage] Hi @niravpi, thank you for opening this issue. For the scenario you described, it seems like there may be a more appropriate way of getting the information you are requesting. Specifically, your SAML configuration may be able to record the failed authentication attempts and log this information for you. Generally, we avoid scenarios where audit logging will send duplicate information or the same type of information (auth info) to different logs. Please reopen this issue if this does not address your request.

**Comment by peternied** [comment]
Checkout section 3.2.1 `Complex Type RequestAbstractType` from the SAML v2.0 [spec](https://www.oasis-open.org/committees/download.php/56776/sstc-saml-core-errata-2.0-wd-07.pdf#page=40) there is extra data about why a request was failed, but it isn't required.  Its possible this scenario could be supported, you might want to check SAML response to see if it has the principal in the failure.

We would be able to review a pull request if you wanted to add this functionality.
