### ISSUE TITLE
[BUG] DLS filtering is applied to the wrong action

### ISSUE THREAD

**Issue by MarrakchiAyoub** [opensearch-project/security#2736]
**What is the bug?**
Document level security for only one action in an index is applied also on other index_permissions with different actions and no DLS.

**How can one reproduce the bug?**
1. create an index and a user
2. create a role with the following permissions:
```
{ index_permissions: [ 
 {"index_patterns"=>["contacts"],
   "dls"=>"{\"match\":{\"field\":\"value\"}}", 
   "fls"=>["*"],
   "allowed_actions"=>["index"]
 },
 {"index_patterns"=>["contacts"],
   "fls"=>["*"],
   "allowed_actions"=>["read"]
 }
]}
```
4. add  the role to the user
5. when searching the index with the user credentials we only get document where `field` equals `value`

**PS:** the anomaly is also present when creating two different roles and assigning them to the same user

**What is the expected behavior?**
read permission should be on all documents as specified by the second element in the index_permissions.
update should be applicable only to the document concerned by the DLS in the first element.

**Environment**
 I run opensearch with the security plugin on docker, version: 2.6.0

**Comment by davidlago** [comment]
[Triaging] Thanks for reporting this, @MarrakchiAyoub. While we look into this specific behavior, could you please help us understand the use case/intended effect of this filter? (cc @peternied )

**Comment by davidlago** [comment]
Closing for now until/unless further details are added.
