### ISSUE TITLE
[Flaky Test] Configuration is not available after an update for more than 10 seconds

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2742]
Many tests are seeing failures like the following
```
org.opensearch.OpenSearchException: java.util.concurrent.TimeoutException: Timeout after 10SECONDS while retrieving configuration for [CONFIG](index=.opendistro_security)
```

Here is an example list of tests that are impacted
```
Tests with failures:
 - org.opensearch.security.TransportUserInjectorIntegTest.testSecurityUserInjection
 - org.opensearch.security.dlic.rest.api.legacy.LegacyNodesDnApiTests.testNodesDnApiWithPermissions
 - org.opensearch.security.multitenancy.test.TenancyDefaultTenantTests.testDefaultTenantUpdate
 - org.opensearch.security.multitenancy.test.TenancyMultitenancyEnabledTests.testMultitenancyDisabled_endToEndTest
```

Research done by @willyborankin that seems to indicate there is a cleanup/setup issue

> I played a bit with tests and found out that if you run first TenancyDefaultTenantTests and after that TenancyPrivateTenantEnabledTests the second one will fail in JetBrains. If you re-run tests afterwards they all green. It looks like a bug in the SingleClusterTest class I will try to take a look deeper.

_https://github.com/opensearch-project/security/pull/2557#issuecomment-1531908199_

Looks like this could be impacting many different pull requests:
- #2557
- #2735
- #2737

**Comment by peternied** [comment]
@willyborankin Would you be willing to take this issue on? If so please assign it to yourself, otherwise let me know and I'll figure out what to do next

**Comment by peternied** [comment]
Thanks, I've assigned you the issue

> I can't assigned myself since I'm _**yet**_ not a maintainer.

Fixed that for you

**Comment by scrawfor99** [comment]
Hi @willyborankin and @peternied, please let me know if you need a hand getting this sorted. I know @willyborankin is very capable but I am also happy to help if needed :)

**Comment by willyborankin** [comment]
> Hi @willyborankin and @peternied, please let me know if you need a hand getting this sorted. I know @willyborankin is very capable but I am also happy to help if needed :)

Thank you @scrawfor99 looks like i fixed it.

**Comment by willyborankin** [comment]
@peternied and @scrawfor99 found out the root cause of the test flakiness. The reason is tennacy rest endpoint implementation. It updates the sec index on each node and after index update the listener attached to the index sends client notifictions to other nodes :-). I fixed but still has some questions around REST end point itself. I will open PR most probably today.

**Comment by peternied** [comment]
@willyborankin Is this resolved?

- https://github.com/opensearch-project/security/pull/2758

**Comment by willyborankin** [comment]
@peternied  Yes I think I can close it now right?
