### ISSUE TITLE
[Extensions] Create extension point to be able to register security settings into `extensions.yml`

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#2746]
The security plugin uses the [ActionPlugin.getSettings()](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java#L905-L1089) extension point to add security settings to `opensearch.yml`. For extensions, there are multiple instances where the security plugin will need to register security settings for an extension. 

Examples include:

- https://github.com/opensearch-project/security/issues/2616
- https://github.com/opensearch-project/security/issues/2730

There needs to be an extension point that the security plugin can hook into to add settings that would be placed into `extensions.yml` so that the security plugin can read in the settings.

**Comment by davidlago** [comment]
[Triaging] @peternied to take a look at this, related to the Extensions project.

**Comment by peternied** [comment]
I'm tackling making these items available, but I won't reuse the 'Settings' interface, we will use the extensions object so there is a strong interface between core <-> security plugin

**Comment by saratvemulapalli** [comment]
Coming from: https://github.com/opensearch-project/security/pull/2749#issuecomment-1540125931
Thanks @cwperks for more information. 

The terminology confused me, settings in OpenSearch are a way to configure at bootstrap/runtime and is driven by `SettingsModule`.
Extensions also support settings, and these settings are registered with OpenSearch `SettingsModule`. Also as a side note, `opensearch.yml` is not modified after the node bootstrap its one time read only file, any changes to settings are in memory, tracked by `SettingsModule`.

Looks like we'd want to register few settings from Security plugin for extensions. 
I would like to understand how they look like and are they per extension?
On the flip side, it absolutely makes sense for `extensions.yml` to have security config at bootstrap.

**Comment by peternied** [comment]
Removed myself since it looks like @cwperks might want to take point with the implementation

**Comment by cwperks** [comment]
Thank you @peternied, I will look into it.

**Comment by cwperks** [comment]
@peternied I created a PR in core that shows an implementation of how the IdentityPlugin can define additional settings in `extensions.yml` that can then be read in by the security plugin: https://github.com/opensearch-project/OpenSearch/pull/7526

**Comment by cwperks** [comment]
@saratvemulapalli I opened up a PR in core that demonstrates how the IdentityPlugin can extend the settings in `extensions.yml` to add settings needed for security: https://github.com/opensearch-project/OpenSearch/pull/7526

**Comment by cwperks** [comment]
Closing this issue as the PR in core was merged: https://github.com/opensearch-project/OpenSearch/pull/7526
