### ISSUE TITLE
[BUG] Extensions handshake is failing with TLS after change to utilize `lookupInitializedExtensionById`

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#2747]
**What is the bug?**

Handshake with an extension fails with TLS because the extension is not initialized at the time of first handshake. There was a recent [change](https://github.com/opensearch-project/OpenSearch/pull/7374) in core to change the access modifiers of many methods within ExtensionsManager and direct access to the `extensionIdMap` was removed. In order to fix compilation on the security plugin, there was a change in the [SecurityRequestHandler](https://github.com/opensearch-project/security/pull/2741) to use the public method `lookupInitializedExtensionById`, but this data structure only contains initialized extensions. 

One way of solving this issue is to have the extension settings exposed to the security plugin so the security plugin can lookup in a map of extension settings to see if a unique id is present.

**Comment by peternied** [comment]
Looks like we need an `lookupUninitializedExtensionById` or something similar to handle this scenario in core

**Comment by cwperks** [comment]
I included a method to get extension settings in this PR: https://github.com/opensearch-project/OpenSearch/pull/6870

**Comment by cwperks** [comment]
@peternied I opened a PR in core and a PR here for a fix:

- https://github.com/opensearch-project/OpenSearch/pull/7466
- https://github.com/opensearch-project/security/pull/2749
