### ISSUE TITLE
[Refactor] Build failure due to breaking changes introduced in core

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security#2782]
**What is the issue?**
- We need to adapt the breaking change in core OpenSearch: https://github.com/opensearch-project/OpenSearch/pull/7508
- Core OpenSearch has split the imports of `org.opensearch.common.Strings` and `org.opensearch.core.common.Strings`into two. 
- Tracking on the original `toString()` function, since it is not defined in `org.opensearch.core.common.Strings`. The [current fix](https://github.com/opensearch-project/security/pull/2781#discussion_r1198265975) is:
   ```
   ...
   return org.opensearch.common.Strings.toString(JsonXContent.contentBuilder().map(getAsMap()));
   ...
   ```

- LoggerMessageFormat.java location change causing SecurityFilter.java to not compile

**Fixes**
- [x] Fix the `Strings` and `LoggerMessageFormat` package: https://github.com/opensearch-project/security/pull/2781
- [ ] ...wip

**Comment by scrawfor99** [comment]
[Triage] There is a fix for this pending in core. No further action is required.

**Comment by martin-gaievski** [comment]
@scrawfor99 Can you please share core issue that tracks that fix you've mentioned? I've opened another issue in core, do you think it may be related to the fix https://github.com/opensearch-project/OpenSearch/issues/7714?

**Comment by scrawfor99** [comment]
Hi @martin-gaievski, sorry, I did not see your comment before. The original fix should be up in the body of the issue I believe. Let me know if that is not what you were looking for.

**Comment by davidlago** [comment]
[Triage] Keeping open for now for tracking purposes (and if eventually any further work is needed)

**Comment by parasjain1** [comment]
We need to backport this to `2.x`. 

Changes in core were backported to `2.x`.
https://github.com/opensearch-project/OpenSearch/pull/8460

**Comment by RyanL1997** [comment]
Hi @parasjain1, ty for the notification~ I think we did the backport here: https://github.com/opensearch-project/security/pull/2953

**Comment by peternied** [comment]
@RyanL1997 You have another item 'wip...' which I suspect was 'work in progress'.  Doesn't look like there was anything else needed and the pull requests associated were merged and backported to 2.x -- assuming this is complete and closing this issue.
