### ISSUE TITLE
[BUG] javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown

### ISSUE THREAD

**Issue by zalseryani** [opensearch-project/security#2791]
# Issue

- I am trying to setup opensearch with self-signed certificates for transport layer. 
- I created the certificates and signed them with my root-ca.pem 
- I added all the needed parameters to my opensearch.yml (deploying with helm chart) 

- opensearch.yml

![image](https://github.com/opensearch-project/security/assets/49269877/dd868ec1-4e67-457a-a832-f16a6aca2043)
![image](https://github.com/opensearch-project/security/assets/49269877/8b509fc7-390a-49c3-9d69-a97988f3f65e)
![image](https://github.com/opensearch-project/security/assets/49269877/16b2b336-26f5-4fdb-8681-43f7b8c2bfd5)

all those certificates and keys are available in the correct path under config within opensearch pods. 

I tried to import those certificates with init container to cacerts and moving cacerts to /certs folder inside the application with empty dir volume and updated JAVA_OPTS and OPENSEARCH_JAVA_OPTS with the following java property to change the trustStore to the new cacerts trustStore that contains my imported certificates (also validated cacerts store to confirm my certificates are inside) and still facing the same issue. 

Kindly any support on this case, I am seeing many people having the same case.

**Comment by DarshitChanpura** [comment]
@zalseryani Can you verify whether these settings are present in opensearch.yml:
```
plugins.security.ssl.http.keystore_type: type (PKCS12, JKS, etc)
plugins.security.ssl.http.keystore_filepath: /path/to/keystore
plugins.security.ssl.http.keystore_password: your_keystore_password
plugins.security.ssl.http.truststore_type: type (PKCS12, JKS, etc)
plugins.security.ssl.http.truststore_filepath: /path/to/truststore
plugins.security.ssl.http.truststore_password: your_truststore_password
```

**Comment by zalseryani** [comment]
Those parameters are for http, i am using the certificates for transport layer. 

I am willing to use the default keystore but i want the transport layer to use my certs. 

Do I have to use those parameters knowing that I am already providing the root-ca as a trusted CA. 

Kindly advise 
Thank you 🙏

**Comment by zalseryani** [comment]
Kindly consider that the Issue is solved.

**Comment by DarshitChanpura** [comment]
> Kindly consider that the Issue is solved.

Nice that you were able to find a solution. If you don't mind, would you please post the steps for your approach to the solution?

**Comment by Surya-V-28** [comment]
@zalseryani @DarshitChanpura ,  Can you please let me know why is this issues is happening, im also facing it
