### ISSUE TITLE
Speed up CI test workflows in GHA

### ISSUE THREAD

**Issue by nibix** [opensearch-project/security#2798]
The CI job `build` can take more than one hour. As low turnaround times are desirable for speedy development, this should be reduced.

https://github.com/opensearch-project/security/actions/runs/4983823949/jobs/8921355684

![239952005-c5c32b38-e1f8-4096-bdbc-b48cab789f01](https://github.com/opensearch-project/security/assets/33570290/3178b436-bfd5-4684-b0f9-cf366c091a43)

**Comment by nibix** [comment]
@davidlago @peternied @scrawfor99 @cwperks FYI. We are already working on this. I filed this to document and discuss our findings and suggestions for improvement.

**Comment by peternied** [comment]
>Does it for Java-based tests make sense to run the complete tests suites under both operating systems

We have caught several platform specific issues by running the whole suite, we should not alter this strategy.  When we official support mac releases we will add its CI tests as well.

**Comment by peternied** [comment]
>A short term solution would be to parallelize the tests in maybe 4 CI jobs. This should be achievable with additional Gradle tasks. We are working on a prototype for this.

What is the mechanism that you are using to subdivide the test runs?  Are there multiple options, I'd be curious how flexible they are.

**Comment by nibix** [comment]
@peternied 

> We have caught several platform specific issues by running the whole suite, we should not alter this strategy. When we official support mac releases we will add its CI tests as well.

Just out of curiosity: Do you have an example for such a platform specific bug? I would like to know about the character of these bugs to be able to judge this better.
