### ISSUE TITLE
[Proposal] Minimize usage of HTTP 500 and return more specific error codes without any sensitive information

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#2811]
Since HTTP 500 is a catch-all error code there is a potential of stack-trace / sensitive information being leaked and it may also cause poor user experience. 

Implement a better error handling mechanism by replacing 500s with 4xx and a generic error messages

Tasks required:
- [ ] Identify origins of 500 errors
- [ ] Replace each those with a generic error message

Example:
*Note: some details have been redacted for security purpose*
```
Request:

POST /api/console/proxy?path=%2F_opendistro%2F_security%2Fapi%2Fssl%2Fcerts&method=GET HTTP/1.1
Host: localhost:5601
User-Agent: --
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:5601/app/dev_tools
Content-Type: application/json
osd-version: 2.7.0
osd-xsrf: osd-fetch
Origin: http://localhost:5601
Content-Length: --
Connection: close
Cookie: security_authentication=--
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin

{
"query": {
 "match_all": {x:"//////////////////"}
}
}
Response:

HTTP/1.1 502 Bad Gateway
content-type: application/json; charset=utf-8
osd-name: dd3eeb41e887
cache-control: private, no-cache, no-store, must-revalidate
set-cookie: security_authentication=--
vary: accept-encoding
Date: --
Connection: close
Content-Length: --

Unexpected end of JSON input
```

In this scenario, deserialization errors should be gracefully handled in the backend and a generic 400 should be returned to the user.

**Comment by davidlago** [comment]
[Triaging] @DarshitChanpura to add more details about the specific 500 errors we encountered to make this issue a bit more specific and not a chase of every 500 we throw.

**Comment by DarshitChanpura** [comment]
I have updated the issue description with an example request-response.

**Comment by peternied** [comment]
Aren't 500 errors logging details into the opensearch.log.  I agree we shouldn't throw 500s on invalid input, I think we should accept each of those kinds of '500 when it should be a 4XX' as an individual request.

I'm closing out this issue since there isn't a specific issue associated with this bug - let me know if you think there is some work that should be undertaken before we can close this out
