### ISSUE TITLE
[FEATURE] Improve admin permissions

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/security#2838]
**What solution would you like?**
The current plugin configuration assumes 3 types of admin users:
- super admin - required a separate keystore and SSL certificate
- REST admin - which can be set by settings a predefined role
- Cluster admin - which has access to all cluster and index operations

Such configuration is not intuitive and creates difficulties during configuration of the cluster.
To simplify the configuration of the plugin it would be better to introduce a list of permissions for the admin users and phase out special users (like super admin).

Permissions are:
    - `restapi:admin/<endpoint>/<action>` - has access to REST API interface to change users, roles, role mappings etc.clear caches, etc

In such case an end user can define a separate admin/rest admin and super admin users.
The existing super admin functionality with certificates could be deprecated and removed in future releases.    
Such configuration gives uniformity and flexibility to configure cluster access

**Comment by scrawfor99** [comment]
[Triage] Hi @willyborankin, thank you for filing this issue. The current permission configuration process is complicated so efforts to improve the system are certainly appreciated. Any PRs to this issue would be happily reviewed.

**Comment by davidlago** [comment]
#2411 blurs that line making most of those permissionable, so up to the user/cluster admins to decide how to set up.
