### ISSUE TITLE
Add configuration flag to disable system index permissions

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2845]
#### Problem:
System index permissions allow access to data on clusters that was previously not accessible.  For services that operate managed OpenSearch clusters they could want to restriction based on custom index / plugins configuration.

#### Proposed solution:
Check for a value in the security config something like "system index permissions disabled".
- For existing clusters that migrate to the latest version, the features should be disabled by default.
- For new clusters, the feature should be enabled by default.

**Comment by scrawfor99** [comment]
[Triage] Hi @peternied, this sounds like a good request considering the discussions around system indices. I think that @cwperks will have some suggestions on what may fall under this as well and may want to follow up here.
