### ISSUE TITLE
[FEATURE] Add FLS/DLS Integrated Test for Renamed Processor

### ISSUE THREAD

**Issue by mingshl** [opensearch-project/security#2890]
**Is your feature request related to a problem?**
@sejli contributed to add a RenamedResponseProcessor in OpenSearch Core repo. https://github.com/opensearch-project/OpenSearch/pull/7377

**What solution would you like?**
I record a video offline to test the RenamedResponseProcessor to make sure it complies with FLS/DLS rules, but we should add into integrated tests into security repo and make sure it's working as expected. 

 

**Do you have any additional context?**
 

https://github.com/opensearch-project/security/assets/113382730/91886781-3bda-436a-a739-a596ff0cd957

**Comment by RyanL1997** [comment]
I think this issue has already been implemented by this PR: https://github.com/opensearch-project/security/pull/2876. Could you plz confirm that @mingshl ?

**Comment by DarshitChanpura** [comment]
[Triage] @RyanL1997 to follow-up with @mingshl.

**Comment by mingshl** [comment]
> #2876

Hi @RyanL1997  RenamedResponseProcessor is a different feature than flat object, so we need different tests

**Comment by noCharger** [comment]
@RyanL1997  The search pipeline is going to GA in v2.9.0. Do we have an estimation on when this issue can be resolved? Thanks!

**Comment by davidlago** [comment]
@macohen is your team working on this one? would it make sense to transfer the issue to another repo for tracking purposes?

**Comment by macohen** [comment]
We're tracking it on our board so it's in view, but if you'd rather we move it, we can move it to the OpenSearch repo.

**Comment by davidlago** [comment]
Thanks! it's fine either way... just wanted to make sure it was being tracked somewhere and not falling through the cracks :)

**Comment by msfroh** [comment]
Updating the release target, since this isn't likely to be done before 2.10 ships.

Of course, this is an integration test that doesn't actually go into any released artifacts. So, tagging it to a specific release doesn't really mean anything.

We should try to get this done soon, rather that waiting for the 2.11 release timeframe. The sooner we start testing this automatically the better.

**Comment by peternied** [comment]
@sejli Take a look at https://github.com/opensearch-project/security/pull/2876 as a good example of how these kinds of tests were added in the past.  Feel free to comment on this issue or craft a draft PR if you'd like some pointers - thanks.

**Comment by scrawfor99** [comment]
You can find the tests that @sejli added here: https://github.com/opensearch-project/security/pull/3562.

These tests can be triggered in a similar way to those in core through Gradle or Junit. Check out the actions for this PR it will include the test run.
