### ISSUE TITLE
[CONSULTATION] Integrations API Permissioning

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security#2906]
### Basic Background 

Integrations is a new plugin under development which lets users view and install pre-canned dashboards and assets to allow them to kick off visualizing/playing with their data. The way this is accomplished is by storing a ndjson file defining saved objects that make up the dashboards/assets and then calling the saved objects client provided by OSD to bulk create these saved objects and point them at a specific index pattern, as well as a wrapper "integration instance" saved object that stores all of its children saved objects. Users are then able to go into their "installed" integrations to view these dashboards and other assets. And this call to get their "installed" integrations would be using the saved object client get call with appropriate filters applied. 

### Research Done / Ask from security team

I created a new integration instance and its children saved objects under an "admin" tenet, and then checked to see that the created integration was not visible under the "private" tenet. Is this sufficient to prove that the saved object client will provide the appropriate permissions? Is there some precedent that even if this was done that additional permissioning must be applied to all exposed endpoints? Any other concerns/considerations to raise with the integrations team regarding this high level design?

**Comment by davidlago** [comment]
As it currently stands, saved objects are owned by a tenant, not a user. They can only be viewed by users who have been granted access to that tenant. So long as there is no new specific permissions desired (based on the explanation above I'm not sure there are), I don't have any concerns from the security standpoint.

Now, the permission to fetch saved objects is one thing, but the permissions to actually make the calls to the backend to fetch the necessary data is another. Users need to have enough privileges to be able to populate the dashboards/saved objects with data. Think of it as saved objects being metadata defining the visualizations, and the actual data that populates being its own thing permissioned differently.

**Comment by scrawfor99** [comment]
[Triage] Question answered.
