### ISSUE TITLE
Implement end-to-end testing of the new named routes API and ensure backwards compatibility.

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2928]
Should have the following if not more test cases:

- [x] Allows authorized user to access to AuthZ in REST permissioned API
- [x] Denies unauthorized user to access to AuthZ in REST permissioned API
- [x] Denies unauthenticated user access to AuthZ in REST permissioned API 

Each of these tests should confirm:
- response code
- response body
- message saved to the audit log
- message saved to the error log

**Comment by scrawfor99** [comment]
[Triage] Thank you for detailing this information @peternied. Assigning to @DarshitChanpura as he is driving this feature.

**Comment by peternied** [comment]
- Note there is some overlap with https://github.com/opensearch-project/security/issues/3099 both issues could be handled at once, or together.

**Comment by DarshitChanpura** [comment]
Note: this is a two part effort.
- [x] Add a test that verifies the new functionality
- [ ] Add end-to-end testing to ensure backwards compatibility.

**Comment by DarshitChanpura** [comment]
No sure why the codecov/project report shows decrease of .01% when upon clicking the link to codecov it shows an increase of .01%
