### ISSUE TITLE
RestLayerPrivilegesEvaluator must have 100% branch code coverage

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2929]
Coverage should be enhanced to 100% these areas

- RestLayerPrivilegesEvaluator.java [82%](https://app.codecov.io/gh/opensearch-project/security/blob/main/src%2Fmain%2Fjava%2Forg%2Fopensearch%2Fsecurity%2Fprivileges%2FRestLayerPrivilegesEvaluator.java)
- SecurityRestFilter.java [62%](https://app.codecov.io/gh/opensearch-project/security/blob/main/src%2Fmain%2Fjava%2Forg%2Fopensearch%2Fsecurity%2Ffilter%2FSecurityRestFilter.java)

**Comment by DarshitChanpura** [comment]
The tests are already added as part of #2753.

**Comment by scrawfor99** [comment]
Closing as completed.

**Comment by peternied** [comment]
@scrawfor99

**Comment by scrawfor99** [comment]
Hi @peternied, of course. Sorry I thought it was completed since the associated PR was merged. My bad.

**Comment by scrawfor99** [comment]
In `RestLayerPrivilegeEvaluator`, I am not going to add code coverage for:

```
 if (isDebugEnabled) {
            log.debug("Evaluate permissions for {} on {}", user, clusterService.localNode().getName());
            log.debug("Action: {}", actions);
            log.debug("Mapped roles: {}", mappedRoles.toString());
```

or 

```
 if (isDebugEnabled) {
                    log.debug("Allowed because we have permissions for {}", actions);
                }
```

in `SecurityRestFilter`, I am not going to add coverage for:


```
 if (pres.isAllowed()) {
                log.debug("Request has been granted");
```
