### ISSUE TITLE
Internal Database Anonymous User

### ISSUE THREAD

**Issue by cdenneen** [opensearch-project/security#293]
Curious if it would be possible to add a built-in anonymous user into the Internal Database.
This user could be disabled or have no permissions by default.

Would like is the option of enabling a way to mimic IP based ACL.

So for example if the request is anonymous (basic curl GET):
if Role Mapping had Hosts "10.1.0.0/24" with Action Group of "get" and Index pattern of "movies" this would allow anyone in the 10.1.0.0/24 CIDR Read-Only anonymous access to the movies index.
if Role Mapping had Hosts "10.1.0.22/32" with Action Group of "crud" and Index pattern of "*" this would allow this Host access to read/write to any index including "movies".

This would allow host-based Fine Grained Access Control.

Is this functionality available? Could this be added feature?

**Comment by ldrolez** [comment]
role mapping should already work with a single IP, did you try?

**Comment by Anthony7774** [comment]
@cdenneen The anonymous user can be enabled in config.yml with below line:

`http:
      anonymous_auth_enabled: true`

and permissions can be assigned to a built in role (opendistro_security_anonymous_backendrole) vies roles.yaml file

Hope this helps

**Comment by scrawfor99** [comment]
[Triage] This issue has been addressed.
