### ISSUE TITLE
 [Maintenance] Use dependabot for tacking latest security updates

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/security#2933]
**Is your feature request related to a problem?**
To better track new versions of libs we use in the project. I suggest to use:

[Dependabot security updates](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates)

which automatically creates PRs with new version and CVEs libraries have.

**Comment by peternied** [comment]
I am in favor of adding a dependabot.yml file.  Here is a screenshot of the current dependent settings in case that isn't visible more broadly.  

![image](https://github.com/opensearch-project/security/assets/2754967/db966c4e-4880-4fd2-9e18-c604bc1a33dc)
