### ISSUE TITLE
[FEATURE] Add token manager to security plugin 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#2939]
This issue describes the addition of a feature that will add a token manager implementation to allow for the creation of auth tokens for both Users and InternalUser objects. The User objects will make use of the OnBehalfOfTokens while InternalUsers make use of a encoded basic authtoken. 

After this feature is added, it will be possible for a request to get an authtoken for a User or InternalUser account and then use that token with the corresponding handling mechanism. 

This change has been in progress since it is blocked by current work in the feature/extensions branch. 

Current PR: https://github.com/opensearch-project/security/pull/2787.

**Comment by scrawfor99** [comment]
[Triage] This is part of the Identity work being done to support extensions.

**Comment by davidlago** [comment]
#3176 is taking care of that, closing
