### ISSUE TITLE
[FEATURE] Grant a Service Account to an Extension on bootstrap 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#2942]
Per the title, this issue describes a feature where Extensions are assigned a service account during the installation process. This account should then be associated with that application and it should be possible to identify when an extension is using the Service Account or not.

Permission assignment is outside the scope of this issue.

**Comment by scrawfor99** [comment]
[Triage] This is part of the Identity work being done in core.

**Comment by davidlago** [comment]
#3176 addresses this
