### ISSUE TITLE
[Spike] Work pending to merge Feature/Extensions into Main

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#2945]
As the title suggests, we want to merge the feature/extensions branch into the main branch. 

This issue is an exploratory work of what the merge from the feature branch into main would look like. From this, we can estimate work needed to bring this to closure and plan for it (it might result in sub-issues/tasks)

This task involves a pre-review of what the merge looks like.

**Comment by scrawfor99** [comment]
[Triage] This issue is meant to track progress of merging feature/extensions branch into the main branch.

**Comment by davidlago** [comment]
This issue is an exploratory work of what the merge from the feature branch into main would look like. From this, we can estimate work needed to bring this to closure and plan for it (it might result in sub-issues/tasks)
