### ISSUE TITLE
[Question] Remove config V6 models

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/security#2967]
**Is your feature request related to a problem?**
I'm not sure that we support confiig V6 models maybe it is time to remove it?

**What solution would you like?**
Remove ConfigV6 model

**Comment by scrawfor99** [comment]
[Triage] Hi @willyborankin, this is a good point. @cwperks is going to share info for possible deprecation.

**Comment by peternied** [comment]
[Triage] We migrate from v6 -> v7 so they are 'supported' for the moment.  I'm not sure if clusters can be created with v6 configurations, if they cannot maybe it would make sense to depreciate and remove on v3.0.0.  Curious if there is any work that is being held up if we continue to support them in the 2.x ecosystem.

**Comment by nibix** [comment]
Done in #4546 :-)
