### ISSUE TITLE
Unable to `reloadcerts` on Windows

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/security#2984]
OpenSearch 2.8.0 is installed on Windows and, root, node and admin certs/keys are created, and the root cert and admin cert/key are successfully used with `securityadmin.bat` to load configurations like `internalusers.yml`. 

According to docs, hot-loading of certificates is possible by performing a `PUT` on `_opendistro/_security/api/ssl/transport/reloadcerts`. While undocumented, this is only possible when authenticating with the admin cert.

There are 3 curl options on Windows:
1. PowerShell's (v7.x) `Invoke-WebRequest` and its siblings who required a PFX cert. I created one with my admin cert and key but the request failed to auth.
2. Windows' built-in `curl.exe` simply doesn't support certificate-based authentication.
3. [curl for Windows](https://curl.se/windows/) which failed with `alert certificate unknown` indicating it failed as well.

Questions:
1. Is there any way to authenticate with admin certs on Windows?
2. Is there any other way to hot-reload the certs, perhaps using securityadmin.bat, or even a periodical auto-reload like the one ES offers?

**Comment by peternied** [comment]
> While undocumented this is only possible when authenticating with the admin cert.

See [reload-certificates](https://opensearch.org/docs/latest/security/access-control/api/#reload-certificates) for documentation. Recently, access to administrative APIs such as reload certs was opened up removing the requirement for certificated based authentication, [see details](https://opensearch.org/docs/latest/security/access-control/api/#access-control-for-the-api).  This might avoid some of the problems you've encountered while configuring a client.

**Comment by AMoo-Miki** [comment]
Thanks Peter; I will experiment with it and report back.

**Comment by peternied** [comment]
[Triage] Based on the workaround posted I think this scenario is possible, or you'll need to take a look at the capabilities of those different clients in the windows ecosystem - maybe stackoverflow would be a better place to get traction on those tools?
