### ISSUE TITLE
Add ability to pass additional URL parameter to OIDC IdP

### ISSUE THREAD

**Issue by yann-soubeyrand** [opensearch-project/security#2986]
**Is your feature request related to a problem? Please describe.**

We’d like to pass the `kc_idp_hint` parameter to our Keycloak IdP (https://www.keycloak.org/docs/latest/server_admin/#_client_suggested_idp).

**Describe the solution you'd like**

We’d like a way to configure additional parameters to pass in the OIDC redirect URI.

**Describe alternatives you've considered**

We don’t really have an alternative.

**Additional context**

If the `kc_idp_hint` URL parameter could be set based on the reverse proxy host used to access OpenSearch dashboards, it would be awesome!

**Comment by peternied** [comment]
[Triage] If there is a generic way we could support this scenario I think this would be a good feature to add, but a keycloak specific parameter seems less likely.

@willyborankin @RyanL1997 Did you have thoughts this?

**Comment by cwperks** [comment]
[Triage] @cwperks Can you look into this further?

**Comment by peternied** [comment]
[Triage] @cwperks Did you still want to look into this?

**Comment by scrawfor99** [comment]
[Triage] @willyborankin to follow up.

**Comment by willyborankin** [comment]
`kc_idp_hint` should be set via Login/Auth URL, so technically if you use a static file instead with OpenID .well known URL you can add it to your auth endpoint definition: `{KK}/realms/{RM}/protocol/openid-connect/auth?kc_idp_hint`

**Comment by scrawfor99** [comment]
[Triage] Closing this issue since the parameter is available already. You just need to add it to your URL as a param; this is also overly specific to keycloak so we cannot commit to supporting further integration on the home codebase. I would recommend making further changes to your local version.
