### ISSUE TITLE
[BUG] [CI] Investigate Flaky test failure for windows CI tasks

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#3021]
**What is the bug?**

Windows CI has been flaky with recent runs for tasks, specifically  `citest`, `dlicRestApiTest`.

See these runs for example:

https://github.com/opensearch-project/security/actions/runs/5577190458/attempts/1 <-- 3 tasks failed
https://github.com/opensearch-project/security/actions/runs/5577190458/attempts/2 <-- 2 tasks failed (1 prev failed task passed)
https://github.com/opensearch-project/security/actions/runs/5577190458/attempts/3 <-- 1 task failed
https://github.com/opensearch-project/security/actions/runs/5577190458/attempts/5 <-- all tasks passed

<details>
  <summary>Failure Details</summary>

|        | (citest, windows-latest, 11)                                                                                                            | (citest, windows-latest, 17)                                                                                              |
|--------|----------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------|
| 1st run| - org.opensearch.security.SecurityAdminTests.testSecurityAdmin<br> - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testRestApiRolesEnabled<br> - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testComplianceEnable<br> - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testRestApiRolesDisabled<br> - org.opensearch.security.multitenancy.test.MultitenancyTests.testTenantParametersSubstitution<br> - org.opensearch.security.auditlog.integration.BasicAuditlogTest.testDeleteByQuery<br> - org.opensearch.security.httpclient.HttpClientTest.testPlainConnection<br> - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testComplianceEnable<br> - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testRestApiRolesEnabled| - com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticatorTest.initialConnectionFailureTest<br> - com.amazon.dlic.auth.ldap2.LdapBackendIntegTest2.testIntegLdapAuthenticationSSL<br> - org.opensearch.security.SecurityAdminTests.testIsLegacySecurityIndexOnV7Index<br> - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testInternalConfig<br> - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testComplianceEnable<br> - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testInternalConfig<br> - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testBCryptHashRedaction<br> - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testRestApiRolesDisabled<br> - org.opensearch.security.multitenancy.test.TenancyPrivateTenantEnabledTests.testPrivateTenantDisabled_Update_EndToEnd<br> - org.opensearch.security.auditlog.integration.BasicAuditlogTest.testSensitiveMethodRedaction<br> - org.opensearch.security.auditlog.integration.BasicAuditlogTest.testScroll<br> - org.opensearch.security.auditlog.integration.BasicAuditlogTest.testScroll<br> - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testBCryptHashRedaction|
| 2nd run| - org.opensearch.security.SecurityAdminTests.testSecurityAdminRegularUpdate<br> - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testInternalConfig<br> - org.opensearch.security.auditlog.integration.BasicAuditlogTest.testDeleteByQuery<br> - org.opensearch.security.multitenancy.test.TenancyMultitenancyEnabledTests.testMultitenancyDisabled_endToEndTest<br> - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testInternalConfig<br> - org.opensearch.security.auditlog.integration.BasicAuditlogTest.testDeleteByQuery| - com.amazon.dlic.auth.ldap2.LdapBackendIntegTest2.testAttributesWithImpersonation<br> - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testWriteHistory<br> - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testBCryptHashRedaction<br> - org.opensearch.security.multitenancy.test.MultitenancyTests.testTenantParametersSubstitution<br> - org.opensearch.security.multitenancy.test.MultitenancyTests.testMt<br> - org.opensearch.security.multitenancy.test.MultitenancyTests.testMtMulti<br> - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testBCryptHashRedaction|
| 3rd run| - org.opensearch.security.SecurityAdminTests.testSecurityAdmin<br> - org.opensearch.security.SecurityAdminTests.testSecurityAdminInvalidCert<br> - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testRestApiRolesEnabled<br> - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testRestApiNewUser<br> - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testUpdate<br> - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testInternalConfig<br> - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testRestApiRolesEnabled<br> - org.opensearch.security.auditlog.integration.BasicAuditlogTest.testDeleteByQuery<br> - org.opensearch.security.multitenancy.test.MultitenancyTests.testMt<br> - org.opensearch.security.auditlog.integration.BasicAuditlogTest.testDeleteByQuery<br> - org.opensearch.security.multitenancy.test.TenancyMultitenancyEnabledTests.testMultitenancyDisabled_endToEndTest<br> - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testRestApiNewUser<br> - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testInternalConfig<br> - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testUpdate|

</details>

<details>
  <summary>Test Methods with failures across all mentioned runs</summary>

```
- org.opensearch.security.SecurityAdminTests.testSecurityAdmin
- org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testRestApiRolesEnabled
- org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testComplianceEnable
- org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testRestApiRolesDisabled
- org.opensearch.security.multitenancy.test.MultitenancyTests.testTenantParametersSubstitution
- org.opensearch.security.auditlog.integration.BasicAuditlogTest.testDeleteByQuery
- org.opensearch.security.httpclient.HttpClientTest.testPlainConnection
- com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticatorTest.initialConnectionFailureTest
- com.amazon.dlic.auth.ldap2.LdapBackendIntegTest2.testIntegLdapAuthenticationSSL
- org.opensearch.security.SecurityAdminTests.testIsLegacySecurityIndexOnV7Index
- org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testInternalConfig
- org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testBCryptHashRedaction
- org.opensearch.security.multitenancy.test.TenancyPrivateTenantEnabledTests.testPrivateTenantDisabled_Update_EndToEnd
- org.opensearch.security.auditlog.integration.BasicAuditlogTest.testSensitiveMethodRedaction
- org.opensearch.security.auditlog.integration.BasicAuditlogTest.testScroll
- org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testBCryptHashRedaction
- org.opensearch.security.multitenancy.test.MultitenancyTests.testMt
- org.opensearch.security.multitenancy.test.MultitenancyTests.testMtMulti
- org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testWriteHistory
- org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testRestApiNewUser
- org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testUpdate
- org.opensearch.security.SecurityAdminTests.testSecurityAdminInvalidCert
- org.opensearch.security.multitenancy.test.TenancyMultitenancyEnabledTests.testMultitenancyDisabled_endToEndTest
```
</details>

**What is the expected behavior?**
No flakiness.

**Comment by peternied** [comment]
[Triage] Thanks for filing, could we get a list of tests that are impacted?

**Comment by cwperks** [comment]
@DarshitChanpura it looks like there were a few fixes put into main for windows support that may not have been backported to 2.x.

Particularly this one: https://github.com/opensearch-project/security/pull/2180

There is a list of issues that @peternied added to this PR description: https://github.com/opensearch-project/security/pull/2291 - it may be best to backport the one's of those that can be backported

**Comment by peternied** [comment]
From https://github.com/opensearch-project/security/pull/3032#pullrequestreview-1537440909

#### CI / test (citest, windows-latest, 11) (pull_request) Failing after 29m
```
Tests with failures:
 - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testInternalConfig
 - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testComplianceEnable
 - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testUpdate
 - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testRestApiNewUser
 - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testInternalConfig
 - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testAutoInit
 - org.opensearch.security.multitenancy.test.TenancyMultitenancyEnabledTests.testMultitenancyDisabled_endToEndTest
 - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testUpdate
 - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testAutoInit
 - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testComplianceEnable
```

**Comment by DarshitChanpura** [comment]
> [Triage] Thanks for filing, could we get a list of tests that are impacted?

Updated the issue description to include two sections: 1. Run Details. 2. Test Methods with failure

**Comment by DarshitChanpura** [comment]
Seems like there were no failures in https://github.com/opensearch-project/security/pull/3032 and #3037 after #3035  was merged which suggests this issue might have been fixed.

**Comment by cwperks** [comment]
I've seen these failures in a couple of places now:

```
Tests with failures:
 - org.opensearch.security.SecurityAdminTests.testSecurityAdmin
 - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testInternalConfig
 - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testRestApiNewUser
 - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testBCryptHashRedaction
 - org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testInternalConfig
 - org.opensearch.security.multitenancy.test.MultitenancyTests.testMultitenancyAnonymousUser
 - org.opensearch.security.multitenancy.test.MultitenancyTests.testMt
 - org.opensearch.security.auditlog.integration.BasicAuditlogTest.testScroll
 - org.opensearch.security.auditlog.integration.BasicAuditlogTest.testScroll
 - org.opensearch.security.httpclient.HttpClientTest.testSslConnectionPKIAuth
 - org.opensearch.security.multitenancy.test.TenancyMultitenancyEnabledTests.testMultitenancyDisabled_endToEndTest
 - org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testBCryptHashRedaction
```

When trying a single test suite locally like this:

```
./gradlew -x opensslCITest test --tests ComplianceAuditlogTest -i
```

I see that it fails in blocks like [this](https://github.com/opensearch-project/security/blob/2.x/src/test/java/org/opensearch/security/auditlog/compliance/ComplianceAuditlogTest.java#L378-L383) and I can see the following error in the logs:

```
    [2023-07-21T17:52:31,538][WARN ][rest.suppressed] path: /humanresources/_doc/100, params: {pretty=, index=humanresources, id=100}
    org.opensearch.OpenSearchSecurityException: No user found for indices:admin/mapping/auto_put
        at org.opensearch.security.filter.SecurityFilter.apply0(SecurityFilter.java:356) ~[main/:?]
        at org.opensearch.security.filter.SecurityFilter.apply(SecurityFilter.java:165) ~[main/:?]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:188) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:107) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:110) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:97) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:476) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1537) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.cluster.action.index.MappingUpdatedAction.sendUpdateMapping(MappingUpdatedAction.java:161) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.cluster.action.index.MappingUpdatedAction.updateMappingOnClusterManager(MappingUpdatedAction.java:126) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.action.bulk.TransportShardBulkAction.lambda$dispatchedShardOperationOnPrimary$1(TransportShardBulkAction.java:415) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:646) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:467) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:531) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:412) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:124) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.action.support.replication.TransportWriteAction$1.doRun(TransportWriteAction.java:223) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
```

which I had seen before when testing out this PR: https://github.com/opensearch-project/security/pull/2765

I created a branch to revert that change in 2.x locally to check if it would help with CI stability (https://github.com/cwperks/security/tree/check-2.x-build) and the tests did pass after the first try.

**Comment by cwperks** [comment]
I think https://github.com/opensearch-project/security/pull/2765 may need to be reverted. After seeing the error on both main and 2.x on Friday I did more sanity testing on the RC build to try to produce the error outside of CI, but I was not able to.

To see examples of the error you can check a recent [build on main](https://github.com/opensearch-project/security/actions/runs/5641609795/job/15279963463?pr=3042#step:4:837) and look for

```
org.opensearch.OpenSearchSecurityException: No user found for indices:admin/mapping/auto_put
```

or another on 2.x [here](https://github.com/opensearch-project/security/actions/runs/5624614406/job/15252475728?pr=3033)

From what I have put together the issue is reproducible on many of the ComplianceAuditlogTest like [this one](https://github.com/opensearch-project/security/blob/main/src/test/java/org/opensearch/security/auditlog/compliance/ComplianceAuditlogTest.java#L405-L444).

and fails when writing the first document to the `humanresources` where under the hood its doing a PutMappingRequest (`indices:admin/mapping/auto_put`). I believe that this request does a BulkShardRequest (`indices:data/write/bulk[s]`) which spawns a BulkShardRequest[Primary](`indices:data/write/bulk[s][p]`) and BulkShardRequest[Replica] (`indices:data/write/bulk[s][r]`)

The error is coming up during the derivative BulkShardRequest[Primary] and BulkShardRequest[Replica] requests. 

After tracing through the code it looks like the assumption that the transient headers will still be available on the receiving end of a transport request on a local node may not be accurate. From doing some testing, it looks like direct requests still go through the same `OutboundHandler` and `InboundHandler` as transport requests. 

Flow in the OutboundHandler

1. In an OutboundHandler the threadContext is sent as headers in the [OutboundMessage](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/transport/OutboundHandler.java#L105-L129)
2. The threadcontext is serialized [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/transport/OutboundMessage.java#L87-L89)
3. and in the ThreadContext it looks like only the request headers (not the transient headers) are written to the OutputStream: https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java#L812-L831

Flow in the InboundHandler

1. It gets the headers from the [InboundMessage](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/transport/InboundHandler.java#L123)
2. It stashes the local threadcontext and puts the headers from the [InboundMessage](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/transport/InboundHandler.java#L126-L129)

I'm having some trouble tracing all of the calls, but it looks like more work may need to be done to skip the serialization-deserialization of the transient headers on local node calls.

I'm still doing testing on the RC to see if the issue is reproducible there.

**Comment by DarshitChanpura** [comment]
[CI passed](https://github.com/opensearch-project/security/actions/runs/5508209014/job/14910702431) on #2765's merge to main (without any retries) so I don't believe that is the root cause. However, the failures seem oddly specific to requests involving action: `indices:admin/mapping/auto_put` (See [this run](https://github.com/opensearch-project/security/actions/runs/5600899211/job/15172193262#step:4:2803) for example)

All failures point to this source:
```
[{"type":"security_exception","reason":"No user found for indices:admin/mapping/auto_put"}],"type":"security_exception","reason":"No user found for indices:admin/mapping/auto_put"},"status":500
```

**Comment by scrawfor99** [comment]
[Triage] This is being actively looked at by @DarshitChanpura.

**Comment by DarshitChanpura** [comment]
There are 3 mains areas that were identified:
- this failure was hidden behind test retries, and could not be uncovered until recently
- we don't have 100% confidence in identifying whether #2765 introduces this
- We may see 500s with "No user found for .." message in 2.9 clusters

>and in the ThreadContext it looks like only the request headers (not the transient headers) are written to the OutputStream:

@cwperks From what I see in OutboundMessage class, the transient headers are being written to output stream: https://github.com/opensearch-project/OpenSearch/blob/3ee42920fa886bdf566f1bb7b1666ffa72d36f54/server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java#L321-L325

**Comment by cwperks** [comment]
In my local testing, the transmitter (SecurityInterceptor) and the receiver (SecurityRequestHandler) are using different threadpools even when handling a local node request. I don't think persistent threadcontext headers would help here if there are different threadpools.

**Comment by reta** [comment]
> I don't think persistent threadcontext headers would help here if there are different threadpools.

We've been looking with @DarshitChanpura and the hypothesis here (not confirmed yet) is that the thread context may not work here: the `SecurityInterceptor` thread may finish before the `SecurityRequestHandler` (basically the  `SecurityRequestHandler` won't see the stashed thread context but the previous one)

**Comment by cwperks** [comment]
One thing that's interesting, is that I see that sometimes it bypasses the sender during local requests and the logic to bypass is actually in core.

1. In TransportService, [sendRequest first calls on getConnection](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/transport/TransportService.java#L810-L825)
2. getConnection returns a [localConnection if its the local node](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/transport/TransportService.java#L912-L922)
3. The localNodeConnection calls [sendLocalRequest](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/transport/TransportService.java#L912-L922) which does not call on the AsyncSender at all

In the failing tests the AsyncSender is called somehow (on a local node request) which always precedes the failures seen in CI.

**Comment by cwperks** [comment]
In doing more local testing, I think I see an identity crisis happening where core thinks the local node is node1 and the security plugin thinks its node2. I'm looking into how this can happen now. Both the security plugin and core should be aware of node they are running on without any conflicts.

I added logging statements in [`TransportService.getConnection`](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/transport/TransportService.java#L912-L922) and then again inside `SecurityInterceptor.sendRequestDecorate` which is called directly after `getConnection` on remote node requests.

**Comment by reta** [comment]
I think I nailed it folks:

```
    public static DiscoveryNode getLocalNode() {
        return localNode;
    }

```

We run 3 nodes in single JVM, with 3 security plugins

**Comment by DarshitChanpura** [comment]
This localNode is set by using clusterService.localNode() method upon node bootstrap:
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/node/Node.java#L1379

And security plugin uses this localNode reference to then compare if request is for sameNode:
https://github.com/opensearch-project/security/blob/37aacdc0ceab4462498c9bdf339e6e0b5d30ef80/src/main/java/org/opensearch/security/transport/SecurityInterceptor.java#L149-L150

i'm not super-convinced on what would happen in a multi-node cluster when the request ends up in the same node. Will the thread be shared between SecurityInterceptor and SecurityRequestHandler?

**Comment by cwperks** [comment]
> We run 3 nodes in single JVM, with 3 security plugins, only one of them wins. @DarshitChanpura I think at this moment - this is 100% test related problem that should not leak into production.

I think so too, I was not able to replicate the issue on the RC.

That being said I think the code path [here in the SecurityInterceptor](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/transport/SecurityInterceptor.java#L279-L293) and the corresponding [code in the receiver](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java#L144-L168) is dead code. In reality, the user is not serialized on local node requests because it takes the [bypass route described here](https://github.com/opensearch-project/security/issues/3021#issuecomment-1650334388)

**Comment by DarshitChanpura** [comment]
I will update here with an RCA and next steps soon.

**Comment by davidlago** [comment]
Closing this one as the major blocker was resolved. Future flaky tests can have their own issues.

**Comment by DarshitChanpura** [comment]
> I will update here with an RCA and next steps soon.

Posted results here: https://github.com/opensearch-project/security/issues/2724#issuecomment-1669639995
