### ISSUE TITLE
[BUG] 403 on `/_plugins/_security/tenantinfo`

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/security#3058]
**What is the bug?**
Authenticated as the admin user, I get 403 when i call GET on `/_plugins/_security/tenantinfo`
```
* using HTTP/1.x
* Server auth using Basic with user 'miki'
> GET /_plugins/_security/tenantinfo HTTP/1.1
> Host: osd.aws.barahmand.com:9200
> Authorization: Basic xxxxxxxxxxxxxxxxx
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< content-type: text/plain; charset=UTF-8
< content-length: 0
< 
* Connection #0 to host osd.aws.barahmand.com left intact
```

The account details with `/_plugins/_security/api/account`:
```json
{
  "user_name": "miki",
  "is_reserved": true,
  "is_hidden": false,
  "is_internal_user": true,
  "user_requested_tenant": null,
  "backend_roles": [
    "admin",
    "kibanauser",
    "readall"
  ],
  "custom_attribute_names": [],
  "tenants": {
    "admin_tenant": true,
    "miki": true,
    "Trinity Lite Presentation": true,
    "global_tenant": true
  },
  "roles": [
    "own_index",
    "kibana_user",
    "all_access",
    "readall"
  ]
}
```

**How can one reproduce the bug?**
1. Download the release archive from the website
2. Comment out all users in `internal_users.yml` and add
    ```yml
    miki:
      hash: "$xxxxxxxxxxxxxx"
      reserved: true
      backend_roles:
      - "admin"
      - "kibanauser"
      - "readall"
      description: "Miki"
    ```
3. Do `securityadmin` magic.
4. GET `/_plugins/_security/tenantinfo`

**What is the expected behavior?**
Not 403

**What is your host/environment?**
 - OS: OSX, AL2, AL2023
 - Version: 2.8.0
 - Plugins: All as bundled in 2.8.0 release

**Do you have any additional context?**
This worked just fine with 2.7.0, returning the tenants.

As a hack, in 2.8.0, if i add ...
```yml
config.dynamic.kibana.server_username: "miki"
```
... and do the `securityadmin` magic, things work.

**Comment by scrawfor99** [comment]
[Triage] Hi @AMoo-Miki, thank you for filing this issue. Someone will take a look to confirm this issue is still persistent with the 2.9.0 version. There was some fixes around the tenancy features in 2.9, so this may already be addressed.

**Comment by peternied** [comment]
Seems like this filed in relationship to this slack thread [1], where you mention the issue was resolved after updating the configuration with the securityadmin tool.  I'm going to close this out, please reopen if you this is a separate issue

- [1] https://opensearch.slack.com/archives/C051Y637FKK/p1690406440537719

**Comment by FactorT** [comment]
@FactorT the problem was fixed this way:
File config/opensearch-security/config.yml was changed before installation 
Before changing:
```config:
  dynamic:
    # Set filtered_alias_mode to 'disallow' to forbid more than 2 filtered aliases per index
    # Set filtered_alias_mode to 'warn' to allow more than 2 filtered aliases per index but warns about it (default)
    # Set filtered_alias_mode to 'nowarn' to allow more than 2 filtered aliases per index silently
    #filtered_alias_mode: warn
    #do_not_fail_on_forbidden: false
    #kibana:
    # Kibana multitenancy
    #multitenancy_enabled: true
    #server_username: kibanaserver
    #index: '.kibana'```
After changing:
```config:
  dynamic:
    # Set filtered_alias_mode to 'disallow' to forbid more than 2 filtered aliases per index
    # Set filtered_alias_mode to 'warn' to allow more than 2 filtered aliases per index but warns about it (default)
    # Set filtered_alias_mode to 'nowarn' to allow more than 2 filtered aliases per index silently
    #filtered_alias_mode: warn
    #do_not_fail_on_forbidden: false
    kibana:
    # Kibana multitenancy
    #multitenancy_enabled: true
      server_username: {{ os_kibanaserver_user }}
    #index: '.kibana'```
