### ISSUE TITLE
Investigate CI Failures

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3064]
The PR queue is piling up with various issues seen on pull requests. 

There is one known error causing flakiness in primarily the `ComplianceAuditlogTest` due to an issue described #3021 [1] which is being actively worked on by @DarshitChanpura.

As of writing, the top 3 PRs in the queue are failing with various different issues:

- https://github.com/opensearch-project/security/pull/3062 <- Not only the windows checks failing
- https://github.com/opensearch-project/security/pull/3061 <- Not only the windows checks failing

Getting to the root of CI issues and getting stable CI will help clear the PR queue from piling up

#### Related
- [1] https://github.com/opensearch-project/security/issues/3021

**Comment by peternied** [comment]
I've broken the windows wget install into a separate issue that I'll track down

**Comment by peternied** [comment]
I'm going to tackle `citest`

- @RyanL1997  could you look into the `ciSecurityIntegrationTest` tests
- @scrawfor99 could you look into the `dlicDlsflsTest` tests

**Comment by peternied** [comment]
Note; there are still these tests that are intermittently failing, please address them in # of failure order after addressing the consistent failures

| Row Labels                                                                                                    | Count of Failed Test |
| ------------------------------------------------------------------------------------------------------------- | -------------------- |
| ciSecurityIntegrationTest                                                                                     | -                    |
| org.opensearch.security.IntegrationTests.testDeleteByQueryDnfof                                               | 1                    |
| org.opensearch.security.HttpIntegrationTests.testBulk                                                         | 1                    |
| org.opensearch.security.SlowIntegrationTests.testDelayInSecurityIndexInitialization                           | 1                    |
| org.opensearch.security.HttpIntegrationTests.testHTTPBasic                                                    | 1                    |
| org.opensearch.security.TransportUserInjectorIntegTest.testSecurityUserInjection                              | 1                    |
| org.opensearch.security.SystemIntegratorsTests.testInjectedAdminUser                                          | 1                    |
| org.opensearch.security.HttpIntegrationTests.testTenantInfo                                                   | 3                    |
| citest                                                                                                        | -                    |
| org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testWriteHistory                           | 1                    |
| org.opensearch.security.auditlog.compliance.RestApiComplianceAuditlogTest.testAutoInit                        | 1                    |
| org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testUpdate                                 | 1                    |
| org.opensearch.security.util.SettingsBasedSSLConfiguratorV4Test.testPemClientAuth                             | 1                    |
| org.opensearch.security.multitenancy.test.MultitenancyTests.testMtMulti                                       | 1                    |
| com.amazon.dlic.auth.http.jwt.keybyoidc.SingleKeyHTTPJwtKeyByOpenIdConnectAuthenticatorTest.mismatchedAlgTest | 1                    |
| org.opensearch.security.SecurityAdminTests.testSecurityAdminHostnameVerificationNotEnforced                   | 1                    |
| org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testComplianceEnable                       | 2                    |
| dlicDlsflsTest                                                                                                | -                    |
| org.opensearch.security.dlic.dlsfls.CCReplicationTest.testReplication                                         | 1                    |

**Comment by scrawfor99** [comment]
Issue is not from the REST API change.

**Comment by cwperks** [comment]
I believe these test failures are a result of the Lucene upgrade in core: https://github.com/opensearch-project/OpenSearch/pull/8668

Some audit log events are working like access granted or access denied, but its failing to log document read events. 

Looking into this further now.

**Comment by reta** [comment]
Thanks @cwperks , looking into it!

**Comment by peternied** [comment]
We are seeing issues in DLS/FLS & Audit logging because the way we detect field access is through the DlsFlsFilterLeafReader which looks like no longer works in the same with the most recent version of lucene.  This class is used to notify the audit logging systems after a document read has been completed so it can save the document get audit event and it should be of little surprise that the DLS/FLS systems depend on knowing what fields were accessed.

This is what is impacting all of the different classes of tests that are consistently failing [[comment]](https://github.com/opensearch-project/security/issues/3064#issuecomment-1656085299) - same root cause.  Intermittent tests still need consideration.

---

Pretty sure the underlying reason is coming from changes to IndexReader [[link]](https://lucene.apache.org/core/9_7_0/core/org/apache/lucene/index/IndexReader.html#method.summary) `document(...)` methods have been marked as deprecated.  We will need to use the alternative paths / adapt for them.


```java
  /**
   * Expert: visits the fields of a stored document, for custom processing/loading of each field. If
   * you simply want to load all fields, use {@link #document(int)}. If you want to load a subset,
   * use {@link DocumentStoredFieldVisitor}.
   *
   * @deprecated use {@link #storedFields()} to retrieve one or more documents
   */
  @Deprecated
  public abstract void document(int docID, StoredFieldVisitor visitor) throws IOException;
```

**Comment by peternied** [comment]
Haha- well @cwperks you beat me to it. I say that is definitely what is going on.

**Comment by reta** [comment]
@cwperks thanks a lot for the investigation, are you looking into the fix or you need a hand there? (I started to look but haven't yet reached the cause and/or solution), thank you

**Comment by cwperks** [comment]
Hey @reta , I just opened up a draft PR a second ago: https://github.com/opensearch-project/security/pull/3069

It was a Lucene-related change that broke the build, but it wasn't the upgrade to 9.8 that broke the security plugin's build. It was this PR: https://github.com/opensearch-project/OpenSearch/pull/7792
