### ISSUE TITLE
[BUG] Restoring snapshot from GUI gives error

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/security#3067]
**What is the bug?**
Restoring snapshots from the GUI does not work, although the user has the admin backend role the restore fails. From the feedback sessions I did for the project I understand you like to see the user interact with the systems. 

So I made a video, download (25MB, Github max 10MB): https://bitwarden.ict-one.nl/#/send/XIdOiapVSE2vRUtHarmYMQ/I621D0fAXQ5EIcvRTOZ6ug

The video details how we do a disaster recovery of an on prem cluster hosted in Kubernetes. The only solution is to use the admin certificate and do it through the API's, which I did from some python scripts. But this renders the new fancy GUI useless for restores which is a shame. It's nice. 

We encountered this before, I was under the impression this would be fixed already.

**How can one reproduce the bug?**
See vid

**What is the expected behavior?**
Snapshot restore begins

**What is your host/environment?**
Opensearch / Dashboards 2.8.0 docker containers with azure repo plugin installed

**Do you have any screenshots?**
See vid

**Do you have any additional context?**
Add any other context about the problem.

**Comment by scrawfor99** [comment]
[Triage] Hi @ict-one-nl, I am not currently able to open the video link. Would you be able to provide additional written steps for reproducing the issue? In particular, I would be curious about the inclusion/exclusion of the security index. Thank you always. Miss you at these meetings :)

**Comment by ict-one-nl** [comment]
Hi Stephen, I was late at home, couldn't join :) And damn you're right, in my scripts I exclude it in the call to opensearch. Used the GUI this time and that's where I forgot. Maybe the exclusion of the security index should be default in the GUI to make the restore process more seamless and add an option in the advanced section to do it anyway.

Would make it more user friendly?

**Comment by scrawfor99** [comment]
Closing this issue since @ict-one-nl is opening a front end one.
