### ISSUE TITLE
Resolved class getAliases() are not covered by tests

### ISSUE THREAD

**Issue by DmitryOlshansky** [opensearch-project/security#307]
Accidentally found during re-write of said functionality by mistakenly putting patterns instead of actual aliases into the respective set:

https://github.com/opendistro-for-elasticsearch/security/pull/258

There is exactly one place of use for it btw, maybe it's time to drop it altogether?

**Comment by nateynateynate** [comment]
Hi @DmitryOlshansky, 

OpenDistro has since been superseded by OpenSearch. Do you mind pulling latest and checking again?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
