### ISSUE TITLE
[Enhancement][opensearch][opensearch-dashboards] Request for better documentation on setting initial passwords.

### ISSUE THREAD

**Issue by leynebe** [opensearch-project/security#3086]
**Is your feature request related to a problem? Please describe.**
It has been very confusing and time consuming trying to understand and trying to get to work a way to set the initial passwords using both charts. I have not been successful. Coming from working with an elasticsearch image I am simply able to set the password using an environment variable (which I naively expected to also be the case with Opensearch).

As I understand it, the Opensearch API security plugin can be enabled with the following config:
```
securityConfig:
  enabled: true
  ...
```
This sets the default username and password to admin. To further customize these I think I have to edit values under `securityConfig` but these are not explained in the README.md and no links to documentation is given. 

For opensearch dashboard I found the following snippet:
```
opensearchAccount:
  secret: ""
  keyPassphrase:
    enabled: false
```
However, I have found no explanation of this key `opensearchAccount` in the table under the README.md's configuration (https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch-dashboards/README.md#configuration).

I THINK I have to set the keys username and password in a secret and link it via the code, but this simply sets OPENSEARCH_USERNAME and OPENSEARCH_PASSWORD. Are these specifically credentials for the opensearch dashboard or does it also change the user for the opensearch api?

**Describe the solution you'd like**
Better explanation for initial username+password settings.
Better documentation on various values parameters related to this. Specifically the various parameters under `securityConfig` for opensearch and `opensearchAccount` for opensearch dashboards.

**Describe alternatives you've considered**
To be honest this is really pushing me to just use elasticsearch.

**Additional context**
/

Thanks.

**Comment by peternied** [comment]
[Triage] Can we get a pointer to the setup guide that could help @leynebe to get unblocked for this scenario?

**Comment by leynebe** [comment]
@peternied I should say I switched to elasticsearch for my problem. But the link could help others.

**Comment by peternied** [comment]
@leynebe Thanks for taking the time to file and issue and follow up - even if it didn't work out.

**Comment by pawelw1** [comment]
@leynebe If you decide to use OpenSearch helm charts, please open a thread in the security category of the [OpenSearch forum](https://forum.opensearch.org/c/security/3) for security-related issues.

**Comment by scrawfor99** [comment]
[Triage] Going to close this issue, since there are changes that have added explicit documentation to the website and UI changes in the security dashboards repo that create a visual indicator of password strength.
