### ISSUE TITLE
[BUG] Document GET API is broken for DLS queries that need call to rewrite before createWeight

### ISSUE THREAD

**Issue by msfroh** [opensearch-project/security#3088]
**What is the bug?**
Recent changes to the Lucene `TermInSetQuery` removed the `createWeight` method, which breaks the GET document API in the presence of a DLS query that use `terms`. The underlying issue is that DlsGetEvaluator calls `createWeight` without calling `rewrite`.

**How can one reproduce the bug?**
1. Create a DLS query based on `terms` like `{ "terms": { "foo" : ["bar"] } }`
2. Add some documents to an index.
3. Issue a GET document call like `GET <index>/_doc/5`
4. Receive an error message like `Query XXX does not implement createWeight`

**What is the expected behavior?**
The GET document call should succeed and return the relevant document if allowed by the DLS query (or not return it if not allowed by the DLS query).

The fix should be as simple as changing [this line](https://github.com/opensearch-project/security/blob/5384272a63771433905ae409de794786d5747cba/src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java#L235C31-L235C31) to say:

```
final Weight preserveWeight = searcher.createWeight(dlsQuery.rewrite(searcher), ScoreMode.COMPLETE_NO_SCORES, 1f);
```

While this probably broke for `terms` queries as a direct result of [this commit](https://github.com/apache/lucene/commit/3809106602a9675f4fd217b1090af4505d4ec2a7), it may have previously been broken for other MultiTermQuery subclasses. In general, Lucene assumes that code paths that call `createWeight` call `rewrite` first.

**What is your host/environment?**
 - OS: N/A
 - Version: OpenSearch 2.8
 - Plugins: N/A

**Do you have any screenshots?**
Nope

**Do you have any additional context?**
* Lucene change that made `TermInSetQuery` extend `MultiTermQuery` and removed the `createWeight` method from the (non-rewritten) `Query` class: https://github.com/apache/lucene/commit/3809106602a9675f4fd217b1090af4505d4ec2a7
* Conversation from OpenSearch Slack that motivated this issue: https://opensearch.slack.com/archives/C0539F41Z5X/p1690714779140659
* Note that in that Slack thread, I suggested a workaround of replacing the DLS query with a small number of terms with a single `term` query if only a single term is being matches or a `bool` query with `should` clauses for the relevant terms, since that's what the `rewrite` method rewrites to anyway (if there are 16 or fewer terms).

**Comment by west117** [comment]
Thanks for raising this @msfroh
