### ISSUE TITLE
Give user default permissions to .kibana_*_$(user_name)*?

### ISSUE THREAD

**Issue by aetter** [opensearch-project/security#31]
Hi team,

While investigating https://github.com/opendistro/for-elasticsearch-docs/issues/45, the question came up as to whether or not a user should have some default permissions to the `.kibana_*_<user-name>*` index that gets created when they log in.

Currently, users can log into Kibana the moment they get an account, but after logging in, they can't even create an index pattern due to this lack of permissions.

I'm not clear on whether there are any negative security tradeoffs to increasing the default permissions here, but it seemed like a reasonable conversation to have. Let me know what you think.

@elfisher @hardik-k-shah @shivdoshi

**Comment by elfisher** [comment]
@aetter this is interesting. Are you thinking this basically ensures the user has access to their own tenant? Are you thinking of a seperate role or combining this with the kibana_user role?

**Comment by aetter** [comment]
Hi @eli, I was actually thinking about combining it with the `own_user` role (which gets mapped to `*` in the default configuration).

**Comment by scf0920** [comment]
@aetter  Hi, how is this problem?  
And I found a new problem... I created a new account called `aaa_bbb`, its corresponding kibana index is `.kibana_-xxxxxxxxx_aaabbb`. This happens even if I give it `.kibana_*_$(user_name)*` permission...beacause `aaabbb` != `aaa_bbb`...

**Comment by aetter** [comment]
Hi @scf0920, no changes on our end. If that's the case and we can't reliably refer to the name of the index using the variable, we likely want to keep the current behavior.

Maybe the better option is to display a message or banner in Kibana if the user has no permissions to do anything. @elfisher, do you have thoughts here? It's a little unfortunate to let people into Kibana and present them with a UI that they can't do anything with.

**Comment by elfisher** [comment]
@aetter maybe we render a specific screen that says "no permissions configured" or something. @stevensideyliu thoughts?

**Comment by scf0920** [comment]
@aetter @elfisher  I think this is a bug..
The same as the https://github.com/opendistro/for-elasticsearch-docs/issues/45, before the restart kibana, the `someone` has permission to search `.kibana_xxxxxxxxx_someone`, of course can also be configured `index pattern`.
![image](https://user-images.githubusercontent.com/16220813/57899706-9b70de80-7890-11e9-9163-f1205b718933.png)

But after the restart kibana, its corresponding kibana index has been migrated:
![image](https://user-images.githubusercontent.com/16220813/57899800-f86c9480-7890-11e9-842a-28c176a3e702.png)
![image](https://user-images.githubusercontent.com/16220813/57899861-3a95d600-7891-11e9-99ac-3724d97f7335.png)

And this time we can't search `.kibana_xxxxxxxxx_someone`.
![image](https://user-images.githubusercontent.com/16220813/57899772-df63e380-7890-11e9-9819-f441ed98ee07.png)

The whole process includes only a restart. I think it should not lead to lost the `.kibana_xxxxxxxxx_someone` permission.

Thanks.

**Comment by scf0920** [comment]
ping  @aetter  @elfisher

**Comment by aetter** [comment]
Hi @scf0920, I'm able to reproduce the migration of `.kibana_-2029640462_someone` to `.kibana_-2029640462_someone_1` and `.kibana_-2029640462_someone_2`, but `.kibana_-2029640462_someone_2` gets aliased to `.kibana_-2029640462_someone`, just like in your screenshot.

So as long as `someone` has permissions to `.kibana_-2029640462_someone` (or `?kibana_*_${user_name}`, I'm able to run searches on it before/after the restart.

I'm concerned that we're still not fully understanding your issue, so please let me know if I'm just not getting it. Thanks a bunch for being so patient.

![someone](https://user-images.githubusercontent.com/9122297/58128088-b2366e80-7bcb-11e9-96b6-65ae0c4f3889.png)

![someone-role](https://user-images.githubusercontent.com/9122297/58128093-b498c880-7bcb-11e9-9485-66c9cc13ffa9.png)

**Comment by scf0920** [comment]
@aetter  sorry..I said a little leakage and maybe my English is not good...
I mean without the permission `?kibana_*_${user_name}`, I'm not able to search after restart.
 
But the same does not have this permission, it can be searched before restarting.

I think there would have been the permission, after the restart, the `?kibana_*_${user_name}` has been lost. 
The whole process includes only a restart. I think it should not lead to lost the `.kibana_xxxxxxxxx_someone` permission. So I think this a bug, not you said that the increase of the tip.
And if solved the bug,  the new problem (new account `aaa_bbb`)will be readily solved.

I can solve the previous problem manually, but I can't solve the new problem manually, and I have the requirement with "_" in the name.

Thanks.

**Comment by aetter** [comment]
Hi @scf0920, unfortunately, I don't think we're making any progress on trying to reproduce your issue. Can you provide comprehensive, start-to-finish steps with the expected behavior and the actual behavior? I know it's tedious, but I think we need something very thorough to figure out what's going on, something like:

```
1. Save the following Docker Compose file to disk:

   some file

1. `docker-compose up`
1. Open Kibana
1. Click **Management**
1. Create an index pattern
1. `docker-compose down`
1. `docker-compose up`
1. Open Kibana
1. Click **Dev Tools**

Expected: the Management tab displays.
Actual: The following error message displays: asdf
```

**Comment by nateynateynate** [comment]
Hi @scf0920 !

I realize it's been a while, but can you confirm that the main issue reported (https://github.com/opensearch-project/security/issues/31#issue-432642972) is still hindering you in the latest OpenSearch? If so, any additional information would be helpful, such as the reproduction steps @aetter asked for above. 

Thanks!
