### ISSUE TITLE
[Documentation] Setup guide for extensions covers the risks associated with allowing OBO access

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security#3100]
### Description 
This issue can be seen as a placeholder for discussing the possible risks involved in granting OBO access to extensions. Once the discussion has reached a satisfactory point, the content from this issue can serve as a reference when drafting the documentation.

**Comment by davidlago** [comment]
Let's define what the work is here, whether this is the whole guide, what that guide is, etc.

**Comment by peternied** [comment]
[Triage] @RyanL1997 Could you please add concrete outcomes for this issue?

**Comment by RyanL1997** [comment]
We can close this due to the tracking of #3290
