### ISSUE TITLE
Add test that confirms when Rest and Transport authorization checks overlap

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3112]
Coming from https://github.com/opensearch-project/security/issues/2867, want to confirm that REST authorization and Transport authorization are both checked when there is an overlap which is expected during migration scenarios.

### Exit Criteria
- [ ] Add a test that confirms when REST is authorized and Transport is unauthorized
- [ ] Add a test that confirms when REST is authorized and Transport is authorized
- [ ] Add a test that confirms when REST is unauthorized and Transport is unauthorized
- [ ] Add a test that confirms when REST is unauthorized and Transport is authorized

**Comment by DarshitChanpura** [comment]
>Add a test that confirms when REST is authorized and Transport is unauthorized

This case was verified via [this test](https://github.com/opensearch-project/security/blob/6cc90e655ec4209f7a3c30c4684af03cfc5a4b5a/src/integrationTest/java/org/opensearch/security/rest/WhoAmITests.java#L128). This test checks for legacy vs new implementation.

>Add a test that confirms when REST is authorized and Transport is authorized

This case was verified via [this test](https://github.com/opensearch-project/security/blob/6cc90e655ec4209f7a3c30c4684af03cfc5a4b5a/src/integrationTest/java/org/opensearch/security/rest/WhoAmITests.java#L74) 

>Add a test that confirms when REST is unauthorized and Transport is unauthorized

Request will never reach Transport Layer, if they are unauthorized at REST layer. This case was verified via [this test](https://github.com/opensearch-project/security/blob/6cc90e655ec4209f7a3c30c4684af03cfc5a4b5a/src/integrationTest/java/org/opensearch/security/rest/WhoAmITests.java#L128)
 
>Add a test that confirms when REST is unauthorized and Transport is authorized

Request will never reach Transport Layer, if they are unauthorized at REST layer. And so this scenario will never exist, and a test cannot be implemented for this.


Current design suggests that all new named routes have an option to support legacy action names which were originally evaluated at TransportLayer via PrivilegesEvaluator. I'll be more than happy to modify existing tests with any additional details as required.

**Comment by peternied** [comment]
These scenarios are not correct , the whoami API is implemented as a Rest handler action - not a transport action.  We need to be sure that overlapping functionality between different actions is still handled as expected.

**Comment by peternied** [comment]
Here is some pseudo code of what I think this test could look like, we will need to register some plugins that exist only during the test scenario to go through the registration process and test invariants in this scenario.

```
public void testOverlappingAuthz() {
   // Setup plugin with transport layer action, named: `Foo`
   // Setup plugin with a rest handler also has legacyName: `Foo`, and has name `NewFoo` calls transport action Foo
   // Setup user1 with role mapping that links to role with permission for `NewFoo`

   // Make request as user1 against rest endpoint for NewFoo
   ... 
   // Setup user with role mapping that links to role with permission for `Foo`   

   // Make request as user1 against rest endpoint for NewFoo
}

**Comment by scrawfor99** [comment]
[Triage] Thanks for filing this issue @peternied. At this time, it looks like this issue is actionable. Going to label this as triaged.

**Comment by DarshitChanpura** [comment]
Closing as these tests will be covered by #3226 under #2928
