### ISSUE TITLE
[BUG] Unexpected Coverage Changes on SelfRefreshingKeySet, SecurityInterceptor and SecuritySSLNettyTransport

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3137]
**What is the bug?**
There are several classes that are seeing random behavior in code coverage reports.  Test should be added/modified to ensure these code paths are always exercised - keeping codecov results useful.

- [x] src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/SelfRefreshingKeySet.java
  - Has tests to attempt race conditions, might need to alter the class and tests to be able to exercise the 'races' guaranteed
- [x] src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
  - Needs a tweak, or additional unit test to confirm a local node vs remote node scenario
- [x] src/main/java/org/opensearch/security/ssl/transport/SecuritySSLNettyTransport.java
  - Needs unit tests
- [x] src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
  - Needs unit tests that exercise exceptions around ClusterHealthRequest
  
![image](https://github.com/opensearch-project/security/assets/2754967/dcae6001-32ad-4ba7-90b8-e06a22af1f5e)

Codecov [[Report link]](https://app.codecov.io/gh/opensearch-project/security/pull/3133/indirect-changes)
Codecov [[Unexpected Coverage Changes]](https://docs.codecov.com/docs/unexpected-coverage-changes)

**How can one reproduce the bug?**
1. Create a pull request that only changes markdown file
2. Look at the checks for the pull requset
3. See the codecov check
4. See error that coverage has dropped .0X%

**What is the expected behavior?**
Code coverage should not fluctuate, testing should be deterministic and 'exhaustive' 

**Do you have any additional context?**
This is causing code coverage failures on many pull requests and code is being merged without all checks passing regularly.

**Comment by scrawfor99** [comment]
[Triage] Thank you for filing this issue @peternied. Based on the provided checklist, I will label this issue as actionable and triaged.

**Comment by davidosorno** [comment]
@peternied I Started looking into it. Please let me know if you have any useful information that I can use to address this.

**Comment by peternied** [comment]
@davidosorno I'm excited to see these get fixed, In the descriptions 'checklist' is most of my thoughts - we can dig in more with a pull request - I'd recommend to create a draft, happy to review if you've got questions.

**Comment by scrawfor99** [comment]
The second and third check boxes should be all set shortly.
