### ISSUE TITLE
Make FLS, DLS and Field Masking Unit Tests more extensive by testing more document retrieval APIs

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3139]
There was an [issue filed recently](https://github.com/opensearch-project/security/issues/3088) where a user in the public slack mentioned that document retrieval was broken for a user that was mapped to a role with a DLS terms query. This bug revealed a gap in testing where our current [DlsTest Suite](https://github.com/opensearch-project/security/blob/main/src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java) did not cover this scenario so it was not caught during CI. 

I'm filing an issue to track what the current Test Suite covers and identify opportunities to make the FLS, DLS and Field Masking tests more extensive. 

Ideally, all permutations of DLS queries and document retrieval actions have a test.

[ ] Identify all OpenSearch actions that retrieve documents from an index or set of indices
[ ] Write a test for the action with a user that has a role with DLS restrictions containing a `bool` query
[ ] Write a test for the action with a user that has a role with DLS restrictions containing a `terms` query
[ ] Write a test for the action with a user that has a role with FLS restrictions
[ ] Write a test for the action with a user that has a role with Field Masking restrictions

**Comment by scrawfor99** [comment]
[Triage] Thanks @cwperks for filing this issue. The first item required will be identifying the gaps in testing and then addressing those gaps.

**Comment by peternied** [comment]
[Triage] @cwperks could you add exit criteria for this item?  I think this would be a good candidate for a good first issue if we had the extra information around it.

**Comment by scrawfor99** [comment]
[Triage] Hi @cwperks, thank you for updating the exit criteria. Looks good!
