### ISSUE TITLE
Look into opensearch-keystore

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3140]
### Description
There is a tool that is part of the OpenSearch distribution `opensearch-keystore`.  Seems like there might be overlapping functionality with the security plugin.

### Exit Criteria
- [ ] Discovery how the keystore is actively used today, might need to search for usage / documentation around `elasticsearch-keystore` name.
- [ ] Determine if/what scenarios overlap with security plugin functionality
- [ ] Provide a recommendation on further investigation or features.

### Do you have any additional context?**
- Source code https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/settings/KeyStoreWrapper.java
- CLI source code https://github.com/opensearch-project/OpenSearch/tree/main/distribution/tools/keystore-cli

**Comment by scrawfor99** [comment]
[Triage] Thank you @peternied for this very clear issue.

**Comment by willyborankin** [comment]
@peternied OpenSearch's keystore widely use in plugins. I know such plugins:
- all snapshot repositories use it to store 3rd party system credential information
- alerting plugin uses it to store email server creds

We can use it to store PEM private keys, JSK passwords and additional sensitive information we use in the plugin. The reason why it wasn't added I think the fact that OpenSearch's keystore prior ES7 couldn't store files.

**Comment by peternied** [comment]
Seeing discussion/limitations around the keystore [1] - maybe there are good cases to expand how the tool works in a distributed way

- [1] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4797#issuecomment-1696563724

**Comment by willyborankin** [comment]
@peternied yes I was thinking about moving keystore to the security plugin. Since it is sec plugin responsibility in the end.

**Comment by cwperks** [comment]
Opster has a really good article on the keystore here: https://opster.com/guides/opensearch/opensearch-security/opensearch-keystore/

Some highlights:

1. To add a secret to the keystore:

``` 
./bin/opensearch-keystore add plugins.security.ssl.http.pemkey_password_secure
> Enter secret when prompted
```

2. List values stored in the keystore

```
./bin/opensearch-keystore list
```

3. Configure `opensearch.yml` using a value stored in the keystore:

```
> opensearch.yml

plugins.security.ssl.http.pemkey_password_secure: ${plugins.security.ssl.http.pemkey_password_secure}
```

I'm not sure if its possible to reference keystore secrets in the security plugin's `config.yml`, but if it is then that could provide a good solution to this feature request: https://github.com/opensearch-project/OpenSearch/issues/12033

I cannot find a page on the opensearch documentation website with documentation on the keystore. I think a page should be added to the documentation website describing the usage of the keystore.

**Comment by dblock** [comment]
People do ask for features for it, https://github.com/opensearch-project/OpenSearch/issues/13387.

**Comment by peternied** [comment]
@cwperks Based on the research that you've done I feel like we could close out this issue or are there other follow up tasks that should be created to capture the direction you'd plan for this tool?

**Comment by peternied** [comment]
Lets start a new issue - the investigation is over :D
