### ISSUE TITLE
OnBehalfOf tokens internal security review process + App Sec signoff

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3162]
This item is tracking that the security review for OnBehalfOf tokens is in progress and not yet completed.  The feature should not be released until this has been completed.

See [RELEASING.md#security-reviews](https://github.com/opensearch-project/.github/blob/1dfeeed40b71518f00221057c3046297ef8ac5ea/RELEASING.md#security-reviews) for information about this process.

**Comment by scrawfor99** [comment]
[Triage] This is an issue tracking the security review status of the OnBehalfOf token changes. To be closed when review is complete.

**Comment by peternied** [comment]
This security review process has been completed, this feature is approved to release.
