### ISSUE TITLE
Issue and ferry a Service Account Token to an Extension on bootstrap

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3176]
As part of [[META] System Indices access for Extensions](https://github.com/opensearch-project/security/issues/2529), the plan is for an extension that reserves indices to receive a token on bootstrap that the extension can utilize to interact with its reserved indices. This token will be referred to as a Service Account Token because it represents the identity of the extension and can be used by the extension to act as itself when making requests on the extension's reserved indices.

I'm filing an issue to track the work to create an interface within the [`IdentityPlugin` extension point](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/plugins/IdentityPlugin.java) of core that can be used to trigger the security plugin's implementation of issuing a service account token. After issuance, the token also needs to be ferried to an extension.

I see 2 possible options for ferrying this token to an extension:

1. As part of the [`InitializeExtensionRequest`](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/extensions/ExtensionsManager.java#L398-L407) which is initiated from core and used to initialize an extension. The handler on the SDK side can be found [here](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java#L48-L96).

2. As a separate Transport action that is sent after successful initialization. I recommend this option. 

You can see a sample implementation of a separate transport action for ferrying service account tokens in [here](https://github.com/cwperks/OpenSearch/pull/94/files#diff-c9a4accc046eb92a0e6a025970b3eacacc330f40bb55b02859df05a79710c8c8R416). (There's an open PR on the SDK repo to address token handling on the SDK side that provided implementations of ferrying a service account token and obo token: https://github.com/opensearch-project/opensearch-sdk-java/pull/892)

Sending this as a separate Transport Request potentially allows the transport action to be re-used for token rotation, whereas an initialization request is only meant to be performed once. 

Acceptance Criteria:

- [x]  Define an interface in core on the IdentityPlugin that can be called to issue a service account token given an extension's unique ID.
- [x] Create a new TransportAction that runs after successful InitializeExtensionRequest to issue and ferry the service account token to an extension
- [ ] Implement the interface in the Security plugin

Future followup:
- [ ] Update https://github.com/opensearch-project/opensearch-sdk-java/pull/892 to consume the TransportAction and initialize the `extensionRestClient` on the SDK side

**Comment by scrawfor99** [comment]
[Triage] Thanks for filing this issue @cwperks. Please add an additional note about what is required for closing.

**Comment by scrawfor99** [comment]
[Triage] Hi @cwperks, thanks for adding the action items. This looks like it is clear defined so marking as triaged.

**Comment by scrawfor99** [comment]
Still waiting on review in core. Left comment asking for review.

**Comment by scrawfor99** [comment]
Still waiting.

**Comment by scrawfor99** [comment]
Still waiting.

**Comment by peternied** [comment]
Adding this back to make sure that we check off all the acceptance criteria are complete

**Comment by peternied** [comment]
@scrawfor99 If you have any pointers/POCs for how this could be done that would be useful to add to this item
