### ISSUE TITLE
Reenable gradle build cache

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3185]
The gradle build cache is used between github actions to speed up build times, but if the wrong cache sources are being used this can result in unexpected failures that are hard to troubleshoot.

We are disabling the remote gradle cache to while stabilizing the build infrastructure.  We should revisit what the impact of not having this cache.

Task 1: Determine the best path forward for re-enabling the build cache. Should we re-instate it the same way or in a different way? 
Task 2: Re-enable cache in best way.

**Comment by peternied** [comment]
With the cache disabled we will see more failures due to intermittent network issues when downloading dependencies.  It might be a good idea to support at least for some level of dependencies

```
Cache is disabled: will not restore state from previous builds.
C:\Windows\system32\cmd.exe /D /S /C "D:\a\security\security\gradlew.bat ciSecurityIntegrationTest "-Dbuild.snapshot=false" -x test"
Downloading https://services.gradle.org/distributions/gradle-8.2.1-bin.zip

Error: Exception in thread "main" javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1719)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1518)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
```
Source https://github.com/opensearch-project/security/actions/runs/5883917137/job/15957604175?pr=3196

**Comment by peternied** [comment]
Looks like downloading the gradle distro got interrupted and failed a run
https://github.com/opensearch-project/security/actions/runs/5907712274/job/16026096868?pr=3196

```
C:\Windows\system32\cmd.exe /D /S /C "D:\a\security\security\gradlew.bat ciSecurityIntegrationTest "-Dbuild.snapshot=false""
Downloading https://services.gradle.org/distributions/gradle-8.2.1-bin.zip

Error: Exception in thread "main" java.net.SocketException: An established connection was aborted by the software in your host machine
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:425)
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:445)
```

**Comment by DarshitChanpura** [comment]
Seems like this is a good solution for enabling gradle build cache: https://github.com/marketplace/actions/gradle-cache

i will raise a PR soon.

**Comment by DarshitChanpura** [comment]
Closing this as CI is pretty fast without enabling cache. ([comment](https://github.com/opensearch-project/security/pull/3546#issuecomment-1792634163))

**Comment by DarshitChanpura** [comment]
Feel free to re-open if this still needs to be addressed
