### ISSUE TITLE
Backport integration tests to 2.x

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3188]
Stemming from discussion on https://github.com/opensearch-project/security/pull/3182, the codeql check is failing with:

> Task :compileIntegrationTestJava FAILED

https://github.com/opensearch-project/security/actions/runs/5870600207/job/15918932614?pr=3182

The integrationTest framework was introduced in a series of PRs into main and was intentionally not backported to 2.x[link to discussion]. No support for the [integrationTest package](https://github.com/opensearch-project/security/tree/main/src/integrationTest) exists on 2.x and no gradle task related to the integrationTest package should works on 2.x. We should backport these changes. 

Task: Backport changes associated with the linked PR.

**Comment by scrawfor99** [comment]
[Triage] Hi @cwperks, thank you for pointing this out. For the time being, it seems like the actionable task is going to be adding the integration tests to the 2.x line.

**Comment by cwperks** [comment]
Closing this issue as a duplicate. https://github.com/opensearch-project/security/issues/3230 has more details on which PRs need to be backported.
