### ISSUE TITLE
Service Accounts internal security review process

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3199]
This item is tracking that the security review for Service Account is in progress and not yet completed. The feature should not be released until this has been completed.

See [RELEASING.md#security-reviews](https://github.com/opensearch-project/.github/blob/1dfeeed40b71518f00221057c3046297ef8ac5ea/RELEASING.md#security-reviews) for information about this process.

**Comment by scrawfor99** [comment]
[Triage] Acknowledging this issue with closure being contingent on completion of the review.

**Comment by peternied** [comment]
This security review process has been completed, this feature is approved to release.
