### ISSUE TITLE
[Feature/Extension] Add integration test case to that ip based role mapping are not part of OBO authentication tokens

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security#3222]
**Is your feature request related to a problem?**
In issue #3000 with PR #3161, we decided to not consider IP-based rolemapping into the scope of OBO authentication. According to this, we should have an integration test case to capture this design.

**What solution would you like?**
A potential place to implement this is at the existed integration tests suite of OBO auth ([source code](https://github.com/opensearch-project/security/blob/feature/extensions/src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java))

**Good state for closing this issue**
This test case should specifically assess whether the OBO auth remains unaffected by host mappings, particularly IP-based roles mapping. After setting up the test environment, we can issue a token and evaluate its functionality, ensuring it operates independently of any preceding host mapping configurations.

**Comment by scrawfor99** [comment]
[Triage] Hi @RyanL1997, thank you for filing this issue. This item appears actionable with the completion criteria being a PR which adds an IT to confirm Ip-based roles are not passed in OBO tokens.
