### ISSUE TITLE
[Refactor] Refactor BWC to remove internal project nesting

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#3233]
**Is your feature request related to a problem?**
The current structure of the Security plugin makes use of a second set of gradle files used to control the /bwc sub-project. Specifically, we have gradle wrapper files, settings.gradle, gradlew, and gradlew.bat inside the bwc/ directory. This is a form of code bloat that I do not believe is necessary. We should be able to remove the internal project and just include the `build.gradle` file that defines the tasks for running the bwc tests.  

**What solution would you like?**
I would like to refactor the code to move the BWC tests into the /src path as a module alongside the integrationTest dir. 

**What alternatives have you considered?**
We can leave it as is but again, this is a form of code bloat and there does not seem to be any reason to have the internal project.

**Comment by peternied** [comment]
I don't have a problem with modifying the project structure - so long as we do it separate from any other changes.  I know there is a lot of fast and loose changes to try to get the BWC tests back into shape, after we are back to a known good so pull requests reviews are easier I'd be happy to wade through a refactor on this codebase.

**Comment by peternied** [comment]
Fixed in https://github.com/opensearch-project/security/pull/3642
