### ISSUE TITLE
[Maintenance] Compare differences between feature/extensions branch and main 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#3234]
**What is the bug?**
Following completion of https://github.com/opensearch-project/security/issues/2945, we will need to confirm that all desired features are migrated from the feature/extensions branch into the the main branch. Because the merge to main is not a "true" merge but instead a selected PR including many of the features, we want to make sure we did not miss anything. 

Specifically, we will certainly need to move both the distinguished names and elliptic curve changes from the feature branch. Additional features we want to move over may also exist. 

In order to resolve this issue:

- [ ] Compare the differences between main and feature/extensions 
- [ ] Create a list of the features present in the feature branch but not main
- [ ] Determine which of these should be ported over
- [ ] Complete the migration of the final features 

Once all these tasks are resolved, this issue can be closed.

**Comment by peternied** [comment]
Issue https://github.com/opensearch-project/security/issues/3235 will address
