### ISSUE TITLE
[Enhancement] Set up a Util class for OBO Authenticator for key checks and endpoints checks

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security#3238]
## Description
Transferring some of the discussion from [here](https://github.com/opensearch-project/security/pull/3179#discussion_r1302217243), it is reasonable to setup a public field in codebase to holding some of the common logic for OBO authentication, such as the configuration checks.

## Related issue/PR

* Related #2573 
* Relate https://github.com/opensearch-project/security/pull/3179 (need the merge of this)

## Potential solutions

**Potential place 1: ~/security/src/test/java/org/opensearch/security/authtoken**
- reason: it is related to the OnBehalfOf feature, so that we can setup an util class in here.

**Potential place 2: ~/security/src/main/java/org/opensearch/security/util
- reason: Just like its name it is the util directory. (Recommended)

## Exit Criteria
Set up the ultil class to place the reusable logic for checking endpoint calls, checking keys.

**Comment by scrawfor99** [comment]
[Triage] Hi @RyanL1997 following up on this for additional details. Thank you.

**Comment by peternied** [comment]
@peternied Can you do a quick review of this work
