### ISSUE TITLE
[Proposal] Enable resolve all comments before PR merge option

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3241]
_Recognizing @kotwanikunal who wrote up this policy recommendation for OpenSearch [1]_

### Is your feature request related to a problem? Please describe.
OpenSearch repo currently allows a PR to be merged without marking all the comments resolved. In case of multiple comments across commits, there can be comments from maintainers which might not be resolved.
Although contributors walk through the comments addressing them, in the interest of missing out any comments, we should enable the feature to marking all comments as resolved before merging in the PR.

### Describe the solution you'd like
Github provides the capability under branch protection policy within repository settings to prevent merges until all comments have been marked as resolved. This should be enabled for all branches within the repository.

### Additional Context 
This policy has been active in OpenSearch since May without being reverted.  

- [1] https://github.com/opensearch-project/OpenSearch/issues/6807

Example UX contributors and maintainers

#### Hint on mergeability pane
![image](https://github.com/opensearch-project/security/assets/2754967/bcf979e2-da1e-4398-967f-28b0be623a9b)

#### Unresolved conversations shortcuts
_Found by clicking View from above_
![image](https://github.com/opensearch-project/security/assets/2754967/ab3964ea-3e9d-4269-97e5-a4ba318dd322)

**Comment by peternied** [comment]
[Triage] Lets revisit this during the next triage meeting to capture the votes.  You can vote by adding a +1 / -1 or 👍 👎 on this issue.

**Comment by scrawfor99** [comment]
[Triage] Looks like this passed the vote, so we will go ahead and accept a change for this workflow. Going to mark as triaged and help wanted.
