### ISSUE TITLE
AuditLog: deprecate "NONE" in favor of "~" or "null"

### ISSUE THREAD

**Issue by vrozov** [opensearch-project/security#325]

**Comment by dbjnbnrj** [comment]
Mentioned in the earlier PRs as well. Prefer null.

**Comment by vrozov** [comment]
https://symfony.com/doc/current/components/yaml/yaml_format.html#nulls

**Comment by nateynateynate** [comment]
Looks like the merges have completed the requirements for this one. I'm going to close it out. Please feel free to reopen if this is in error.
