### ISSUE TITLE
UpdateRequest with DLS/FLS enabled

### ISSUE THREAD

**Issue by skleis** [opensearch-project/security#326]
When using opendistro-security with DLS and/or FLS enabled it is no longer possible to update documents, but the reasoning behind this decision is not clear.

I have a opendistro security setup with granular dls-permissions for reading multiple indices, while having separate roles for writing in these indices. If a user has both read and write access to an index it is no longer possible for him to use the _update API of Elasticsearch.

My plan is to remove this limitation from the relevant code but I am unsure if I create a serious security flaw with this.  I would greatly appreciate any further insight in this.

https://github.com/opendistro-for-elasticsearch/security/blob/a17bc7a8620f893cd33107a370b1a4cbc1954f55/src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/DlsFlsValveImpl.java#L70

**Comment by Anthony7774** [comment]
@skleis 
As I am not able to reproduce using opensearch 1.0.0, can you elaborate on which permissions does the user have which is trying to use _update API? Is this the user that is assigned role with dls and fls permissions/limitations?

**Comment by cliu123** [comment]
The issue is not reproducible. If you're having issue with one permission overwriting the other permission, you can upgrade to OpenSearch 2.0.0-rc1 when it's available use the new setting `plugins.security.dfm_empty_overrides_all` to overwrite how it works.
