### ISSUE TITLE
[Checkstyle] Checkstyle should check for * imports and refuse them, according to OpenSearch style guidelines

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security#3260]
**Is your feature request related to a problem?**
The repo currently allows for * imports, which goes against opensearch's style guidelines: 
https://github.com/opensearch-project/OpenSearch/blob/main/gradle/formatting.gradle#L89-L94
This should be changed to match the upstream.

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by willyborankin** [comment]
I noticed that it stopped checking the license header for new files.

**Comment by willyborankin** [comment]
I fixed it
