### ISSUE TITLE
[Tracking] Windows GHA failing with network issues often

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3266]
I've filed a ticket with GitHub about the failure rate associated with Windows runners and network issues.  Using this to provide visibility to the investigation / resolution.

### Additional context
- Disabling gradle cache might have made this worse by causing more time spend downloading files instead of getting them from cache https://github.com/opensearch-project/security/issues/3185
- PR to retry code coverage upload network failures https://github.com/opensearch-project/security/pull/3242

**Comment by scrawfor99** [comment]
[Triage] @peternied to add associated link form GitHub team working on investigating the issue. Marking as triaged since this is a tracking issue.

**Comment by peternied** [comment]
No failures on the first run [1], rerunning.

- [1] https://github.com/peternied/security/actions/runs/6226986894

**Comment by peternied** [comment]
Looks like there will be a modification to how GitHub runners operate - I'll update when this has completed. 

> We would like to update that engineering team is working towards fixing it. We will inform you as soon as the fix has been rolled out.

**Comment by peternied** [comment]
I've looked at our recent [run history](https://github.com/opensearch-project/security/actions/workflows/ci.yml?query=branch%3Amain) and I do not see any errors from the windows runner associated issues downloading dependencies via gradle or wget due to network issues.

Note; there was a couple of errors associated with flaky tests, but we will have to continue to iterate on them.
