### ISSUE TITLE
[SAML] Deprecate the legacy prefix of `_opendistro` in SAML flow

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security#3271]
**Description**
We should replace the SAML usage of legacy prefix `_opendistro` with `_plugin` at the next major version.

**How can one reproduce the bug?**
- [ ] `/_opendistro/_security/saml/acs` ([source code](https://github.com/opensearch-project/security/blob/0338cdd4ab701e6dfdbaaf49765300b1d6190aa0/src/main/java/com/amazon/dlic/auth/http/saml/Saml2SettingsProvider.java#L221-L228))
- [ ] `/_opendistro/_security/saml/logout` in [documentation of dashboards configuration](https://opensearch.org/docs/latest/security/authentication-backends/saml/#opensearch-dashboards-configuration)

**Exit Criteria**
Replace the above paths with new prefix at first slug - `_plugin`

**Do you have any additional context?**
A potential fix + migration of `/_opendistro/_security/saml/acs`:
- Step 1: Security frontend changes to support new ACS url: https://github.com/opensearch-project/security-dashboards-plugin/pull/1565
- Step 2: Security backend changes to register ACS url with new prefix: https://github.com/opensearch-project/security/pull/3246
- Step 3: Dashboard core change to modify the xsrf.allowList if the user input the legacy url : https://github.com/opensearch-project/OpenSearch-Dashboards/compare/main...RyanL1997:OpenSearch-Dashboards:xsrfallowlist-update

**Useful links**
1. Setting up ACS url in SAML: https://github.com/opensearch-project/security-dashboards-plugin/pull/1565#issuecomment-1698021702

**Comment by scrawfor99** [comment]
[Triage] Thank you @RyanL1997 for filing this issue. This is part of the overall work to remove the deprecated nomenclature from the next major version.

**Comment by cwperks** [comment]
Closing as a duplicate of https://github.com/opensearch-project/security/issues/2060
