### ISSUE TITLE
[BUG] Lots of waring message `No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'` in log

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/security#3273]
**What is the bug?**

When i enable both SAML and basic auth and login with SAML, there have lots of basic auth warning message 
`[2023-08-31T13:35:04,053][WARN ][o.o.s.h.HTTPBasicAuthenticator] [bcd07463160c] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'` printed in OpenSearch log file 

**How can one reproduce the bug?**

**What is the expected behavior?**
Don't print warning message or should this be debug level

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

![image](https://github.com/opensearch-project/security/assets/113890546/2e8e6588-9f2c-41b6-b567-aaad845d6c05)

enable both SAML and basic 
![image](https://github.com/opensearch-project/security/assets/113890546/e3eb7410-50fc-4b7e-bc2d-ab371b89c32f)

**Do you have any additional context?**
Add any other context about the problem.

**Comment by scrawfor99** [comment]
[Triage] Thank you for filing this issue. This message is a warning message that is expected when you run with the SAML endpoint configuration you are using. This is a response from not having a Basic auth header (you have none because you are using SAML). You can disregard this message. 

We can follow-up this issue by making a change so that this log is TRACE instead of WARNING level. Then you should not see this output.

**Comment by taltsafrirpx** [comment]
any update with a solution?

**Comment by Hailong-am** [comment]
> any update with a solution?

@taltsafrirpx the log level have changed to trace, so you should not see those warning by default.

**Comment by jkrishnarao2003** [comment]
We are using OpenSearch 2.10.0. We are seeing this log message hugely.  Which version this was fixed?

**Comment by Hailong-am** [comment]
https://github.com/opensearch-project/security/commit/d7d8472eeab0d0f497d89267bd1e7ec360c6f18c
should be 2.11.0
![image](https://github.com/opensearch-project/security/assets/113890546/4f9ba3a2-a526-4844-8122-0f2265545d66)

**Comment by SeemsLikeIt** [comment]
For information just migrated my cluster to 2.11.1 and got log as warning with SAMl configuration.
[2024-01-31T20:12:52,211][WARN ][o.o.s.h.HTTPBasicAuthenticator] [os1] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'

**Comment by sandervandegeijn** [comment]
It's probably the order of the backens that's playing a role here. We are going to switch those so openid comes first and see what happens.

**Comment by ComBin** [comment]
> It's probably the order of the backens that's playing a role here. We are going to switch those so openid comes first and see what happens.
In my case if i place SAML auth first it is breaks my basic auth.

Also i open new [issue](https://github.com/opensearch-project/security/issues/4054).
