### ISSUE TITLE
[BUG] Add a test to ensure that using PATCH API to update Roles Mappings works on a static role

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3276]
With the recent refactor of the security REST APIs introduced in https://github.com/opensearch-project/security/pull/3123 a regression was made that changed the behavior of how the PATCH API to update roles mappings worked.

Before the PR was merged the PATCH API was able to perform operations on `static` roles.

```
> curl -XPATCH https://admin:admin@localhost:9200/_plugins/_security/api/rolesmapping/all_access --insecure -H "Content-Type: application/json" --data '
[
        {
        "op": "remove",
        "path": "/users",
        "users": ["jwt_test"]
        }
]
'
{"status":"OK","message":"'all_access' updated."}
```

After the PR was merged the PATCH API started failing with the following error:

```
> curl -XPATCH https://admin:admin@localhost:9200/_plugins/_security/api/rolesmapping/all_access --insecure -H "Content-Type: application/json" --data '
[
        {
        "op": "remove",
        "path": "/users",
        "users": ["jwt_test"]
        }
]
'
{"status":"FORBIDDEN","message":"Resource 'all_access' is static."}
```

The reason this was not caught is because there currently is no unit test to assert the behavior of the PATCH API to update roles mappings on a static role. There should be a unit test to assert the intended behavior.

**Comment by peternied** [comment]
As described this is a functional test scenario, why do you think this should be a unit test?

**Comment by willyborankin** [comment]
@peternied We have such tests in `RolesMappingApiTest` but they cover only `hidden` roles verification not `reserved` and `statics` both for `PUT` and `PATCH` as result it is not clear from tests how it should work.

**Comment by scrawfor99** [comment]
[Triage] This PR: https://github.com/opensearch-project/security/pull/3278, resolved this issue so going to close.
