### ISSUE TITLE
Replace `admin:admin` default credentials with environment variable password 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#3286]
This issue describes the tasks required to replace the basic `admin:admin` default credentials with an alternative method which takes a provided password from a defined environment variable. This issue results from https://github.com/OpenSearch-Security/OpenSearch-Security/issues/3. It is a twin issue to #3285. 

The tasks required to complete this include:

- [ ] Update documentation on how to set environment variable (2 hours)
- [ ] Add code to parse the environment variable on launch (3 hours) 
- [ ] Reconcile configuration issues for multi-node clusters (1 day) 
- [ ] Make sure nodes sync admin credentials in config to match the env. variable (1 day) 
- [ ] Mark cluster after first password use (1 day) *

This issue can be closed when all of the listed tasks are completed.

* Note: @peternied noted that we may not need to mark the cluster. However, I am still not sure. From what I was thinking, the issue with not marking the cluster in some way is that we want to be able to change the password like normal afterwards. If we provide a password <MY_DEFAULT>, we want to be able to then swap the admin password to <NEW_PASSWORD> as normal. If we are not marking the cluster in someway or wiping the variable, then we will be resetting the password to the password in the environment. This should be addressed during the PR(s) making these changes.

**Comment by scrawfor99** [comment]
[Triage] This is a follow-up to the existing issue: https://github.com/opensearch-project/security/issues/3285. Going to mark triaged given the prior interest in completing the issue.

**Comment by peternied** [comment]
Change https://github.com/opensearch-project/security/pull/3329 also resolves this issue
