### ISSUE TITLE
[Documentation] Documentation guidance for Service Accounts + OnBehalfOf Authentication

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security#3290]
### Description
This is issue is targeting on providing the guidance for the feature of Service Accounts and On Behalf Of Authentication. General design details from internal threat model document can be transferred to here as the guidance for documentation work on our doc website. So, let's using the comment section of this issue to capture all these informations with all the latest design changes.

### Exit Criteria
Having the following portions of guidance:

**On Behalf Of Authentication:**
- [x] Introduction / General design of OBO (including the general designs, and some naming conventions)
- [x] Setup and Configuration for generic usage of OBO (including the security config, endpoint setup, and required permissions)
- [x] Extension related usage of OBO (including the risks)

**Service Account**
- [x] Introduction Service Account - what are they for?
- [x] When should you use a service account vs another method?
- [x] What is unique about service accounts, You can deactivate them, why and how?

### References
1. Original meta issue of OBO: #2573 
2. Original meta issue of Service Accounts: #2944

**Comment by scrawfor99** [comment]
Hi @RyanL1997 thanks for filing this issue. I can definitely help you with the Service Accounts and anything else you may need related to this.

**Comment by scrawfor99** [comment]
[Triage] This is an item for service accounts and on behalf of tokens.

**Comment by RyanL1997** [comment]
## On-Behalf-Of Authentication

### 1.0 Usage
The security team has opted to develop an on-behalf-of JSON Web Token for managing authentication requests between the user's client and the extension just-in-time which means that the token is issued just before it is needed for usage. The token will have a configurable short time window of validity after which it is expired and cannot be used.

These tokens will allow the extension to interact with the OpenSearch cluster using the same privileges as the initiating user, that’s the reason it is named as “on-behalf-of”. However, since this token doesn’t have any restrictions in place, it also has the capability of letting a service operate as if they are the original user until it is invalid. This implies that this feature can be used more broadly and is not limited to extension related use cases.

### 1.1 Configuration
In the security config file, the on-behalf-of configuration is located under the dynamic config section. It contains the signing key for token signature and the encryption key for the token payload (role information) decryption:
```
config:
  dynamic:
    on_behalf_of:
      enabled: #'true'/non-specified will be consider as 'enabled'
      signing_key: #encoded signing key here
      encryption_key: #encoded encryption key here
...
```

The encoded algorithm is HMAC SHA512 by default for the signing of the JWT. Both the signing key and encryption key are Base64 encoded and stored on the file system of the OpenSearch node. the keys should be the same on all hosts, otherwise it wouldn't work - deployment of these keys is managed by cluster operator.

### 1.2 Token Structure
The payload of this token must comprehensively include all standard configurations of a JWT (JSON Web Token), along with encrypted and decrypted roles. Depending on the setting of the "Plugin Backward Compatibility Mode," backend roles should also be incorporated into role claims. It's important to note that the absence of any of these claims will result in a malformed token, failing to meet the required standard for authentication.

The On Behalf Of token contains following claims:
* Issuer (`iss`): OpenSearch Cluster Identifier
    * It's essential that the issuer is validated as a part of security control measures. This strategy is forward-thinking, particularly in the context of potential multi-tenant scenarios like OpenSearch Serverless, where differing cryptographic keys could be associated with each issuer. By checking the value of issuer, each on-behalf-of token is limited to be used to its associated cluster.
* Issue-at (`iat`): Current time of issuing this token
    * Just use as the reference of the expiration.
* Not-before (`nbf`): The earliest point at which the token can be used.
    * Given that the on-behalf-of token is designed for just-in-time usage, its `nbf` should align with the `iat` (issued-at) time, indicating the moment when the token was created.
* Expiry (`exp`): Expiration time
    * The On Behalf Of  token incorporates an expiration mechanism, which is verified upon receipt of the token. Once it gets issued, it cannot be revoked. Furthermore, the generation of On Behalf Of tokens by extensions is subject to dynamic settings. This functionality safeguards the system by preventing the issuance of future tokens under certain conditions.
    * The default configuration establishes an expiration time of 300 seconds for these tokens. Recognizing that different scenarios may necessitate different token durations, we have incorporated the capability for users to personalize this expiration time. At present, the maximum duration that can be assigned to a token is 600 seconds.
    * In reference to the current design of the on-behalf-of (obo) token, it's accurate to say that token revocation isn't a current concern, given its intended just-in-time use and brief lifespan. However, if future adjustments necessitate an extended lifespan for this token, we will certainly integrate revocation functionality. This strategy will be adopted to improve and solidify the security measures associated with its use.
* Subject (`sub`): User Identifier
    * Name of the user to which this on-behalf-of token is associated.
* Audience (`aud`): Extension’s unique identifier/ Service
    * For the Extension scenario, the aud reference to the specific extension to represent the target service.
    * For the REST API Usage, the the API parameter “service” will let user to specify the target services for using this token, and the default value is set to “self-issued“
* Roles: Security Privilege Evaluation
    * Role Security Mode [[source code](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java#L151)]: Also known as “Role Security Mode”. This configuration determines the encryption of the roles claim. 
        * Role Security Mode On (default value) - Roles claim will be encrypted.
            * Encrypted mapped roles (er)
        * Role Security Mode Off - Roles claims will be in plain-text, and both mapped roles and backend roles will be included in the claim [[related discussion](https://github.com/opensearch-project/security/issues/2865)]
            * Decrypted mapped roles in plain text (`dr`)
            * Decrypted backend roles (`br`)

**Comment by RyanL1997** [comment]
## Service Accounts

### 1.0 Introduction of Service Accounts
Service Accounts are a new authC/authZ path where extensions can execute requests without assuming the roles of the active user. Service Accounts are a special type of principal associated with each extension and have a set of permissions. The permissions assigned to a Service Account grant the associated extension the authorization to execute any of the mapped operations without needing to assume the roles of the active user or stash the user’s roles in the ephemeral user context. With the introduction of Service Accounts, extensions have the ability to operate without stashing the roles of the active user and have their actions authorized against a unique set of permissions. 

### 2.0 Service Account Background
For the current extension design, it is not possible for an extension to execute a request without assuming the roles of the active user. Instead, when a request is processed, an ephemeral “Plugin User” is created. The Plugin User then assumes all the permissions of the currently authenticated operator (human user). The result is a Plugin User which acts on the extension’s behalf but has all of the privileges of the operator. In this way, the current model can be said to have extensions “impersonate” the operator. This impersonation approach leads to two main issues:
* Impersonation compromises referential integrity, meaning it is difficult for auditors to identify which requests were executed by an extension or by an operator. A system with referential integrity maintains a transactional record in its audit log. The record provides a clear history of actions taken by various subjects at specific times. When extensions impersonate users for both requests they make on behalf of the operator, and requests they execute on their own, the audit log lacks referential integrity. 
* Impersonation also makes it impossible to restrict an extension’s permissions beyond those of the user it impersonates. When an extension assumes the roles of the active subject, it copies all of the roles. This includes even those permissions which are uneccessary for executing its intended actions. This practice not only deviates from the principal of least-privileges, but also increases the threat surface area. With each additional permission granted to the Plugin User, the potential impact a misconfigured or malicious extension may have grows. 

### 3.0 Service Account Benefit
Service Accounts address the issues listed in 2.0 by defining a separate state which autonomously executing extensions run in. Service Accounts maintain referential integrity by making a distinct state which extensions can run in when executing requests on their own behalf. Instead of impersonating the operator when executing their own requests, extensions will now make use of their own unique accounts to perform actions. As a result, it is possible to track whether an extension is operating on its own or at the request of the operator. Audit logging can then record when an extension executes on its own—it will make authC/authZ calls against the Service Account—or whether it is executing an action on behalf of the operator and therefore making use of the OnBehalfOf tokens.

Similarly, Service Accounts address threat exposure concerns by separating the roles an extension assumes from those of the operator or a generic hard coded user such as the super user. Service Accounts will not assume the roles of the operator since they will now have their own privileges listed in the Service Account. The roles associated with a Service Account can therefore be as a restrictive as possible in alignment with the principle of least-privileges. The extension author should have a strong understanding of what types of operations the extension hopes to execute, they are then able to assign the privileges in accordance with the operations their extension will need to execute. 

### 4.0 API Endpoint
As suggested by the name, the boolean flag `service` denotes whether a given internal user account is Service Account. If an account is not a Service Account, then attempts to generate an associated auth token will fail. Similarly, the `enabled` field dictates when a Service Account can be used by an extensions to perform operations. If a Service Account is not `enabled` attempts to fetch its auth token will be blocked and it will be unable to execute requests on its own behalf. 
* Here is an example of create a service account with ALL PERMISSIONS for your service/extension:
```
curl -XPUT "[https://localhost:9200/_plugins/_security/api/internalusers/admin-extension https://localhost:9200/_plugins/_security/api/internalusers/hello-world" -H 'Content-Type: application/json' -d' 
{
 "opendistro_security_roles": ["all_access"],
 "backend_roles": [],
 "attributes": {
  "enabled": "true",
  "service": "true"
 }
}' -u "admin:admin" --insecure
```

**Comment by RyanL1997** [comment]
## Handling OnBehalfOf & Service Account Requests
While both OnBehalfOf token handling and Service Accounts can be viewed as independent features, the most significant benefits are realized when coupled. Specifically, OpenSearch exposes a client which is used to connect to the OpenSearch cluster and provided Plugins the ability to execute requests. With the introduction of OnBehalfOf tokens and Service Accounts the client is now able to be used to handle requests which will make use of both of these new features. When the client executes a request which requires an extension to use an OnBehalfOf token, the first step of handling the request is the forwarding of the request to the Security Plugin. In the Security Plugin, the  request is authenticated and authorized against the active user. If the active user is permitted, the request returns to OpenSearch’s core code base where a request to create an OnBehalfOf for the target extension using the active user’s identity is created. This request to generate the OnBehalfOf token is then handled by the IdentityPlugin implementation. In the standard scenario this is the Security Plugin so the request is returned to the Security Plugin’s implementation of the TokenManager interface which generates a new OnBehalfOf token for the request. After generating the token, the Security Plugin forwards the request with the OnBehalfOf token to the extension. At that point, the extension is then able to call OpenSearch’s REST methods with the token. The permissions associated with the token will then be evaluated for the authorization of the request. If the token conveys the permissions required for the operation, the action will be performed and the response will be sent back to the extension. After processing OpenSearch’s response, the extension will forward its own handling of the response to the client. If instead, the OnBehalfOf token does not entail the permissions required for execution of the target action, the a forbidden response is returned to the extension. 

Extensions acting on their own behalf also make use of the client exposed by OpenSearch. When an extension is first initialized in OpenSearch, the IdentityPlugin is triggered to create a new Service Account for it and provide the associated Service Account token. In the default configuration, the Security Plugin is the IdentityPlugin so handles these processes. After OpenSearch receives the Service Account token, it forwards that token to the associated extension. After the extension has received its token, requests by the client to make use of the Service Account associated with the extension are operable. In these scenarios, the extension receives the requests from the client, and then forwards the request along with the Service Account token to OpenSearch. OpenSearch further transfers the packages to the Security Plugin where the token is parsed and the request is treated as a traditional request using Basic Authentication in the InternalAuthenticationBackend. 

In both OnBehalfOf and Service Account token request flows, the IdentityPlugin `TokenManager` interface is used by the IdentityPlugin to handle the distribution and processing of the tokens. This interface is implemented by the Security Plugin as an IdentityPlugin and contains logic for issuing a token which is either an OnBehalfOf or Service Account token.

**Comment by scrawfor99** [comment]
Opened a PR in the documentation repo: https://github.com/opensearch-project/documentation-website/pull/5123

**Comment by DarshitChanpura** [comment]
Removing 2.11 label as this is being tracked for 2.12 now.

**Comment by RyanL1997** [comment]
Closing this due to the merge of https://github.com/opensearch-project/documentation-website/pull/5123 and the release of `2.12.0`: https://opensearch.org/docs/latest/security/access-control/authentication-tokens/
