### ISSUE TITLE
Security Plugin cannot startup due to AccessControlException: access denied

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3309]
The security plugin cannot be loaded because of an issue with the bouncy castle dependancy coming from OpenSearch core.

```
 java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
�  Likely root cause: java.lang.InternalError: cannot create instance of org.bouncycastle.jcajce.provider.digest.GOST3411$Mappings : java.security.AccessControlException: access denied ("java.security.SecurityPermission" "putProviderProperty.BC")
�  	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadServiceClass(Unknown Source)
�  	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadAlgorithms(Unknown Source)
�  	at org.bouncycastle.jce.provider.BouncyCastleProvider.setup(Unknown Source)
�  	at org.bouncycastle.jce.provider.BouncyCastleProvider.access$000(Unknown Source)
�  	at org.bouncycastle.jce.provider.BouncyCastleProvider$1.run(Unknown Source)
�  	at java.base/java.security.AccessController.doPrivileged(Native Method)
�  	at org.bouncycastle.jce.provider.BouncyCastleProvider.<init>(Unknown Source)
�  	at org.opensearch.security.OpenSearchSecurityPlugin$2.run(OpenSearchSecurityPlugin.java:323)
...
```

### Additional Context
- Plugin install failure https://github.com/opensearch-project/security/actions/runs/6086574945/job/16513238110?pr=3307
- BWC test startup failure https://github.com/opensearch-project/security/actions/runs/6086574929/job/16513238774?pr=3307
- SecurityManager permissions issue with other plugins https://github.com/opensearch-project/security/issues/3213

**Comment by peternied** [comment]
Root cause change in main [1] & backport to 2.x [2]

- [1] https://github.com/opensearch-project/OpenSearch/pull/9289/
- [2] https://github.com/opensearch-project/OpenSearch/pull/9736

**Comment by peternied** [comment]
@cwperks Can you help drive this from the security plugin?

FYI - @reta @willyborankin

**Comment by reta** [comment]
@cwperks let me know if you need any help

**Comment by cwperks** [comment]
@reta all eyes are appreciated on this issue. This is release blocking for 2.10.0.

**Comment by reta** [comment]
Sure, I am taking it, @cwperks!

**Comment by cwperks** [comment]
@willyborankin opened a related issue a few days ago: https://github.com/opensearch-project/security/issues/3213

It looks like the `plugin-security.policy` file in this repo is being ignored.

**Comment by peternied** [comment]
@cwperks @reta I think we need to remove the `opensearch-encryption-sdk` from OpenSearch to get unblocked - I am open to other suggestions, but we need to be wary of the impact to the security posture of OpenSearch.

**Comment by reta** [comment]
@peternied on the same page, I think I found the solution to unblock us, hold on please

**Comment by willyborankin** [comment]
@peternied im for reverting PR. Im for crypto-sdk but it need t be implemented differently.

**Comment by cwperks** [comment]
I'm on the same page as well. I'm trying a few different things in the security plugin and in core, but reverting would get the release unblocked while a strategic fix is worked on
