### ISSUE TITLE
[FEATURE] Port issue labels to PR

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#3335]
Coming from https://github.com/opensearch-project/OpenSearch/issues/8199

Port all labels overs from associated issues to PR.

There should be a logic to exclude some labels like `untriaged`

**Comment by scrawfor99** [comment]
[Triage] Hi @DarshitChanpura thanks for opening this issue. It does not seem like Security is the best place to put this. Perhaps core would be more appropriate? Thank you.
