### ISSUE TITLE
[FEATURE] Improve permission granularity for tenants

### ISSUE THREAD

**Issue by uj-ff48** [opensearch-project/security#3346]
**Is your feature request related to a problem?**
Read only users of a tenant cannot save searches. This makes impossible for such an user to create/download a report, even if it got the rights.
**What solution would you like?**
It would be desirable to improve the permission granularity when it comes to tenant rights.
For instance, I would like to specify what kind of tenant object is writeable: `kibana:saved_objects/search/write`.
**What alternatives have you considered?**
A simple solution is to force r/o users to work on their private tenant, but people are lazy and do not want to import objects into their own space (and take responsibility).

**Comment by scrawfor99** [comment]
[Triage] Hi @uj-ff48, thank you for filing this issue. @davidlago could you follow-up on this? Thank you.

**Comment by davidlago** [comment]
Thanks for the tag, @scrawfor99. Closing this one and linking to the new workspaces effort that is the reincarnation of tenants, where the way these are access controlled will be improved https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4615.
