### ISSUE TITLE
[Bug] Cannot update com.puppycrawl.tools:checkstyle due to conflict

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3355]
### Description

We cannot bump com.puppycrawl.tools:checkstyle from 10.12.1 to a future version because of a conflict with `com.google.collections:google-collections`:

### Reproduction

1. Update `com.puppycrawl.tools:checkstyle` in `build.gradle` to >10.12.1
1. `./gradlew checkstyleMain`

See this error message

```
Execution failed for task ':checkstyleMain'.
> Could not resolve all files for configuration ':checkstyle'.
   > Could not resolve com.google.guava:guava:32.0.1-jre.
     Required by:
         project : > com.puppycrawl.tools:checkstyle:10.12.3
      > Module 'com.google.guava:guava' has been rejected:
           Cannot select module with conflict on capability 'com.google.collections:google-collections:32.1.2-jre' also provided by [com.google.collections:google-collections:1.0(runtime)]
   > Could not resolve com.google.collections:google-collections:1.0.
     Required by:
         project : > com.puppycrawl.tools:checkstyle:10.12.3 > org.apache.maven.doxia:doxia-core:1.12.0 > org.codehaus.plexus:plexus-container-default:2.1.0
      > Module 'com.google.collections:google-collections' has been rejected:
           Cannot select module with conflict on capability 'com.google.collections:google-collections:1.0' also provided by [com.google.guava:guava:32.1.2-jre(jreRuntimeElements)]
```

### Exit Criteria

- [x] Fix the conflict and merge an update to the latest version of `com.puppycrawl.tools:checkstyle`

### Additional Context

- https://github.com/opensearch-project/security/pull/3345
- https://github.com/opensearch-project/security/pull/3105

**Comment by scrawfor99** [comment]
[Triage] Thank you @peternied, this issue looks ready to be taken on. Going to mark as triaged.

**Comment by peternied** [comment]
- Fixed in https://github.com/opensearch-project/security/pull/3465
