### ISSUE TITLE
[FEATURE] [RFC] Provide an Admin endpoint to return the permissions necessary to perform some action

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security#3381]
**Is your feature request related to a problem?**
Is there some way to evaluate and return the necessary cluster and index permissions in order to perform a certain action? 
This would be useful when:
- Admin is evaluating what is the minimum permissions a user requires to perform a specific function
- UI is evaluating what "kind of view" to show to a user - can they click a link? - can we know this beforehand and make the link not-clickable for certain users, based on their permissions?

Currently, the permissioning system in OpenSearch is kind of a black box, I am not sure what many of these permissions mean/what they are doing. Additionally, when requests fail due to lack of permissions, it fails on the first one and returns that. This is useful, but means that if someone wants to give minimum permissions they will need to manually add them one by one until the request passes. This seems like a bad user experience, and may lead to admins configuring too-permissible roles, just to avoid this situation.

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by davidlago** [comment]
[Triaging] Thanks for filing, @derek-ho ! We'll need a bit more details about the exit criteria & UX around this feature before we can apply the triaged label.

**Comment by scrawfor99** [comment]
This issue cannot be acted on currently as permission evaluation and requirements are evaluated on execution. This would need further details before we can mark this triaged. Please open a new request should additional info become available.
