### ISSUE TITLE
[FEATURE] An interface to know if the security plugin is disabled in the cluster or not.

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/security#3413]
**Is your feature request related to a problem?**

Currently from the plugins code, there's no easy way to know if the security is enabled or not. Currently in ml-commons, we check like if [user == null](https://github.com/opensearch-project/ml-commons/blob/2.x/plugin/src/main/java/org/opensearch/ml/helper/ModelAccessControlHelper.java#L150-L151), then we know either security is disabled or it is super admin user.

But there can be a use case, when we need to know if the security plugin is enabled and the user is super admin user.

Currently there's no easy to know this.

In ML-Commons side, we have a use case to create  a special type of "Hidden Model" which will only be applicable for Security Enabled Cluster.

So in our case if we just check user == null , that can fail with backward compatibility. As for security disabled domain, every model will be treated as Special Hidden Model

**What solution would you like?**
May be an interface from which other plugin can know about this status.

**What alternatives have you considered?**
I was considering to invoke `/_cat/plugins` api and then see if the security plugin is listed or not. But this will only work if security plugin is removed from the plugins directory. But if the plugin is disabled from opensearch.yml file, then list will still show the security plugin. 

In addition, this doesn't seem idea as from plugin, we need to make another rest api request to know this status. 

**Do you have any additional context?**

**Comment by davidlago** [comment]
[Triage] @cwperks @peternied could you pease add a bit more context on the differences between plugin installed and FGAC enabled, and understand a bit better the use case @dhrubo-os is proposing?

**Comment by cwperks** [comment]
There are 2 instances where superuser comes into the picture when security is installed and enabled (enabled meaning its not running in SSL only mode or installed but explicitly disabled):

1. Plugin stashes the thread context and essentially switches to operating in a trusted mode where it can do anything
2. User connects using the admin certificate
3. 
Are you more interested in the second case?

If that's the case the user should still be in the threadcontext (`user != null`), but the username should be in the list of admin_dns which are defined in this list: https://github.com/opensearch-project/security/blob/main/tools/install_demo_configuration.sh#L381-L382

I would need to double check, but I believe there is a user entry in the threadcontext that you can retrieve through common utils. Matching the username against that list would tell you if the authenticated user is a superuser

**Comment by cwperks** [comment]
@dhrubo-os Can you please show how the linked Draft PR in the common-utils repo would be used?

**Comment by scrawfor99** [comment]
Hi @cwperks and @dhrubo-os are there any updates on this issue? Is this still being pursued? Thanks
