### ISSUE TITLE
[META] Document changes related to default admin credentials

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3415]
Once the changes related to admin credentials have been merged, we need to update the documentation. This involves updating documentation at following places:

- [x] #3694
- [x] #3695

### Additional Context:
- #3622 
- #3623 
- #3624

**Comment by DarshitChanpura** [comment]
- [ ] Update [docker-hub](https://hub.docker.com/r/opensearchproject/opensearch) and [jenkins](https://hub.docker.com/r/jenkins/jenkins) description once the change is officially released and is documented. (Owners: @peterzhuamazon @prudhvigodithi )
