### ISSUE TITLE
[BUG] Security plugin does not properly delegate RestHandler implementations to original Handler

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3422]
In order to provide authentication, the security plugin wraps REST Handlers to perform authentication before the original handler is called in the [SecurityRestFilter](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/filter/SecurityRestFilter.java#L118-L146)

The [RestHandler](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/rest/RestHandler.java) interface in core has many other methods that are not currently being delegated properly to the original handler after the Security plugin wraps the original handler. The way the security plugin creates a wrapped Rest Handler using an anonymous function means that all of the other methods in the RestHandler would resort to their default implementation instead of the delegated implementation.

There is an optimization in [core](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/rest/RestController.java#L313-L315) to skip a call to ensure safe buffers on Search and Bulk requests that is currently not working given that when the security plugin wraps the original rest handler it would return the default implementation of `allowsUnsafeBuffers` as `false` instead of the delegated implementation. [Bulk](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/rest/action/document/RestBulkAction.java#L119-L122) and [Search](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java#L404-L407) rest handlers override the RestHandler interface's default implementation.

Acceptance Criteria:

- [ ] The call to `handler.allowsUnsafeBuffers()` in [core](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/rest/RestController.java#L313-L315) should delegate to the original REST Handler

**Comment by davidlago** [comment]
[Triage] @cwperks to add checklist of exit criteria before flipping to triaged.
