### ISSUE TITLE
[Tests] integration-tests are not being run on windows

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3423]
### Description 
integration-tests are not being run on windows

### Repro
1. _Checkout the `2.x` branch that has the latest version of these tests_
   - https://github.com/opensearch-project/security/pull/3512 is in the process of merging these changes to main
1. Go to `.github/workflows/ci.yml`
3. Find the `integration-tests` section, then update the `platform`
4. Add `windows-latest`
5. Commit change
6. Push / create pull request and run the CI workflow

### Additional Context
The tests themselves are solid, [[here]](https://github.com/opensearch-project/security/actions/runs/6305277168/job/17118384937?pr=3388) is 10x runs of these same tests executed on the linux platform.  Windows execution was dropped during the backporting process [1] to expedite the workflow.

Windows is seeming to have problems in general, tracking issue [2]

- [1] #3388
- [2] #3266 

### Exit Criteria
- [ ] Root cause and specific issues that exist and see about resolving them.
- [ ] Run the test at least 10 times and see no failures - [how to do this](https://github.com/opensearch-project/security/pull/3388/commits/a714cf5cd07c0fa624965ab0b1a7c34e5143b75e)

**Comment by MaciejMierzwa** [comment]
Hi, I'm looking into it

**Comment by peternied** [comment]
@MaciejMierzwa 

I've updated the description to include the branch, which for the moment is only limited to 2.x - this should get you unblocked to look into this issue until the PR to main has been merged.

> 1. _Checkout the `2.x` branch that has the latest version of these tests_
>   - https://github.com/opensearch-project/security/pull/3512 is in the process of merging these changes to main

**Comment by MaciejMierzwa** [comment]
Hi @peternied could it be that this issue is obsolete by now? Here's a draft PR that includes windows and runs integration tests 10 times. All integration-tests are green on the first pass, without any other changes.
https://github.com/opensearch-project/security/pull/3706

**Comment by MaciejMierzwa** [comment]
Hi opened this bug since the test mentioned here is outside of scope for this task: https://github.com/opensearch-project/security/issues/3772
