### ISSUE TITLE
[Test] Reenable disable test case PointInTimeOperationTest.listAllPits_positive

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3424]
### Description
Looks like the call to the cluster `cleanUpPits` is returning before all of the PITs have actually been deleted on the cluster.  

### Repo
1. Go to `src/integrationTest/java/org/opensearch/security/PointInTimeOperationTest.java`
2. Find the `@Ignore` entry on the test named `listAllPits_positive`
3. Delete that attribute
4. Run the tests with `./gradlew integrationTest --tests org.opensearch.security.PointInTimeOperationTest.listAllPits_positive`

### Exit Criteria
- [ ] Ensure that PITs have been cleaned up in a deterministic way - note this could be a product change too
- [ ] Run the test at least 10 times and see no failures - [how to do this](https://github.com/opensearch-project/security/pull/3388/commits/a714cf5cd07c0fa624965ab0b1a7c34e5143b75e)

**Comment by EduardoCorazon** [comment]
Good evening @peternied , I would like to help contribute to this issue is that's ok.

**Comment by peternied** [comment]
Sure, I've assigned this issue to you, thanks!

**Comment by cwperks** [comment]
This issue is now resolved with the merge of https://github.com/opensearch-project/security/pull/3871.
