### ISSUE TITLE
[Test] CrossClusterSearchTests are flaky

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3425]
### Description
It looks like the cross cluster setup that evolves multiple clusters coming online and communicating with one another have issues that make them fragile.

### Repo
1. Go to `src/integrationTest/java/org/opensearch/security/CrossClusterSearchTests.java`
2. Find the `@Ignore` entry on the class
3. Delete that attribute
4. Run the tests with `./gradlew integrationTest --tests org.opensearch.security.CrossClusterSearchTests`

### Exit Criteria
- [ ] Find the root cause of the failing cluster startup process
- [ ] Run the test at least 10 times and see no failures - [how to do this](https://github.com/opensearch-project/security/pull/3388/commits/a714cf5cd07c0fa624965ab0b1a7c34e5143b75e)

**Comment by EduardoCorazon** [comment]
Good evening @peternied, I would like to help contribute to this issue if that's ok? I've been trying to replicate the issue and while using the debugger yields passing tests, using `./gradlew integrationTest` with the `--tests` filter results in errors for both this and other test files. I was wondering if this might be an issue on my end or if this is something that needs to be fixed?

**Comment by peternied** [comment]
> I've been trying to replicate the issue and while using the debugger yields passing tests

Just to double check, you've deleted the `@Ignore` annotation, the gradle to execute the tests succeed, and the `./build/reports/tests/integrationTest/index.html` you can see that all the tests in that class ran and succeed?

Assuming that is the case, interesting.  It might be a difference in how the GitHub runners work vs your local machine, I'm guessing GitHub runners are slower and have less memory.

You can confirm this by running the tests multiple times in GitHub by adding checking in on the commit linked in the above 
 description (and [here](https://github.com/opensearch-project/security/pull/3388/commits/a714cf5cd07c0fa624965ab0b1a7c34e5143b75e)) showing how to modify the GitHub action to run the tests more times.  You can see this on your fork or by making a draft PR with changes.
 
If you are unable to find any issues then you can resolve this issue by removing the ignore attribute from the class and create a PR for that change along side the other exit criteria for this issue.
