### ISSUE TITLE
[Test] SearchOperationTest is flaky

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3426]
### Description
- There are many tests that use audit log validation of scenarios and it seems either the number of requests is not always consistent
- There are many tests that use reindexing and it looks like the operation isn't being confirmed as completed before the tests continue
- There are many tests that use alias creation / clean up and it seems resolution on these actions is not completing before the tests continue causing issues.

### Repo
1. Go to `src/integrationTest/java/org/opensearch/security/SearchOperationTest.java`
2. Find the `@Ignore` many tests in this class
3. Delete that attribute
4. Run the tests with `./gradlew integrationTest --tests org.opensearch.security.SearchOperationTest`

### Exit Criteria
- [ ] Find the root cause(s) of the audit log mismatches, all audit log data should expect exact counts, or have a deterministic function to calculate the count based on number of requests, etc.
- [ ] Find the root cause of the reindexing issues, add a deterministic process to be sure this has completed, note; this could involve a product fix
- [ ] Find the root cause of the aliases issues, add a deterministic process to be sure this has completed, note; this could involve a product fix
- [ ] Run the test at least 10 times and see no failures - [how to do this](https://github.com/opensearch-project/security/pull/3388/commits/a714cf5cd07c0fa624965ab0b1a7c34e5143b75e)

**Comment by MaciejMierzwa** [comment]
Looking into it

**Comment by MaciejMierzwa** [comment]
This issue is linked to this one: https://github.com/opensearch-project/security/issues/2141
Looking into both

**Comment by MaciejMierzwa** [comment]
Hi, here is backport PR: https://github.com/opensearch-project/security/pull/3862
@scrawfor99 @peternied @cwperks @davidlago @DarshitChanpura

**Comment by cwperks** [comment]
Closing this issue as associated PRs have been merged.
