### ISSUE TITLE
[Question] How should WhoAmI and Health requests be handled with the header verifier?

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3440]
As part of work related to: https://github.com/opensearch-project/OpenSearch/issues/10260

A new step in the netty pipeline is being introduced before decompression called `header_verifier`. From the Draft implementation in https://github.com/opensearch-project/security/pull/3418, it will skip decompression for unauthenticated requests since the body will only wind up being ignored. 

The security plugin has logic to skip authentication for [3 types of requests](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/filter/SecurityRestFilter.java#L248):

- OPTIONS
- WhoAmI
- Health

How should these be handled with conditional decompression? Its invalid for each of these requests to have a body so is it possible to reject them if they do? Since conditional decompression is an optimization to forgo decompressing a request if its unauthenticated, can we take advantage of that optimization and skip decompression if these requests have a body?

**Comment by cwperks** [comment]
There are 2 acs endpoints for SAML:

- /_opendistro/_security/saml/acs
- /_opendistro/_security/saml/acs/idpinitiated

I am trying to understand who and how both of these endpoints are called and will update this post with more info after diving further into the implementation of these endpoints.

**Comment by scrawfor99** [comment]
[Triage] Hi @cwperks, thank you for filing this issue. This seems like a tracking issue for work you are currently conducting. Please leave your findings here and then close or alternatively provide explicit action items & closure criteria for someone else to pick up. Otherwise great job investigating!

**Comment by cwperks** [comment]
[Triage] @cwperks Please provide more information on this issue.
