### ISSUE TITLE
[Question] What are System Integrators?

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3447]
Related to: https://github.com/opensearch-project/OpenSearch/issues/10260

There is a suite of tests called [SystemIntegratorTests](https://github.com/opensearch-project/security/blob/main/src/test/java/org/opensearch/security/SystemIntegratorsTests.java) that uses a [UserInjectorPlugin](https://github.com/opensearch-project/security/blob/main/src/test/java/org/opensearch/security/test/plugin/UserInjectorPlugin.java#L55-L60) that installs a custom HttpTransport called `org.opensearch.security.http.UserInjectingServerTransport`.

The purpose of this transport is to wrap a RestHandler and inject a user into the threadcontext if a specific HttpHeader is present.

This plugin works with the SecurityPlugin installed (albeit the Security plugin is not used as an HttpTransport so no SSL is configured) and can inject a user into the ThreadContext that get's picked up by the SecurityPlugin.

In https://github.com/opensearch-project/security/pull/3418, the SystemIntegratorTests started failing because it was configured to use the HttpTransport from the UserInjectorPlugin instead of the HttpTransport from the SecurityPlugin. 

In order to facilitate moving authn to a step in the netty pipeline before decompression, then the security plugin must be the configured HttpTransport and no other plugin.

**Comment by scrawfor99** [comment]
[Triage] Hi @cwperks, sounds like you got an answer to this question. Please feel free to amend this information to the architecture guide and feel free to close this issue.

**Comment by scrawfor99** [comment]
Closing this issue. Thank you for your investigation :)
