### ISSUE TITLE
Determine if TransportPassiveAuthSetting can be safely removed

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3448]
I found another instance related to Transport auth in the security plugin that looks like its a contender for removal. [TransportPassiveAuthSetting](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/setting/TransportPassiveAuthSetting.java#L18) appears to be related to Transport-layer authentication which was removed with the TransportClient in https://github.com/opensearch-project/security/pull/1701.

Acceptance Criteria:

- [ ] Determine if TransportPassiveAuthSetting is safe to remove
- [ ] If it is safe to remove, open a PR and remove it

**Comment by scrawfor99** [comment]
[Triage] Hi @cwperks, feel free to open a PR to this point.

**Comment by cwperks** [comment]
Closing this issue, this setting is transient and applicable when performing a rolling upgrade of a cluster where security is disabled to a cluster where security is enabled. https://github.com/opensearch-project/security/pull/1156

**Comment by peternied** [comment]
@cwperks Is there anything we should do to make it clearer that it is important?  Do you remember what caused you to think it should be deleted in the first place on inspection?
