### ISSUE TITLE
This pull request could have been automatically merged by adding the author 'dependabot[bot]' to discerning-merger list of allowed-authors.

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3450]
This pull request could have been automatically merged by adding the author 'dependabot[bot]' to discerning-merger list of allowed-authors.

_Originally posted by @github-actions in https://github.com/opensearch-project/security/pull/3434#issuecomment-1743351266_

**Comment by scrawfor99** [comment]
[Triage] This is already addressed.
