### ISSUE TITLE
[BUG] Add precommit hook to the pipeline

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/security#3471]
**What is the bug?**

Since we do not have a `precommit` hook in the pipeline it is possible to push and merge files without license header.
To fix the problem we need to add it to the pipeline.

**Do you have any additional context?**
Add any other context about the problem.

**Comment by scrawfor99** [comment]
[Triage] Hello @willyborankin, thank you for filing this issue. This looks good to me! I agree a precommit hook would be helpful here.
