### ISSUE TITLE
[BUG] `install_demo_configuration` script shows confusing log

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#3489]
**What is the bug?**
When spinning up distribution cluster, the following message is present in the log: `"Unable to find the admin password for the cluster. Please run 'export initialAdminPassword=<your_password>' or create a file $ADMIN_PASSWORD_FILE with a single line that contains the password."`
This suggests that admin user no longer has admin password, but that is not the case. Admin user does get created with `admin` as its password.

**How can one reproduce the bug?**
1. Download latest [docker-compose.yml](https://opensearch.org/samples/docker-compose.yml)
2. Ensure it points to distribution that contains admin:admin change
3. Run docker-compose up.
5. See the message in the logs

**What is the expected behavior?**
Either the cluster shouldn't spin up or the error message shouldn't appear.

**Comment by RyanL1997** [comment]
Closing this since the fix has been merged into 2.11
