### ISSUE TITLE
[BUG] Demo configuration is still using the `admin:admin` credential if `initialAdminPassword` is not provided

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security#3508]
**What is the bug?**
Demo configuration is still using the admin:admin if there is an absent of the `initialAdminPassword`
* Relate: https://github.com/opensearch-project/security/pull/3490
* Relate: https://github.com/opensearch-project/opensearch-build/issues/4094

**How can one reproduce the bug?**
1. Run the demo configuration script without providing `initialAdminPassword`.
2. When the cluster is ready, try the `admin:admin` credential

**What is the expected behavior?/Exit Criteria**
If there is an failure for providing the `initialAdminPassword` during the setup of the demo configuration, the script needs to fail hard (kill the cluster) and users should not be able to be authenticated with default `admin:admin` credential.

**Do you have any additional context?**
* Potential Fix: https://github.com/opensearch-project/security/pull/3449

**Comment by scrawfor99** [comment]
[Triage] Hi @RyanL1997, thank you for filing this issue. Looks good--we should make sure we kill the cluster as you describe.
