### ISSUE TITLE
[META] Ensure changes to admin credentials work on all supported OpenSearch distributions

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#3623]
## High-level Idea

Stemming from the [spike](https://github.com/opensearch-project/security/issues/3560), this feature-requests focuses on ensuring all distributions work as expected once the hardcoded admin password has been replace with a more dynamic value.
This issue should be worked in tandem with the meta to update the code to replace hardcoded admin password inside demo configuration script.

## Acceptance Criteria

- [x] The modification is implemented in all compatible OpenSearch distributions.
- [x] The change is reflected consistently across all supported OpenSearch distributions.

## Exit Criteria

- [x] #3705
- [x] #3634
- [x] #3708
- [x] #3709
- [x] #3710
- [x] #3711
- [x] #3712

**Comment by scrawfor99** [comment]
[Triage] This is another meta issue related to the work of removing the use of default credentials. Marking as triaged given clear exit criteria and action items.

**Comment by derek-ho** [comment]
There are three test cases for each distribution type that needs to be verified:

1. Run `./opensearch-tar-install.sh` without no initialAdminPassword environment variable set, no initialAdminPassword.txt.
    a. Verify a secure password is generated
    b. Verify that admin:admin fails authentication
    c. Verify that admin:${Generated Password} succeeds authentication
2. Run `./opensearch-tar-install.sh` initialAdminPassword environment variable set
    a. Verify that a "weak" password fails and stops script execution in a clean way
    b. Verify that a "strong" password succeeds
        i. Verify that admin:admin fails authentication
        ii. Verify that admin:${initialAdminPassword} succeeds authentication
3. Run `./opensearch-tar-install.sh` no initialAdminPassword environment variable set, initialAdminPassword.txt present.
    a. Verify that a "weak" password fails and stops script execution in a clean way
    b. Verify that a "strong" password succeeds
        i. Verify that admin:admin fails authentication
        ii. Verify that admin:${initialAdminPassword.txt contents} succeeds authentication

**Comment by DarshitChanpura** [comment]
all sub-tasks complete.
