### ISSUE TITLE
[META] Update all instances of admin:admin across different repositories

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#3624]
## Description

There are many instances of `admin:admin` credentials usage across [different repositories](https://github.com/opensearch-project/opensearch-build/issues/4094#issuecomment-1747577939). They will be affected by the change to replace hard-coded admin password with a dynamic value. This issue requests fixing all those instances of admin credentials to address this breaking change.

## Acceptance Criteria

- [ ] All hard-coded instances across repos are addressed 
- [ ] Ensure that tests, if any, work as expected

## Tasks 

Search and update the references to `admin:admin`, password `admin` and demo install script in following repos, as required:
(to track work done, tag the PR next to the repo name)

(Legend:  ❌ - no updates, 🕐 - in progress, ⌛ - Waiting 2.12 release, ✅ - complete)

| Status | Repo | PR | Issue | Notes |
|--------|------|----|-------|-------|
| ⌛ | [logstash-output-opensearch](https://github.com/opensearch-project/logstash-output-opensearch) | [#233](https://github.com/opensearch-project/logstash-output-opensearch/pull/233) | [#234](https://github.com/opensearch-project/logstash-output-opensearch/issues/234) | will be merged post 2.12 release |
| ⏳ | [opensearch-go](https://github.com/opensearch-project/opensearch-go) | [#449](https://github.com/opensearch-project/opensearch-go/pull/449) | [#459](https://github.com/opensearch-project/opensearch-go/issues/459) | will be merged post 2.12 release |
| ⏳ | [opensearch-js](https://github.com/opensearch-project/opensearch-js) | [#669](https://github.com/opensearch-project/opensearch-js/pull/669), [#707](https://github.com/opensearch-project/opensearch-js/pull/707) | [#699](https://github.com/opensearch-project/opensearch-js/issues/699) | will be merged post 2.12 release |
| ⏳ | [opensearch-migrations](https://github.com/opensearch-project/opensearch-migrations) | [#480](https://github.com/opensearch-project/opensearch-migrations/pull/480) | [#479](https://github.com/opensearch-project/opensearch-migrations/issues/479) | will be merged post 2.12 release |
| ⏳ | [opensearch-py](https://github.com/opensearch-project/opensearch-py) | [#631](https://github.com/opensearch-project/opensearch-py/pull/631) | [#648](https://github.com/opensearch-project/opensearch-py/issues/648) | will be merged post 2.12 release |
| ⏳ | [opensearch-rs](https://github.com/opensearch-project/opensearch-rs) | [#234](https://github.com/opensearch-project/opensearch-rs/pull/234) | [#236](https://github.com/opensearch-project/opensearch-rs/issues/236) | will be merged post 2.12 release |
| ⏳ | [opensearch-ruby](https://github.com/opensearch-project/opensearch-ruby) | [#217](https://github.com/opensearch-project/opensearch-ruby/pull/217) | [#222](https://github.com/opensearch-project/opensearch-ruby/issues/222) | will be merged post 2.12 release |
| ⏳ | [reporting-cli](https://github.com/opensearch-project/reporting-cli) | [#56](https://github.com/opensearch-project/reporting-cli/pull/56) | [#58](https://github.com/opensearch-project/reporting-cli/issues/58) | will be merged post 2.12 release |
| ⏳ | [terraform-provider-opensearch](https://github.com/opensearch-project/terraform-provider-opensearch) | [#138](https://github.com/opensearch-project/terraform-provider-opensearch/pull/138) | [#146](https://github.com/opensearch-project/terraform-provider-opensearch/issues/146) | will be merged post 2.12 release |

| Status | Repo | PR | Issue | Notes |
|--------|------|----|-------|-------|
| ✅ | [alerting](https://github.com/opensearch-project/alerting) | [#1399](https://github.com/opensearch-project/alerting/pull/1399) | [#1347](https://github.com/opensearch-project/alerting/issues/1347) | |
| ✅ | [alerting-dashboards-plugin](https://github.com/opensearch-project/alerting-dashboards-plugin) | [#849](https://github.com/opensearch-project/alerting-dashboards-plugin/pull/849) | [#861](https://github.com/opensearch-project/alerting-dashboards-plugin/issues/861) | |
| ✅ | [anomaly-detection](https://github.com/opensearch-project/anomaly-detection) | [#1134](https://github.com/opensearch-project/anomaly-detection/pull/1134) | [#1120](https://github.com/opensearch-project/anomaly-detection/issues/1120) | |
| ✅ | [anomaly-detection-dashboards-plugin](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin) | | [#662](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/662) | no action needed |
| ✅ | [asynchronous-search](https://github.com/opensearch-project/asynchronous-search) | [#521](https://github.com/opensearch-project/asynchronous-search/pull/521) | [#515](https://github.com/opensearch-project/asynchronous-search/issues/515) | |
| ✅ | [common-utils](https://github.com/opensearch-project/common-utils) | [#581](https://github.com/opensearch-project/common-utils/pull/581) | [#579](https://github.com/opensearch-project/common-utils/issues/579) | |
| ✅  | [cross-cluster-replication](https://github.com/opensearch-project/cross-cluster-replication) | [#1298](https://github.com/opensearch-project/cross-cluster-replication/pull/1298) | [#1310](https://github.com/opensearch-project/cross-cluster-replication/issues/1310) | |
| ✅  | [custom-codecs](https://github.com/opensearch-project/custom-codecs) | | [#92](https://github.com/opensearch-project/custom-codecs/issues/92) | no action needed |
| ✅ | [data-prepper](https://github.com/opensearch-project/data-prepper) | [#3869](https://github.com/opensearch-project/data-prepper/pull/3869) | [#3978](https://github.com/opensearch-project/data-prepper/issues/3978) | |
| ✅  | [dashboards-observability](https://github.com/opensearch-project/dashboards-observability) | [#1296](https://github.com/opensearch-project/dashboards-observability/pull/1296) | [#1371](https://github.com/opensearch-project/dashboards-observability/issues/1371) | |
| ✅ | [dashboards-visualizations](https://github.com/opensearch-project/dashboards-visualizations) | | [#308](https://github.com/opensearch-project/dashboards-visualizations/issues/308) | no action needed |
| ✅ | [docker-images](https://github.com/opensearch-project/docker-images/) | | | archived |
| ✅ | [documentation-website](https://github.com/opensearch-project/documentation-website) | [#5887](https://github.com/opensearch-project/documentation-website/pull/5887), [#6058](https://github.com/opensearch-project/documentation-website/pull/6058), [#6279](https://github.com/opensearch-project/documentation-website/pull/6279) | [#5946](https://github.com/opensearch-project/documentation-website/issues/5946) |  |
| ✅  | [flow-framework](https://github.com/opensearch-project/flow-framework) | | [#310](https://github.com/opensearch-project/flow-framework/issues/310) | no action needed |
| ✅ | [geospatial](https://github.com/opensearch-project/geospatial) | [#616](https://github.com/opensearch-project/geospatial/pull/616) | [#615](https://github.com/opensearch-project/geospatial/issues/615) | |
| ✅ | [helm-charts](https://github.com/opensearch-project/helm-charts) | [#518](https://github.com/opensearch-project/helm-charts/pull/518)| [#515](https://github.com/opensearch-project/helm-charts/issues/515) |  |
| ✅  | [index-management](https://github.com/opensearch-project/index-management) | [#1076](https://github.com/opensearch-project/index-management/pull/1076) | [#1064](https://github.com/opensearch-project/index-management/issues/1064) | |
| ✅ | [index-management-dashboards-plugin](https://github.com/opensearch-project/index-management-dashboards-plugin) | [#954](https://github.com/opensearch-project/index-management-dashboards-plugin/pull/954) | [#957](https://github.com/opensearch-project/index-management-dashboards-plugin/issues/957) | |
| ✅ | [job-scheduler](https://github.com/opensearch-project/job-scheduler) | | [#553](https://github.com/opensearch-project/job-scheduler/issues/553) | no action needed |
| ✅ | [k-NN](https://github.com/opensearch-project/k-NN) | [#1415](https://github.com/opensearch-project/k-NN/pull/1415) | [#1359](https://github.com/opensearch-project/k-NN/issues/1359) | |
| ✅ | [logstash-input-opensearch](https://github.com/opensearch-project/logstash-input-opensearch) | [#55](https://github.com/opensearch-project/logstash-input-opensearch/pull/55) | [#56](https://github.com/opensearch-project/logstash-input-opensearch/issues/56) | |
| ✅ | [ml-commons](https://github.com/opensearch-project/ml-commons) | | [#1899](https://github.com/opensearch-project/ml-commons/issues/1899) | no action needed |
| ✅ | [ml-commons-dashboards](https://github.com/opensearch-project/ml-commons-dashboards) | | [#292](https://github.com/opensearch-project/ml-commons-dashboards/issues/292) | |
| ✅ | [neural-search](https://github.com/opensearch-project/neural-search) | [#551](https://github.com/opensearch-project/neural-search/pull/551) | [#550](https://github.com/opensearch-project/neural-search/issues/550) | |
| ✅ | [notifications](https://github.com/opensearch-project/notifications) | | [#832](https://github.com/opensearch-project/notifications/issues/832) | no action needed |
| ✅ | [opensearch-build](https://github.com/opensearch-project/opensearch-build) | [#4302](https://github.com/opensearch-project/opensearch-build/pull/4302) | [#4303](https://github.com/opensearch-project/opensearch-build/issues/4303) | |
| ✅ | [opensearch-cluster-cdk](https://github.com/opensearch-project/opensearch-cluster-cdk) | [#86](https://github.com/opensearch-project/opensearch-cluster-cdk/pull/86) | | |
| ✅ | [OpenSearch-Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards) | [#5736](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5736) | [#5636](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5636) | |
| ✅ | [opensearch-dashboards-functional-test](https://github.com/opensearch-project/opensearch-dashboards-functional-test) | [#981](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/981) | | |
| ✅ | [opensearch-k8s-operator](https://github.com/opensearch-project/opensearch-k8s-operator) | [#692](https://github.com/opensearch-project/opensearch-k8s-operator/pull/692) | [#703](https://github.com/opensearch-project/opensearch-k8s-operator/issues/703) | no action neede |
| ✅ | [opensearch-net](https://github.com/opensearch-project/opensearch-net) | [#480](https://github.com/opensearch-project/opensearch-net/pull/480) | [#520](https://github.com/opensearch-project/opensearch-net/issues/520) | |
| ✅ | [opensearch-net-abstractions](https://github.com/opensearch-project/opensearch-net-abstractions) | | | archived |
| ✅ | [opensearch-php](https://github.com/opensearch-project/opensearch-php) | | [#172](https://github.com/opensearch-project/opensearch-php/issues/172) | no action needed |
| ✅ | [opensearch-py-ml](https://github.com/opensearch-project/opensearch-py-ml) | [#365](https://github.com/opensearch-project/opensearch-py-ml/pull/365) | [#371](https://github.com/opensearch-project/opensearch-py-ml/issues/371) | |
| ✅ | [opentelemetry-demo](https://github.com/opensearch-project/opentelemetry-demo) | [#114](https://github.com/opensearch-project/opentelemetry-demo/pull/114) | [#113](https://github.com/opensearch-project/opentelemetry-demo/issues/113) | |
| ✅ | [performance-analyzer](https://github.com/opensearch-project/performance-analyzer) | | [#613](https://github.com/opensearch-project/performance-analyzer/issues/613) | no action needed |
| ✅ | [performance-analyzer-rca](https://github.com/opensearch-project/performance-analyzer-rca) | [#526](https://github.com/opensearch-project/performance-analyzer-rca/pull/526) | [#527](https://github.com/opensearch-project/performance-analyzer-rca/issues/527) | |
| ✅ | [reporting](https://github.com/opensearch-project/reporting) | | [#938](https://github.com/opensearch-project/reporting/issues/938) | no action needed |
| ✅ | [search-processor](https://github.com/opensearch-project/search-processor) | [#214](https://github.com/opensearch-project/search-processor/pull/214) | [#216](https://github.com/opensearch-project/search-processor/issues/216) | |
| ✅ | [security](https://github.com/opensearch-project/security) | [#3844](https://github.com/opensearch-project/security/pull/3844) | | |
| ✅ | [security-analytics](https://github.com/opensearch-project/security-analytics) | [#832](https://github.com/opensearch-project/security-analytics/pull/832) | [#831](https://github.com/opensearch-project/security-analytics/issues/831) | |
| ✅ | [security-dashboards-plugin](https://github.com/opensearch-project/security-dashboards-plugin) | [#1696](https://github.com/opensearch-project/security-dashboards-plugin/pull/1696) | | |
| ✅  | [sql-cli](https://github.com/opensearch-project/sql-cli) | [#25](https://github.com/opensearch-project/sql-cli/pull/25) | [#26](https://github.com/opensearch-project/sql-cli/issues/26) | |
| ✅ | [sql-odbc](https://github.com/opensearch-project/sql-odbc) | | [#65](https://github.com/opensearch-project/sql-odbc/issues/65) | no action needed |

**Comment by scrawfor99** [comment]
[Triage] This is a meta tracking issue for replacing default credential usage in the cluster.

**Comment by derek-ho** [comment]
Relevant line in opensearch-build repo: https://github.com/opensearch-project/opensearch-build/blob/main/scripts/default/integtest.sh#L92

**Comment by derek-ho** [comment]
CI references to admin:admin :https://github.com/search?q=org%3Aopensearch-project+admin%3Aadmin&type=code&p=1

**Comment by derek-ho** [comment]
https://github.com/search?q=org%3Aopensearch-project+admin%3Aadmin+repo%3Aopensearch-project%2Fopensearch-js&type=code&p=1, solved by: https://github.com/opensearch-project/opensearch-js/pull/669

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/alerting-dashboards-plugin/pull/849

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/index-management-dashboards-plugin/pull/954

**Comment by dlvenable** [comment]
What version of OpenSearch will have the new password? Data Prepper actually has quite a few occurrences of the password `admin`. Search for `password=admin`, `password: admin`, `password: "admin"`.

**Comment by DarshitChanpura** [comment]
@dlvenable it will be for version 2.12 and above

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/sql-cli/pull/25

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/reporting-cli/pull/56

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/cross-cluster-replication/pull/1298

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/terraform-provider-opensearch/pull/138

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/opensearch-ruby/pull/217

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/opensearch-rs/pull/234

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/opensearch-go/pull/449

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/project-website/pull/2501

**Comment by derek-ho** [comment]
Most references in this repo: seem to disable install demo config: https://github.com/opensearch-project/opensearch-benchmark/blob/main/osbenchmark/resources/docker-compose.yml.j2#L18, I don't think we need to do anything for this repo, but maybe we should make an issue and tag maintainers.

**Comment by derek-ho** [comment]
This one is testing that the jenkins builds are working with admin:admin, I think this repo doesn't need changes: https://github.com/search?q=repo%3Aopensearch-project%2Fopensearch-build-libraries%20admin%3Aadmin&type=code, but we need to change in the build repo so that the job is configured to create distributions with admin:admin

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/opensearch-php/actions/runs/7250326156/job/19750248987 - opensearch-php is running without security it seems like, so no changes necessary

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/opensearch-build/pull/4302 - this means that all repos which still need to maintain their own integtest.sh files should be switching to admin:myStrongPassword123! as new default creds

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/opensearch-php/issues/172

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/opensearch-migrations/pull/480

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/sql-odbc/issues/65

**Comment by derek-ho** [comment]
[1/4/2024] Current status:

PRs we are blocked for reviews on (build related):

https://github.com/opensearch-project/opensearch-build-libraries/pull/357
https://github.com/opensearch-project/helm-charts/pull/504
https://github.com/opensearch-project/helm-charts/pull/503
https://github.com/opensearch-project/terraform-provider-opensearch/pull/138
https://github.com/opensearch-project/opensearch-build/pull/4302
https://github.com/opensearch-project/opensearch-build/pull/4250
https://github.com/opensearch-project/opensearch-build/pull/4274
https://github.com/opensearch-project/opensearch-build/pull/4279
https://github.com/opensearch-project/opensearch-k8s-operator/pull/692

Other PRs we should merge before 2.12.0 release (plugins):

https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/981 (In progress)
https://github.com/opensearch-project/cross-cluster-replication/pull/1298 (In progress)

**Comment by DarshitChanpura** [comment]
[1/10/2024] 

PRs blocked on reviews: 
- Decision on RPM/DEB : https://github.com/opensearch-project/opensearch-build/pull/4332

**Comment by DarshitChanpura** [comment]
adding @bbarani to keep this in his radar

**Comment by derek-ho** [comment]
Right now we have 34 non-compliant/unknown issues

**Comment by DarshitChanpura** [comment]
> Right now we have 27 non-compliant/unknown issues

This number is down to 22 now.

**Comment by jackiehanyang** [comment]
- For AD:
pr for addressing anomaly-detection: https://github.com/opensearch-project/anomaly-detection/pull/1134

- For AD-Dashboard:
No action needed as there's no reference of using the `admin:admin` credential


Please help updating AD and AD-Dashboard status in the Task sheet in the issue description above (I cannot edit it..

**Comment by DarshitChanpura** [comment]
> Please help updating AD and AD-Dashboard status in the Task sheet in the issue description above (I cannot edit it..

Already updated.

**Comment by vibrantvarun** [comment]
Please help updating Neural Search status in the Task sheet in the issue description above (I cannot edit it.)

cc: @DarshitChanpura

**Comment by DarshitChanpura** [comment]
[Update: 01/24/'24]

| Status | Count |
|-------|-------|
| Will be merged post release ⌛  | 10 |
| In Progress 🕐  | 8 |
| No updates ❌ | 11 |
| Complete ✅ | 21 |

**Comment by DarshitChanpura** [comment]
[Update: 01/26/'24]

| Status | Count |
|-------|-------|
| Will be merged post release ⌛  | 10 |
| In Progress 🕐  | 9 |
| No updates ❌ | 5 |
| Complete ✅ | 26 |

**Comment by DarshitChanpura** [comment]
[Update: 01/29/'24]

| Status | Count |
|-------|-------|
| No updates ❌ | 2 |
| In Progress 🕐  | 7 |
| Will be merged post release ⌛  | 9 |
| Complete ✅ | 32 |

**Comment by DarshitChanpura** [comment]
[Update: 01/31/'24]

| Status | Count |
|-------|-------|
| ❌ No updates | 2 |
| 🕐 In Progress | 7 |
| ⌛ Will be merged post release | 9 |
| ✅ Complete | 33 |

**Comment by DarshitChanpura** [comment]
[Update: 02/01/'24]

| Status | Count |
|-------|-------|
| ❌ No updates | 1 |
| 🕐 In Progress | 4 |
| ⌛ Will be merged post release | 10 |
| ✅ Complete | 36 |

**Comment by DarshitChanpura** [comment]
[Update: 02/02/'24]

| Status | Count |
|-------|-------|
| ❌ No updates | 1 |
| 🕐 In Progress | 4 |
| ⌛ Will be merged post release | 10 |
| ✅ Complete | 36 |

**Comment by DarshitChanpura** [comment]
[Update: 02/05/'24]

| Status | Count |
|-------|-------|
| ❌ No updates | 1 |
| 🕐 In Progress | 4 |
| ⌛ Will be merged post release | 10 |
| ✅ Complete | 37 |

**Comment by DarshitChanpura** [comment]
[Update: 02/06/'24]

| Status | Count |
|-------|-------|
| ❌ No updates | 0 |
| 🕐 In Progress | 4 |
| ⌛ Will be merged post release | 9 |
| ✅ Complete | 40 |

**Comment by DarshitChanpura** [comment]
[Update: 02/07/'24]

| Status | Count |
|-------|-------|
| ❌ No updates | 0 |
| 🕐 In Progress | 2 |
| ⌛ Will be merged post release | 9 |
| ✅ Complete | 42 |

**Comment by DarshitChanpura** [comment]
[Update: 02/07/'24]

| Status | Count |
|-------|-------|
| ❌ No updates | 0 |
| 🕐 In Progress | 0 |
| ⌛ Will be merged post release | 11 |
| ✅ Complete | 42 |

**Comment by DarshitChanpura** [comment]
Next update will be post 2.12 release. This task is no longer a blocker for 2.12

**Comment by DarshitChanpura** [comment]
[Update: 02/22/'24]

| Status | Count |
|-------|-------|
| ❌ No updates | 0 |
| 🕐 In Progress | 0 |
| ⏳  Will be merged post release | 9 |
| ✅ Complete | 44 |


This is the last update on this issue. The maintainers of PRs with ⏳ status have been nudged to bring this across the finish line. Closing this as the feature has been delivered in 2.12.
