### ISSUE TITLE
Update documentation-website repository to reflect the changes to admin credentials in demo configuration

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#3695]
Once all changes related to default admin credentials have been implemented, a section should be added to [documentation website for security](https://github.com/opensearch-project/documentation-website/tree/main/_security/configuration) to reflect these changes.

## Acceptance
- [x] A section has been added to [security configuration](https://github.com/opensearch-project/documentation-website/tree/main/_security/configuration) around usage of demo configuration install script.
- [x] Installation steps related to all distributions have been updated

**Comment by prudhvigodithi** [comment]
Also @DarshitChanpura  please make sure to add a point in documentation for the users who are upgrading to `2.12.0` should not be impacted with this default admin password change as the security index is already created and the `install_demo_configuration.sh` wont be executed. This should only impact users who do a fresh cluster install with 2.12.0.

**Comment by DarshitChanpura** [comment]
Closed this as complete via: https://github.com/opensearch-project/documentation-website/pull/6058
