### ISSUE TITLE
Ansible distribution should reflect changes to default admin credentials in demo configuration

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#3712]
Ansible already has an option to set admin password with admin_password variable.

## Acceptance Criteria:
- [ ] Ensure that existing option to set admin password is re-used.
- [ ] A cluster should spin-up without hardcoded admin password.
- [ ] If no password is provided one should be generated.
- [ ] A call with admin:admin to the cluster should fail.

**Comment by derek-ho** [comment]
After a quick search, it seems that ansible is not using `install_demo_configuration.sh` script to generate security setup: https://github.com/derek-ho/ansible-playbook/blob/main/roles/linux/opensearch/tasks/security.yml#L134, instead it is relying on its own way of generating admin password and certs: https://github.com/derek-ho/ansible-playbook/blob/main/roles/linux/opensearch/templates/internal_users.yml#L12. Thus, ansible should not be affected by this change. However, to be thorough, I will checkout 3.0.0 on ansible and verify admin should not be able to be passed in as a weak password.

**Comment by derek-ho** [comment]
Closing this issue as confirming that ansible does not use the `install_demo_configuration.sh` script. It is doing its own thing. Admin:admin does not affect ansible. Confirms it fails if you do not pass in an admin password.
