### ISSUE TITLE
[Flaky Test] org.opensearch.security.TransportUserInjectorIntegTest.testSecurityUserInjection is flaky

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3729]
Seen in https://github.com/opensearch-project/security/actions/runs/6896058512/job/18761443796?pr=3727

**Comment by scrawfor99** [comment]
[Triage] This is a flaky test which should be addressed by either removing the flaky behavior or replacing the test.

**Comment by peternied** [comment]
- Impacted test run https://github.com/opensearch-project/security/actions/runs/6949168658/job/18910461790?pr=3759, impacted PR #3759

**Comment by peternied** [comment]
- Impacted test run https://github.com/opensearch-project/security/actions/runs/6947393851/job/18901098103?pr=3758, impacted PR #3758
