### ISSUE TITLE
[BUG] Wrong deserialization method is chosen in a mixed cluster of <2.11 and 2.11 nodes when PA is enabled

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3771]
In a mixed cluster of <2.11 and >=2.11 nodes with Performance Analyzer (PA) enabled the 2.11 nodes can choose the wrong method of deserialization (Custom instead of JDK) when receiving a transport request from the >2.11 and receive the following error:

```
opensearch-node1  | Caused by: java.lang.IllegalArgumentException: -84 is not a valid id
opensearch-node1  |     at org.opensearch.security.support.Base64CustomHelper$CustomSerializationFormat.fromId(Base64CustomHelper.java:61) ~[?:?]
opensearch-node1  |     at org.opensearch.security.support.Base64CustomHelper.deserializeObject(Base64CustomHelper.java:115) ~[?:?]
opensearch-node1  |     at org.opensearch.security.support.Base64Helper.deserializeObject(Base64Helper.java:46) ~[?:?]
opensearch-node1  |     at org.opensearch.security.transport.SecurityRequestHandler.messageReceivedDecorate(SecurityRequestHandler.java:196) ~[?:?]
opensearch-node1  |     at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceived(SecuritySSLRequestHandler.java:169) ~[?:?]
opensearch-node1  |     at org.opensearch.security.OpenSearchSecurityPlugin$6$1.messageReceived(OpenSearchSecurityPlugin.java:774) ~[?:?]
opensearch-node1  |     at org.opensearch.indexmanagement.rollup.interceptor.RollupInterceptor$interceptHandler$1.messageReceived(RollupInterceptor.kt:113) ~[?:?]
opensearch-node1  |     at org.opensearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:43) ~[?:?]
opensearch-node1  |     at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106) ~[opensearch-2.10.0.jar:2.10.0]
opensearch-node1  |     at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:471) ~[opensearch-2.10.0.jar:2.10.0]
opensearch-node1  |     at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) ~[opensearch-2.10.0.jar:2.10.0]
opensearch-node1  |     at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.10.0.jar:2.10.0]
opensearch-node1  |     ... 3 more
```

Performance Analyzer (PA) sets up a transport interceptor that [wraps a TransportChannel](https://github.com/opensearch-project/performance-analyzer/blob/main/src/main/java/org/opensearch/performanceanalyzer/transport/PerformanceAnalyzerTransportChannel.java#L147-L151). The security plugin has logic to [extract the inner channel](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java#L100-L103) so that the rest of SecuritySSLRequestHandler uses the original channel. There is logic before the inner channel extraction to determine whether to use JDK Serialization if the incoming message was received from a [node running OS <= 2.10](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java#L89-L92). That code relies on `channel.getVersion()` to get the version of the node that transmitted the transport request, but when the channel is wrapped its not delegating to the original channel in PA. This PR moves the logic after the extraction of the inner channel to ensure that `channel.getVersion()` correctly returns the version from the transmitting node.

The coupling of the Security plugin and PA should be re-visited to avoid having to use reflection to extract the inner channel. With the Telemetry feature, there is also another instance where the TransportChannel can be wrapped: https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/transport/InboundHandler.java#L253

**Comment by waqarsky** [comment]
Hi @cwperks  Was this fixed in the 2.12 release?

**Comment by peternied** [comment]
Yes - this was included in 2.12, https://github.com/opensearch-project/security/commit/9110114cbfccfa21fe2b9ea73b5c1a686513a5ad

![image](https://github.com/opensearch-project/security/assets/2754967/9da29912-1828-4a35-8403-d427c332c360)

**Comment by uj-ff48** [comment]
Hello there,

**Comment by uj-ff48** [comment]
Hello,
I am commenting this closed ticket as yesterday we experienced this issue yet again while migrating the cluster from 2.12.0 to 2.14.0.
Was there a code regression  ?
Anyway, is there a way to prevent it from happening in the future ?
