### ISSUE TITLE
[BUG] Refactor SlowIntegrationTests.testDelayInSecurityIndexInitialization()

### ISSUE THREAD

**Issue by MaciejMierzwa** [opensearch-project/security#3772]
**What is the bug?**
That test: [SlowIntegrationTests.testDelayInSecurityIndexInitialization()](https://github.com/opensearch-project/security/blob/3b070c88792e6df1b72798fcb70029fe86df815a/src/test/java/org/opensearch/security/SlowIntegrationTests.java#L221C17-L221C55) is heavily dependent on custom timeouts and suspending thread while testing to create test scenario.
This causes test to be highly unstable.

_Originally posted by @peternied in https://github.com/opensearch-project/security/pull/3706#discussion_r1400946242_
            

**What solution would you like?**
 It would be a good idea to rewrite this test to make in more stable

**What is the expected behavior?**
Expected behavior is to be able to run tests multiple times without flaky executions. 

**Exit Criteria**

- [ ] Refactor SlowIntegrationTests.testDelayInSecurityIndexInitialization() 
- [ ] Run the test at least 10 times and see no failures - [how to do this](https://github.com/opensearch-project/security/pull/3388/commits/a714cf5cd07c0fa624965ab0b1a7c34e5143b75e)

**Comment by cwperks** [comment]
[Triage] Closing as a duplicate of https://github.com/opensearch-project/security/issues/2230

@MaciejMierzwa I have opened a PR to address this test (https://github.com/opensearch-project/security/pull/3763). Please provide any review feedback if there are better ways to address the test.
