### ISSUE TITLE
[BUG] Logstash static role should include the ecs-logstash pattern in index permissions

### ISSUE THREAD

**Issue by dpavlos** [opensearch-project/security#3791]
**What is the bug?**
Since logstash 8.x has the ecs v8 compatibility mode enabled by default for all ecs compatible plugins and the `logstash-output-opensearch` plugin sets the [default index pattern for the ecs](https://github.com/opensearch-project/logstash-output-opensearch/blob/7c770365298ab2bd3dd128d24c48b23c55d2ff80/lib/logstash/outputs/opensearch.rb#L430C25-L430C52) mode to be `ecs-logstash-%{+yyyy.MM.dd}` then the minimum index permissions for the [builtin logstash static role](https://github.com/opensearch-project/security/blob/main/src/main/resources/static_config/static_roles.yml#L134) should allow at least the creation and crud operations on all indexes following this pattern.

**How can one reproduce the bug?**
Use logstash in ecs compatibility mode and its builtin static role along with the logstash-output-opensearch plugin to ingest events into OpenSearch.

**What is the expected behavior?**
Logstash should have enough permissions to create and modify indexes with prefix `ecs-logstash`

**What is your host/environment?**
Logstash version: 8.9.0-oss
OpenSearch version: 2.9.0
Logstash output plugin: logstash-output-opensearch

**Do you have any screenshots?**
Error message:
```
[INFO ][logstash.outputs.opensearch][main][2a15a812080baab0c6fe9a5ece656b985ecb67109da737d3b3644d70e810668e] Retrying failed action {:status=>403, :action=>["index", {:_id=>nil, :_index=>"ecs-logstash-2023.11.19
", :routing=>nil}

[...]

error=>{"type"=>"security_exception", "reason"=>"no permissions for [indices:admin/create] and User 
[name=logstash, backend_roles=[logstash], requestedTenant=null]"}}
```

**Comment by cwperks** [comment]
[Triage] @dpavlos Thank you for filing this issue and PR. It looks like the role needs to be updated for all default index patterns. Thank you for the details.
