### ISSUE TITLE
[BUG] HTTP Challenge Response changed slightly in 2.11

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3803]
**What is the bug?**

Associated issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5562

The HTTP Challenge response uses to contain a body with the text "Unauthorized", but was changed in 2.11 to have no body.

- [2.10.0](https://github.com/opensearch-project/security/blob/2.10/src/main/java/org/opensearch/security/http/HTTPBasicAuthenticator.java#L69) 
- [2.11.0](https://github.com/opensearch-project/security/blob/2.11/src/main/java/org/opensearch/security/http/HTTPBasicAuthenticator.java#L68-L73)

See more details in a comment on the associated issue in OSD: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5562#issuecomment-1836925336

How the issue manifests is that running OpenSearch w/ the Security plugin installed, but not running OSD with security-dashboards-plugin installed will not challenge the user for credentials and instead fails to load the home page.

**Comment by cwperks** [comment]
Could be related: https://github.com/opensearch-project/security/issues/3678

**Comment by peternied** [comment]
Isn't needed for 2.12 release, moving out to be addressed at any time.
