### ISSUE TITLE
[FEATURE] get a list of indices and aliases for which my user has been granted permission

### ISSUE THREAD

**Issue by chet5619** [opensearch-project/security#3806]
**Is your feature request related to a problem?**
We are developing an application where user will be able to connect to their OpenSearch instance and expand their connection to see a list of the indices & aliases that they may have permissions. We have been investigating several options as described in this [forum thread](https://forum.opensearch.org/t/how-to-get-a-list-of-indices-for-which-i-have-been-granted-permission/16692) but so far there hasnt been any good solution. We are noticing that there doesnt seem to be a singe REST API call that would just return the indices, aliases and user permissions.

**What solution would you like?**
Working with elasticsearch we found that we can call `_security/user/_privileges` without any specific permissions set for the user and that will return information about what permissions the user has and which indices/aliases the user can see. This would be a great enhancement to th Opensearch platform.

**What alternatives have you considered?**
As described in the forum thread above, we have tried various options, but can never seem to get the simple answer of what indices and aliases can my user see.

**Comment by scrawfor99** [comment]
[Triage] Hi @chet5619, thanks for filing this issue. There are some complexities with resolving the roles into the indices, permissions, etc. Basically, any time you do that, you had to resolve all roles which is computationally expensive. If you are interested, you could create an API to take the roles mappings and then return the resolved roles (with index patterns not concrete indices) from these mappings. If you would think this would be of help, you are more than welcome to contribute an API for review :)

**Comment by peternied** [comment]
- We've got another issue tracking this request, closing this issue in favor of the previous feature request https://github.com/opensearch-project/security/issues/2652
