### ISSUE TITLE
[FEATURE] Update instances of admin:admin in Security

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security#3840]
**Is your feature request related to a problem?**
https://github.com/search?q=org%3Aopensearch-project+admin%3Aadmin+++repo%3Aopensearch-project%2Fsecurity&type=code

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by peternied** [comment]
Looks like this is a duplicate of line items on the meta issues associated with default password
