### ISSUE TITLE
[BUG] Naming of initialAdminPassword doesn't comply with convention

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#3842]
**What is the bug?**

I found https://github.com/opensearch-project/security/blob/e69831505a13fc79dab14c0743c8a12864cdb94d/src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java#L97 that relies on an environment variable `initialAdminPassword`. This feels at least "unusual". Most variables I've seen are `OPENSEARCH_SOMETHING_SOMETHING`.

**What is the expected behavior?**

The variable should be `OPENSEARCH_ADMIN_PASSWORD` or `OPENSEARCH_INITIAL_ADMIN_PASSWORD`.

**Comment by peternied** [comment]
Thanks for filing @dblock - I agree with this suggestion.  I'd vote for `OPENSEARCH_INITIAL_ADMIN_PASSWORD`

**Comment by DarshitChanpura** [comment]
Ty @dblock for filing this. I've created a PR to update the name: https://github.com/opensearch-project/security/pull/3843
Please feel free to review this.

**Comment by dblock** [comment]
> Thanks for filing @dblock - I agree with this suggestion. I'd vote for `OPENSEARCH_INITIAL_ADMIN_PASSWORD`

And looking at https://github.com/opensearch-project/opensearch-py/pull/631/files#diff-a3c4761b16aa51b10e83377d99fec8879c360931ae22d98f2181cac72e207d29, we don't want it to be something like `users.admin.password=...`?
