### ISSUE TITLE
[BUG] _render Operation is not working in OS_2.11

### ISSUE THREAD

**Issue by niravpi** [opensearch-project/security#3861]
**What is the bug?**
OpenSearch provide support for ```_render``` operation which helps to validate stored template, attached reference documents below.

* OpenSearch Doc : https://opensearch.org/docs/latest/api-reference/search-template/#save-and-execute-search-templates

But for OS_2.11 FGAC enabled domains   ```_render``` operation is not working as it is failing with the following exception 
```
    {
        "type": "security_exception",
        "reason": "Unexpected exception indices:data/read/search/template"
      }
```

While analyzing further observed that the issue might be related to recent PR 
* https://github.com/opensearch-project/OpenSearch/pull/9122

**How can one reproduce the bug?**
1. Create FGAC enabled OS_2.11 domain
2. Then perform the following operations on the domain 
3. First save search template as a script 
```
POST _scripts/play_search_template
{
  "script": {
    "lang": "mustache",
    "source": {
      "from": "{{from}}{{^from}}0{{/from}}",
      "size": "{{size}}{{^size}}10{{/size}}",
      "query": {
        "match": {
          "play_name": ""
        }
      }
    },
    "params": {
      "play_name": "Henry IV"
    }
  }
}
```
4.Then try to perform render operation to validate saved template 
```
POST _render/template
{
  "id": "play_search_template",
  "params": {
    "play_name": "Henry IV"
  }
}
```
5. See error as below 
```
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "Unexpected exception indices:data/read/search/template"
      }
    ],
    "type": "security_exception",
    "reason": "Unexpected exception indices:data/read/search/template"
  },
  "status": 500
}
```

**What is the expected behavior?**
render operation should have worked and the output for the above reproduction steps should be as follow instead of exception 
```
{
  "template_output": {
    "from": "0",
    "size": "10",
    "query": {
      "match": {
        "play_name": "Henry IV"
      }
    }
  }
}
```
**What is your host/environment?**
 - OpenSearch version OS_2.11

**Do you have any screenshots?**
![Screenshot 2023-12-18 at 3 51 05 PM](https://github.com/opensearch-project/security/assets/84867659/a4d4e500-b3ed-4881-96ed-e207afc06601)

**Comment by anijain-Amazon** [comment]
Duplicate of https://github.com/opensearch-project/security/issues/3672

**Comment by cwperks** [comment]
Closing as duplicate of https://github.com/opensearch-project/security/issues/3672
