### ISSUE TITLE
[v2.12.0] Ensure CI/documentation reflect changes to default admin credentials

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security#3884]
## Background
Previously, when installing the security plugin demo configuration, the cluster was spun up with the default admin credentials, `admin:admin`. A change was made in `main` and backported to `2.x` for the `2.12.0` release, which now requires an initial admin password to be passed in via the environment variable `OPENSEARCH_INITIAL_ADMIN_PASSWORD`. This will break some CI/testing that relies on OpenSearch to come up without setting this environment variable. This tracking issue is to ensure compliance with the new changes.

Coming from: https://github.com/opensearch-project/security/issues/3624

## Acceptance Criteria
 - [x] All documentation references to the old default credentials `admin:admin` are removed
 - [x] Ensure that CI/testing is working with `main` and `2.x` branches

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho, could you check whether this is completed? Thank you! Otherwise looks good.

**Comment by derek-ho** [comment]
Integ test failures causing autocuts. Hopefully resolved with this PR: https://github.com/opensearch-project/opensearch-build/pull/4331, but will keep this issue updated.

**Comment by derek-ho** [comment]
Original two acceptance criteria fulfilled, but i am waiting to close this until we resolve the opensearch-build repo integtest workflow to unblock all plugins.
