### ISSUE TITLE
[BUG] Fix the hardcode instance of check for NettyAttribute

### ISSUE THREAD

**Issue by Gaganjuneja** [opensearch-project/security#3911]
**What is the bug?**
Fix the hardcode `instance of` check for NettyAttribute. It fails if the HttpChannel is wrapped during the instrumentation.

https://github.com/opensearch-project/security/blob/26e62d5b77300695e3bd94352a5e297e28828b15/src/main/java/org/opensearch/security/filter/NettyAttribute.java#L28

**How can one reproduce the bug?**

**What is the expected behavior?**
It shouldn't fail if tracing is enabled.

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by Gaganjuneja** [comment]
@reta, need your help in fixing this. Thanks!

**Comment by reta** [comment]
@Gaganjuneja https://github.com/opensearch-project/security/pull/3514 was supposed to fix that

**Comment by Gaganjuneja** [comment]
@reta, yes, this line item was with you. Since that issue is closed so opened the new issue.

https://github.com/opensearch-project/security/pull/3514#discussion_r1366388993
