### ISSUE TITLE
[Enhancement] Ensure graceful termination if weak/no initial admin password set

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security#3915]
**Is your feature request related to a problem?**
Currently, all distributions are picking up the default admin credentials changes successfully in both 3.0.0 and 2.12.0. However there is still a lingering issue - if either a weak or no initial admin password is set, the install scripts from the build repo side keep executing, ending up failing at a later point (when the certs are not found). This is a bad user experience. Instead, we should gracefully fail install execution as soon as we detect weak/no initial admin password. This will be more clear as to the reason why the installation script failed.

**Comment by derek-ho** [comment]
This issue will be closed with the completion of:

- [ ] https://github.com/opensearch-project/opensearch-build/pull/4250 (tar)
- [ ] https://github.com/opensearch-project/opensearch-build/pull/4274 (docker/windows)

Still pending decision on:

**Comment by scrawfor99** [comment]
Closing this since the linked tasks are completed.
