### ISSUE TITLE
Can we disable Transport Layer TLS?

### ISSUE THREAD

**Issue by 10000-ki** [opensearch-project/security#3921]
Hi! I'm a user who really loves opensearch

I have one request.

https://opensearch.org/docs/latest/security/configuration/tls/#transport-layer-tls

> TLS is optional for the REST layer and mandatory for the transport layer.

Transport layer tls is mandatory with a security plugin

But this can have a performance impact
In a cluster of internally secure situations, we don't have to use it

Can we use Transport Layer TLS optionally?

**Comment by peternied** [comment]
@10000-ki This is a great question for our forums [1], can you repost your question over there? 

By posting in our forms it helps make answers discoverable by search engines and has a community of developers, cluster admins, and users.  I'm going to close out this issue.


- [1] https://forum.opensearch.org/c/security/3

**Comment by pawelw1** [comment]
@peternied As per documentation the TLS at the transport layer is mandatory by design. I assume this is a feature request to make the transport layer TLS optional. 
There was a similar discussion already in the OpenDistro but it was closed and wasn't continued in the OpenSearch. 
https://github.com/opensearch-project/security/issues/37

**Comment by peternied** [comment]
@pawelw1 So yes the documentation does say that about transport layer; however, v2.0.0's release the transport layer and the rest communication layers were merged.  So this features area is ambiguous.

**Comment by pawelw1** [comment]
@peternied In v2.0.0 only client authentication/authorization has been deprecated in the Transport layer and moved to the REST layer (9200). OpenSearch nodes are still using the Transport layer with TLS to communicate with each other. 

https://github.com/opensearch-project/security/pull/1701

**Comment by 10000-ki** [comment]
> I assume this is a feature request to make the transport layer TLS optional.

yes right

**Comment by 10000-ki** [comment]
When using a private internal network, not an external network
There are cases where it's enough to apply tls to the REST layer
