### ISSUE TITLE
[FEATURE] role mappings: assign to all users which *don't* have a specific backend role

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/security#3925]
**Is your feature request related to a problem?**
situation:

* there are two roles: role A with DLS, role B without DLS, both giving access to an index X
* role A is granted to all users (intent: grant it to all "real" users so that they see only the data they need)
* role B is granted to a technical user to give him additional rights (e.g. data import user which needs to be able to see all documents)
* because role A is granted to all users it is also given to the technical user

due to the technical user having role B he should be able to see all documents in index X, even though he also has role A.

since we can't identify non-technical users (there's no specific role for them in the JWT to reference in the role mapping) we currently use `dfm_empty_overrides_all` (see #1572) so that the technical user still gets access to everything.

**What solution would you like?**
it'd be nice if it'd be possible to do a role mapping based on what a user _doesn't_ have (i.e. in our case based on which role is _not_ present in a JWT).
this way we could grant role A in the example above to all users which don't have the admin role in the JWT.

**What alternatives have you considered?**
we can continue to use `dfm_empty_overrides_all` but also have to deal with the downsides of that (slightly wider impact).

**Do you have any additional context?**
n/a

**Comment by scrawfor99** [comment]
[Triage] Hi @rursprung, thanks for filing this issue. It seems like this may be related to your other issue around the use of `dfm...`. 

Because of the complexity of DLS/FLS the Security plugin as a whole aims to only have "positive" or additive features. In this case, it sounds like you are requesting a feature to support negative permissions which can add to existing confusion. I am going to close this issue but feel free to follow up with other comments or questions. Thank you.

**Comment by rursprung** [comment]
> In this case, it sounds like you are requesting a feature to support negative permissions which can add to existing confusion.

@scrawfor99: i think there's a misunderstanding here: this is not about taking away any rights with a role! this is about having a negative selector for the role assignment, i.e. "grant role only to users which don't have backend role X").

the relation with the other issue is that we're setting the DFM setting so that the admin user gets to see everything even though he also gets the other role (with the DLS). if we have the possibility to grant the DLS role based on the negative filter ("everyone but the admin") then we'd presumably not need the DFM setting anymore
