### ISSUE TITLE
[BUG] Update security config from API

### ISSUE THREAD

**Issue by disaster37** [opensearch-project/security#3958]
**What is the bug?**

Update security config from API not working.
I get `{"status":"FORBIDDEN","message":"Access denied"}` with admin account that have to role `all_access`.

I follow the doc https://opensearch.org/docs/latest/security/access-control/api/#update-configuration

**How can one reproduce the bug?**
1. Start new Opensearch cluster with demo
2. Run curl command to update config

```bash
curl -XPUT -k "https://localhost:9200/_plugins/_security/api/securityconfig/config" -H 'Content-Type: application/json' -d'
{
  "dynamic": {
    "filtered_alias_mode": "warn",
    "disable_rest_auth": false,
    "disable_intertransport_auth": false,
    "respect_request_indices_options": false,
    "opensearch-dashboards": {
      "multitenancy_enabled": true,
      "server_username": "kibanaserver",
      "index": ".opensearch-dashboards"
    },
    "http": {
      "anonymous_auth_enabled": false
    },
    "authc": {
      "basic_internal_auth_domain": {
        "http_enabled": true,
        "transport_enabled": true,
        "order": 0,
        "http_authenticator": {
          "challenge": true,
          "type": "basic",
          "config": {}
        },
        "authentication_backend": {
          "type": "intern",
          "config": {}
        },
        "description": "Authenticate via HTTP Basic against internal users database"
      }
    },
    "auth_failure_listeners": {},
    "do_not_fail_on_forbidden": false,
    "multi_rolespan_enabled": true,
    "hosts_resolver_mode": "ip-only",
    "do_not_fail_on_forbidden_empty": false
  }
}'
```

I get `{"status":"FORBIDDEN","message":"Access denied"}`

**What is the expected behavior?**

I should to get 
```json
{
  "status": "OK",
  "message": "'config' updated."
}

and have config updated.
```

**What is your host/environment?**
Opensearch 2.11.0 from official docker image

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by peternied** [comment]
@disaster37 Thanks for filing - but this isn't a bug.  Please find or create a topic in the forums around this issue https://forum.opensearch.org/c/security/3 those answers can be picked up by search engines and post a link back here.
