### ISSUE TITLE
[BUG] User is not serialized into the ThreadContext for user connecting with the admin certificate

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3965]
Many plugins rely on the `_opendistro_security_user_info` threadcontext header to get information about the currently authenticated user. Plugins have a dependecy on common-utils where they can use the common-utils User class to parse this threadcontext header and construct a user object. (See example from [AD](https://github.com/opensearch-project/anomaly-detection/blob/7c0ce4cb554a05230ecf5365b903219f357997bf/src/main/java/org/opensearch/timeseries/util/ParseUtils.java#L433-L445))

When a request is made using the admin certificate, the user is never serialized into the threadcontext. The serialization of the user into the threadcontext occurs in the PrivilegesEvaluator [here](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java#L273). This works for regular users, however, for a user connecting with the admin cert there is a [bypass](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/filter/SecurityFilter.java#L287-L296) that skips privilege evaluation for this user. As a result, the ThreadContext header is never populated and a plugin relying on this header to get information about the currently authenticated user will not be able to obtain the information using the `_opendistro_security_user_info` header which is the designated header for plugin's to use to interact with the security plugin.

**Comment by peternied** [comment]
I'm concerned about building up more dependence on the thread context - I think we should push plugins teams or ourselves to plumb through Identity interfaces.

Something that would help me understand if we should mitigate this issue vs focusing on a longer term solution is if there a user facing bug.  Is there a customer facing issue that should be referenced?

**Comment by scrawfor99** [comment]
[Triage] Hi @cwperks thanks for filing this issue. It seems like there is some discussion going on about the way to share this information. Perhaps we can re-frame this issue as adding a way for a plugin to query for the super admin? 

Going to remove the untriaged label but not add the triaged label for the meantime. @cwperks perhaps you could add additional context or share more information from the initial scenario? Thanks :)
