### ISSUE TITLE
[FEATURE] Use LocalNodeClusterManagerListener::onClusterManager to initialize security index

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/security#3972]
**Is your feature request related to a problem?**
If the `plugins.security.allow_default_init_securityinde` sets to `true` the plugin tries initialize the security index on each node in the cluster which could lead to race conditions. Instead `OpenSearch` has a special interface      `LocalNodeClusterManagerListener` which we can use to initialize index properly.

**What solution would you like?**
Use `LocalNodeClusterManagerListener::onClusterManager` to initialize the index.

**Comment by scrawfor99** [comment]
[Triage] Hi @willyborankin, thank you for filing this issue. This seems like a smart change that will help us avoid some tricky scenarios. 

We can mark this issue complete when the initialization is swapped over the listener mentioned above.
