### ISSUE TITLE
SAML configuration error if IDP service is down on elasticsearch start

### ISSUE THREAD

**Issue by horacimacias** [opensearch-project/security#40]
I have a working elasticserch+kibana setup using SAML authentication with a custom IDP.

Sometimes the IDP service takes a bit longer to start, which means IDP is not fully up by the time elasticsearch starts.
Looking at the elasticsearch logs, I see elasticsearch cannot connect to IDP and keeps retrying every minute or so:

_Metadata Resolver SamlHTTPMetadataResolver com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticator_1: Next refresh cycle for metadata provider 'xxxxxx' will occur on_ 

The problem I see is that, once IDP fully starts, and I can see on the next retry by elasticsearch it manages to connect (_Metadata Resolver SamlHTTPMetadataResolver com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticator_1: New metadata successfully loaded for_) still I'm not able to login to kibana using SAML.

If I then run securityadmin.sh on elasticsearch, then I am able to authenticate through SAML.

So, all in all, it looks like there is some startup that needs to happen on the SAML logic in elasticsearch and/or kibana that only happens on first startup, not whenever the metadata is successfully loaded because elasticsearch was able to read it.

**Comment by dinusX** [comment]
Hi @horacimacias ,

How do you provide the metadata content ? is it through "metadata_url" ?
If yes, then most likely SAML is not able work properly until it can access the url to load metadata.

You mentioned, that even after IDP restarts and it's up the SAML is still not working until you run "securityadmin.sh". 
I'll try to reproduce this issue and will report back.

One solution that can solve your issue and keep the SAML continuously working on ES is by replacing "metadata_url" with "metadata_file". For this you'll have to create an XML file in the ES config folder with the same content as in that metadata URL. The file needs to be present on all the nodes.

https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/saml/

**Comment by horacimacias** [comment]
it's been a while but yes I was using metadata_url

Perhaps the issue is no longer there anymore as I ended up checking if my IDP is fully up before even trying to start elastic.

**Comment by nateynateynate** [comment]
Thanks for this  @horacimacias - if you have no further issue, I'll go ahead and close this out. By the way - the [community forums](discuss.opendistrocommunity.dev) are an excellent place to troubleshoot issues you're having with other community members.
