### ISSUE TITLE
[FEATURE] Support custom SAML headers for expiry time

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security#4046]
**Is your feature request related to a problem?**
Coming from this comment: https://github.com/opensearch-project/security-dashboards-plugin/issues/159#issuecomment-1022438420, it seems like a deficiency with the security project that we are hard forcing timeout based on one field, when there are popular SAML IDP's (i.e. auth0) which do not follow this format. We should evaluate whether we can support this from the security backend side, or if we can suggest users to somehow map it on their side. I found this: https://auth0.com/docs/authenticate/protocols/saml/saml-configuration/customize-saml-assertions, but not sure if it actually solves their use case.

**Comment by DarshitChanpura** [comment]
[Triage] @derek-ho thanks for filing this issue. Would you please add exit criteria that can be actioned upon to mark this as triaged?

**Comment by derek-ho** [comment]
Closing this as nobody as commented otherwise.
