### ISSUE TITLE
[BUG] CA used to generate certs is expired 

### ISSUE THREAD

**Issue by seiimonn** [opensearch-project/security#4047]
### What is the bug?
The cert used by the container is signed by the CA found in `config/root-ca.pem`. This CA is expired but the certs are valid for 10 years.

The CA:
```
openssl x509 -in root-ca.pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            77:e4:af:3e:fc:da:9f:93:f6:4d:06:c4:67:8c:e3:e0:6b:7a:15:8a
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: DC = com, DC = example, O = Example Com Inc., OU = Example Com Inc. Root CA, CN = Example Com Inc. Root CA
        Validity
            Not Before: Aug 29 04:20:03 2023 GMT
            Not After : Sep 28 04:20:03 2023 GMT
        Subject: DC = com, DC = example, O = Example Com Inc., OU = Example Com Inc. Root CA, CN = Example Com Inc. Root CA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
```

The cert:

```
openssl x509 -in esnode.pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            66:3a:e5:0c:f3:fc:6b:34:43:3d:97:21:03:f5:c4:b3:1d:17:da:22
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: DC = com, DC = example, O = Example Com Inc., OU = Example Com Inc. Root CA, CN = Example Com Inc. Root CA
        Validity
            Not Before: Aug 29 04:23:12 2023 GMT
            Not After : Aug 26 04:23:12 2033 GMT
        Subject: C = de, L = test, O = node, OU = node, CN = node-0.example.com
        Subject Public Key Info:
```

### How can one reproduce the bug?
Pull the lastest image and check the cerst.

### What is the expected behavior?
Is would be nice if the default certs could be used for a testing use case without having to generate our own certs.

### What is your host/environment?
https://hub.docker.com/layers/opensearchproject/opensearch/latest/images/sha256-5495aa4f6ce16c689918846a6e8acc5ef991141693ff7ce3d09c151e25f19e9d?context=explore&tab=vulnerabilities

### Do you have any screenshots?
See the outputs from openssl above.

### Do you have any additional context?
This worked for previous versions of the image, I do not know when it broke.

**Comment by peternied** [comment]
@DarshitChanpura Could you look into this?

- I'm pretty sure that since you added https://github.com/opensearch-project/security/pull/3669 we are generating certs automatically.

**Comment by DarshitChanpura** [comment]
I will provide an update once I dive deep into this.

**Comment by jeffcourtade** [comment]
I am experiencing the same issue.
I am unable to trust the cert chain in other applications because of this.

Is someone assigned to update the docker image for this issue?

Is there a guide for replacing these certificates in the docker images?

**Comment by jeffcourtade** [comment]
> I will provide an update once I dive deep into this.

can you please let me know if there is any progress on this?

We are blocked in a deployment because of this bug

**Comment by DarshitChanpura** [comment]
@seiimonn @jeffcourtade This bug will be addressed via: https://github.com/opensearch-project/security/pull/4061
