### ISSUE TITLE
[FEATURE] Log more information about Password strength feature

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security#4048]
**Is your feature request related to a problem?**
It was brought up that we log out that a password is weak, with no steps as to how to determine the strength of a password. Maybe linking to this: https://lowe.github.io/tryzxcvbn/, or at least logging out that we are using zxcvbn could help.

**Comment by DarshitChanpura** [comment]
[Triage] Thanks for filing this. The exit criteria here is to log more information when a password strength validator is called and password is deemed weak. 

Related: https://github.com/opensearch-project/security-dashboards-plugin/issues/1523

**Comment by peternied** [comment]
> It was brought up that we log out that a password is weak,

In what scenario?  Please include how to get to this state, is this part of cluster startup/configuration, user setup, or something else?

**Comment by camerondurham** [comment]
Here's an example, just trying to run the latest version successfully was a bit annoying. Finally succeeded with something from my password manager.

```
finch run \
    -p 9200:9200 \
    -p 9600:9600 \
    -e "discovery.type=single-node" \
    -e "OPENSEARCH_INITIAL_ADMIN_PASSWORD=sample@1029"  \
    opensearchproject/opensearch:latest
```

Results:
```
Enabling OpenSearch Security Plugin
Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin
OpenSearch 2.12.0 onwards, the OpenSearch Security Plugin a change that requires an initial password for 'admin' user.
Please define an environment variable 'OPENSEARCH_INITIAL_ADMIN_PASSWORD' with a strong password string.
If a password is not provided, the setup will quit.
 For more details, please visit: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/
### OpenSearch Security Demo Installer
### ** Warning: Do not use on production or public reachable systems **
OpenSearch install type: rpm/deb on Linux 6.6.9-100.fc38.x86_64 amd64
OpenSearch config dir: /usr/share/opensearch/config/
OpenSearch config file: /usr/share/opensearch/config/opensearch.yml
OpenSearch bin dir: /usr/share/opensearch/bin/
OpenSearch plugins dir: /usr/share/opensearch/plugins/
OpenSearch lib dir: /usr/share/opensearch/lib/
Detected OpenSearch Version: 2.12.0
Detected OpenSearch Security Version: 2.12.0.0
Password sample@1029 is weak. Please re-try with a stronger password.
FATA[0001] exit status 1

```

**Comment by peternied** [comment]
@camerondurham A PR to improve this scenario would be great - thanks!
