### ISSUE TITLE
[Feature] Remove support for TLSv1.1 by default

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#4059]
TLSv1.1 was deprecated in 2021 (RFC [8996](https://datatracker.ietf.org/doc/html/rfc8996)).

We have an outstanding PR change the default behavior [1], thanks @willyborankin 
- https://github.com/opensearch-project/security/pull/4053

Proposals
On 2.x release, change the default to use only supported TLSv1.2+ standard.  Allow TLSv1/1.1 to be set via manual config. 
 Print a deprecation message if TLSv1 is used.

Lets discuss/review as a triage team and come an agreement. 

---

Follow up:  Was not much movement either way during the triage meeting.  Lets vote 👍 or 👎 for the proposal and come up with an decision this time next week based on the votes.

**Comment by DarshitChanpura** [comment]
[Triage] Thanks for filing this issue. +1 to deprecating the TLS v1.1. I will invite community to vote on the path forward for this deprecation.

**Comment by peternied** [comment]
@willyborankin Could you advertise this issue out in the `#security` slack channel or other places people might want to know?  Please feel free to update the description to be more inline with what you were thinking as well as any other supporting detail you would want on hand.

**Comment by derek-ho** [comment]
[Triage] from @willyborankin it sounds like there are some concerns with different setups (such as LDAP), which this would required painful upgrades. It seems like we want to only include a deprecation log message which can be overiden. It sounds like we want to write a blog or other public communication to make folks aware of this change.

**Comment by willyborankin** [comment]
@peternied I think we can close it?
