### ISSUE TITLE
Default name for log4j audit sync should be swapped to "audit" from legacy naming 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#4101]
**What is the bug?**
[A doc issue](https://github.com/opensearch-project/documentation-website/issues/6602) was filed asking about the true default name of the audit sync. Because of the origin of the Security plugin, the default name is currently 'sgaudit' this should be swapped over to the name 'audit' as described on the documentation website.

**Comment by derek-ho** [comment]
Seems like this was closed with the merge of: https://github.com/opensearch-project/security/pull/4146
