### ISSUE TITLE
[FEATURE] Downport 'Handle too large cookies gracefully' fix to OS 1.3.x 

### ISSUE THREAD

**Issue by julia-siegl** [opensearch-project/security#4114]
**Is your feature request related to a problem?**
We are still using OS version 1.3.x and currently struggle with the same issue described in https://github.com/opensearch-project/security/issues/375

**What solution would you like?**
Downport the fix that was introduced after issue: https://github.com/opensearch-project/security/issues/375 with PR: https://github.com/opensearch-project/security-dashboards-plugin/pull/1402 to a previous version such that also OS version 1.3.x handles cookies gracefully as well. 

**What alternatives have you considered?**
We plan to update to a newer OpenSearch version but are currently blocked by multiple braking changes.

**Comment by cwperks** [comment]
[Triage] Thank you for filing this issue @julia-siegl. There is an open PR to [backport](https://github.com/opensearch-project/security-dashboards-plugin/pull/1662) this fix to the 1.3 line that is targeted for the [next release of 1.3.15](https://opensearch.org/releases.html).

**Comment by pc-jedi** [comment]
Backport to 1.3.x was done in https://github.com/opensearch-project/security-dashboards-plugin/pull/1831

**Comment by cwperks** [comment]
Closing this issue. This will be released in the next patch release for 1.3: 1.3.15.
