### ISSUE TITLE
[FEATURE] Switch to built-in security transports from core

### ISSUE THREAD

**Issue by reta** [opensearch-project/security#4118]
**Is your feature request related to a problem?**

As part of [1], the responsibility to provide the secure transports moves to `NetworkPlugin`, whereas the `Plugin` has been extended to provide `SecureSettingsFactory`.

[1] https://github.com/opensearch-project/OpenSearch/issues/12256

**What solution would you like?**
The `security` plugin does not need to provide the  secure transports anymore but `SecureSettingsFactory` so the core transport modules will be able to configure those.

- [ ] Add `SecureSettingsFactory` 
- [ ] Remove SecuritySSLNettyHttpServerTransport  & SecuritySSLNettyTransport
- [ ] Preserve old SSL related settings 
- [ ] Update references in core with permalinks to `2.13.0` branch 

**What alternatives have you considered?**
Keep everything in `security` plugin

**Do you have any additional context?**
See please https://github.com/opensearch-project/OpenSearch/issues/12256

**Comment by cwperks** [comment]
[Triage] Thank you for filing the issue and opening a companion PR in the security plugin to show how the new secure transport modules in core can be configured from the security plugin.
