### ISSUE TITLE
[FEATURE] Add posibility to create hidden security entities (roles mapping, roles, etc) via REST API

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/security#4166]
Currently it is impossible to create hidden security entities using REST API, but it is possible to delete them which is confusing.  

**What solution would you like?**
Add possibility to create hidden config entities like  roles, roles mapping, internal users etc. using REAT Admin or Super Admin only.

**Comment by scrawfor99** [comment]
[Triage] Hi @willyborankin, thank you for filing this issue. This seems like an easy fix that is worthwhile doing. Going to mark as triaged.
