### ISSUE TITLE
[FEATURE] How other plugins can check if security plugin is ready or not

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/security#4169]
**Is your feature request related to a problem?**
In ml-commons plugin we maintain model routing table(models on running nodes) to dispatch requests to different nodes(round robin), but when a cluster adds a new node the new node will be deployed with the running model automatically by autoredeploy feature in ml-commons, once the model deployment complete, the model routing table gets updated and new requests can be dispatched to the new node. And issue happens here:
1. When performing the model autoredeploy, the request is from internal cluster which is a transport action request without user information: https://github.com/opensearch-project/ml-commons/blob/main/plugin/src/main/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployer.java#L312. In security plugin this kind of requests won't be checked: https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/filter/SecurityFilter.java#L328. 
2. When real user requests come, the security plugin might be still under initializing phase but the check will happen here: https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/filter/SecurityFilter.java#L369, and user gets `security_exception`: 
```
{"error":{"root_cause":[{"type":"security_exception","reason":"OpenSearch Security not initialized for cluster:admin/opensearch/ml/predict"}],"type":"security_exception","reason":"OpenSearch Security not initialized for cluster:admin/opensearch/ml/predict"},"status":503}
```

**What solution would you like?**
Other plugins can pass parameters in the client thread context, e.g. a key named `enforce_privileges_evaluation` and in security plugin fetch this key and if it's true, do the initialization check like this line: https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/filter/SecurityFilter.java#L369.
This approach all plugins can get the correct status of security plugin to avoid exceptions.

**What alternatives have you considered?**
1. Other plugins can put mock user information in the client thread context and security plugin can fetch them and check like in this line: https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/filter/SecurityFilter.java#L196, but the thing is the User class is within security plugin and other plugins can't access to this class so not able to create such object. Adding security plugin to other plugins doesn't seem a good option because it make the architecture much more complex and messy.
2. Other plugins can inject user to the client thread context like in this line: https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/filter/SecurityFilter.java#L197, this can somehow bypass this issue, but other plugins have to check the error message to determine it's security plugin not initialized or other security issue, because a lot of cases can cause the same security_exception issue: https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/filter/SecurityFilter.java#L479. This is not a good approach either since based on error message checking can be easier break by accident. 

**Do you have any additional context?**

**Comment by scrawfor99** [comment]
[Triage] Hi @zane-neo, thanks for filing this issue. A quick solution to your issue is to call something like check health to see whether the plugin is initialized. Passing things in the thread context is a pattern we try to avoid due to the security concerns it entails and how unmaintainable it is. Your best bet is probably to send a request beforehand to check on the initialization and then proceed accordingly. 

Going to close this issue since we cannot address the initial request to support fetching the plugin state. That being said, if the security plugin is taking too long to spin up then please file a new issue explaining the behavior you are seeing.
