### ISSUE TITLE
Memoize results of resolveIndexPatterns

### ISSUE THREAD

**Issue by tdinucci** [opensearch-project/security#421]
CC @DmitryOlshansky 

I've just come across https://github.com/opendistro-for-elasticsearch/security/pull/309 as I was preparing to start some work on trying to resolve an issue I've mentioned on the projects forum:

https://discuss.opendistrocommunity.dev/t/security-plugin-performance/2629

It looks like this PR may go some way towards resolving my issue (very high CPU on coordinating nodes) however I'm wondering if there is a reason why the cache is only kept for a single request?  Can you see much risk in making the cache longer lived, so that repeated bulk writes (which is common when using log forwarders) benefit from this too?

I am very happy to see this!

**Comment by DmitryOlshansky** [comment]
@tdinucci The reason to keep only aingle request was twofold - minimize the surface of change and to nullify any concerns about security violations that may stem from use of outdated cache entries.

Indeed the next logical step is a global cache with configurable  short TTL.  I think values in the range of a few seconds would work well without rising concerns about outdated permission information.

@vrozov what do you think - should we extend the patch in that direction?

**Comment by DmitryOlshansky** [comment]
See also other optimizations: https://github.com/opendistro-for-elasticsearch/security/pull/310

**Comment by tdinucci** [comment]
Configurable TTL sounds perfect. Would love to see this in the next release!

**Comment by vrozov** [comment]
Prior to building a shared global cache (that will bring synchronization, additional memory and outdated/stale issues), I'd like to see how much of the problem remains after @DmitryOlshansky fixes (#198 and #309). @tdinucci can you provide detailed description of the use case, or if you don't mind, create rally track that demo the problem?

**Comment by tdinucci** [comment]
I have upgraded our clusters to v1.6 and there has been a very noticeable improvement in terms of CPU use on our coordinating nodes.  However CPU is still very high compared to what it was when we were using vanilla Elasticsearch.

Our current setup is as follows - however this is a significant reduction on the levels pre-Covid-19 and what we hope to be back to again soon, the figures quoted here are ~25% of what we hope to get back to:

There are a few clusters + one cluster which is dedicated to coordinating cross-cluster-search.

Our AWS instance types, on all but the cross-cluster-search cluster are:
Master: m5.xlarge
Data: i3en.3xlarge
Coordinating: c5.2xlarge

We have 3 masters in each cluster.

Two clusters are roughly equal and each ingests per day ~2bn documents (~2.5TB of data stored).  There are ~1.5k index **series** which are managed by ISM and at the moment there are ~3.5k actual indices and a little more than 7k shards.  There are 8 data and 5 coordinating nodes in each of these clusters.

A 3rd cluster ingests about the same number of docs and amount of data as above however there are only 3 index **series** and around 1.5k shards.  There are 4 data and 2 coordinating nodes here.

There are a couple of other smaller clusters that aren't that interesting.

The 3rd cluster runs like a dream, even though its ingesting roughly the same number of docs and amount of data as the other two clusters.  This is running very happily with half the number of data nodes and less than half the number of coordinating nodes and there is still capacity to spare, especially with the coordinating nodes (which are only using ~10% CPU).

There is a very definite correlation between the number of indices and CPU use and the hot threads API states that the security plugin resolving index patterns is where the majority of time is spent (somewhere around 90% of CPU time).

Before we upgraded from OpenDistro 1.4 to 1.6 we actually had 7 coordinating nodes in the first two clusters and these were all maxed on CPU.  After the upgrade, on average 2 are maxed and the other 3 are somewhere between 20% and 60% - I think the uneven CPU distribution may be due to Logstash holding long lived connections to Elastic and new nodes can take a long time to take load from older nodes.

I hope this is enough detail for you?

**Comment by DmitryOlshansky** [comment]
Great stuff @tdinucci 

A few comments:
> A 3rd cluster ingests about the same number of docs and amount of data as above however there are only 3 index series and around 1.5k shards. There are 4 data and 2 coordinating nodes here.

This is typical even for vanila ES - lots of indices means a lot of heap spent on metadata which tends to boil CPU cores on GC activity and slower operation in general. If you can at all run async-profiler or JFR to get (sampling) flame graph of CPU time on one of these nodes, that would be terrific. 

As far as our production goes - we have cut CPU utilization from 60% -> ~10% on coordinators with latest patches (manually backported to 1.4).

One thing to check is the structure of your batches - how many different indices are present in a single batch. Avoid sending mixed batches (lots of target indices within one batch e.g. > ~5 is suboptimal for a number of reasons and not only related to OpenDistro).

> However CPU is still very high compared to what it was when we were using vanilla Elasticsearch.


Could you be more specific - is CPU x4 higher then it used to be? Are you certain the bottleneck is on the ES side and is not related to Logstash side for instance.

**Comment by DmitryOlshansky** [comment]
> Prior to building a shared global cache (that will bring synchronization, additional memory and outdated/stale issues

Yes, cache invalidation is tricky, but it could be sidestepped by keeping the TTL very small (<1sec). If the traffic is high we could be certain that we'd hit at least 100+ RPS which makes shared short-lived cache valuable.

**Comment by DmitryOlshansky** [comment]
> There are ~1.5k index series which are managed by ISM and at the moment there are ~3.5k actual indices and a little more than 7k shards.

OT: we are still using ILM and kind of wondering if we should drop it in favor of ISM. What's your experience with it ?

**Comment by tdinucci** [comment]
Thanks for the feedback @DmitryOlshansky - I will try and set aside some time to do some profiling.  It didn't look like GC'ing was what was causing the high CPU though but I will confirm.

Re. the question about our old vanilla setup.  It was ES 5.6 and was a single massive cluster with ~40k shards and ~15k indices and was storing around 25TB a day.  Logstash was (and still is) installed on separate instances.  Basically our new setup is breaking this apart into smaller clusters but even though the clusters are smaller we've had to use meatier coordinators and these are still being pushed much harder than the old ones.

Re. ISM.  This is working well on our cluster that just has the 3 big indices but not so well on the others.  It's frequently failing to rollover indices and we're then having to manually trigger a rollover when we notice shards are getting too big.  The problem seems to be due to the way ISM stores its state in the overall cluster state and has an unconfigurable timeout of 30 seconds on writes.  Basically this means if it times out for a particular index then it's basically put into an unknown state and rollovers won't occur automatically :(

**Comment by vrozov** [comment]
@tdinucci 1.6.0.0 does not include the optimization from #309. It does include the fix from #198 that helps with CPU utilization, but for a full fix, it will be necessary to upgrade to a version that will include the other fix as well.

**Comment by tdinucci** [comment]
Thanks for the info @vrozov - I did wonder this since I think I saw #309 in the 1.6 branch but not under the v1.6 tag.

Do you have any idea when this will be released, and will it be made compatible with ES 7.6.2?  Ideally I don't want to go through another full upgrade.  

Judging by the repos tags it looks like you do back-port some things however I couldn't find releases of these (either in Maven central or via the Cloudfront URL which is mentioned in this OpenDistro docs)

**Comment by tdinucci** [comment]
@DmitryOlshansky - I have sent a copy of a 2 minute JFR I've taken from one of the nodes to the email address you have on your profile.

This is from a node that is used for coordinating requests only - 99+% of requests will be bulk writes from Logstash.

Most expensive method at the minute seems to be `com.amazon.opendistroforelasticsearch.security.support.WildcardMatcher.simpleWildcardMatch(String, String)` however GCs do look like an issue too.

It's hard to get a one-size-fits-all configuration for our forwarders, because there are thousands of them however I think I could probably increase the batch sizes a bit and this may help cut down on the number of allocations overall.

**Comment by tdinucci** [comment]
A minor update on this - I've upped the size of the nursery generation to half the heap size and this has helped a little.  After a few hours of leaving things running there has been a very marked reduction in overall GC time and there has been a slight reduction in overall CPU utilisation.

As you would expect though the main hot method is still `WildcardMatcher.simpleWildcardMatch(...)`

**Comment by tdinucci** [comment]
OK, some good news with this one.  I've applied #309 to a fork of this repo and have rolled it out to a couple of the clusters.  There's been a reduction of around 50% in CPU utilisation!

Assuming no issues arise over the next couple of days this should mean I can kill a couple of the coordinators in each cluster 🎉

**Comment by vrozov** [comment]
> Thanks for the info @vrozov - I did wonder this since I think I saw #309 in the 1.6 branch but not under the v1.6 tag.

Right, there was no release on 1.6 branch since the backport.

> Do you have any idea when this will be released, and will it be made compatible with ES 7.6.2? Ideally I don't want to go through another full upgrade.

It should be released soon as part of 1.7 release. It will be compatible with ES 7.6.1 (no change since 1.6 release).

> Judging by the repos tags it looks like you do back-port some things however I couldn't find releases of these (either in Maven central or via the Cloudfront URL which is mentioned in this OpenDistro docs)

ODFE releases are not published to Maven central and are available for downloads from Cloudfront [opendistro_security-1.6.0.0.zip](https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-security/opendistro_security-1.6.0.0.zip)

**Comment by vrozov** [comment]
> OK, some good news with this one. I've applied #309 to a fork of this repo and have rolled it out to a couple of the clusters. There's been a reduction of around 50% in CPU utilisation!
> 
> Assuming no issues arise over the next couple of days this should mean I can kill a couple of the coordinators in each cluster 🎉

@tdinucci Do you still see uneven distribution of the CPU load or after applying the fix it is mostly the same across the cluster? Do you plan to do prototyping of the shared cache or there is no longer a need to do it?

@DmitryOlshansky @tdinucci What do you think about a short blog that describes your use cases and the performance improvement after applying the fix?

**Comment by tdinucci** [comment]
@vrozov Yes there still is uneven distribution however I not currently thinking that this is anything to do with the security plugin.  Logstash keeps long lived connections to Elasticsearch and I'm reasonably confident that this is the reason for the pattern of distribution.  Things do (very slowly) start to move closer to equilibrium over time.

Basically, if I restart a coordinator then the load that was on that coordinator is reasonably equally distributed across the others however the restarted coordinator will stay at close to 0% CPU for a long time, until forwarders connections are recycled.  I can speed the process up a bit by restarting forwarders manually.

I've since looked at our old vanilla ES cluster and this actually is a pattern there too.  I just hadn't noticed before because CPU was so much lower on these.

Re. prototyping the cache - I think I can answer the question as to whether it's worthwhile quite quickly (as in next week).  If it is then there'll have to be some thought put into the best/safest way to go about things.

Re. a blog post - sounds interesting to me

**Comment by tdinucci** [comment]
Not had as much time as I'd hoped to get anywhere significant with this yet but have been having some thoughts and wonder what people think.

I wonder if there should be two separate paths when it comes to index resolution.  The split could either be on reads v's writes, or wildcard v's literal.  Basically at the moment, even if wildcards are not being used the WildcardMatcher plays a big role in index resolution and this just iterates over collections looking for matches.  If wildcards weren't a concern I don't think there'd be a reason to have to consider every item in the collection and much more efficient lookups could be performed.

I suspect that getting rid of the looping for the majority of requests would help considerably and maybe even mean that we don't even need to consider caching.  

At least when it comes to using Elasticsearch as a logging platform the number of writes are always going to dwarf the number of reads so if we can make the write path very efficient (which wildcards don't factor into AFAIK) then this should get over the main bottleneck that we've been talking about.

What do you think?

**Comment by DmitryOlshansky** [comment]
> Most expensive method at the minute seems to be com.amazon.opendistroforelasticsearch.security.support.WildcardMatcher.simpleWildcardMatch(String, String) however GCs do look like an issue too.

I have a PR for that thingie. Still lots of small issues to iron out.

**Comment by DmitryOlshansky** [comment]
> The split could either be on reads v's writes, or wildcard v's literal

Yes, fast path / slow path classic optimization stuff.

In fact for writes we should only consider 1 index out of the whole bunch with the same alias.

**Comment by vrozov** [comment]
> > Most expensive method at the minute seems to be com.amazon.opendistroforelasticsearch.security.support.WildcardMatcher.simpleWildcardMatch(String, String) however GCs do look like an issue too.
> 
> I have a PR for that thingie. Still lots of small issues to iron out.

@DmitryOlshansky Please see PR #458.

**Comment by tdinucci** [comment]
That PR looks interesting.  You're both obviously actively working on stuff in this area so I'll hold off on digging into this further until you are done with that 👍 

@vrozov in terms of the blog post, are you thinking about the [OpenDistro blog](https://opendistro.github.io/for-elasticsearch/blog/)? Is there anyone else we'd need to speak to first?

**Comment by vrozov** [comment]
> @vrozov in terms of the blog post, are you thinking about the [OpenDistro blog](https://opendistro.github.io/for-elasticsearch/blog/)? Is there anyone else we'd need to speak to first?

Yes, I'll check how to post on the [OpenDistro blog](https://opendistro.github.io/for-elasticsearch/blog/).

**Comment by peternied** [comment]
Hi @tdinucci its been a long time since this was opened the performance characteristics of the plugin and OpenSearch have changed over time.  I am going to close this issue out, please reopen if you feel this issue is still warranted or create a new one if you'd like.
