### ISSUE TITLE
Replace Bouncy Castle Blake2bDigest in MaskedField

### ISSUE THREAD

**Issue by terryquigleysas** [opensearch-project/security#4212]
**Is your feature request related to a problem?**
Replace Bouncy Castle Blake2bDigest in MaskedField
https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/configuration/MaskedField.java

**What solution would you like?**
Replace with https://mvnrepository.com/artifact/com.rfksystems/blake2b

**Do you have any additional context?**
This would help towards the following issues as Blake2b is not FIPS-compliant and is not present in the Bouncy Castle FIPS libraries:
- https://github.com/opensearch-project/security/issues/3420
- https://github.com/opensearch-project/security/issues/1500

**Comment by cwperks** [comment]
[Triage] @terryquigleysas Is this issue a duplicate of this [similar issue](https://github.com/opensearch-project/security/issues/4213)? If this is a duplicate, could you please close one of the issues. Thank you!

**Comment by terryquigleysas** [comment]
@cwperks They are closely related but not duplicate issues. We will be submitting standalone code for both.

**Comment by terryquigleysas** [comment]
I think there is possibly a bug in the current Blake2b code. The **defaultSalt** variable is not passed to the Blake2bDigest constructor using the **salt** parameter as I would expect. It uses **personalization** instead. Is this correct?

![image](https://github.com/opensearch-project/security/assets/77437788/f08427a6-664c-447a-b75e-f085c3ad7e9b)

![image](https://github.com/opensearch-project/security/assets/77437788/399cc805-76ae-4e05-9b36-de806abcafd7)

In order to proceed which of these options is recommended?

1. Change to pass the **defaultSalt** variable to the Blake2bDigest constructor using the **salt** parameter. This will change the hash values. OR
2. Continue to pass the **defaultSalt** variable to the Blake2bDigest constructor using the **personalization** parameter, assuming there is a valid reason for this. The hash values generated will remain the same.

**Comment by peternied** [comment]
@terryquigleysas Thanks for digging in on this.  I'd say we need to keep the digested values the same on existing clusters.  However, I think we should do the right thing in respect to the alternative implementation of Blake2bDigest.

**Comment by terryquigleysas** [comment]
@peternied I am unsure why the digested values need to stay the same. The values are still masked, to the same length, but are now honoring the salt being passed in which appears to be the correct approach.

**Comment by peternied** [comment]
We cannot predict how the values are utilized once they are returned through the API. For instance, these might serve as obfuscated identifiers, like transforming a social security number `123-45-1234` into a hash `9fe023e1` that acts as a unique key paired with another index or external datastore. If the hash output changed from `123-45-1234` to `e90a2fdf` without intentional modifications (like altering the salt), it could sever established relationships and lead to data integrity issues post-migration.

Consistency in our current results is crucial, we must ensure that any such changes to data transformations are handled deliberately to avoid unexpected disruptions.

**Comment by terryquigleysas** [comment]
Yes, I can appreciate your point, but I would say that there is another aspect to consistency.

Since Blake2b implementations should be deterministic and return the same digest given the same parameters the current code is incorrect and should be updated as it does not produce the expected hash.

If you feel strongly enough that the digests should stay exactly the same I can undo the fix and just change the implementation. However I do have reservations about submitting code that appears to have a clear bug in it.

**Comment by peternied** [comment]
I am saying we do not replace the existing implementation, for customers that need to use a specific source of the algorithm - we add a new implementation that can be enabled - that uses the parameters correctly.   What do you think of this alternative?

I believe this is the best outcome as it allows customers that need the functionality to make the decision to change their configuration and they can always change back if they needed.

**Comment by terryquigleysas** [comment]
@peternied It looks best to split this into two issues. I will produce a new PR first thing next week that only changes the library used as that was the original intention. I will raise another issue about the salt being applied incorrectly, possibly referencing/alluding that with a comment in the code (if that isn't against your practices), and look at the approach you suggest.

Does that sound ok?

**Comment by terryquigleysas** [comment]
Created https://github.com/opensearch-project/security/issues/4274 for the existing bug
