### ISSUE TITLE
[BUG] Unauthorized response does not have response body only HTTP status

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/security#4214]
**What is the bug?**
An unauthorized response does not have a response body, only an HTTP status.

**How can one reproduce the bug?**

```bash
curl http://a:b@localhost:9300/_plugins/_security/account
```

**What is the expected behavior?**
A response should have a body

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by cwperks** [comment]
Closing as a duplicate of https://github.com/opensearch-project/security/issues/3803
