### ISSUE TITLE
Introduce Environment variable for choosing serialisation - JDK or custom

### ISSUE THREAD

**Issue by Dhruvan1217** [opensearch-project/security#4227]
**Is your feature request related to a problem?**
Currently, In some cases, users are having problems (#4085) while upgrading from 2.10 to 2.11+ where it switches the serialisation to custom serialisation technique (Ref: #2780) and have shard allocation issues.

**What solution would you like?**
* We can introduce an environment variable like `USE_JDK_SERIALIZATION=true` (Boolean) to allow the users to choose what serialisation they want to choose until all the corner cases are sorted for using custom serialisation. 
* Maybe default value for `USE_JDK_SERIALIZATION` is **false** if we think the custom serialisation is faster.

**Comment by cwperks** [comment]
Thank you for filing this request @Dhruvan1217. @parasjain1 do you have any concerns with introducing a setting (something like `plugins.security.use_jdk_serialization`) that will explicitly tell a cluster to use JDK serialization? There is a [ConfigConstant](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/support/ConfigConstants.java#L336) for this, but it is not read in as a setting and used where the serialization format is [determined](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java#L93-L96).

**Comment by scrawfor99** [comment]
[Triage] Hi @Dhruvan1217 thanks for filing this issue. @parasjain1 could you please provide your input on this request and make a contribution towards resolving the backwards compatibility issue. Otherwise we will have to pull the feature in the next version release.

**Comment by peternied** [comment]
I'll be looking into this, I don't think we should add a feature flag, but I'll address the upgrade problem
