### ISSUE TITLE
[BUG] searching for multiple indices fails without tenant permissions

### ISSUE THREAD

**Issue by tmokmss** [opensearch-project/security#4230]
### Describe the bug

Whenever I try to search for multiple indices, for example, `GET /*,-.*/_search` (i.e. query containing `,`), it will always fail due to the below error, even with `unlimited` cluster/index permission.

```json
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "no permissions for [indices:data/read/search] and User [name=unlimited, backend_roles=[], requestedTenant=null]"
      }
    ],
    "type": "security_exception",
    "reason": "no permissions for [indices:data/read/search] and User [name=unlimited, backend_roles=[], requestedTenant=null]"
  },
  "status": 403
}
```

The user has unlimited permission for both cluster and index permissions.
![image](https://github.com/opensearch-project/OpenSearch/assets/7490655/667d9526-4ace-4b7a-9b67-6b8469339cb5)

If I only search for single index, for example, `GET /*/_search`, it successes without any problem.

### Related component

Plugins

### To Reproduce

1. Create a user with a role with unlimited permission for both cluster and index permissions.
2. Send the below query:

```
curl  -X GET \
  'https://localhost:8443/*%2C-.*/_search' \
  --header 'Authorization: Basic xxxx' \
  --header 'Content-Type: application/json' \
  --data-raw '{
  "query": {
    "match_all": {}
  }
}'
```

3.  You get 403 error.

### Expected behavior

The query successes.

### Additional Details

**Plugins**
I'm using Amazon OpenSearch Service 2.11 as-is.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

After I configured tenant permission for the role as below, the error was gone. It was ok even if the tenant pemission did not have any actions assigned. 

![image](https://github.com/opensearch-project/OpenSearch/assets/7490655/40f52985-74a0-4133-8b23-5a10fa2de702)

I think it's an undocumented behavior. Is it even expected?

**Comment by scrawfor99** [comment]
[Triage] Hi @tmokmss thanks for filing this issue. Could you please provide some additional information about your scenario to help diagnose this issue? 

Specifically, could you share:

* The roles definition for the user you are using
* Whether this issue occurs without putting the pattern into the Search request HTTP URI 
* What the expected username for the active user is (it says "unlimited" but it also shows you roles as that)

Thanks

**Comment by tmokmss** [comment]
@scrawfor99 

> The roles definition for the user you are using

The original role definition:

```json
{
  "cluster_permissions": [
    "unlimited"
  ],
  "index_permissions": [{
    "index_patterns": [
      "*"
    ],
    "allowed_actions": [
      "unlimited"
    ]
  }]
}
```

Then I added tenant_permissions like this:

```json
{
  "cluster_permissions": [
    "unlimited"
  ],
  "index_permissions": [{
    "index_patterns": [
      "*"
    ],
    "allowed_actions": [
      "unlimited"
    ]
  }],
  "tenant_permissions": [{
    "tenant_patterns": [
      "*"
    ],
    "allowed_actions": [
    ]
  }]
}
```

> Whether this issue occurs without putting the pattern into the Search request HTTP URI

I haven't tested it. At least the issue reproduces when using pattern like this: `GET /*,-.*/_search`? Can you try this?

> What the expected username for the active user is (it says "unlimited" but it also shows you roles as that)

I named the user `unlimited` when I reproduced it, but I guess user name is not relevant to the issue.

**Comment by tmokmss** [comment]
@peternied Sorry, I don't understand what you mean. I'm talking about tenant permission, not cluster permission. I suspect it is a functionality bug that an empty tenant permission is required to search indices, while the error message is just saying `no permissions for [indices:data/read/search]`.

**Comment by peternied** [comment]
@tmokmss Please read the documentation I've referenced and follow up in the forums.  If you have trouble getting traction there please feel free to tag me on this issue.

**Comment by tmokmss** [comment]
@peternied 
Do you think `"cluster_permissions": [ "unlimited" ]` causing this issue? Then why adding an empty tenant permission makes the request success? I'm afraid the document does not answer the question, and there's no related post in the forum.

**Comment by tmokmss** [comment]
@peternied Hi, I found [this doc](https://opensearch.org/docs/latest/security/access-control/default-action-groups/) stating that `unlimited` on cluster permission grants complete access to action groups. Apparently it contradicts what you said.  Can you confirm which is true? 

> "cluster_permissions": [ "unlimited" ], this doesn't impart permissions 

> unlimited | Grants complete access to action groups. Can be used on an cluster- or index- level. Equates to “*”.
