### ISSUE TITLE
[BUG] /ssl/certs REST API endpoint does not return certificates from all nodes in the cluster

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/security#4280]
**What is the bug?**
The outcome of https://github.com/opensearch-project/security/pull/4252.
Existing solution returns SSL certificates info only for coordinator node but not for each node in the cluster.

**What is the expected behavior?**
`/ssl/certs` REST API should provide SSL certificate  information from each node in the cluster

**Comment by scrawfor99** [comment]
[Triage] Thanks for filing this issue @willyborankin. This seems like a good fix and we can take a look at the PR you opened for this shortly.
