### ISSUE TITLE
[FEATURE] Publish snapshots to maven for 1.3 line

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security#4281]
This issue was created because the publish snapshots to maven workflow was never successfully backported into the 1.3 branch. This means that maven artifacts for 1.3 doesn't exist. We should manually backport to ensure that going forward 1.3.x artifacts exist. 

https://github.com/opensearch-project/security/pull/2438#issuecomment-1819588107

**Comment by peternied** [comment]
@derek-ho This seems closed out to me with that code change merged - can you confirm?
