### ISSUE TITLE
[BUG] Builds fail due to SnapshotUtils.filterIndices() not being resolved

### ISSUE THREAD

**Issue by dancristiancecoi** [opensearch-project/security#4312]
**What is the bug?**
Builds are failing due to filterIndices() method being moved from SnapshotUtils to IndexUtils as part of a recent commit in core https://github.com/opensearch-project/OpenSearch/pull/8922

**How can one reproduce the bug?**
1. Pull in latest code and refresh dependencies
2. Build

**What is the expected behavior?**
Builds without errors

**Comment by dancristiancecoi** [comment]
I will create a pull request with the fix soon.

**Comment by scrawfor99** [comment]
[Triage] Hi @dancristiancecoi thanks for filing this issue. Looks like this has been addressed, so I will close this.
