### ISSUE TITLE
[BUG] Starting v2.12 - plugins.security.ssl.http.enabled cannot be set to false

### ISSUE THREAD

**Issue by c3-davidtran** [opensearch-project/security#4348]
### Describe the bug

Following upgrade to opensearch 2.12, the demo internal certificates are no longer created when plugins.security.ssl.http.enabled is set to false in opensearch.yml file.

This is a regression compared to previous versions where the demo certificates were created and used for transport layer.

### Related component

Plugins

### To Reproduce

Update the config opensearch.yml content with plugins.security.ssl.http.enabled: false.
Notice the security plugin will run with log :
```/usr/share/opensearch/config/opensearch.yml seems to be already configured for Security. Quit.```
Then no demo certificate is created.

Deployment will fail with error : 

```installation fails with error OpenSearchException[Unable to read /usr/share/opensearch/config/esnode.pem (/usr/share/opensearch/config/esnode.pem). Please make sure this files exists and is readable regarding to permissions. Property: plugins.security.ssl.transport.pemcert_filepath]```

### Expected behavior

Do not append additional plugins.security configuration if they have been provided by end users.
But still create the demo certificates unless DISABLE_INSTALL_DEMO_CONFIG is set to true

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by cwperks** [comment]
@c3-davidtran When using the `install_demo_configuration.sh` script there must be no `plugins.security...` settings in `opensearch.yml` or it will [abort running the script](https://github.com/opensearch-project/security/blob/d19a8bab517180e55fb17344afa989936411b173/src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java#L107-L126).

If you wish to disable HTTPS, then I recommend to first run the the script to install the demo configuration and then flip `plugins.security.ssl.http.enabled` to `false`.

**Comment by derek-ho** [comment]
[Triage] @c3-davidtran can you make a post in the [forums](https://forum.opensearch.org/c/security/3) to get some more assistance there? Or please re-open this issue with additional concerns if you think this is a bug.

**Comment by c3-davidtran** [comment]
@cwperks  Thank you for clarifying.
May I ask what is your recommended process for cluster upgrade in this case ?
Should we delete the generated demo certs and rerun the install_demo_configuration.sh script or does the script automatically updates the existing certificates ?
My understanding is, as part of its upgrade process, Opensearch cluster automatically renews its certificates with the certificates it is provided.

@derek-ho  I wouldn't say it's a bug, but for users who, like me, use the demo certs for transport TLS and disable REST TLS, that new behaviour breaks our opensearch upgrade flow because additional steps have to be done.
It could be beneficial to update the documentation and provide warning/information notice for this specific use case.

**Comment by cwperks** [comment]
@c3-davidtran There is no renewal process for demo certificates. The demo certificates are static and widely known. They can change between minor versions, but are only meant to be used for demonstration purposes to show how to configure a cluster securely.

The process for generating self-signed certs from be found in the DEVELOPER_GUIDE: https://github.com/opensearch-project/security/blob/main/DEVELOPER_GUIDE.md#refreshing-demo-certificates

**Comment by c3-davidtran** [comment]
@cwperks Got it. I was actually concerned of what would happen if they change between minor versions as you implied.
But by looking at the doc you've sent and my understanding of the script, I'm assuming even if the demo certs change between minor versions, they will be automatically updated on the cluster.
