### ISSUE TITLE
Index patterns in role configuration is case-sensitive although index name must be in lowercase

### ISSUE THREAD

**Issue by NovikovEvgeny** [opensearch-project/security#435]
ODFE version: 1.0.2

TEST CASE:

1. Create a role
```
{
  "index_permissions": [
    {
      "index_patterns": [
        "CONTENT_*"
      ],
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "indices:admin/*",
        "indices:data/*"
      ]
    }
  ],
  "tenant_permissions": [],
  "cluster_permissions": []
}
```

2. and map it to `test` internal user 
```
{
  "backend_roles": [],
  "hosts": [],
  "users": [
    "test"
  ]
}
```

3. Login with test user and try to create an index (index name must be lowercase, otherwise wi'll get `"reason": "Invalid index name [CONTENT_TEST], must be lowercase",` error):
```
PUT content_test
{
}
```

OBSERVED BEHAVIOR:
security error:
```
"reason": "no permissions for [indices:admin/create] and User [name=test, roles=[someRole], requestedTenant=__user__]"
```

EXPECTED BEHAVIOR:
index is created 

Comments:
1. if we set lowercase index pattern in role configuration, everything works as expected
2. yes, I know there is no reason to use uppercase in index pattern in role configuration, but then maybe it makes sense to automatically transform patterns to lowercase?

**Comment by debjanibnrj** [comment]
Hi @NovikovEvgeny,

Thanks for your question. Elasticsearch currently only supports lowercase index names (see: https://www.elastic.co/guide/en/elasticsearch/guide/current/_document_metadata.html#_index).

**Comment by NovikovEvgeny** [comment]
Hi @debjanibnrj 

Thank you for your answer


Yes, I understand that ES supports only lowercase in index names 

The “problem” is that ODFE role config  `index_patterns` property is case sensitive. and there is no sense to be case sensitive. 

So, if I create such tech user and accidentally missconfigure the role with UpperCase in `index_pattern`, this permission will never be applied for any action. 

The behavior of the ODFE security plugin e.g. could be similar to the behavior of the ES itself - an error could be thrown if index pattern contains Capital letter. Or index pattern can just be transformed to lowercase.

I mean nobody should use Capital Letter in `index_pattern` property since it is impossible to use Capital Letters in index names on creation

Thanks

**Comment by nateynateynate** [comment]
Thanks for bringing this up @NovikovEvgeny - if I'm not asking for too much, could you check to see if your observation is still true in the latest version of OpenSearch and then re-file if you're still having issues?
