### ISSUE TITLE
[BUG] ActionGroup has `type` property which can be set as null using REST API 

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/security#4374]
**What is the bug?**
The `type` property for action groups never been validated. As result it is possible to crate/update an action group without it and this group is never involved into permissions check.  Besides it is possible to set any string for the type.

**What is the expected behavior?**
REST API should validate action group `type` and accept two possible values: `cluster` and `index`.

**Comment by scrawfor99** [comment]
[Triage] Hi @willyborankin thanks for filing this issue. Nice catch. We should definitely validate the action groups coming in.
