### ISSUE TITLE
check why JOSE library is escaping it and find if there is a way to ignore escaping character in Jose library itself, instead unescaping it.

### ISSUE THREAD

**Issue by hardik-k-shah** [opensearch-project/security#438]
We should check why JOSE library is escaping it and find if there is a way to ignore escaping character in Jose library itself, instead unescaping it.

_Originally posted by @hardik-k-shah in https://github.com/opendistro-for-elasticsearch/security-advanced-modules/pull/16_

**Comment by cliu123** [comment]
The issue should have been resolved by [this PR](https://github.com/opensearch-project/security/pull/1546)
