### ISSUE TITLE
[BUG] DNFOF does not work for some APIs

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security#4413]
**What is the bug?**
Some APIs which DNFOF should work for do not. Namely:
GET _cat/aliases

A similar issue was fixed for cat/indices here: https://github.com/opensearch-project/security/pull/3236. It seems like the initial issue also called out aliases as a bug, but that was not addressed: https://github.com/opensearch-project/security/issues/1815

**How can one reproduce the bug?**
Create a user without access to some of the following list, would expect DNFOF setting to work, but it does not

**What is the expected behavior?**
DNFOF should work

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho, thank you for filing this issue. This seems like a good addition based on the past discussion.
