### ISSUE TITLE
[FEATURE] security_authentication cookie lacks SameSite attribute

### ISSUE THREAD

**Issue by simonelbaz** [opensearch-project/security#4421]
During `proxy` authentication flow, the `security_authentication` cookie lacks SameSite attribute.

A warning is emitted by the Console browser tab:

![image](https://github.com/opensearch-project/security/assets/1821095/6acd2fac-7962-4705-9c7f-ba38fd7eb08e)

**What solution would you like?**
Would it be possible to set SameSite to 'Strict' or make it available as a parameter ?

**What alternatives have you considered?**
This is warning. So that's OK.

**Comment by shikharj05** [comment]
Hi, this is configurable today. Have you tried adding ```opensearch_security.cookie.isSameSite: Strict```  to ``opensearch_dashboards.yml`` file and restarting dashboards?
