### ISSUE TITLE
Investigate ISM failures caused during 2.15 RC generation for a bug fix to remove static meta-fields

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#4475]
During 2.15 RC generation ISM ran into integ-test failures where a warning was prominent:
```log
[2024-06-15T03:57:00,516][WARN ][o.o.i.c.IndicesClusterStateService] [node_name_9200] [openactionit_index_1][0] marking and sending shard failed due to [failed to create index]
java.lang.NullPointerException: Cannot invoke "org.opensearch.index.mapper.MapperService.getMetadataFields()" because the return value of "org.opensearch.index.IndexService.mapperService()" is null
	at org.opensearch.security.configuration.SecurityFlsDlsIndexSearcherWrapper.<init>(SecurityFlsDlsIndexSearcherWrapper.java:65) ~[?:?]
```

This was root-caused to be a fix for the issue: https://github.com/opensearch-project/security/issues/4349 via PR: https://github.com/opensearch-project/security/issues/4349

A revert PR: https://github.com/opensearch-project/security/pull/4474 was introduced to unblock 2.15. This fix is still present in 2.x line and will be included in next release unless the issue is investigated and fixed.

Expectations:
- [ ] Issue is fixed and shipped in v2.16.0
OR
- [ ] Issue is not fixed and will have to be reverted from 2.x line until a fix is found.

--

Other relevant info:

https://github.com/opensearch-project/security/pull/4474#issuecomment-2176901030

**Comment by scrawfor99** [comment]
[Triage] Going to mark as triaged.
