### ISSUE TITLE
[BUG] FLS rule doesn't apply when retrieving mappings of a closed index

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#4477]
**What is the bug?**
When making a GET request to retrieve field mappings for an index:
1. if index is **open**, FLS rules are applied and field marked as excluded is not returned as part of the mapping
2. if index is **closed**, FLS rules are **not** applied and field marked as excluded is returned as part of the mapping.

**How can one reproduce the bug?**
1. Login as admin and add sample ecommerce data.
2. Create a new role `test-role` with :
    a. cluster permissions: cluster_all
    b. index permissions: 
        i. pattern: *
        ii. FLS: includes: currency, excludes: customer_gender
3. Create a test user and map it to test-role.
4. Open an incognito tab and log in as test user.
5. Navigate to Dev Tools on both tabs
6. On test user tab, execute: `GET opensearch_dashboards_sample_data_ecommerce`. You should not see a field mapping for `customer_gender`
7. On admin user tab, execute: `POST opensearch_dashboards_sample_data_ecommerce/_close` to close the index
8. On test user tab, execute: `GET opensearch_dashboards_sample_data_ecommerce` again. You should see customer_gender field on the returned mappings

**What is the expected behavior?**
FLS rules should apply regardless of index status. Otherwise there is potential of information leak.

**Comment by kumargu** [comment]
Hey @DarshitChanpura , can i pick up this issue?
