### ISSUE TITLE
[BUG] Role opensearch_dashboards_read_only + index read permissions isn't sufficient to view Dashboard Page, 403

### ISSUE THREAD

**Issue by kpolicar** [opensearch-project/security#4496]
**What is the bug?**
403 Forbidden error when attempting to open a dashboard page that performs an index search. The user has been granted read permission for this index.

**How can one reproduce the bug?**
1. Create index pattern: **example-***
2. Create dashboard that searches the index pattern **example-***
3. Create internal user: **example_user**
4. Map **example_user** to **opensearch_dashboards_read_only** role ([Reference](https://opensearch.org/docs/latest/security/access-control/users-roles/#predefined-roles))
5. Create role **example_role** with following properties:
    - Cluster permissions: cluster_composite_ops_ro ([Reference](https://opensearch.org/docs/latest/security/access-control/users-roles/#defining-a-basic-read-only-role))
    - Index permissions:
        - example-*: read
    - Tenant permissions: global_tenant: read
6. Login with **example_user**, attempt to access the dashboard
7. Error: page doesn't load

**What is the expected behavior?**
The user has been granted the permission, the dashboard page should load.

**What is your host/environment?**
 - OS: AWS-managed Opensearch
 - Version OpenSearch_2_13_R20240520-P2
 - Plugins: Default

**Temporary solution**
Grant the user **read** permission on the **.kibana** and **.opensearch_dashboards** index patterns.

**Do you have any screenshots?**
Screenshots depict a dashboard that queries the datastream **demo-logs-kubernetes**
*Before applying temporary solution:*
![image](https://github.com/opensearch-project/security/assets/9630422/20ef2f76-93bb-45aa-bd78-66f89c847753)
*After applying temporary solution:*
![image](https://github.com/opensearch-project/security/assets/9630422/c5be4576-9282-4331-81b7-085ee331d6fa)
**opensearch_dashboards_user** compared to **opensearch_dashboards_read_only**
![image](https://github.com/opensearch-project/security/assets/9630422/6d5f54d1-c6d3-4602-b0de-1d95126d18c8)

I would expect these permissions be granted as part of the **opensearch_dashboards_read_only** role

**Comment by scrawfor99** [comment]
[Triage] Hi @kpolicar, thank you for filing this issue. This looks like a configuration scenario where you can expect the best help from the forum: https://forum.opensearch.org/. Going to close this for now.
