### ISSUE TITLE
Add granular Kibana roles

### ISSUE THREAD

**Issue by CarlMeadows** [opensearch-project/security#45]
Add action groups and/or roles that will allow for more granular access control over Kibana ad its functionality including.

A role that will block users from logging into Kibana. 
Add the ability to associate permissions that would allow the ability to granularly  block/hide Kibana features including Console, Advanced Settings, Index Management, Security and Alerting.

**Comment by ThisUsedToBeAnEmail** [comment]
This is useful when you want to build a stand-alone application using the Elasticsearch apis which has complicated data filters built into it's logic, and you do not want the user to have access to Kibana where they can see all data for any time period.

My use case is: 
On login to my stand alone application - I authenticate with an internal service.
If the user authenticates this returns an JWT token which will always have permissions to authenticate to Elasticsearch indexes. If the internal admin has an internal privilege "kibana" then the JWT token can also be used to authenticate to Kibana. (Note: when I say internal, this information is not stored in ELK)

My current work around is:
Never exposing the JWT to the client and always authenticating server side, and then passing through the cookies back to the client.

But it would be favourable to have the ability to protect this from elk side also.

**Comment by davidlago** [comment]
Closing this for now as we are rethinking how we do permissions in Dashboards and this could either no longer be relevant or change shape as a result.

**Comment by davidlago** [comment]
Re-opening after an offline conversation where perhaps we can add more details to this and use this issue to collect some of the additional permission ideas for Dashboards.

**Comment by jimishs** [comment]
To expand on the initial requirements - Today OpenSearch Dashboards has 3 types of users - 1/Those who are read only - can only access dashboards and nothing else. 2/Security managers or admins who have access to the security panel to configure the permissions of their users 3/Users with a set of cluster permissions and index permissions. 

As an admin if you wanted to restrict certain sets of users to only be able to see the alerts panel in Dashboards, there is no option to do that. Similarly if you wanted to restrict certain users to see only a subset of the Dashboards features (this includes, ISM, Alerting, Anomaly Detection and other plugins as well), there isnt a workflow that allows you to control the granular access to Dashboards features. 

The proposal here is to create additional permissions that would allow for example bank ABC to give access to dashboards and alerts to its analysts, while limiting access to view or access ISM policies or other cluster configuration. 

As @ThisUsedToBeAnEmail also suggests, this could be useful to create an external stand alone application that has better control over what aspects of Dashboards it wants to make accessible to its users.

**Comment by peternied** [comment]
[Triage] There is great thoughts in this space, this is in flux.  We don't have active plans to make improvements.  If there are other specific features please create issues for them.

@jimishs Please consider the topics raised in this issue as you think about the other efforts in OpenSearch / OpenSearch Dashboards, thanks!
