### ISSUE TITLE
If you start an OpenSearch cluster with 3 nodes at the same time, check the status of the nodes and the error message OpenSearch Security Not Initialized is displayed. [Bug]: 

### ISSUE THREAD

**Issue by hubcomsix** [opensearch-project/security#4567]
### Describe the bug

If you start an OpenSearch cluster with 3 nodes at the same time, check the status of the nodes and the error message OpenSearch Security Not Initialized is displayed. 

### To reproduce

If you start an OpenSearch cluster with 3 nodes at the same time, check the status of the nodes and the error message OpenSearch Security Not Initialized is displayed. 

### Expected behavior

# PossibleSolution 
Restart the cluster every 30 seconds and restore the cluster to normal

**Comment by scrawfor99** [comment]
[Triage] Hi @hubcomsix, thanks for filing this issue. Could you please provide more information on the scenario you are encountering? For example, could you share any configuration changes you have made from the default config? Could you also share the time frame you are checking and whether you have let the cluster come up successfully before checking for the security index?

**Comment by stephen-crawford** [comment]
[Triage] Going to close this since it appears this issue is no longer relevant.
