### ISSUE TITLE
[Workflow] Security IT workflows failed in other plugins because the "Push snapshots to maven" job failed in security plugin

### ISSUE THREAD

**Issue by LantaoJin** [opensearch-project/security#4576]
**What is the bug?**
Security IT workflows in SQL plugin [failed](https://github.com/opensearch-project/sql/actions/runs/9968000398/job/27542744022?pr=2829) with 
```
Unexpected exception java.lang.NoSuchMethodError: 'java.util.List org.opensearch.indices.SystemIndexRegistry.matchesSystemIndexPattern(java.lang.String[])'
  java.lang.NoSuchMethodError: 'java.util.List org.opensearch.indices.SystemIndexRegistry.matchesSystemIndexPattern(java.lang.String[])'
 at org.opensearch.security.privileges.SystemIndexAccessEvaluator.getAllSystemIndices(SystemIndexAccessEvaluator.java:182) ~[opensearch-security-2.16.0.0-SNAPSHOT.jar:2.16.0.0-SNAPSHOT]
```
due to the "Push snapshots to maven" job failed
https://github.com/opensearch-project/security/actions/runs/9967076404/job/27540175842 

Could any maintainer help to re-run it to fix the issue?

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by reta** [comment]
> Ping code owners @cliu123 @cwperks @DarshitChanpura @peternied @RyanL1997 @scrawfor99 @reta @willyborankin, it blocks PRs for 2.x branch in other plugins!

@LantaoJin this is a question for CI/infra team(s), I pinged @peterzhuamazon on a few occurrences https://github.com/opensearch-project/opensearch-java/pull/1086#issuecomment-2233568475 but no news so far.

**Comment by LantaoJin** [comment]
@reta do you mean manually re-run the workflow job will continue fail? If not, please help to trigger re-run manually.

**Comment by reta** [comment]
> @reta do you mean manually re-run the workflow job will continue fail? If not, please help to trigger re-run manually.

@LantaoJin  sometimes it helps (rerun, let's see) but the cause of the issue is not addressed

**Comment by reta** [comment]
FYI, opened this one, please feel free to add more repos: https://github.com/opensearch-project/opensearch-ci/issues/480

**Comment by DarshitChanpura** [comment]
@LantaoJin This change in signature was addressed by this PR: https://github.com/opensearch-project/security/pull/4574
Would you try re-running to see if the issue is fixed?

**Comment by LantaoJin** [comment]
It has worked with manual help from @reta.
