### ISSUE TITLE
[FEATURE] Add support for configuring BCrypt password hashing

### ISSUE THREAD

**Issue by dancristiancecoi** [opensearch-project/security#4590]
**What solution would you like?**
Currently password hashing with BCrypt is not configurable.  It will be useful for cluster administrators to be able to configure properties such as:

- number of rounds
- version of the BCrypt algorithm

**Do you have any additional context?**
The work for this was completed as part of https://github.com/opensearch-project/security/pull/4524. Raising this issue so we can tag it for 2.16

**Comment by scrawfor99** [comment]
[Triage] Hi @dancristiancecoi, thanks for filing this issue. This sounds like a good addition to the existing BCrypt support. Will mark as triaged.
