### ISSUE TITLE
Rename 'Global' tenant

### ISSUE THREAD

**Issue by mporracindie** [opensearch-project/security#46]
It would be really useful to be able to rename a tenant even the Global one.

**Comment by CarlMeadows** [comment]
Moved to Security repo - and flagged as a feature enhancement - being able to rename all tenants is a good request.

**Comment by scrawfor99** [comment]
[Triage 2/6] Maintains relevance, keeping in the backlog as a useful request.

**Comment by davidlago** [comment]
Tenants's new incarnation is being discussed as part of the [Workspaces RFC](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4615). Closing this one to make sure we capture all the feedback in one place.
