### ISSUE TITLE
[BUG] OPENSEARCH_INITIAL_ADMIN_PASSWORD Not Working on Upgraded Cluster

### ISSUE THREAD

**Issue by B2RN** [opensearch-project/security#4602]
**What is the bug?**
Setting the admin password on an existing cluster via the `.env` method and including:

```
- OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
```

in the `docker-compose.yml` file does not work on an existing cluster. Result being that it's not possible to change the admin password and the cluster is stuck with the default password.

**How can one reproduce the bug?**
1. Have a cluster with the admin password set to default before 2.12
2. Update the cluster to 2.12 or above (2.15 in our case)
3. Try to change the password as specified [here](https://opensearch.org/docs/latest/security/configuration/demo-configuration/#setting-up-a-custom-admin-password)
4. You'll notice that the admin password remains unchanged and the default credentials still work

**What is the expected behavior?**
The admin password should change based on what's being read from the `.env` file and passed to the `docker-compose.yml` file.

**What is your host/environment?**
 - OS: CentOS Linux release 8.5.2111
 - Version v 2.15.0

**Do you have any screenshots?**

**Do you have any additional context?**
At the moment it's unclear whether this is the preferred method of changing the password whenever one wants or just the method to set it up when first making the cluster. 

I've done a search for anything password related in the logs but there's nothing there so I assume it's not a problem with the password itself. The password also passes the checks when trying to reset it manually via the dashboard, but that doesn't work due to the user being restricted.

**Comment by DarshitChanpura** [comment]
An upgraded cluster with existing data will not have updated password since the security configuration is not overwritten in the `.opendistro-security` index. Hence, the new password will not be applied.

**Comment by scrawfor99** [comment]
[Triage] Hi @B2RN, thanks for filing this issue. Since this is the expected behavior going to go ahead and close this issue.
