### ISSUE TITLE
[BUG] Audit Log publish Incorrect FAILED_LOGIN event for Successful login attempt by SAML user on SAML enabled Domain

### ISSUE THREAD

**Issue by niravpi** [opensearch-project/security#4608]
**What is the bug?**
For SAML enabled domain, audit log publishes ```FAILED_LOGIN``` event for successful login attempt of SAML user.

**How can one reproduce the bug?**
* Create any SAML enabled domain
*  Enable Audit log for that domain
*  Now try to lg in to dashboard via valid SAML user creds
* You can see in the audit logs event there will be ```FAILED_LOGIN```

**What is the expected behavior?**
For SAML enabled domain, there should be no ```FAILED_LOGIN``` audit log event for successful login attempt of SAML user

**What is your host/environment?**
- OS: Linux
- Plugins: Security

**Do you have any screenshots?**
![Screenshot 2024-07-30 at 1 07 04 PM](https://github.com/user-attachments/assets/bd71c21b-1082-473e-ba1a-b35fe31595bc)

**Do you have any additional context?**
NA

**Comment by expani** [comment]
The code path that likely triggers https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/auth/BackendRegistry.java#L296-L299

**Comment by cwperks** [comment]
[Triage] Thank you for filing this issue @niravpi. That auditlog entry corresponds to this [line](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/auth/BackendRegistry.java#L306) and it will always be hit on SAML login because the SAML login flow requires `challenge` to be set to `true` to enter the `reRequestAuthentication` flow. This line will always be hit on successful login for SAML and it is confusing since the overall login is successful. I am in favor of removing this audit log entry for the SAML login flow.

**Comment by TristisOris** [comment]
got same issue with 2.19

zabbix server, https requests, login name not logged for unknown reason.
```
{
  "_index": "security-auditlog-2025.03.05",
  "_id": "TKcRZZUBx750GiUNlUtB",
  "_version": 1,
  "_score": null,
  "_source": {
    "audit_cluster_name": " ",
    "audit_node_name": " ",
    "audit_rest_request_method": "HEAD",
    "audit_category": "FAILED_LOGIN",
    "audit_request_origin": "REST",
    "audit_node_id": "XYNU66GNTJa3mpPFpOhWYw",
    "audit_request_layer": "REST",
    "audit_rest_request_path": "/",
    "@timestamp": "2025-03-05T06:50:06.016+00:00",
    "audit_request_effective_user_is_admin": false,
    "audit_format_version": 4,
    "audit_request_remote_address": " ",
    "audit_node_host_address": " ",
    "audit_rest_request_headers": {
      "User-Agent": [
        "Zabbix 7.2.4"
      ],
      "Host": [
        " :9200"
      ],
      "Accept-Encoding": [
        "deflate, gzip, br, zstd"
      ],
      "Accept": [
        "*/*"
      ]
    },
    "audit_request_effective_user": "<NONE>",
    "audit_node_host_name": " "
  },
  "fields": {
    "@timestamp": [
      "2025-03-05T06:50:06.016Z"
    ]
  },
  "highlight": {
    "audit_rest_request_headers.User-Agent": [
      "@opensearch-dashboards-highlighted-field@Zabbix@/opensearch-dashboards-highlighted-field@ 7.2.4"
    ]
  },
  "sort": [
    1741157406016
  ]
}
```

another service.
```
{
  "_index": "security-auditlog-2025.03.05",
  "_id": "_08mZZUBB4xG5wuqRv6c",
  "_version": 1,
  "_score": null,
  "_source": {
    "audit_cluster_name": " ",
    "audit_node_name": " ",
    "audit_rest_request_method": "POST",
    "audit_category": "FAILED_LOGIN",
    "audit_request_origin": "REST",
    "audit_node_id": "w-7srv34QRONPporg3TY2g",
    "audit_request_layer": "REST",
    "audit_rest_request_path": "/ /_doc",
    "@timestamp": "2025-03-05T07:12:42.140+00:00",
    "audit_request_effective_user_is_admin": false,
    "audit_format_version": 4,
    "audit_request_remote_address": " ",
    "audit_node_host_address": " ",
    "audit_rest_request_headers": {
      "User-Agent": [
        "opensearch-php/2.5.0 (Linux 6.8.0-53-generic; PHP 8.1.31)"
      ],
      "Host": [
        " "
      ],
      "Accept": [
        "application/json"
      ],
      "Content-Length": [
        "7909"
      ],
      "Content-Type": [
        "application/json"
      ]
    },
    "audit_request_effective_user": "logger",
    "audit_node_host_name": " "
  },
  "fields": {
    "@timestamp": [
      "2025-03-05T07:12:42.140Z"
    ]
  },
  "sort": [
    1741158762140
  ]
}
```
