### ISSUE TITLE
[FEATURE] Create APIs to support configuration of rate limiting

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security#4614]
**Is your feature request related to a problem?**
Coming from: https://github.com/opensearch-project/security-dashboards-plugin/issues/2070, there is a request to support configuration of rate limiting/auth failure listeners via UI. In order to better support this, I am proposing that the backend security plugin expose some way to modify these settings, instead of only being able to be modified via config, securityadmin.sh, or admin cert.
**What solution would you like?**
An API that would be able to create/modify/delete these settings.
**What alternatives have you considered?**
None
**Do you have any additional context?**
None

**Comment by cwperks** [comment]
[Triage] @derek-ho It sounds like a good idea to have an API for this. Can you also post some detail about the API like the route, params and responses?

**Comment by derek-ho** [comment]
Hi @cwperks I was thinking of something like the following (subject to change):
```
GET /authfailurelisteners/${id} - return response like:
200
{type: ip
allowed_tries: 10
time_window_seconds: 3600
 block_expiry_seconds: 600
max_blocked_clients: 100000
max_tracked_clients: 100000}
```
```
GET /authfailurelisteners - return response like:
200
[
{...}, ....
]
```

```
DELETE /authfailurelisteners/${id} - return response like:
200
```

```
POST /authfailurelisteners
{type: ip
allowed_tries: 10
time_window_seconds: 3600
 block_expiry_seconds: 600
max_blocked_clients: 100000
max_tracked_clients: 100000}

 - return response like:
201
```

```
PUT /authfailurelisteners/${id}
{type: ip
allowed_tries: 10
time_window_seconds: 3600
 block_expiry_seconds: 600
max_blocked_clients: 100000
max_tracked_clients: 100000}

 - return response like:
201
```
