### ISSUE TITLE
[BUG] Changelog for 2.12.0 does not mention switching of libraries

### ISSUE THREAD

**Issue by jarkko-rantavuori-vincit** [opensearch-project/security#4617]
Changelog for 2.12.0 (https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.12.0.md) does not mention switch from org.apache.cxf.rs.security.jose to com.nimbus.jose.jwk (https://github.com/opensearch-project/security/pull/3595). This slowed us down considerably when trying to find out what was the breaking change between 2.11.1 and 2.12.0.

**Comment by cwperks** [comment]
[Triage] @jarkko-rantavuori-vincit Thank you for filing this issue. I think the release notes should be retroactively updated to reflect that a change in the JWT library was made in 2.12.
