### ISSUE TITLE
[BUG] kibana_read_only role has no permissions

### ISSUE THREAD

**Issue by eugene7421** [opensearch-project/security#4626]
**What is the bug?**
After installing OpenSearch 2.15 and OpenSearchDashboards 2.15 using docker-compose, there is an empty kibana_read_only role with no permissions.

**How can one reproduce the bug?**
1. Go to https://opensearch.org/versions/opensearch-2-15-0.html
2. Click on 'Download docker-compose.yml'
3. Install OS and OSD using docker-compose
4. After installing that, log in as an admin to OSD
5. Click on Menu button -> Security -> Roles -> search kibana_read_only
6. Click on kibana_read_only. There are no permissions for that.

**What is the expected behavior?**
After installing OS and OSD, there is a predefined kibana_read_only role with necessary permissions. 

**What is your host/environment?**
 - OS: Ubuntu
 - Version: 22.04
 - Plugins

**Do you have any screenshots?**
I have attached the screenshot below.
![image](https://github.com/user-attachments/assets/2b1d8d0d-79a0-4c38-9b68-dc2126a64277)

**Comment by stephen-crawford** [comment]
[Triage] Hi @eugene7421, thank you for filing this issue. Someone can double check, however, this role is intended strictly to access the frontend kibana/opensearch dashboards. As a result you will not see the cluster permissions or index permissions filled here. Someone can quickly take a look just to confirm and then close this issue.

**Comment by shikharj05** [comment]
Hi @eugene7421 - 
@stephen-crawford is correct, this is a reserved role https://github.com/opensearch-project/security/blob/main/config/roles.yml#L6-L7 which is meant to be coupled with configuration like  
```opensearch_security.readonly_mode.roles: ["kibana_read_only"]```

You can read more about it here- https://opensearch.org/docs/latest/security/access-control/users-roles/#opensearch-dashboards-readonly_mode

**Comment by stephen-crawford** [comment]
Hi @shikharj05, thanks for following up on this and providing insight. I am going to go ahead and close this issue since it working as intended.

**Comment by eugene7421** [comment]
The issue is not solved. 

The line `opensearch_security.readonly_mode.roles: [kibana_read_only]` is included in the configurations out-of-the-box.

There are no permissions for the kibana_read_only role. In my understanding, every role has to have some permissions. In my tests, I can't make it work using the kibana_read_only role out-of-the-box. I definitely have to add permissions for this role to open a dashboard. 

The proof that the kibana_read_only role has no permissions out-of-the-box:
![image](https://github.com/user-attachments/assets/b5a76d58-3828-424d-81c1-db6c81eb43d3)

I can make it work using the kibana_user role instead of the kibana_read_only role. But kibana_user has also write and delete permissions. I need a role with only read permissions for kibana users. My kibana_user has permissions out-of-the-box as expected: 
![image](https://github.com/user-attachments/assets/3bcaf3e3-a655-45bb-bab3-dbf76eb252c9)
