### ISSUE TITLE
[BUG] Auth Failure Listener API follow ups

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security#4712]
**What is the bug?**
There are a few gaps surrounding the new auth failure listener APIs that should be addressed:

- The naming should be more general, to extend support for API tokens and other mechanisms of rate limiting in the future (to prevent breaking changes)
- Auth failure listeners/rate limiters should be added to the existing mechanism of delegating API access in this PR: https://github.com/opensearch-project/security/pull/2411/files. This should only require a simple addition into this list: https://github.com/opensearch-project/security/blob/d2daa9870ca586d80588428d90caacd9739de583/src/main/java/org/opensearch/security/dlic/rest/api/RestApiAdminPrivilegesEvaluator.java#L63

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by cwperks** [comment]
[Triage] Thank you for filing this issue @derek-ho. This should follow the same permissions model as other security APIs where its either permitted by role or individually permitted with a `restapi:admin/...` permission.
