### ISSUE TITLE
[BUG] Roles inconsistency

### ISSUE THREAD

**Issue by n9** [opensearch-project/security#4730]
**What is the bug?**
[The current documentation](https://github.com/opensearch-project/documentation-website/blob/978c1576f88727738997e18cc5fadd223bc15115/_security/configuration/yaml.md?plain=1#L268) says: 

> **roles.yml**
> This file contains any initial roles that you want to add to the Security plugin. Aside from some metadata, the default file is empty, because the Security plugin has a number of static roles that it adds automatically.

**How can one reproduce the bug?**
1. Read [the current documentation](https://github.com/opensearch-project/documentation-website/blob/978c1576f88727738997e18cc5fadd223bc15115/_security/configuration/yaml.md?plain=1#L268) to see the text above.
2. Open [/usr/share/opensearch/config/opensearch-security/roles.yml](https://github.com/opensearch-project/security/blob/30760168263404e628a25fd13a54100d2610810c/config/roles.yml#L5) from the opensearch image and see that the file contains roles.

**What is the expected behavior?**
Either the file should be empty or the documentation should not say that.

**What is your host/environment?**
 - OS: N/A
 - Version 2.16
 - Plugins: Security

**Do you have any screenshots?**
Not needed.

**Do you have any additional context?**

> because the Security plugin has a number of static roles that it adds automatically

Is this still true? Where I can find it in the source code?

**Comment by cwperks** [comment]
[Triage] @n9 `kibana_read_only` is a special role w/o permissions. It get's functionality through a setting in `opensearch_dashboards.yml`:

```
 opensearch_security.readonly_mode.roles: [kibana_read_only]
```

A user mapped to this role can view saved objects, but cannot save saved objects. Saved objects is a generic term for items such as:

- index patterns
- visualizations
- dashboards
- etc.

Closing this issue. Please let me know if you need any further information.

For general questions I would also recommend posting on the OpenSearch forum: https://forum.opensearch.org/c/security/3

**Comment by n9** [comment]
@cwperks What about the *bug* that the default roles file is not empty? (But according to the documentation it should be.)

**Comment by cwperks** [comment]
@n9 You're right, that should be changed. The `roles.yml` file contains default roles that grant functionality to plugins that are shipped in the default distributions. The documentation-website should be updated to reflect that.

**Comment by n9** [comment]
>  The roles.yml file contains default roles that grant functionality to plugins that are shipped in the default distributions.

@cwperks But why `kibana_user` is static, but `kibana_read_only` is default?

**Comment by cwperks** [comment]
I can't really tell based on the history: https://github.com/opensearch-project/security/pull/96

There is some overlap between the meanings of "reserved" and "static" and if I had to guess, it was added to `config/roles.yml` at first and never changed.

This comment goes into the difference between static and reserved: https://github.com/opensearch-project/security/issues/4387#issuecomment-2200708847
