### ISSUE TITLE
Adding ssl settings to support certs with separate clientAuth and serverAuth extended key usage

### ISSUE THREAD

**Issue by lavacat** [opensearch-project/security#474]
Right now this plugin and official ES supports ssl certs only with both clientAuth and serverAuth usage property.
See [Note](https://www.elastic.co/guide/en/x-pack/5.4/ssl-tls.html#installing-node-certificates)

I think it will be more flexible and secure to support separate certs for clientAuth and serverAuth. Sometimes company security enforces separate usage and one can only get certs with explicit usage.

Correct me if I'm wrong but it will be a small change to include new set of settings and pass new cert [here](https://github.com/opendistro-for-elasticsearch/security/blob/663053a28aaebcd721b79318642a8131cb56dd01/src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/DefaultOpenDistroSecurityKeyStore.java#L363)

Proposed settings:
`
OPENDISTRO_SECURITY_SSL_TRANSPORT_MIXED_KEY_USAGE_ENABLED = "opendistro_security.ssl.transport.mixed_key_usage_enabled";
OPENDISTRO_SECURITY_SSL_TRANSPORT_MIXED_KEY_USAGE_ENABLED_DEFAULT = true;
OPENDISTRO_SECURITY_SSL_TRANSPORT_SERVER_PEMKEY_FILEPATH = "opendistro_security.ssl.transport.server.pemkey_filepath";
OPENDISTRO_SECURITY_SSL_TRANSPORT_SERVER_PEMKEY_PASSWORD = "opendistro_security.ssl.transport.server.pemkey_password";
OPENDISTRO_SECURITY_SSL_TRANSPORT_SERVER_PEMCERT_FILEPATH = "opendistro_security.ssl.transport.server.pemcert_filepath";
OPENDISTRO_SECURITY_SSL_TRANSPORT_SERVER_PEMTRUSTEDCAS_FILEPATH = "opendistro_security.ssl.transport.server.pemtrustedcas_filepath";
`

Are you ok with me contributing back this change?

**Comment by hardik-k-shah** [comment]
Few things:

1) Are you referring to Transport certificate used for node to node communication or certificate for rest layer ? 

2) Based on your configuration in message and code pointer, it shows about TLS certificate plugin uses for node to node communication. For node to node communication each node can be client and a server at a given time. And that certificate is purely for node to node communication. Not sure what security benefit you will achieve by providing two different certificate?

3) You can still configure different certificate for each node to use for node to node communication. 
like Node 1 can use n1.example.com and node 2 can use n2.example.com and so on.. 
and these node will use their own dedicated certificate to authenticate and communicate with each other. 

4) In your sample configuration, I am not seeing information regarding client transport cert.

**Comment by lavacat** [comment]
@hardik-k-shah 
1. I'm referring to transport certificate used for node to node communication

2. By default certificate will have `extendedKeyUsage = serverAuth,clientAuth`, but it's also possible to generate 2 certificates with `extendedKeyUsage = serverAuth` and `extendedKeyUsage = clientAuth`. We are forced to use second way with 2 certs. I don't want to argue security benefits but think of it as another way to provide certs.
If I use our server cert in current setup, I get `javax.net.ssl.SSLHandshakeException: Extended key usage does not permit use for TLS **client** authentication`
If I use client cert, I get `javax.net.ssl.SSLHandshakeException: Extended key usage does not permit use for TLS **server** authentication`

3. Agreed, but it won't solve our issue. We'll still have 2 certs instead of 1 for each node.

4. I was going to use existing OPENDISTRO_SECURITY_SSL_TRANSPORT_PEMKEY_FILEPATH as client cert, but it's probably cleaner to create new OPENDISTRO_SECURITY_SSL_TRANSPORT_CLIENT_PEMKEY_FILEPATH

I think it's less common to have extendedKeyUsage set, but I found some references of people having similar issue. The solution is usually to generate new cert, but in our case it's enforced.
https://discuss.elastic.co/t/ssl-between-elasticsearch-nodes-fails/67082
https://discuss.elastic.co/t/client-unable-to-trust-server-certificate/223404
https://discuss.elastic.co/t/ssl-between-elasticsearch-nodes-fails/67082
https://www.ibm.com/support/pages/elk-services-cannot-be-started-using-external-certificate

**Comment by scrawfor99** [comment]
[Triage] This issue has been resolved.
