### ISSUE TITLE
Debian package shouldn't install demo configuration by default

### ISSUE THREAD

**Issue by rlueckl** [opensearch-project/security#48]
The Debian package **opendistro-security** is installing the demo configuration by default via the *postinst* script. This causes problems with the [Puppet Forge Elasticsearch](https://forge.puppet.com/elastic/elasticsearch) module which installs the configuration by default to `/etc/elasticsearch/$instance_name`:

```
Setting up opendistro-security (0.9.0.0-0) ...
OpenDistro for Elasticsearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/elasticsearch
This script maybe require your root password for 'sudo' privileges
Unable to determine Elasticsearch config directory. Quit.
dpkg: error processing package opendistro-security (--configure):
 subprocess installed post-installation script returned error exit status 255
dpkg: dependency problems prevent configuration of opendistroforelasticsearch:
 opendistroforelasticsearch depends on opendistro-security (>= 0.9.0); however:
  Package opendistro-security is not configured yet.
 opendistroforelasticsearch depends on opendistro-security (<< 0.9.1); however:
  Package opendistro-security is not configured yet.
```

I understand that a demo configuration can be pretty useful and it's nice that there is a tool for it, but why is it installed by default through *postinst*?

This is problematic for installations on production systems, especially (Puppet-)managed systems or setups with custom configuration.

Could the *postinst* be changed so that in only outputs a message saying something like:
> If you want a demo configuration run the following script...

Another option would be updating `install_demo_configuration.sh` to check for more than the default directories. This would probably open up a whole new can of worms, like:
 * how do you reliably determine the configdir (`/etc/elasticsearch/$instance_name` is just an example based on the Puppet Forge module)
 * you could use `/etc/default/elasticsearch` (`ES_PATH_CONF`) but that would be a) very OS-specific b) again wrong for the Forge Module which uses `/etc/default/elasticsearch-$instance_name`

All of the above also applies to the RPM package.

**Comment by rlueckl** [comment]
Any news?

**Comment by apsivam** [comment]
+1
I would also like to see the demo cert installation using postinstall scriptlet removed for RPM packages. This is causing a big issue in automating deployment in an environment that I support. I have a workaround in place for now but please prioritize this in your planning.

**Comment by deknos** [comment]
demos should be additional packages lying somewhere under /usr .. /doc/... and there should be a script in the packages under /usr/share ... which installs the demo. that would be the sane solution to this.

**Comment by pawelw1** [comment]
@rlueckl have you found a solution to your issue?

**Comment by rlueckl** [comment]
Wow, this is an old ticket. :smile: 

Our workaround was that we installed the opendistro plugin with `elasticsearch-plugin` and then install the remaining components (`opendistro-alerting`, `opendistro-sql`) from the Debian repo. This way the demo config isn't installed. The `opendistro` package is just a meta-package which installs the other packages.

Example code for puppet:

```
  exec { 'Install opendistro-security':
    command     => '/usr/share/elasticsearch/bin/elasticsearch-plugin install -b com.amazon.opendistroforelasticsearch:opendistro_security:0.9.0.0',
    unless      => '/usr/bin/test -d /usr/share/elasticsearch/plugins/opendistro_security',
    environment => [
      "ES_JAVA_OPTS=-Dhttp.proxyHost=company.proxy -Dhttp.proxyPort=3128 -Dhttps.proxyHost=company.proxy -Dhttps.proxyPort=3128",
      "ES_PATH_CONF=/etc/elasticsearch/${cluster_name}",
    ],
    require     => Class['elasticsearch'],
  } ->
  package { [
    'opendistro-alerting',
    'opendistro-sql',
  ]:
    ensure  => $opendistro_version,
    require => [
      Class['elasticsearch'],
      Apt::Source['opendistro'],
    ],
  }
```

**Comment by pawelw1** [comment]
@rlueckl thanks for sharing. I was curious about the solution.

**Comment by cliu123** [comment]
@opensearch-project/engineering-effectiveness Would you please transfer this issue to [opensearch-build](https://github.com/opensearch-project/opensearch-build) repo?

**Comment by cliu123** [comment]
ODFE is not actively supported anymore. We recommend you to move to OpenSearch that is actively supported. But OpenSearch hasn't support Debian package so far. Please file an issue in the [opensearch-build repo](https://github.com/opensearch-project/opensearch-build/issues) if you still need any help with this. Thanks! Closing this issue.
