### ISSUE TITLE
[BUG] `integTest` not called with test workflows during release

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/security#4805]
**What is the bug?**

Coming from the issue https://github.com/opensearch-project/opensearch-metrics/issues/68 to index the failed tests to the metrics cluster which will be useful during the release cycle to exactly find out the failed test metrics for a given RC, what was found with the security plugin is the `integTest` was renamed to `integrationTest` and security plugin uses the default [integtest.sh](https://github.com/opensearch-project/opensearch-build/blob/main/scripts/default/integtest.sh) part of the build repo. The script calls the `./gradlew integTest` for running the integration tests in a repo. 

With the change to `integrationTest` the `integTest` is skipped and not called, here is the sample [stdout log ](https://ci.opensearch.org/ci/dbc/integ-test/2.16.0/10154/linux/x64/tar/test-results/8503/integ-test/security/with-security/stdout.txt)
```
> Task :copyPluginPropertiesTemplate
> Task :pluginProperties
> Task :processTestResources
> Task :testClasses
> Task :integTest SKIPPED
```

**How can one reproduce the bug?**

Clone the repo and run `./gradlew integTest` and see the output as `integTest` is skipped.

**What is the expected behavior?**

The expected behavior is run the integrations test using the build repo test workflows during the release. The [test workflow](https://github.com/opensearch-project/opensearch-build/wiki/Testing-the-Distribution) is generic, either calls the `integTest` task by default or uses the script part of its own repo. Example https://github.com/opensearch-project/cross-cluster-replication/blob/main/scripts/integtest.sh.

**Do you have any additional context?**

- Would recommend to continue using the `integTest` and not `integrationTest` as gradle task so that no changes needs to be made in the testing side of things during the release.
- If want to proceed with `integrationTest`, the security repo need to onboard to new `integtest.sh` which should be part of the security repo and during the release testing this script would be called by default.

**Comment by prudhvigodithi** [comment]
Adding @cwperks @peterzhuamazon @gaiksaya @getsaurabh02.

**Comment by cwperks** [comment]
@prudhvigodithi, can you provide more info on the new `integtest.sh`? I know that a lot of repos used to contain a file called `scripts/integtest.sh` that has since been removed. The one in the security plugin was removed in https://github.com/opensearch-project/security/pull/3844/files. Can this file be restored and updated to reflect how integ tests are currently run in the repo?

**Comment by gaiksaya** [comment]
Hi @cwperks 
If the integration test task is any different than the default one used [here](https://github.com/opensearch-project/opensearch-build/blob/main/scripts/default/integtest.sh), you can create an integtest.sh in this repo with the right task under `scripts` folder.
