### ISSUE TITLE
multi-tenancy with multiple JWT/OpenID endpoints?

### ISSUE THREAD

**Issue by wyllys66** [opensearch-project/security#487]
I'm pretty sure this is not possible today (1.7.0), but Im looking for  a way to support multiple OIDC endpoints within a single elasticsearch service.

We use keycloak with multiple realms (i.e. tenants) for a web-based service. User's of the service authenticate and get OIDC tokens that are passed around to various internal services, including elasticsearch.   Currently, the authc configuration for openid (and jwt) auth only supports the use of a single jwt key or a single openid connect url which means that the service can only authenticate tokens from a single keycloak tenant (realm).  I think it's possible to make it such that the openid_auth module could determine the authentication based on the info in the token that is presented and not be limited to a single auth domain/tenant/realm.

The presented OIDC access token contains enough information to derive the well-known URL ("iss" value + ".well-known/openid-configuration").  Knowing that URL, you can query for everything else needed to verify the token and complete the auth flow. This would enable elasticsearch to support auth from OIDC tokens from multiple tenants.

Has anyone considered this?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
