### ISSUE TITLE
[BUG] Setting for Anonymous Authentication is not working as expected

### ISSUE THREAD

**Issue by sukhbir-singh** [opensearch-project/security#4883]
**What is the bug?**
I’ve installed the security plugin in OpenSearch version 2.15 and followed the developer guide on GitHub. However, when I access localhost:9200, it prompts me for a username and password. Although entering the credentials works, I want to disable this authentication. My primary use of the security plugin is to add TLS to the transport layer, So I want to bypass authentication for all HTTP endpoints like localhost:9200 and localhost:9200/_cat/health?v

I tried enabling the config.dynamic.http.anonymous_auth_enabled setting as mentioned in the OpenSearch documentation ([here](https://opensearch.org/docs/2.15/install-and-configure/configuring-opensearch/security-settings/)), but it didn’t work. The authentication prompt still appears when accessing localhost:9200. How can I remove/disable this authentication in security plugin config ?

**How can one reproduce the bug?**
1. In OpenSearch 2.15, Install security plugin, following the developer guide.
2. After installing it you will see that when you open localhost:9200, it will ask for authentication username and password.
3. Now update the `config\opensearch-security\config.yml ` this config and set this config to true.
```
config:
  dynamic:
    http:
      anonymous_auth_enabled: true
```

4. After setting this config, start open search again and open localhost:9200. Observe that it is still asking for same authentication credentials.

**What is the expected behavior?**
The expected behavior is that by settings these configurations we should be able to remove the authentication while accessing localhost:9200 and other APIs

**What is your host/environment?**
 - OS: Windows 11
 - Version: OpenSearch 2.15
 - Plugins: Security Plugin 2.15

**Do you have any screenshots?**
![image](https://github.com/user-attachments/assets/cabfa26b-58b0-4fd7-9c9d-f27876bcac64)

**Do you have any additional context?**
I think there should be more information in the open search documentation page related to this.

**Comment by cwperks** [comment]
@sukhbir-singh When using anonymous auth make sure that no auth configuration has `challenge` set to `true.

> Either enables or disables anonymous authentication. When you enable anonymous authentication, all defined HTTP authenticators are non-challenging. See [The challenge setting](https://opensearch.org/docs/latest/security/authentication-backends/basic-authc/#the-challenge-setting).

https://opensearch.org/docs/latest/security/access-control/anonymous-authentication/#configuration

Closing this issue. Please re-open if you suspect there to be a bug. This sounds like a misconfiguration.
