### ISSUE TITLE
Please support index settings of audit logs

### ISSUE THREAD

**Issue by xial-thu** [opensearch-project/security#498]
## background

I set up a single-node opendistro cluster in a testing environment where I do not need HA, fault tolerance, etc. I edited node role and discovery type, and started the cluster successfully. Then I initialized security plugin and installed kibana.

All works fine until I checked cluster health and found that some shards of audit logs are unassigned. 

## what happended

Here's the output.

```
green  open .kibana_1                    oW3iHN1zRVihYPMDEyXgug 1 0  1 0   3.6kb   3.6kb
yellow open security-auditlog-2020.06.09 Ya2DF7ELQnC664BCOwIBWw 5 1 33 0 482.9kb 482.9kb
green  open .opendistro_security         Ew7J6oNsQIy8Y04tbNC6PA 1 0  5 0  28.3kb  28.3kb
```

What confuses me is that other indices smartly adjust themselves to 1 shard, 0 replicas in a single-node cluster, but audit log remains the default setting.

I checked out the [security-audit-logs doc](https://opendistro.github.io/for-elasticsearch-docs/docs/security-audit-logs/) and did not find how to configure index settings.

## what do I expect?

x-pack offers audit-log index setting by

```yaml
xpack.security.audit.index.settings:
  index:
    number_of_shards: 1
    number_of_replicas: 1
```

I'd appreciate if opendistro offers the same capability. I't will save users' effort on adjusting index setting.

**Comment by yoke88** [comment]
use index template to set index settings and use index policy to delete old security audit logs

**Comment by Marci24h** [comment]
A small template could look like this: 
```
{
  "index_patterns": ["security-auditlog-*"],
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas" : 0
  }
```

with curl upload it the following way:
```
curl -X PUT -uadminuser -p "https://node.domain.tld:443/_template/security-auditlog?pretty" -H 'Content-Type: application/json' -d'
{
  "index_patterns": ["security-auditlog-*"],
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas" : 0
  }
}
'
```

Make sure the URL matches your environment. You may have to change the protocol from https to http or replace the port.
You should get `{"acknowledged":true}` in response.

hope it helps,
best regards

**Comment by scrawfor99** [comment]
[Triage] This issue appears to have been addressed.
