### ISSUE TITLE
Intern or Internal?

### ISSUE THREAD

**Issue by ajdelgado** [opensearch-project/security#4980]
In this example says intern but in the documentation it says internal
https://github.com/opensearch-project/security/blame/2f870c72fe7b14a03c7ed0df33df29cfbe25f263/config/config.yml#L110

**Comment by cwperks** [comment]
Both intern and internal are accepted: https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV7.java#L259-L260

**Comment by cwperks** [comment]
The name `intern` has caused a lot of confusion. I support marking this as deprecated and moving all instances to `internal` instead while still supporting the use of `intern` for existing clusters. Closing this issue.
