### ISSUE TITLE
Suggested feature: access control for user that need to import object 

### ISSUE THREAD

**Issue by jlopezza** [opensearch-project/security#518]
Suggested feature: access control for user with operator role whom will need to import object into Kibana  (Kibana > Management > Saved Objects > Import)  do NOT need administrator privileges like defining user/roles others ( Kibana > Security > Authentication Backends/ Permissions and Roles , Kibana > Alerting. The general idea is to have to define/create a role for user with less access to administration functions an ONLY have Permissions required to import object into Kibana.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
