### ISSUE TITLE
Feature: Prioritize Security index shard restore before other shards

### ISSUE THREAD

**Issue by DandyDeveloper** [opensearch-project/security#534]
During Kubernetes upgrades, the default update stratergy defaults to reboot all data nodes. 

The issue with this is, the nodes have to retrigger their sharding health, which also means waiting for the .opendistro_security index with credentials to also be recovered.

The "real" solution here is to make sure multiple data nodes don't go offline at the same time, but in these cases, wouldn't it make more sense to trigger this index to take priority? Is this feasible?

**Comment by vrozov** [comment]
@DandyDeveloper do you suggest plugin to manage the priority of the .opendistro_security index or looking for a way to accomplish this in your installation? For former, I am not sure that there is a solution that fits everyone. For the second, please see https://www.elastic.co/guide/en/elasticsearch/reference/current/recovery-prioritization.html

**Comment by DandyDeveloper** [comment]
@vrozov Yeah, sorry I should have been clearer/provided the above link myself. 

This is something I can trigger, yes, but I think it would be good when opendistro initializes this that it added the priority itself.

**Comment by vrozov** [comment]
@DandyDeveloper It is not clear what will be a good default that security plugin can use (what will work for one installation may not work for another). Do you have a suggestion?

**Comment by DandyDeveloper** [comment]
@vrozov As most clusters initialize with no priority, why not just set an abnormally high number like 9999 on the index prio? 

Because otherwise, the cluster is completely inaccessible should a DR scenario happen, until the ES initialization eventually gets to the shards for this index.

**Comment by DandyDeveloper** [comment]
@vrozov Follow up on this. It looks like base users need a specific role or just plain have no access to updating this index:

```
{
    "error": {
        "root_cause": [
            {
                "type": "security_exception",
                "reason": "no permissions for [] and User [name=admin, backend_roles=[all_access], requestedTenant=null]"
            }
        ],
        "type": "security_exception",
        "reason": "no permissions for [] and User [name=admin, backend_roles=[all_access], requestedTenant=null]"
    },
    "status": 403
}
```

Looks as though it's a protected index, so I can't seem to add priority to this, even if I wanted to.

**Comment by vrozov** [comment]
Changing (any) settings on the `.opendistro_index` requires the admin certificate to be provided in the request.

**Comment by debu99** [comment]
the .opendistro_index  index.priority should be added by default during the first time creation

**Comment by bgagnon** [comment]
Isn't this issue a duplicate of #68 ?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
