### ISSUE TITLE
Why is IP address required in SAN fields for Elasticsearch certificates?

### ISSUE THREAD

**Issue by namrataa-p** [opensearch-project/security#540]
Hi,

I'm using elasticsearch-oss v6.7.1 and ODFE security plugin v0.9.0.0.
I was wondering why IP addresses are required in certificates that are used for Elasticsearch.
I did come across _No subject alternative names matching IP address_ error that's covered in [check-certificate-ip-addresses](https://opendistro.github.io/for-elasticsearch-docs/docs/troubleshoot/tls/#check-certificate-ip-addresses) in troubleshoot section and while it's not an issue to include it in SAN fields but when IP address changes often (as it's the case in our environment), it makes the certificates useless and we have to update it every time.
Is there a way to stop Elasticsearch from checking for IP address in certificates?

**Comment by Anthony7774** [comment]
@namrataa-p The [docs](https://opensearch.org/docs/latest/security-plugin/configuration/generate-certificates/) for certificates have been updated, you can use common name (CN) for the certificate that matches the hostname of the intended node with plugins.security.ssl.transport.enforce_hostname_verification set to true

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
