### ISSUE TITLE
Regex support for REST API whitelisting config

### ISSUE THREAD

**Issue by rahulkarajgikar** [opensearch-project/security#554]
Currently, REST API whitelisting checks the exact URI of incoming requests. This can sometimes be an issue when trying to whitelist PUT/PATCH APIs, since each exact URI needs to be individually whitelisted. A feature that enables whitelisting 'requests' in this manner: 

requests: /_opendistro/_security/api/rolesmapping/* : ["PUT"]

could be a potential solution to allow all PUT requests with URI's that start with /_opendistro/_security/api/rolesmapping to be whitelisted.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
