### ISSUE TITLE
User impersonation doesn't work in default Kubernetes + Ingress environment

### ISSUE THREAD

**Issue by dpotapov** [opensearch-project/security#56]
The header `opendistro_security_impersonate_as` contains underscore characters, which are banned by default:
http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers

Ingress can be configured with this server-level option:
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-underscores-in-headers

However not everyone have possibility to change it. Thus would be good to have impersonation header with dashes at least...

**Comment by nateynateynate** [comment]
Hi @dpotapov! Thanks for the issue. It's been a while since submission - I'd love to find out if this is still causing you any pain. Do you mind trying this out on the latest version of OpenSearch to see if those underscored headers are still being blocked? 

Thanks! 

Nate

**Comment by dpotapov** [comment]
hi, I'm no longer working on that project. Feel free to close the issue since no one else hit into this.
