### ISSUE TITLE
Members Of the Same AD Group Can't Login

### ISSUE THREAD

**Issue by jokerzt0wn** [opensearch-project/security#62]
We’ve begun playing with Open Distro security and have run into an interesting issue. We have configured AD authc/z and for the most part can logon without any issues. However, there are certain users that are in the same mapped AD role as I am that are unable to login. When those users try to login, they get this message:

"An Error Occurred while checking your credentials, make sure you have an ElasticSearch Cluster secured by security running." 

There are two differences (not sure if they matter) with these users:

They have almost double the number of AD groups on their account
When searching for their userid in the domain they have other special accounts that show up (the ID is a tad different, eg user123-special).

Much appreciated!

**Comment by pawelw1** [comment]
@jokerzt0wn have you found a solution? If not, can you check what is the security_authentication cookie size for failed authentication?
