### ISSUE TITLE
Adding index recovery priority to .opendistro_security index

### ISSUE THREAD

**Issue by mporracindie** [opensearch-project/security#68]
As an enhancement, I would like to suggest that the out of the box the .opendistro_security index had priority for recovery due to how critical it is.

(https://www.elastic.co/guide/en/elasticsearch/reference/current/recovery-prioritization.html)

**Comment by bgagnon** [comment]
This is really important. On a large node with several hundred shards, it can take a very long time to recover gigabytes of indices. The very small `.opendistro_security` index should be given top priority.

**Comment by cliu123** [comment]
Duplicate of #534
