### ISSUE TITLE
Maven central release fix for incorrect SHA hash

### ISSUE THREAD

**Issue by sujithvm** [opensearch-project/security#754]
- Upload only necessary jars to sonatype. Currently the maven release task pushes ZIP and SHA files.
- SHA 512 file for `opendistro_security-<version>-.zip` is being replaced with SHA for `opendistro_security-<version>-securityadmin-standalone.zip.`
```
[INFO] Installing /home/runner/work/security/security/target/releases/opendistro_security-1.10.1.0-securityadmin-standalone.zip.sha512 to /home/runner/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security/1.10.1.0/opendistro_security-1.10.1.0.zip.sha512
```
- Remove `com.floragunn:checksum-maven-plugin` artifact if not needed

**Comment by sujithvm** [comment]
PR to generate SHA 512 hash only for `opendistro_security-<version>.zip` https://github.com/opendistro-for-elasticsearch/security/pull/753

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
