### ISSUE TITLE
Metrics for security

### ISSUE THREAD

**Issue by sachingsachin** [opensearch-project/security#793]
Does OpenDistro provide metrics for security like number of FAILED_LOGINs per minute etc?
It would be good to have them as part of metrics API (and JMX Mbeans).
The documentation should mention the same too.

**Comment by cliu123** [comment]
Please look at https://opendistro.github.io/for-elasticsearch-docs/docs/security/audit-logs/
The FAILED_LOGIN event tracked could be used to generate the metrics that you want.

**Comment by sachingsachin** [comment]
I am aware of this one @cliu123 
But wanted to have it exposed as a metric (in an API or a JMX mbean etc).
Parsing logs to get this is not very sophisticated IMO.

**Comment by jimishs** [comment]
@sachingsachin Are you keeping these logs on your cluster or sending it to another destination?

**Comment by sachingsachin** [comment]
I have a few clusters running this.
In all of them the logs are first created on disk.
And in some of them, they are sent to a splunk cluster after which the file is deleted.
But the point is convenience of having these metrics.
I can get them by having log-scrapping or from splunk but that is not convenient and sometimes can be performance intensive too.
Hence the need to have them exposed through metrics/JMX-mbenas

**Comment by scrawfor99** [comment]
[Triage] @opensearch-project/transfer-request could you please move this issue to [security-analytics repo](https://github.com/opensearch-project/security-analytics). (So you know @jimishs)

**Comment by davidlago** [comment]
We are not currently considering adding this support via API calls. The information is captured, though, as indicated above, so sending it to the right place where those numbers can be summarized and exposed via an API call is possible.
