### ISSUE TITLE
Add exclusion in index_permission for role

### ISSUE THREAD

**Issue by mxmorin** [opensearch-project/security#807]
With the API, ES allows index patterns with indices exclusion when prefixed par -

I need to allow all indices for a role except those starting with admin
I've tried to add 2 index patterns in Kibana like this with no luck

![image](https://user-images.githubusercontent.com/58942529/97322003-ab576500-186f-11eb-8ccf-bff7eed77687.png)

Is it possible to add this feature ?

**Comment by debjanibnrj** [comment]
Thanks for your question @mxmorin.

Index Patterns are just normal regex patterns, you should be able to use index pattern `/^(?!admin).*/` to solve your issue. 

Let me know if you run into any issues.

**Comment by mxmorin** [comment]
Thanks for your response
Seems to work. 
Maybe need to add a text saying index pattern are regex and not those used by ES index pattern 
Close this issue

**Comment by mxmorin** [comment]
I reopen this issue because this is not working in discovery.
With regex, /^(?!admin).*/ we can't create index pattern admin* but with pattern * discovery show documents in admin* indices

**Comment by scrawfor99** [comment]
[Triage] Closing this issue because the exclusion of permissions for index permissions is actively being avoided in the new Identity project. Please reach out to @scrawfor99 for more details. Thank you.
