### ISSUE TITLE
Trusting multiple root CA

### ISSUE THREAD

**Issue by reynaldiwijaya** [opensearch-project/security#86]
I am using opendistro with SSL authentication in my kubernetes cluster. In that way, i am using Kubernetes CA as my CA, and it worked fine if my logstash is from the same cluster.

Right now, I have a situation where I need to deploy the logstash from a different cluster. This resulting in SSL error since it could not trust the certs that my logstash are using. When I read the documentation, it says that opendistro can trust multiple CA through this key

opendistro_security.ssl.transport.pemtrustedcas_filepath

However, no luck so far when I try to add my other kubernetes root CA certs to this key. Is there a practical example of how the opendistro plugin can trust more than one root CA?

**Comment by jimishs** [comment]
Thanks for your question @reynaldiwijaya and apologies from the Open Distro team. Could you give this another try with the most recent release 1.7.0.0 The documentation has also been updated. For the flag you mentioned above, could you check if the root CA is present in the config directory as well?

opendistro_security.ssl.transport.pemtrustedcas_filepath ->
Path to the root CAs (PEM format), which must be under the config directory, specified using a relative path. Required.

**Comment by thenom** [comment]
Do you have an example of how this looks within the yml?

**Comment by vrozov** [comment]
Please take a look at https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/tls/

**Comment by thenom** [comment]
Hi @vrozov 

I have been through this documentation and it doesnt give an example or mention how to supply more than 1 CA cert.

opendistro_security.ssl.transport.pemtrustedcas_filepath

asks for:
```
Path to the root CAs (PEM format), which must be under the config directory, specified using a relative path. Required.
```
This doesnt state whether it should be a single PEM file with multiple CA's in it our if it should be a folder with multiple separate PEM files or can a list be provided to this property, i.e.:
```
opendistro_security.ssl.transport.pemtrustedcas_filepath:
  - ca-cert1.pem
  - ca-cert2.pem
```

**Comment by debjanibnrj** [comment]
Hi @thenom, It should be a single pem file with multiple CA's

**Comment by thenom** [comment]
Thanks for that @debjanibnrj.  This is good information to know, especially when the CA needs replacing because the nodes need to go through a transition period where they trust the old and new.

This info should probably be in the documentation.

**Comment by sergiospa** [comment]
Hi @debjanibnrj @thenom how did you manage to do this? I have dumped the content of the local CA on the remote CA, resulting a file like the following:

```
-----BEGIN CERTIFICATE-----
<remote CA.pem content>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<local CA.pem content>
-----END CERTIFICATE-----
```

Elasticsearch restarts successfully on the remote node, but when I try to read information from the local cluster, I get the following response:
```
[root@centos7-50 vagrant]# curl -XGET -k -u admin:admin https://<LOCAL_NODE_IP>:9200/<remote_cluster_name>:<index_name>/_search?pretty
{
  "error" : {
    "root_cause" : [
      {
        "type" : "transport_exception",
        "reason" : "handshake failed because connection reset"
      }
    ],
    "type" : "connect_transport_exception",
    "reason" : "[][<REMOTE_NODE_IP>:9300] general node connection failure",
    "caused_by" : {
      "type" : "transport_exception",
      "reason" : "handshake failed because connection reset"
    }
  },
  "status" : 500
}
```

I really don't know how to proceed. I did it successfully with Xpack but with Open Distro I'm having a hard time. Any help would be appreciated!

Thanks,
Sergio.

**Comment by thenom** [comment]
Hi @sergiospa,

To be honest i pretty much did the same thing, i concatenated the 2 certs into one.  Are you getting protocol\cipher issues as i am not sure i got handshake failed messages.  Does OD support the  protocol (i.e. TLS1.2) and your ciphers on the server?

**Comment by nateynateynate** [comment]
Hi @reynaldiwijaya - it looks like you've found a workaround. That's great! If you're still using ODFE, you may want to give this another try using the latest OpenSearch which has superseded ODFE.
