### ISSUE TITLE
Deprecation message found in kibana dev tools with 1.12

### ISSUE THREAD

**Issue by yuxitang-amzn** [opensearch-project/security#868]
**Version**: 1.12.0.0
**ES/Kibana version**: 7.10.0
**Description**: seeing following warning message after a query. `#! Deprecation: this request accesses system indices: [.kibana_-152937574_admintenant_1, .kibana_-866730430_readonly_1, .kibana_1, .kibana_92668751_admin_1], but in a future major version, direct access to system indices will be prevented by default.`
**Impact**: currently didn't find impact on any function.

Screenshot:
![image](https://user-images.githubusercontent.com/63078162/101083929-175d7500-3562-11eb-87da-7ad7ca5b9b32.png)

Seems this message comes from elasticsearch: 
~~~
% curl -v https://localhost:9200/kibana_sample_data_flights/_search --insecure -u admin:admin
...{some verbose information}
< Warning: 299 Elasticsearch-7.10.0-51e9d6f22758d0374a0f3f5c6e8f3a7997850f96 "this request accesses system indices: [.kibana_-152937574_admintenant_1, .kibana_-866730430_readonly_1, .kibana_1, .kibana_92668751_admin_1], but in a future major version, direct access to system indices will be prevented by default"
...{response body}
~~~

**Comment by apsivam** [comment]
Any update on this issue? Is there a workaround (other than reducing root logger level) to suppress just this deprecation warning?

**Comment by cliu123** [comment]
Not sure what your index `kibana_sample_data_flights` looks like. Could you explain why your search for `kibana_sample_data_flights` is trying to access those system indices?

**Comment by cliu123** [comment]
@yuxitang-amzn What does the `index kibana_sample_data_flights` look like? I wonder why the search for index  kibana_sample_data_flights is trying to access those system indices.

**Comment by yuxitang-amzn** [comment]
@cliu123 `kibana_sample_data_flights` is a sample data set provided by kibana. Actually querying any data will show this warning. You could also try adding a doc.

~~~
curl -XPOST -v -u admin:admin --insecure "https://localhost:9200/my-data-stream/_doc/?pretty" -H 'Content-Type: application/json' -d'
{
  "@timestamp": "2020-12-07T11:06:07.000Z",
  "user": {
    "id": "8a4f500d"
  },
  "message": "Login successful"
}
'
~~~

And you will see the warning message in the middle of the output.

**Comment by apsivam** [comment]
Just want to document the workaround for people running 1.12

https://discuss.opendistrocommunity.dev/t/upgrading-from-odfe-1-11-0-to-1-12-0-deprection-logs-complain-about-a-lot/4389/3

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
