### ISSUE TITLE
Netscape security validation

### ISSUE THREAD

**Issue by franco-martin** [opensearch-project/security#871]
A reproducible test case or series of steps:
Im using pfsense to generate certificates. I had to edit the /usr/local/share/pfSense/ssl/openssl.cnf with [this](https://redmine.pfsense.org/projects/pfsense/repository/revisions/46869dd2b5ebf32e8297d65f98444fb38d314336/diff) to be able to generate certificates for both client and server auth. 
When elasticsearch is starting I get the following exception:
Caused by: sun.security.validator.ValidatorException: Netscape cert type does not permit use for SSL client

Are we still validating netscape? can it be bypassed?

The version of our code being used
1.11.0

**Comment by vrozov** [comment]
Please provide full exception stack trace.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
