### ISSUE TITLE
LDAP user with cyclic group membership causes infinite loop and GC thrashing

### ISSUE THREAD

**Issue by jtackaberry** [opensearch-project/security#887]
We have some users in Active Directory with circular group memberships:

```
Group A
  |
  +-- Group B
         |
         +-- Group C
                |
                +-- Group A (cycle)
```

When such a user authenticates, the process appears to enter an infinite loop.  I'm not certain the loop is *actually* infinite, but it does begin pulling gigabytes from LDAP over several minutes, enters GC hell, and stops responding to SIGTERM.  SIGKILL is our corrective measure (which is obviously problematic for other reasons). Packet captures indicate continuous traversal of groups involved in the cycle.

Interestingly, setting `resolve_nested_roles` to `false` doesn't mitigate.  (Although we need that functionality, I tried disabling it as an experiment / act of desperation.)

I suppose there needs to be some sort of "seen list" to prevent traversal into already-visited groups.

**Comment by vrozov** [comment]
Please provide stack trace (jstack <pid> > stact.txt)

**Comment by jtackaberry** [comment]
Hi @vrozov, thanks for taking a look at this.

I believe I have oversimplified the conditions to recreate the problem.  I've tried to reproduce things using my own account by creating the circular membership described above, but no dice.

I managed to flag down the affected user today to get him to reauthenticate and grabbed two stack traces:

[jstack-before.log](https://github.com/opendistro-for-elasticsearch/security/files/5683567/jstack-before.log): a baseline taken before the user authenticated
[jstack-during.log](https://github.com/opendistro-for-elasticsearch/security/files/5683568/jstack-during.log): taken a minute or so after the user attempted authentication, after about 500MB of data was exchanged with LDAP.

I've also included an excerpt from the packet capture (just a copy/paste from Wireshark's summary view), with sensitive details redacted, to give you a sense of what's happening, if you have the patience to look at it. :)

[wireshark.txt](https://github.com/opendistro-for-elasticsearch/security/files/5683571/wireshark.txt)

The user in question is a direct member of `AAAA SW Stakeholders` which itself is a member of the `AAAA Stakeholders` group, and this is where the endless loop seems to begin.  `AAAA SW Stakeholders` is not revisited, but `AAAA Stakeholders` is revisited after a protracted journey through several other nested groups, and the adventure repeats ad nauseum until the process is killed.  (Possibly the loop would terminate after 15 minutes, but I've not waited longer than that as service is impaired during this time.)

Another idea -- and possibly a good idea in any case -- would be to provide a configurable recursion depth.  This would be an easy way to address this problem, and might also be useful for other reasons.  For example, our users complain about very slow login times (takes about 20-30 seconds), with typical accounts pulling about 20-40 MB from LDAP after many round trips.  (Our organization makes extensive use of AD groups and has plenty of real-world data messiness, as I'm sure you noticed.)  Although we do need to support nested roles for our ODFE cluster, in practice we only need to resolve to a depth of about 5.

So a configurable recursion depth limit could fix this problem as well as potentially improving our login times.

Thanks!

**Comment by vrozov** [comment]
Hi @jtackaberry, there is a configuration that limits nested depth for ldap role resolution. Please try setting `max_nested_depth` in the LDAP authorization config. The default value is 30.

**Comment by jtackaberry** [comment]
Ah!  The affected user is offline at the moment but once I can get him to test again I'll follow up.

However, I think I have some reason to be pessimistic: looking at `jstack-during.log` I notice there are exactly 30 nested occurrences of:

```
    at com.amazon.dlic.auth.ldap.backend.LDAPAuthorizationBackend.resolveNestedRoles(LDAPAuthorizationBackend.java:1020)
```

So that tells me we are hitting the default limit of 30, and despite that we're still toppling the node.

This suggests any limit may behave the same way.  I'll report back once I have the user test it, but perhaps tracking previously visited roles and preventing recursion if the role has been visited before is the most robust solution after all.

Thanks much @vrozov

**Comment by jtackaberry** [comment]
Setting `max_nested_depth` to `5` mitigates this issue and the user can now authenticate without killing the node.  It still pulls an atypically large amount of data from LDAP (about 50% more than average) but at least the authentication completes and the node stays healthy. 👍

I do still think tracking a visited list to prevent recursion into already-visited roles is ideal though.

Thanks!

**Comment by vrozov** [comment]
> I do still think tracking a visited list to prevent recursion into already-visited roles is ideal though.

I agree. Please keep this issue open till the full fix is implemented.

**Comment by tm-chang** [comment]
We encountered the same issue. Have any plan to fix this?
Thanks,

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
