### ISSUE TITLE
LDAP user with groups containing certain special characters prevents backend role discovery

### ISSUE THREAD

**Issue by jtackaberry** [opensearch-project/security#888]
We have some users that are members of groups containing certain special characters such as backslashes, for example:

```
CN=Access to Build_Server\ProductA (R),OU=Groups,DC=example,DC=com
```
When calling `/_opendistro/_security/authinfo` these users fail to show any backend roles and therefore are not mapped to any OpenDistro roles (except for `own_index`).  

Packet capture reveals OpenDistro is doing an LDAP searchRequest for this object (including a naked backslash without any escaping), and the LDAP server is responding with invalidDNSyntax:

```
0000208F: LdapErr: DSID-0C090787, comment: Error processing name, data 0, v1db1
```

The backslash in such group names needs to be escaped.   [This list](https://social.technet.microsoft.com/wiki/contents/articles/5312.active-directory-characters-to-escape.aspx) is the complete list of characters that need escaping at least with Microsoft's implementation.

**Comment by jtackaberry** [comment]
@cliu123 was the question label added because you're awaiting further clarification from me, or someone else?  I'm happy to provide more info if needed.

I've confirmed my problem was indeed with the backslash and not the parens, so I've updated the original report.

I've also managed to work around the issue by using the `nested_role_filter` authz option to prevent traversal into roles with backslashes:

```yaml
nested_role_filter:
  - '/.*\\.*/'
```

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
