### ISSUE TITLE
Disabling security plugin - Kibana anonymous_auth_enabled

### ISSUE THREAD

**Issue by weand** [opensearch-project/security#89]
When temp disabling security plugin the following message pops up when accessing kibana. The message suggests to enable anonymous_auth_enabled.

![image](https://user-images.githubusercontent.com/1639457/61210408-ae6f2600-a6fc-11e9-8858-d68e91b71c81.png)

We've set the following configs:

###### elasticsearch.yml
```
opendistro_security.disabled: true
```

###### kibana.yml
```
opendistro_security.auth.anonymous_auth_enabled: true
```

###### opendistro security config.yml 
imported using securityadmin.sh before _opendistro_security.disabled: true_ was set
```
...
  dynamic:
...
    http:
      anonymous_auth_enabled: true
...
```

The error remains.

Maybe the docu also needs additional details: https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/disable/. Only _opendistro_security.disabled: true_ is mentioned there. For kibana the docu states, that the plugin needs to be uninstalled. But this doesn't seem to be consistent with the error message (and also the [kibana config _opendistro_security.auth.anonymous_auth_enabled_](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/opendistro-1.0/index.js#L42) ) which suggests the anonymous auth can be configured in kibana.

Regards
Andreas

**Comment by Hronom** [comment]
This will be useful especially with local docker setup, to avoid creation of custom image.
So this options should be read from environment variables

**Comment by cliu123** [comment]
`anonymous_auth_enabled` is a part of security plugin. With disabling security plugin, anonymous authentication does not work. Please check the [OpenSearch doc](https://opensearch.org/docs/latest/security-plugin/configuration/configuration/#http)
