### ISSUE TITLE
Listing subset of indices in kibana 7.9

### ISSUE THREAD

**Issue by yuxitang-amzn** [opensearch-project/security#893]
OD version: 1.11
ES & kibana version: 7.9.1
Question related to https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/598

Since kibana 7.9, the endpoint of listing indices in stack management - index pattern creation screen becomes `internal/index-pattern-management/resolve_index/*` (which may for supporting cross-cluster indices), which correspond to `indices:admin/resolve/index` permission. A workaround is granting `indices:admin/resolve/index` on indices pattern `*` to user. But in this way it listed all the indices.

Is there any way to configure to allow user to list a subset of indices in with this new endpoint? e.g. we have 2 data indices `kibana_sample_data_flight` and `kibana_sample_data_logs` and only allow a user to list and read `kibana_sample_data_flight`. Tested granting `indices:admin/resolve/index` to `kibana_sample_data_fli*` but didn't work.

**Comment by oscarkraemer** [comment]
It seems that Kibana got some improvements in 7.10. So that it is possible to create index patterns without giving users access `indices:admin/resolve/index` to the `*` pattern. It will generate some `INDEX_EVENT` into `.security-auditlog`.
