### ISSUE TITLE
Separating S3 and Maven uploads to different workflows

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/security#894]
As of now the CD workflow of security will upload artifacts to S3 and Maven in one single workflow.
https://github.com/opendistro-for-elasticsearch/security/actions/runs/414102819/workflow

This caused an issue due to sonatype behavior.

Sonatype will remove artifacts from staging repo if user not publishing them after 24 or 48 hours.

In every release, CD workflow runs by security team during ODFE Phase 1.
Infra Team will only publish those jars on ODFE Phase 5.

There are more than 48 hours of gaps between these two phases, cause sonatype to delete the jars.
Therefore, security needs to reupload the jars by running CD workflow, thus also reupload the artifacts to S3.

Infra Team has to rebuild the Release Candidates due to S3 artifacts get overwritten.

Please help us with this issue.

Thanks,
Peter

**Comment by peterzhuamazon** [comment]
https://quip-amazon.com/GHCOA7mFxqam/Maven-Release-Procedures#IOA9CAhbJYf

**Comment by cliu123** [comment]
PR #954 has been merged.

**Comment by peterzhuamazon** [comment]
@cliu123 this is not staging/prod separation issue, this is to separate s3 and maven workflows to 2 separate one.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
