### ISSUE TITLE
Enabling audit in Kibana GUI returns HTTP 501 Not Implemented

### ISSUE THREAD

**Issue by zeising** [opensearch-project/security#948]
When trying to use kibana to adjust audit logging, as documented here https://opendistro.github.io/for-elasticsearch-docs/docs/security/audit-logs/, I get a HTTP 500 response when trying to toggle the "Enable audit logging" button under the Security -> Audit logs menu in Kibana 1.10.1.

**Comment by tianleh** [comment]
Originally this issue was assigned to **_Kibana_** security plugin queue. However, it looks like audit.yml was not available by default at Elasticsearch side. Let me reassign to the **_ES backend_** plugin queue.

**Comment by vrozov** [comment]
Check that `Hot-reloading of audit configuration is enabled` is present in the ES log during restart.

**Comment by Anthony7774** [comment]
@hensko @Franckiboy15 The issue was resolved in Opensearch 1.0.0, Perhaps looking at upgrading is possible solution

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
