### ISSUE TITLE
Restrict LDAP authentication to users in a group

### ISSUE THREAD

**Issue by vnil1994** [opensearch-project/security#986]
Hi,

This is sort of a duplicate of #378 but since that has been closed by the author i created a new issue. Our issue is the same as the issue #378. We need to restrict the authentication to a certain group in our AD. Something like this:

`userbase: “CN=testgroup,OU=Sites,OU=company,DC=company,DC=company”`

Is there no way to achieve this today?
More information in this thread: https://discuss.opendistrocommunity.dev/t/authentication-via-ldap-only-allow-certain-security-groups/4540

**Comment by rml596** [comment]
I am also looking for this. Ideally users that don't fall into any authorization role cannot login at all.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
